### PR TITLE
fix: Don't quietly allow unsupported SQL `SELECT` clauses

### LINKED ISSUE #25270: QUALIFY clause silently ignored in Polars SQL Context
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
import polars as pl
from datetime import datetime

# Create test data with duplicate IDs

df = pl.DataFrame({
    "id": [1, 1, 1, 2, 2, 3],
    "name": ["Alice_v1", "Alice_v2", "Alice_v3", "Bob_v1", "Bob_v2", "Charlie"],
    "updated_at": [
        datetime(2024, 1, 1),
        datetime(2024, 1, 2),
        datetime(2024, 1, 3),
        datetime(2024, 1, 1),
        datetime(2024, 1, 2),
        datetime(2024, 1, 1),
    ],
    "_persist_time": [
        datetime(2024, 1, 1, 12, 0),
        datetime(2024, 1, 2, 12, 0),
        datetime(2024, 1, 3, 12, 0),
        datetime(2024, 1, 1, 12, 0),
        datetime(2024, 1, 2, 12, 0),
        datetime(2024, 1, 1, 12, 0),
    ],
})

# Execute query with QUALIFY
ctx = pl.SQLContext(test_table=df, eager=True)
query = """
    SELECT *
    FROM test_table
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY id
        ORDER BY updated_at DESC, _persist_time DESC
    ) = 1
"""
result = ctx.execute(query)

print(result)
```

Expected Behavior 

Polars should either throw an error if QUALIFY is not supported. I expected it to return the following 3 rows. 

| id | name | updated_at | _persist_time |
|---|---|---|---|
| 1 | Alice_v3 | 2024-01-03 00:00:00 | 2024-01-03 12:00:00 |
| 2 | Bob_v2 | 2024-01-02 00:00:00 | 2024-01-02 12:00:00 |
| 3 | Charlie | 2024-01-01 00:00:00 | 2024-01-01 12:00:00 |

Actual Behavior
The query returns all 6 rows instead of the filtered 3 rows. The QUALIFY clause appears to be silently ignored. 

Actual output:

| id | name | updated_at | _persist_time |
|---|---|---|---|
| 1 | Alice_v1 | 2024-01-01 00:00:00 | 2024-01-01 12:00:00 |
| 1 | Alice_v2 | 2024-01-02 00:00:00 | 2024-01-02 12:00:00 |
| 1 | Alice_v3 | 2024-01-03 00:00:00 | 2024-01-03 12:00:00 |
| 2 | Bob_v1 | 2024-01-01 00:00:00 | 2024-01-01 12:00:00 |
| 2 | Bob_v2 | 2024-01-02 00:00:00 | 2024-01-02 12:00:00 |
| 3 | Charlie | 2024-01-01 00:00:00 | 2024-01-01 12:00:00 |

## Environment
- Polars version: 1.35.2
- Python version: 3.12.9
- OS: macOS

### Log output

```shell

```

### Description
Polars SQL Context does not support the QUALIFY clause, which is a SQL feature supported by BigQuery, Snowflake, Databricks, etc. for filtering based on window function results.

At the moment, it seems that the SQL engine in Polars silently ignores part of the statement or does not parse it correctly. 

### Expected Behavior 
I would either expect that the query engine would either throw an error in the case a SQL statement is not supported. 
Adding support would improve compatibility when testing queries from these platforms in Polars SQL.

### Expected behavior

Expected behavior + Reproducible example in BigQuery. 

```
WITH test_table AS (
  SELECT 1 AS id, 'Alice_v1' AS name, TIMESTAMP('2024-01-01 00:00:00') AS updated_at, TIMESTAMP('2024-01-01 12:00:00') AS _persist_time
  UNION ALL
  SELECT 1, 'Alice_v2', TIMESTAMP('2024-01-02 00:00:00'), TIMESTAMP('2024-01-02 12:00:00')
  UNION ALL
  SELECT 1, 'Alice_v3', TIMESTAMP('2024-01-03 00:00:00'), TIMESTAMP('2024-01-03 12:00:00')
  UNION ALL
  SELECT 2, 'Bob_v1', TIMESTAMP('2024-01-01 00:00:00'), TIMESTAMP('2024-01-01 12:00:00')
  UNION ALL
  SELECT 2, 'Bob_v2', TIMESTAMP('2024-01-02 00:00:00'), TIMESTAMP('2024-01-02 12:00:00')
  UNION ALL
  SELECT 3, 'Charlie', TIMESTAMP('2024-01-01 00:00:00'), TIMESTAMP('2024-01-01 12:00:00')
)

SELECT *
FROM test_table
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY id
    ORDER BY updated_at DESC, _persist_time DESC
) = 1
ORDER BY id;
```

Expected Behavior 
| id | name | updated_at | _persist_time |
|---|---|---|---|
| 1 | Alice_v3 | 2024-01-03 00:00:00 | 2024-01-03 12:00:00 |
| 2 | Bob_v2 | 2024-01-02 00:00:00 | 2024-01-02 12:00:00 |
| 3 | Charlie | 2024-01-01 00:00:00 | 2024-01-01 12:00:00 |

### Installed versions

--------Version info---------
Polars:              1.35.2
Index type:          UInt32
Platform:            macOS-26.1-arm64-arm-64bit
Python:              3.12.9 (main, Mar 17 2025, 21:36:21) [Clang 20.1.0 ]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          2.40.3
great_tables         <not installed>
matplotlib           <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
polars_cloud         <not installed>
pyarrow              22.0.0
pydantic             2.11.7
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #25270.

We weren't actively noticing the presence of certain `SELECT` clauses that we don't support (mostly quite specific or niche clauses used by other backends), leading either to a misleading error or to some parts of a query being silently ignored.

The following clauses are all now _specifically_ identified as being unsupported...
```
"CLUSTER BY"
"CONNECT BY"
"DISTRIBUTE BY"
"LATERAL VIEW"
"PREWHERE"
"QUALIFY"
"SELECT AS VALUE/STRUCT"
"SELECT INTO"
"SORT BY"
"TOP"
"WINDOW"
```
...though I am working on adding support for at least `WINDOW` (named windows are a great quality of life improvement for window functions), and I think we may be able to support `QUALIFY` (and possibly `SELECT AS STRUCT`) in the near future 🤔

The check is done via an exhaustive destructure of the parser's "Select" struct so we won't get caught out if/when support for additional clauses is added in the future (the compiler will catch it for us 🦀).

## Example

Oracle-specific `START WITH … CONNECT BY …` clause:
```python
pl.sql("""
  SELECT
    employee_id,
    employee_name,
    manager_id,
    LEVEL AS hierarchy_level
  FROM
    df_employees
  START WITH
    manager_id IS NULL
  CONNECT BY PRIOR
    employee_id = manager_id
""")
```
Now raises a specific error:
```python
# SQLInterfaceError: CONNECT BY clause is not supported
```

### CODE REVIEW

File: crates/polars-sql/src/context.rs [hunk 1]
```diff
@@ -743,8 +743,80 @@ impl SQLContext {
...
+            ref prewhere,
+            ref qualify,
+            ref sort_by,
+            ref top,
+            ref value_table_mode,
+        } = *select_stmt;
+
+        // Raise specific error messages for unsupported attributes
+        if top.is_some() {
+            polars_bail!(SQLInterface: "TOP clause is not supported; use LIMIT instead")
```
Comment (ritchie46) [inline crates/polars-sql/src/context.rs]: nit: 

```rust
polars_ensure!(top.is_none(), SQLInterface: "TOP clause is not supported; use LIMIT instead")
polars_ensure!(into.is_none(), SQLInterface: "SELECT INTO clause is not supported")
...
```

Comment (alexander-beedie) [reply crates/polars-sql/src/context.rs]: Good point - will update before merging 😎

**Update**: _done._
