### PR TITLE
fix(python): Add correct deprecation warning for .str.concat

### LINKED ISSUE #19144: `.str.concat` does not produce DeprecationWarning
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.DataFrame({"foo": ["bar"]}).select(pl.all().str.concat())

# DeprecationWarning: The default `delimiter` for `str.concat` will change from '-' to an empty string. 
# Pass a delimiter to silence this warning.
```

### Log output

_No response_

### Issue description

I just learned that `.str.concat` is deprecated from the docs.

Currently it only prints a warning about `delimiter` instead of warning that `.str.join()` should be used.
 
There is a `@deprecate_function` for Series, but I can't seem to trigger it.

https://github.com/pola-rs/polars/blob/133bf47a6083dd72b991d0c72dacb30ebd3195f2/py-polars/polars/series/string.py#L2036-L2041

`pl.Series(["foo"]).str.concat()` only gives the `delimiter` warning.

It seems `@deprecate_function` needs to be added for Expr also?

https://github.com/pola-rs/polars/blob/133bf47a6083dd72b991d0c72dacb30ebd3195f2/py-polars/polars/expr/string.py#L2726-L2727

### Expected behavior

DeprecationWarning

### Installed versions

<details>

```
--------Version info---------
Polars:               1.9.0
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MaxJackson**
closes #19144

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
thanks - i think there's some missing parts from https://github.com/pola-rs/polars/issues/19144#issuecomment-2708886590 ?

**Comment by MarcoGorelli** [comment]
is the change in `string.rs` from #19324 still relevant?

**Comment by MarcoGorelli** [comment]
> it seems like a good idea to me to remove any hints that encourage its use.

yeah so we should probably be removing its mention from `strings.rs`, as https://github.com/pola-rs/polars/pull/19324/files did?

File: crates/polars-core/src/series/implementations/string.rs [hunk 1]
```diff
@@ -241,7 +241,7 @@ impl SeriesTrait for SeriesWrap<StringChunked> {
         Err(polars_err!(
             op = "`sum`",
             DataType::String,
-            hint = "you may mean to call `str.concat` or `list.join`"
+            hint = "you may mean to call `str.join` or `list.join`"
```
Comment (MaxJackson) [inline crates/polars-core/src/series/implementations/string.rs:244]: @MarcoGorelli Here's what I amended, following [#19324](https://github.com/pola-rs/polars/pull/19324/files)

**Comment by MaxJackson** [comment]
@MarcoGorelli I removed its mention from `strings.rs`, following [#19324](https://github.com/pola-rs/polars/pull/19324/files)

**Comment by MaxJackson** [comment]
@MarcoGorelli friendly bump! what do you think of the above?

**Comment by MaxJackson** [comment]
@MarcoGorelli check it out - I added a new test to cover `Series.str.concat` deprecation.

**Comment by MaxJackson** [comment]
@MarcoGorelli another friendly bump! anything else we need to look at here?

**Review by MarcoGorelli — APPROVED** [review]
thanks @MaxJackson !
