### PR TITLE
fix(rust): join_asof missing `tolerance` implementation, address edge-cases

### LINKED ISSUE #10462: join_asof tolerance ignored when strategy=nearest
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> import polars as pl
>>> df1 = pl.DataFrame({'ts': ['2023-03-03 09:16:24.96', '2023-03-03 10:40:56.23', '2023-03-03 11:17:33.72'], 'A':[10, 10, 11]})
>>> df2 = pl.DataFrame({'ts': ['2023-03-03 09:20:25.11', '2023-03-03 10:40:56.75', '2023-03-03 11:14:32.01'], 'B':['Y', 'Y', 'N']})
>>> df1 = df1.with_columns(pl.col('ts').str.to_datetime(format = "%Y-%m-%d %H:%M:%S%.f")).sort('ts')
>>> df2 = (df2.
...         with_columns(pl.col('ts').str.to_datetime(format = "%Y-%m-%d %H:%M:%S%.f")). 
...         with_columns(ts_copy = pl.col('ts') ).
...         sort('ts'))
>>>
>>> df1.join_asof(df2, on = 'ts', tolerance = '1s', strategy = 'backward') #works
shape: (3, 4)
┌─────────────────────────┬─────┬──────┬──────────────┐
│ ts                      ┆ A   ┆ B    ┆ ts_copy      │
│ ---                     ┆ --- ┆ ---  ┆ ---          │
│ datetime[ns]            ┆ i64 ┆ str  ┆ datetime[ns] │
╞═════════════════════════╪═════╪══════╪══════════════╡
│ 2023-03-03 09:16:24.960 ┆ 10  ┆ null ┆ null         │
│ 2023-03-03 10:40:56.230 ┆ 10  ┆ null ┆ null         │
│ 2023-03-03 11:17:33.720 ┆ 11  ┆ null ┆ null         │
└─────────────────────────┴─────┴──────┴──────────────┘
>>> df1.join_asof(df2, on = 'ts', tolerance = '1s', strategy = 'forward') #works
shape: (3, 4)
┌─────────────────────────┬─────┬──────┬─────────────────────────┐
│ ts                      ┆ A   ┆ B    ┆ ts_copy                 │
│ ---                     ┆ --- ┆ ---  ┆ ---                     │
│ datetime[ns]            ┆ i64 ┆ str  ┆ datetime[ns]            │
╞═════════════════════════╪═════╪══════╪═════════════════════════╡
│ 2023-03-03 09:16:24.960 ┆ 10  ┆ null ┆ null                    │
│ 2023-03-03 10:40:56.230 ┆ 10  ┆ Y    ┆ 2023-03-03 10:40:56.750 │
│ 2023-03-03 11:17:33.720 ┆ 11  ┆ null ┆ null                    │
└─────────────────────────┴─────┴──────┴─────────────────────────┘
>>> df1.join_asof(df2, on = 'ts', tolerance = '1s', strategy = 'nearest') #does not work
shape: (3, 4)
┌─────────────────────────┬─────┬─────┬─────────────────────────┐
│ ts                      ┆ A   ┆ B   ┆ ts_copy                 │
│ ---                     ┆ --- ┆ --- ┆ ---                     │
│ datetime[ns]            ┆ i64 ┆ str ┆ datetime[ns]            │
╞═════════════════════════╪═════╪═════╪═════════════════════════╡
│ 2023-03-03 09:16:24.960 ┆ 10  ┆ Y   ┆ 2023-03-03 09:20:25.110 │
│ 2023-03-03 10:40:56.230 ┆ 10  ┆ Y   ┆ 2023-03-03 10:40:56.750 │
│ 2023-03-03 11:17:33.720 ┆ 11  ┆ N   ┆ 2023-03-03 11:14:32.010 │
└─────────────────────────┴─────┴─────┴─────────────────────────┘
```

### Issue description

When "as-of-joining" two dataframes, tolerance parameter seems to be ignored when strategy parameter is set to nearest (it is properly taken into account for strategy= backward or forward). For instance, above, the resulting dataframe joins nearest timestamps being more than one second apart even though tolerance='1s'.

 

### Expected behavior

```python
>>> df1.join_asof(df2, on = 'ts', tolerance = '1s', strategy = 'nearest') 
shape: (3, 4)
┌─────────────────────────┬─────┬──────┬─────────────────────────┐
│ ts                      ┆ A   ┆ B    ┆ ts_copy                 │
│ ---                     ┆ --- ┆ ---  ┆ ---                     │
│ datetime[ns]            ┆ i64 ┆ str  ┆ datetime[ns]            │
╞═════════════════════════╪═════╪══════╪═════════════════════════╡
│ 2023-03-03 09:16:24.960 ┆ 10  ┆ null ┆ null                    │
│ 2023-03-03 10:40:56.230 ┆ 10  ┆ Y    ┆ 2023-03-03 10:40:56.750 │
│ 2023-03-03 11:17:33.720 ┆ 11  ┆ null ┆ null                    │
└─────────────────────────┴─────┴──────┴─────────────────────────┘
```

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

### LINKED ISSUE #10532: Allow passing `timedelta` to `tolerance` in `join_asof`
### Problem description

Currently when using `join_asof` on a temporal column, only duration strings like “3d12h4m25s” can be passed to the tolerance argument. It would nice to be able to pass a python `timedelta` like most other methods that accept duration strings.

### LINKED ISSUE #10534: `join_asof` does not respect `tolerance="0"` when `by` is set
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

x = pl.DataFrame(
    {
        "dt": [datetime(2022, 1, 2), datetime(2023, 1, 3)],
        "id": ["a", "a"],
    }
).sort("dt")

y = pl.DataFrame(
    {
        "val": [1.0],
        "dt": [datetime(2022, 1, 2)],
        "id": ["a"],
    }
).sort("dt")

x.join_asof(y, on="dt", tolerance="0", by="id")
```

### Issue description

Setting a tolerance of "0" should produce the same result as an exact left join. This is not the case when setting the `by` parameter: 

```python

x = pl.DataFrame(
    {
        "dt": [datetime(2022, 1, 2), datetime(2023, 1, 3)],
        "id": ["a", "a"],
    }
).sort("dt")
y = pl.DataFrame(
    {
        "val": [1.0],
        "dt": [datetime(2022, 1, 2)],
        "id": ["a"],
    }
).sort("dt")

x.join_asof(y, on="dt", tolerance="0", by="id")

shape: (2, 3)
┌─────────────────────┬─────┬─────┐
│ dt                  ┆ id  ┆ val │
│ ---                 ┆ --- ┆ --- │
│ datetime[μs]        ┆ str ┆ f64 │
╞═════════════════════╪═════╪═════╡
│ 2022-01-02 00:00:00 ┆ a   ┆ 1.0 │
│ 2023-01-03 00:00:00 ┆ a   ┆ 1.0 │
└─────────────────────┴─────┴─────┘
```

The value of `val` in the last row should be `None`. Note that this works correctly when `by` is not set:

```python
x.join_asof(y, on="dt", tolerance="0")

shape: (2, 4)
┌─────────────────────┬─────┬──────┬──────────┐
│ dt                  ┆ id  ┆ val  ┆ id_right │
│ ---                 ┆ --- ┆ ---  ┆ ---      │
│ datetime[μs]        ┆ str ┆ f64  ┆ str      │
╞═════════════════════╪═════╪══════╪══════════╡
│ 2022-01-02 00:00:00 ┆ a   ┆ 1.0  ┆ a        │
│ 2023-01-03 00:00:00 ┆ a   ┆ null ┆ null     │
└─────────────────────┴─────┴──────┴──────────┘
```

### Expected behavior

Setting `tolerance="0"` should work correctly regardless of whether or not `by` is being used.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            macOS-13.2-arm64-arm-64bit
Python:              3.11.1 (main, Feb  8 2023, 16:32:14) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.1.0
matplotlib:          3.7.0
numpy:               1.24.3
pandas:              1.5.3
pyarrow:             12.0.1
pydantic:            1.10.5
sqlalchemy:          1.4.46
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Resolves #10462, Resolves #10534, and Resolves #10532. Main changes:

1. Implemented tolerance for `strategy="nearest"`
2. Increase test coverage for join_asof with nearest.
3. Allow `timedelta` objects for the tolerance input.

### CODE REVIEW

File: crates/polars-core/src/frame/asof_join/asof.rs [hunk 1]
```diff
@@ -182,16 +182,102 @@ pub(super) fn join_asof_backward<T: PartialOrd + Copy + Debug>(
...
 
+pub(super) fn join_asof_nearest_with_tolerance<
+    T: PartialOrd + Copy + Debug + Sub<Output = T> + Add<Output = T> + Bounded,
+>(
+    left: &[T],
+    right: &[T],
+    tolerance: T,
+) -> Vec<Option<IdxSize>> {
+    let n_left = left.len();
+    let mut out = Vec::with_capacity(n_left);
```
Comment (ritchie46) [inline crates/polars-core/src/frame/asof_join/asof.rs:193]: Can we allocate after `if left.is_empty()`. That saves going through the allocator.

File: crates/polars-core/src/frame/asof_join/asof.rs [hunk 2]
```diff
@@ -182,16 +182,102 @@ pub(super) fn join_asof_backward<T: PartialOrd + Copy + Debug>(
...
+            return out;
+        }
+
+        // we might have a match
+        let mut offset: IdxSize = 0;
+        let mut dist = tolerance;
+        let mut found_window = false;
+        for &val_r in right {
+            // haven't reached the window, keep looking
+            if val_l > val_r + tolerance {
```
Comment (ritchie46) [inline crates/polars-core/src/frame/asof_join/asof.rs:234]: Can you assign a temp_val for `val_r + tolerance`? It is used more often.

**Review by ritchie46 — COMMENTED** [review]
Nice @mcrumiller. Great addition. I have left some comments.

File: crates/polars-core/src/frame/asof_join/asof.rs [hunk 3]
```diff
@@ -182,16 +182,102 @@ pub(super) fn join_asof_backward<T: PartialOrd + Copy + Debug>(
...
+
+    if left.is_empty() {
+        return out;
+    }
+    if right.is_empty() {
+        out.extend(std::iter::repeat(None).take(n_left));
+        return out;
+    }
+
+    // if we know the first/last values we can leave early in many cases
```
[the remark this answers is not in the document]
Comment (mcrumiller) [reply crates/polars-core/src/frame/asof_join/asof.rs:203]: @ritchie46 should I go through and sentence-ize the comment phrases?

File: crates/polars-core/src/frame/asof_join/asof.rs (hunk 1 above)
Comment (mcrumiller) [reply crates/polars-core/src/frame/asof_join/asof.rs:193]: Sure thing. I was also wondering if the emptiness of the left/right vectors was checked earlier on (it probably should be if it's not). I'll assume no for now.

File: crates/polars-core/src/frame/asof_join/asof.rs (hunk 2 above)
Comment (mcrumiller) [reply crates/polars-core/src/frame/asof_join/asof.rs:234]: We have a `val_l + tolerance` farther down, which I think you may have mistook for `val_r + tolerance`--this is only used once. However, `val_l + tolerance` doens't change inside the inner loop so we can temp that one.

File: crates/polars-core/src/frame/asof_join/asof.rs (hunk 1 above)
Comment (mcrumiller) [reply crates/polars-core/src/frame/asof_join/asof.rs:193]: @ritchie46 wait, don't we still have to return an empty vec? What do I return if `left.is_empty()` then?

Comment (mcrumiller) [reply crates/polars-core/src/frame/asof_join/asof.rs:193]: Oh, just a `Vec::new()`.

**Comment by mcrumiller** [comment]
Hmm, the `on` column can be an Expr, whose dtype might not be knowable at compile time. What's a good way to address this?

**Comment by mcrumiller** [comment]
@ritchie46 I think this one is good to go if you're happy with the changes.

**Comment by ritchie46** [comment]
Nice one @mcrumiller. Thanks!
