### PR TITLE
fix(rust): microsecond noise on `date` >> `time` cast (add `00:00:00` fast-path)

### LINKED ISSUE #5111: Strange microsecond noise getting `Time` from `Date` (expect `00:00:00`, but get `00:00:00.000019023`)
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

As `Date` has no time component, there are two reasonable outcomes for casting to `Time`: disallow and raise an exception or (much preferred, and what polars has chosen to do ;) return `00:00:00.000000`.

However, for some reason there is a tiny microsecond component being created/returned. Looks like a small bug _and_ a potential optimisation opportunity for this corner-case? (As we know the cast result from `Date` _must_ be `00:00:00`, could directly create the result Series with that const).

### Reproducible example

```python
from datetime import date
import polars as pl

pl.DataFrame({
    "dt":[
        date(2022,1,31),
        date(2022,10,5),
        date(2022,12,31),
  ]
}).with_column(
    pl.col("dt").cast(pl.Time).alias("tm")
)

# shape: (3, 2)
# ┌────────────┬────────────────────┐
# │ dt         ┆ tm                 │
# │ ---        ┆ ---                │
# │ date       ┆ time               │
# ╞════════════╪════════════════════╡
# │ 2022-01-31 ┆ 00:00:00.000019023 │
# ├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
# │ 2022-10-05 ┆ 00:00:00.000019270 │
# ├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
# │ 2022-12-31 ┆ 00:00:00.000019357 │
# └────────────┴────────────────────┘
```

### Expected behavior

Expect the following result (no microsecond noise):

```python
# ┌────────────┬──────────┐
# │ dt         ┆ tm       │
# │ ---        ┆ ---      │
# │ date       ┆ time     │
# ╞════════════╪══════════╡
# │ 2022-01-31 ┆ 00:00:00 │
# ├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
# │ 2022-10-05 ┆ 00:00:00 │
# ├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
# │ 2022-12-31 ┆ 00:00:00 │
# └────────────┴──────────┘
```

### Installed versions

<details>

```
---Version info---
Polars: 0.14.17
Index type: UInt32
Platform: macOS-12.6-arm64-arm-64bit
Python: 3.10.7 (main, Sep 14 2022, 22:38:23) [Clang 14.0.0 (clang-1400.0.29.102)]

---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.4.4
numpy: 1.23.3
fsspec: 2022.8.2
connectorx: <not installed>
xlsx2csv: 0.8
matplotlib: <not installed>```

</details>

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #5111.

-----

Cast from `Date` to `Time` now jumps straight to returning a `TimeChunked`-backed `Series` of `00:00:00` literals (fast-path; `Date` has no time component). I _think_ the patch looks efficient, but if there's a better option that I missed, please point me in the right direction and I'll update/improve it ;)

**Example**
```python
from datetime import date
import polars as pl

df = pl.DataFrame({
    "dt": [
        date(1988, 1, 1),
        date(2000, 3, 8),
        date(2010, 6, 15),
        date(2022, 12, 31),
    ]
}).with_column(
    pl.col("dt").cast(pl.Time).alias("tm")
)
```

**Before** _(incrementing microsecs/noise)_
```python
# ┌────────────┬────────────────────┐
# │ dt         ┆ tm                 │
# │ ---        ┆ ---                │
# │ date       ┆ time               │
# ╞════════════╪════════════════════╡
# │ 1988-01-01 ┆ 00:00:00.000006574 │
# ├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
# │ 2000-03-08 ┆ 00:00:00.000011024 │
# ├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
# │ 2010-06-15 ┆ 00:00:00.000014775 │
# ├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
# │ 2022-12-31 ┆ 00:00:00.000019357 │
# └────────────┴────────────────────┘
```
**After** _(always 00:00:00, as expected)_
```python
# ┌────────────┬──────────┐
# │ dt         ┆ tm       │
# │ ---        ┆ ---      │
# │ date       ┆ time     │
# ╞════════════╪══════════╡
# │ 1988-01-01 ┆ 00:00:00 │
# ├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
# │ 2000-03-08 ┆ 00:00:00 │
# ├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
# │ 2010-06-15 ┆ 00:00:00 │
# ├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
# │ 2022-12-31 ┆ 00:00:00 │
# └────────────┴──────────┘
```
(Think I'll subject temporal casting to some parametric testing, as it's still not clear to me how the gradually-incrementing microsecond noise came about in the first place; the extra tests should provide some additional insight and/or reassurance that there isn't something else waiting to be found).

### CODE REVIEW

File: polars/polars-core/src/chunked_array/logical/date.rs [hunk 1]
```diff
@@ -40,6 +41,12 @@ impl LogicalType for DateChunked {
                     .into_datetime(*tu, tz.clone())
                     .into_series())
             }
+            (Date, Time) => Ok(Int64Chunked::from_iter_values(
```
Comment (ritchie46) [inline polars/polars-core/src/chunked_array/logical/date.rs:44]: We can use `Int64Chunked::full(self.name(), 0, self.len())` here.

Comment (alexander-beedie) [reply polars/polars-core/src/chunked_array/logical/date.rs:44]: Hah; I should have known there was a super-optimal path ;)
Will update accordingly.
