### PR TITLE
fix: Allow exactly one value in start/end for `int_range`

### LINKED ISSUE #10902: int_range silently allows series with length > 1
`pl.int_range` accepts expressions, but does not ensure that the passed series has length 1, instead it silently takes the first element. Since the series-based functionality is in `pl.int_ranges`, `pl.int_range` should check and reject inputs with length != 1. Users that want the old behavior can explicitly write `expr.first()` before passing it to `pl.int_range`.

### PR DESCRIPTION
**Pull request by stinodego**
Closes #10902 

I'd rather have a more specific error type, but I'll pick that up separately.

### CODE REVIEW

File: crates/polars-plan/src/dsl/function_expr/range/utils.rs [hunk 1]
```diff
@@ -7,3 +8,12 @@ pub(super) fn temporal_series_to_i64_scalar(s: &Series) -> i64 {
         .extract::<i64>()
         .unwrap()
 }
+
+pub(super) fn ensure_range_bounds_contain_single_value(
+    start: &Series,
+    end: &Series,
+) -> PolarsResult<()> {
+    polars_ensure!(start.len() == 1, ComputeError: "`start` must contain a single value");
```
Comment (ritchie46) [inline crates/polars-plan/src/dsl/function_expr/range/utils.rs:16]: maybe include `"got {n}"` in the message?

Comment (stinodego) [reply crates/polars-plan/src/dsl/function_expr/range/utils.rs]: Done!
