### PR TITLE
fix: Rechunk on nested dtypes in `take_unchecked_impl` parallel path

### LINKED ISSUE #25651: Large (100x) performance regression in joins -- Python
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

I have written a small script to reproduce the error,

```python
import time

import numpy as np
import polars as pl


def generate_test_data(n_large=1_460_116):
    np.random.seed(42)
    data = {
        "SNID": [str(x) for x in range(n_large)],
        "index": list(range(n_large)),
        "label": np.random.randint(0, 20, n_large, dtype=np.int64),
        "time": [None] * n_large,
        "flux": [None] * n_large,
        "flux_err": [None] * n_large,
        "channel_index": [None] * n_large,
        "channel_wavelength": [None] * n_large,
    }

    for row_idx in range(n_large):
        # Consistent list length for this row (1-243)
        list_len = np.random.randint(1, 244)

        # Fill lists for this row
        data["time"][row_idx] = np.random.randn(list_len).astype(np.float32)
        data["flux"][row_idx] = np.random.randn(list_len).astype(np.float32)
        data["flux_err"][row_idx] = np.random.randn(list_len).astype(np.float32)
        data["channel_index"][row_idx] = np.random.randint(
            0, 8, list_len, dtype=np.int8
        )
        data["channel_wavelength"][row_idx] = np.random.uniform(
            4000, 10000, list_len
        ).astype(np.float32)

    # Add scalar columns
    return pl.DataFrame(data).sort("SNID")


# Generate the test data
print("Generating data...")
df2 = generate_test_data()
print("... done")
n_small = 32_768

for _ in range(10):
    start = time.time()
    df1 = df2.select("SNID").sample(n_small, with_replacement=False, shuffle=True)
    result = df1.join(df2, on="SNID", how="left", maintain_order="left")
    elapsed = time.time() - start
    items_sec = len(result) / elapsed
    batches_sec = items_sec / 256
    print(f"Merge speed: {items_sec:.2f} items/s, {batches_sec:.2f} batches/s")
```

and run this with both Polars 1.34 and 1.35.2 (latest stable),

```
> uv pip install polars==1.34
Using Python 3.12.12 environment at: ...
Resolved 2 packages in 81ms
Installed 2 packages in 8ms
 + polars==1.34.0
 + polars-runtime-32==1.34.0

> python3 repro_polars_bug.py                   
Generating data...
... done
Merge speed: 747580.59 items/s, 2920.24 batches/s
Merge speed: 895157.84 items/s, 3496.71 batches/s
Merge speed: 908429.03 items/s, 3548.55 batches/s
Merge speed: 963963.01 items/s, 3765.48 batches/s
Merge speed: 965391.69 items/s, 3771.06 batches/s
Merge speed: 920247.43 items/s, 3594.72 batches/s
Merge speed: 912239.75 items/s, 3563.44 batches/s
Merge speed: 957742.72 items/s, 3741.18 batches/s
Merge speed: 942789.79 items/s, 3682.77 batches/s
Merge speed: 971973.19 items/s, 3796.77 batches/s

> uv pip uninstall polars polars-runtime-32
Using Python 3.12.12 environment at: ...
Uninstalled 2 packages in 19ms
 - polars==1.34.0
 - polars-runtime-32==1.34.0

> uv pip install polars                    
Using Python 3.12.12 environment at: ...
Resolved 2 packages in 2ms
Installed 2 packages in 13ms
 + polars==1.35.2
 + polars-runtime-32==1.35.2

> python3 repro_polars_bug.py
Generating data...
... done
Merge speed: 7557.04 items/s, 29.52 batches/s
Merge speed: 9212.89 items/s, 35.99 batches/s
Merge speed: 9290.96 items/s, 36.29 batches/s
Merge speed: 8935.52 items/s, 34.90 batches/s
Merge speed: 9238.40 items/s, 36.09 batches/s
Merge speed: 9328.49 items/s, 36.44 batches/s
Merge speed: 9332.71 items/s, 36.46 batches/s
Merge speed: 9365.30 items/s, 36.58 batches/s
Merge speed: 8857.23 items/s, 34.60 batches/s
Merge speed: 9235.43 items/s, 36.08 batches/s
```

### Log output

```shell
Generating data...
... done
join parallel: true
LEFT join dataframes finished
Merge speed: 7489.67 items/s, 29.26 batches/s
join parallel: true
LEFT join dataframes finished
Merge speed: 9068.97 items/s, 35.43 batches/s
join parallel: true
LEFT join dataframes finished
Merge speed: 8751.70 items/s, 34.19 batches/s
join parallel: true
LEFT join dataframes finished
Merge speed: 8854.05 items/s, 34.59 batches/s
join parallel: true
LEFT join dataframes finished
Merge speed: 9270.22 items/s, 36.21 batches/s
join parallel: true
LEFT join dataframes finished
Merge speed: 9188.51 items/s, 35.89 batches/s
join parallel: true
LEFT join dataframes finished
Merge speed: 9245.16 items/s, 36.11 batches/s
join parallel: true
LEFT join dataframes finished
Merge speed: 9286.73 items/s, 36.28 batches/s
join parallel: true
LEFT join dataframes finished
Merge speed: 9315.61 items/s, 36.39 batches/s
join parallel: true
LEFT join dataframes finished
Merge speed: 9307.67 items/s, 36.36 batches/s
```

### Issue description

I tried with left joins and maintain_order="none" as well, no luck.

### Expected behavior

n/a expected performance to be stable

### Installed versions

<details>

```
--------Version info---------
Polars:              1.35.2
Index type:          UInt32
Platform:            Linux-6.8.0-88-generic-x86_64-with-glibc2.39
Python:              3.12.12 (main, Oct 31 2025, 23:02:31) [Clang 21.1.4 ]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                1.42.4
cloudpickle          3.1.2
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2025.12.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.10.7
numpy                2.3.5
openpyxl             <not installed>
pandas               2.3.3
polars_cloud         <not installed>
pyarrow              22.0.0
pydantic             2.12.5
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                2.9.1+cu128
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #25651

Mitigates the `rechunk storm` which happens on chained queries with nested dtypes that call `rechunk()` on every invocation of `take_unchecked` in `gather.rs`.

Note: performance is not (yet) at the level before PR https://github.com/pola-rs/polars/pull/24980. However, this is a tradeoff, since this PR made many expressions faster, including `sort()`.

Pending review of rechunk tradeoff design options and regression test (optional).

In build_release on the MRE:
```
df1 n_chunks: 24

(1) No sort
df2 n_chunks: 1
elapsed for join (no sort): 29.439 ms

(2) Sort
elapsed for sort: 85.679 ms
df2 n_chunks: 24
elapsed for join (no sort): 77.211 ms
```
(Latter was ~30ms originally)

Compare with release 1.36.0-beta.2:
```
df1 n_chunks: 24

(1) No sort
df2 n_chunks: 1
elapsed for join (no sort): 26.232 ms

(2) Sort
elapsed for sort: 76.233 ms
df2 n_chunks: 24
elapsed for join (no sort): 1993.969 ms
```

Compare with original 1.34.0 as released:
```
df1 n_chunks: 1

(1) No sort
df2 n_chunks: 1
elapsed for join (no sort): 32.138 ms

(2) Sort
elapsed for sort: 605.598 ms
df2 n_chunks: 1
elapsed for join (no sort): 30.416 ms
```

### CODE REVIEW

File: crates/polars-core/src/frame/mod.rs [hunk 1]
```diff
@@ -2050,8 +2050,34 @@ impl DataFrame {
     /// # Safety
     /// The indices must be in-bounds.
     pub unsafe fn take_unchecked_impl(&self, idx: &IdxCa, allow_threads: bool) -> Self {
-        let cols = if allow_threads {
-            POOL.install(|| self._apply_columns_par(&|c| c.take_unchecked(idx)))
+        let cols = if allow_threads && POOL.current_num_threads() > 1 {
+            POOL.install(|| {
+                if POOL.current_num_threads() > self.width() {
+                    let stride = usize::max(idx.len().div_ceil(POOL.current_num_threads()), 256);
```
Comment (nameexhaustion) [inline crates/polars-core/src/frame/mod.rs:2056]: Could we also avoid this branch if `self.len() / stride < 2`

**Comment by nameexhaustion** [comment]
I'd suggest adding a Python test for the join performance - something similar to `test_list_struct_field_perf` https://github.com/pola-rs/polars/blob/38bc2db33ded7ba26beab5001eaf4c5aa1baabb8/py-polars/tests/unit/operations/namespaces/list/test_list.py#L1184-L1191

(can be in a separate PR)

File: crates/polars-core/src/frame/mod.rs (hunk 1 above)
Comment (ritchie46) [reply crates/polars-core/src/frame/mod.rs:2056]: In a follow up PR, releasing. ;)

Comment (kdn36) [reply crates/polars-core/src/frame/mod.rs:2056]: Done, see https://github.com/pola-rs/polars/pull/25672
