### PR TITLE
fix: ensure first datapoint is always included in group_by_dynamic

### LINKED ISSUE #15241: First rows get ignored by `group_by_dynamic` when using `offset`
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import UTC, datetime, timedelta

import polars as pl

df = pl.DataFrame(
    data={
        "t": pl.Series(
            [
                datetime(2024, 3, 22, 3, 0, tzinfo=UTC),
                datetime(2024, 3, 22, 4, 0, tzinfo=UTC),
                datetime(2024, 3, 22, 5, 0, tzinfo=UTC),
                datetime(2024, 3, 22, 6, 0, tzinfo=UTC),
            ]
        ).dt.cast_time_unit("ms"),
        "v": [1, 10, 100, 1000],
    }
).set_sorted("t")

resampled = df.group_by_dynamic(
    index_column="t", every="1d", offset=timedelta(hours=5)
).agg(
    [
        pl.sum("v").alias("v"),
    ]
)

print(resampled)
```

### Log output

I ran `POLARS_VERBOSE=1 python polars_bug_report.py` but did not see any output in stderr.

However on stdout I get the result of the aggregation:

```shell
shape: (1, 2)
┌─────────────────────────┬──────┐
│ t                       ┆ v    │
│ ---                     ┆ ---  │
│ datetime[ms, UTC]       ┆ i64  │
╞═════════════════════════╪══════╡
│ 2024-03-22 05:00:00 UTC ┆ 1100 │
└─────────────────────────┴──────┘
```

### Issue description

When using the method `group_by_dynamic` with the parameter `offset`, if the first rows are before the given offset, they are ignored.

In my example, I use a daily aggregation with an offset of 5 hours. If the first lines are in the between midnight and 5AM, they are not counted in the result.

### Expected behavior

Every row should count:

```
shape: (1, 2)
┌─────────────────────────┬──────┐
│ t                       ┆ v    │
│ ---                     ┆ ---  │
│ datetime[ms, UTC]       ┆ i64  │
╞═════════════════════════╪══════╡
│ 2024-03-21 05:00:00 UTC ┆   11 │
│ 2024-03-22 05:00:00 UTC ┆ 1100 │
└─────────────────────────┴──────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32
Platform:             Linux-6.5.0-26-generic-x86_64-with-glibc2.35
Python:               3.11.4 (main, Jun 26 2023, 15:13:33) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.3
pyarrow:              11.0.0
pydantic:             2.5.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.23
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #15241

With the example from that issue, the output becomes:
```
shape: (2, 2)
┌─────────────────────────┬──────┐
│ t                       ┆ v    │
│ ---                     ┆ ---  │
│ datetime[ms, UTC]       ┆ i64  │
╞═════════════════════════╪══════╡
│ 2024-03-21 05:00:00 UTC ┆ 11   │
│ 2024-03-22 05:00:00 UTC ┆ 1100 │
└─────────────────────────┴──────┘
```
which is their expected output

This doesn't break any existing tested behaviour, but does make group-by-dynamic more user-friendly / expected to users using `offset`

Perf impact: there's a little extra computation for finding the first window, but that's only for the first window - after that, the windows just keep getting updated by adding `every` (no change)

### CODE REVIEW

File: crates/polars-time/src/windows/window.rs [hunk 1]
```diff
@@ -8,6 +8,37 @@ use polars_core::prelude::*;
...
+///
+/// - first datapoint is `2020-01-01 01:00`
+/// - `every` is `'1d'`
+/// - `period` is `'2d'`
+/// - `offset` is `'6h'`
+///
+/// then truncating the earliest datapoint by `every` and adding `offset` results
+/// in the window `[2020-01-01 06:00, 2020-01-03 06:00)`. To give the earliest datapoint
+/// a chance of being included, we then shift the window back by `every` to
+/// `[2019-12-31 06:00, 2020-01-02 06:00)`.
```
Comment (MarcoGorelli) [inline crates/polars-time/src/windows/window.rs:23]: Demo:
```python
In [4]: df = pl.DataFrame({'t': [datetime(2020, 1, 1, 1)], 'i': [0]})

In [5]: df.group_by_dynamic('t', every='1d', period='2d', offset='6h', include_boundaries=True).agg('i')
Out[5]: 
shape: (1, 4)
┌─────────────────────┬─────────────────────┬─────────────────────┬───────────┐
│ _lower_boundary     ┆ _upper_boundary     ┆ t                   ┆ i         │
│ ---                 ┆ ---                 ┆ ---                 ┆ ---       │
│ datetime[μs]        ┆ datetime[μs]        ┆ datetime[μs]        ┆ list[i64] │
╞═════════════════════╪═════════════════════╪═════════════════════╪═══════════╡
│ 2019-12-31 06:00:00 ┆ 2020-01-02 06:00:00 ┆ 2019-12-31 06:00:00 ┆ [0]       │
└─────────────────────┴─────────────────────┴─────────────────────┴───────────┘
```

Whereas, on the latest release:
```python
In [18]: df.group_by_dynamic('t', every='1d', period='2d', offset='6h', include_boundaries=True).agg('i')
Out[18]:
shape: (0, 4)
┌─────────────────┬─────────────────┬──────────────┬───────────┐
│ _lower_boundary ┆ _upper_boundary ┆ t            ┆ i         │
│ ---             ┆ ---             ┆ ---          ┆ ---       │
│ datetime[μs]    ┆ datetime[μs]    ┆ datetime[μs] ┆ list[i64] │
╞═════════════════╪═════════════════╪══════════════╪═══════════╡
└─────────────────┴─────────────────┴──────────────┴───────────┘
```

File: crates/polars-time/src/windows/test.rs [hunk 2]
```diff
@@ -340,9 +344,10 @@ fn test_boundaries() {
         false,
         Default::default(),
     );
-    assert_eq!(groups[0], [1, 2]); // 00:00:00 -> 00:30:00
-    assert_eq!(groups[1], [3, 2]); // 01:00:00 -> 01:30:00
-    assert_eq!(groups[2], [5, 2]); // 02:00:00 -> 02:30:00
+    assert_eq!(groups[0], [0, 1]); // (2021-12-15 23:30, 2021-12-16 00:00]
+    assert_eq!(groups[1], [1, 2]); // (2021-12-16 00:00, 2021-12-16 00:30]
+    assert_eq!(groups[2], [3, 2]); // (2021-12-16 00:30, 2021-12-16 01:00]
+    assert_eq!(groups[3], [5, 2]); // (2021-12-16 01:00, 2021-12-16 01:30]
```
Comment (MarcoGorelli) [inline crates/polars-time/src/windows/test.rs:350]: here's an example of where the earliest datapoint is currently being excluded

because `closed='right'`, the `00:00:00` point isn't currently included in any windows. This PR fixes that

File: crates/polars-time/src/windows/window.rs [hunk 3]
```diff
@@ -157,14 +224,20 @@ impl<'a> BoundsIter<'a> {
...
+                },
+                TimeUnit::Milliseconds => {
+                    window.get_earliest_bounds_ms(boundary.start, closed_window, tz)?
+                },
             },
             _ => {
                 {
                     #[allow(clippy::type_complexity)]
-                    let (from, to, offset): (
+                    let (from, to, offset_fn): (
```
Comment (MarcoGorelli) [inline crates/polars-time/src/windows/window.rs:240]: drive-by: renaming to `offset_fn`, partially because that what it's called in other places, and also because otherwise it risks being confused with the `offset` parameter of `group_by_dynamic`

File: crates/polars-time/src/windows/test.rs [hunk 4]
```diff
@@ -148,8 +148,8 @@ fn test_groups_large_interval() {
         false,
         Default::default(),
     );
-    assert_eq!(groups.len(), 2);
-    assert_eq!(groups[1], [2, 2]);
+    assert_eq!(groups.len(), 3);
+    assert_eq!(groups[1], [1, 1]);
```
Comment (MarcoGorelli) [inline crates/polars-time/src/windows/test.rs:152]: same story, earliest datapoint not included in any group due to `closed='right'`

File: crates/polars-time/src/windows/test.rs [hunk 5]
```diff
@@ -651,9 +662,10 @@ fn test_boundaries_ms() {
         false,
         Default::default(),
     );
-    assert_eq!(groups[0], [1, 2]); // 00:00:00 -> 00:30:00
-    assert_eq!(groups[1], [3, 2]); // 01:00:00 -> 01:30:00
-    assert_eq!(groups[2], [5, 2]); // 02:00:00 -> 02:30:00
+    assert_eq!(groups[0], [0, 1]); // (2021-12-15 23:30, 2021-12-16 00:00]
+    assert_eq!(groups[1], [1, 2]); // (2021-12-16 00:00, 2021-12-16 00:30]
+    assert_eq!(groups[2], [3, 2]); // (2021-12-16 00:30, 2021-12-16 01:00]
+    assert_eq!(groups[3], [5, 2]); // (2021-12-16 01:00, 2021-12-16 01:30]
```
Comment (MarcoGorelli) [inline crates/polars-time/src/windows/test.rs:668]: here too

**Review by ritchie46 — APPROVED** [review]
