### PR TITLE
fix(rust): Fix `assert_frame_not_equal()` did not raise on dtype mismatch

### LINKED ISSUE #26507: Dtype check not working for assert frame (not) equal
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from polars.testing import assert_frame_not_equal

schema_a = {
    "int_a": pl.Int16,
    "int_b": pl.Int16,
    "int_c": pl.Int64,
}

schema_b = {
    "int_a": pl.Int64,
    "int_b": pl.Int16,
    "int_c": pl.Int64,
}

a = pl.DataFrame({}, schema=schema_a)
b = pl.DataFrame({}, schema=schema_b)

assert_frame_not_equal(
    left=a,
    right=b,
    check_column_order=False,
    check_dtypes=True,
)
```

### Log output

```shell
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[11], line 18
     15 a = pl.DataFrame({}, schema=schema_a)
     16 b = pl.DataFrame({}, schema=schema_b)
---> 18 assert_frame_not_equal(
     19     left=a,
     20     right=b,
     21     check_column_order=False,
     22     check_dtypes=True,
     23 )

File ~/Workspace/SPF/spf_data_provider/.venv/lib/python3.11/site-packages/polars/_utils/deprecation.py:128, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    123 @wraps(function)
    124 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    125     _rename_keyword_argument(
    126         old_name, new_name, kwargs, function.__qualname__, version
    127     )
--> 128     return function(*args, **kwargs)

File ~/Workspace/SPF/spf_data_provider/.venv/lib/python3.11/site-packages/polars/_utils/deprecation.py:128, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    123 @wraps(function)
    124 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    125     _rename_keyword_argument(
    126         old_name, new_name, kwargs, function.__qualname__, version
    127     )
--> 128     return function(*args, **kwargs)

File ~/Workspace/SPF/spf_data_provider/.venv/lib/python3.11/site-packages/polars/_utils/deprecation.py:128, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    123 @wraps(function)
    124 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
    125     _rename_keyword_argument(
    126         old_name, new_name, kwargs, function.__qualname__, version
    127     )
--> 128     return function(*args, **kwargs)

File ~/Workspace/SPF/spf_data_provider/.venv/lib/python3.11/site-packages/polars/testing/asserts/frame.py:231, in assert_frame_not_equal(left, right, check_row_order, check_column_order, check_dtypes, check_exact, rel_tol, abs_tol, categorical_as_str)
    229 objects = "LazyFrames" if lazy else "DataFrames"
    230 msg = f"{objects} are equal (but are expected not to be)"
--> 231 raise AssertionError(msg)

AssertionError: DataFrames are equal (but are expected not to be)
```

### Issue description

In polars.testing _assert_frame_equal_ and _assert_frame_not_equal_ currently do not correctly check the dtypes if the column order does not matter. I noticed that for the Int dytes comparing Int16 with Int64.
If the param _check_column_order_ is set to True everything works correctly so it is most probably connected to that.

### Expected behavior

assert_frame_equal: an AssertionError is only thrown if the dtypes are different
assert_frame_not_equal: an AssertionError is thrown if any dtype is differnt

### Installed versions

<details>

```
--------Version info---------
Polars:              1.38.1
Index type:          UInt32
Platform:            macOS-15.7.3-arm64-arm-64bit
Python:              3.11.9 (main, Aug 14 2024, 04:17:21) [Clang 18.1.8 ]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       1.25.1
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.19.0
fsspec               2026.1.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                1.26.4
openpyxl             <not installed>
pandas               3.0.0
polars_cloud         <not installed>
pyarrow              20.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             0.8.6
xlsxwriter           3.2.9
```

</details>

### PR DESCRIPTION
**Pull request by Kevin-Patyk**
Resolves https://github.com/pola-rs/polars/issues/26507.

In `assert_dataframe_schema_equal()`, a helper function used in `assert_dataframe_equal()`, the code first checks if `check_dtypes` is `true`. If it is `true`, it then checks if `check_column_order` is `true`. If it is, data types are compared using a vector, comparing element by element in order. This was working properly. 

In the `else` condition, meaning `check_column_order` is `false`, the original code was using a `PlHashSet` of `DataType`. While `PlHashSet` does unordered comparison, it does not preserve column names or duplicate values. So, for example, if the data types of `left` were `{Int16, Int16, Int64}` and the data types of `right` were `{Int64, Int16, Int64}`, using a `PlHashSet` would result in deduplication and the comparison of `{Int16, Int64}` and `{Int64, Int16}`, which is considered equal. 

The solution was to instead use a `PlHashMap` which uses unordered comparison, but preserves the name -> data type association.

Edit: After reviewer comment, used Claude Sonnet 4.5 to help me better understand and work with `IndexMap`.

### CODE REVIEW

**Review by nameexhaustion — CHANGES_REQUESTED** [review]
Wait, why is there a need to be building a new hashset/hashmap at all? The schema is itself already an indexmap with fast lookups

**Comment by Kevin-Patyk** [comment]
Thanks for pointing that out. I made the change so it uses the `IndexMap` directly with no new `HashMap` allocations.

File: crates/polars-testing/src/asserts/utils.rs [hunk 1]
```diff
@@ -767,17 +767,17 @@ fn assert_dataframe_schema_equal(
...
-                    assertion_error = "DataFrames",
-                    "dtypes do not match",
-                    format!("{:?}", left_dtypes),
-                    format!("{:?}", right_dtypes)
-                ));
-            }
+        } else if left_schema.len() != right_schema.len()
+            || left_schema
+                .iter()
+                .any(|(name, dtype)| right_schema.get(name) != Some(dtype))
```
Comment (nameexhaustion) [inline crates/polars-testing/src/asserts/utils.rs:773]: When `right_schema.get(name)` is `None`, we need to report that the column names differ rather than reporting that dtypes differ.

Comment (Kevin-Patyk) [reply crates/polars-testing/src/asserts/utils.rs:773]: I don't think this is required. In the code above this block, the `right_schema.get(name) == None` is already handled. If column sets differ, we return a `"columns mismatch"` error before ever reaching this block. By the time we check the data types, all column names are guaranteed to be present so `get` returning `None` isn't possible.

Maybe adding a comment might make it more clear. Let me know if I should add it!

**Review by nameexhaustion — APPROVED** [review]
