### PR TITLE
fix: Selectors in `{Lazy,Data}Frame.filter`

### LINKED ISSUE #23300: Error filtering on List of Structs
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({
    "id": [1, 2],
    "data": [
        [{"name": "Alice", "age": 30}, {"name": "Bob", "age": 25}],
        [{"name": "Charlie", "age": 35}]
    ]
})

df.filter(pl.col('data').list.eval(pl.element().struct.field('name')== 'Charlie').list.all())

```

### Log output

```shell
ColumnNotFoundError: unable to find column ""; valid columns: ["id", "data"]
```

### Issue description

Filtering errors but the same `pl.Expr` with `.select` works as expected. 

### Expected behavior

Return the dataframe filtered to the single row that satisfies the condition. 

### Installed versions

<details>

```
--------Version info---------
Polars:              1.31.0
Index type:          UInt32
Platform:            Linux-6.1.129-138.220.amzn2023.x86_64-x86_64-with-glibc2.31
Python:              3.11.11 (main, Apr  8 2025, 01:38:54) [GCC 10.2.1 20210110]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  1.6.0
altair               5.5.0
azure.identity       <not installed>
boto3                1.36.24
cloudpickle          2.2.1
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2025.3.0
gevent               <not installed>
google.auth          2.38.0
great_tables         <not installed>
matplotlib           3.10.0
numpy                2.2.5
openpyxl             <not installed>
pandas               2.2.3
polars_cloud         <not installed>
pyarrow              16.1.0
pydantic             2.10.6
pyiceberg            <not installed>
sqlalchemy           2.0.38
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>```

</details>

### LINKED ISSUE #23637: Regression in `.filter()` with `.list.eval().list.any()` in 1.31.0
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from random import randint
from string import ascii_lowercase

test = pl.from_dict({
    "a": list(ascii_lowercase),
    "b": [list({randint(0, 10) for _ in range(5)}) for _ in ascii_lowercase],
})
check = {9, 10}
predicate = pl.col("b").list.eval(pl.element().is_in(check)).list.any()
test.filter(predicate)
```

### Log output

```shell
---------------------------------------------------------------------------
ColumnNotFoundError                       Traceback (most recent call last)
Cell In[2], line 10
      8 check = {9, 10}
      9 predicate = pl.col("b").list.eval(pl.element().is_in(check)).list.any()
---> 10 test.filter(predicate)

File ~/.python3.12/site-packages/polars/dataframe/frame.py:5181, in DataFrame.filter(self, *predicates, **constraints)
   5021 """
   5022 Filter rows, retaining those that match the given predicate expression(s).
   5023 
   (...)   5174 └──────┴──────┴─────┘
   5175 """
   5176 from polars.lazyframe.opt_flags import QueryOptFlags
   5178 return (
   5179     self.lazy()
   5180     .filter(*predicates, **constraints)
-> 5181     .collect(optimizations=QueryOptFlags._eager())
   5182 )

File ~/.python3.12/site-packages/polars/_utils/deprecation.py:97, in deprecate_streaming_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
     93         kwargs["engine"] = "in-memory"
     95     del kwargs["streaming"]
---> 97 return function(*args, **kwargs)

File ~/.python3.12/site-packages/polars/lazyframe/opt_flags.py:330, in forward_old_opt_flags.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    327         optflags = cb(optflags, kwargs.pop(key))  # type: ignore[no-untyped-call,unused-ignore]
    329 kwargs["optimizations"] = optflags
--> 330 return function(*args, **kwargs)

File ~/.python3.12/site-packages/polars/lazyframe/frame.py:2332, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, collapse_joins, no_optimization, engine, background, optimizations, **_kwargs)
   2330 # Only for testing purposes
   2331 callback = _kwargs.get("post_opt_callback", callback)
-> 2332 return wrap_df(ldf.collect(engine, callback))

ColumnNotFoundError: unable to find column ""; valid columns: ["a", "b"]
```

### Issue description

After upgrading to Polars 1.31.0, a previously working filter expression that uses `.list.eval().list.any()` now raises a `ColumnNotFoundError`, despite no changes to the DataFrame schema. This code worked perfectly in version 1.30.0.

### Expected behavior

This should return all rows where **at least one element** in the list in column `"b"` matches any element in the `check` set (`{9, 10}`).

### Installed versions

<details>

```
--------Version info---------
Polars:              1.31.0
Index type:          UInt32
Platform:            Linux-6.15.6-200.fc42.x86_64-x86_64-with-glibc2.41
Python:              3.12.10 (main, May  6 2025, 08:43:14) [GCC 15.1.1 20250425 (Red Hat 15.1.1-1)]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  1.7.0
altair               5.5.0
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          3.1.1
connectorx           0.4.3
deltalake            1.1.0
fastexcel            0.14.0
fsspec               2025.7.0
gevent               25.5.1
google.auth          2.40.3
great_tables         0.18.0
matplotlib           3.10.3
numpy                2.2.6
openpyxl             3.1.5
pandas               2.3.1
polars_cloud         <not installed>
pyarrow              21.0.0
pydantic             2.11.7
pyiceberg            0.9.1
sqlalchemy           2.0.41
torch                2.7.1+cu126
xlsx2csv             0.8.4
xlsxwriter           3.2.5
```

</details>

### PR DESCRIPTION
**Pull request by coastalwhite**
Fixes #23300.
Fixes #23637.

### CODE REVIEW

File: crates/polars-plan/src/plans/conversion/dsl_to_ir/expr_to_ir.rs [hunk 1]
```diff
@@ -80,10 +47,42 @@ fn to_aexpr_impl_materialized_lit(
 }
 
 pub struct ExprToIRContext<'a> {
-    pub with_fields: Option<(Node, Schema)>,
+    pub(super) with_fields: Option<(Node, Schema)>,
     pub arena: &'a mut Arena<AExpr>,
     pub schema: &'a Schema,
+
     pub allow_unknown: bool,
+    /// Check whether mentioned column names exist in the schema.
```
Comment (coastalwhite) [inline crates/polars-plan/src/plans/conversion/dsl_to_ir/expr_to_ir.rs:55]: There is a small refactor here to make it such that can pass whether to check column names or not.

**Review by ritchie46 — APPROVED** [review]
