### PR TITLE
fix(rust, python): rolling_groupy was returning incorrect results when offset was positive

### LINKED ISSUE #9077: `groupby_rolling` bug for positive values of `offset`
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Positive values of `offset` do not appear to behave as expected.  I've taken one of the the unit tests in the library, which appears to produce an incorrect result when changing `offset="1d"` to `offset="-1d"`.

I'd be keen to dig into helping fix this, but wanted to get the issue in as I'm relatively inexperienced on the rust side

### Reproducible example

```python
# Taking & minimally adapting this test: (switching offset from '-1d' to '1d)
# https://github.com/pola-rs/polars/blob/275178c25b4bebf2f2c8a88993d445b5aabc8cc9/py-polars/tests/unit/operations/test_groupby_rolling.py#LL149C1-L163C6

import polars as pl
df = pl.DataFrame(
    {
        "datetime": pl.date_range(
            datetime(2021, 11, 6),
            datetime(2021, 11, 9),
            "1d",
            time_zone=None,
            eager=True,
        ),
        "value": [1, 4, 9, 155],
    }
)
result = df.groupby_rolling(index_column="datetime", period="2d", offset="1d").agg(
    pl.col("value")
)
print(result)

# Output:
┌─────────────────────┬────────────────┐
│ datetime            ┆ value          │
│ ---                 ┆ ---            │
│ datetime[μs]        ┆ list[i64]      │
╞═════════════════════╪════════════════╡
│ 2021-11-06 00:00:00 ┆ [1, 4, 9, 155] │
│ 2021-11-07 00:00:00 ┆ []             │
│ 2021-11-08 00:00:00 ┆ []             │
│ 2021-11-09 00:00:00 ┆ []             │
└─────────────────────┴────────────────┘
```

### Expected behavior

I'd expect the following output:
```
┌─────────────────────┬────────────────┐
│ datetime            ┆ value          │
│ ---                 ┆ ---            │
│ datetime[μs]        ┆ list[i64]      │
╞═════════════════════╪════════════════╡
│ 2021-11-06 00:00:00 ┆ [9, 155]       │
│ 2021-11-07 00:00:00 ┆ [155]          │
│ 2021-11-08 00:00:00 ┆ []             │
│ 2021-11-09 00:00:00 ┆ []             │
└─────────────────────┴────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.17.15
Index type:  UInt32
Platform:    macOS-13.3.1-arm64-arm-64bit
Python:      3.11.3 (main, May 10 2023, 17:19:39) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
There's room for optimisation, but this at least closes #9077 (besides, rolling windows looking into the future don't strike me as a common use-case)

### CODE REVIEW

File: polars/polars-time/src/windows/test.rs [hunk 1]
```diff
@@ -690,15 +690,15 @@ fn test_rolling_lookback() {
...
-    assert_eq!(groups[0], [0, 5]);
-    assert_eq!(groups[1], [1, 5]);
-    assert_eq!(groups[2], [2, 5]);
-    assert_eq!(groups[3], [3, 5]);
-    assert_eq!(groups[4], [4, 5]);
-    assert_eq!(groups[5], [5, 4]);
-    assert_eq!(groups[6], [6, 3]);
-    assert_eq!(groups[7], [7, 2]);
-    assert_eq!(groups[8], [8, 0]);
+    assert_eq!(groups[0], [1, 4]); // (00:00, 02:00]
```
Comment (MarcoGorelli) [inline polars/polars-time/src/windows/test.rs:693]: not sure this test was right to begin with

if the dates are:
[00:00, 00:30, ..., 3:30, 4:00]
and the period is `2h` and the offset is `0h`, then the first window is `(00:00, 02:00]`. So that includes points: `[00:30, 01:00, 01:30, 02:00]`, i.e. the starting offset is `1`, and the length is `4`

File: polars/polars-time/src/windows/groupby.rs [hunk 2]
```diff
@@ -355,7 +355,7 @@ pub(crate) fn groupby_values_iter_partial_lookbehind<'a>(
         let b = Bounds::new(lower, upper);
 
         for &t in &time[lagging_offset..] {
-            if b.is_member(t, closed_window) || lagging_offset == i {
+            if b.is_member(t, closed_window) || (offset.negative && lagging_offset == i) {
```
Comment (ritchie46) [inline polars/polars-time/src/windows/groupby.rs:358]: Can we branch on `offset.negative` outside the loop?

Then we have two loops that compute the `lagging_offset`. The loops are super small, so almost no code bloat.

Comment (ritchie46) [reply polars/polars-time/src/windows/groupby.rs:358]: Can we actually get here if `offset.negative` isn't set? :thinking:

File: polars/polars-time/src/windows/groupby.rs [hunk 3]
```diff
@@ -400,7 +400,16 @@ pub(crate) fn groupby_values_iter_full_lookahead<'a>(
 
             let b = Bounds::new(lower, upper);
 
-            debug_assert!(i < time.len());
+            // find starting point of window
+            for &t in &time[i..] {
```
Comment (ritchie46) [inline polars/polars-time/src/windows/groupby.rs:404]: Given that we have a nested loop now. 

Can we maybe keep the old behavior for `offset= 0`?

We can branch on the `offset=?` case and have a loop for both cases.

Or don't we hit this path on the `offset=0` case?

File: polars/polars-time/src/windows/groupby.rs (hunk 2 above)
Comment (MarcoGorelli) [reply polars/polars-time/src/windows/groupby.rs:358]: only in this test

https://github.com/pola-rs/polars/blob/dc7bfd2ec362ec6fca7ebe0ff470cc11ee16f66c/polars/polars-time/src/windows/test.rs#L711-L734

maybe it's better to just remove that test then?

Comment (MarcoGorelli) [reply polars/polars-time/src/windows/groupby.rs]: I've removed this part of the test, reverted the change to `groupby_values_iter_partial_lookbehind`, and expanded the tests on the python side by doing quite a bit more parametrisation

File: polars/polars-time/src/windows/groupby.rs (hunk 3 above)
Comment (MarcoGorelli) [reply polars/polars-time/src/windows/groupby.rs]: good call, thanks - yes, but only if the window is closed on the left (if it's open on the left, then `time[i]` shouldn't be included in the group)

File: polars/polars-time/src/windows/groupby.rs [hunk 4]
```diff
@@ -398,7 +404,21 @@ pub(crate) fn groupby_values_iter_full_lookahead(
 
             let b = Bounds::new(lower, upper);
 
-            debug_assert!(i < time.len());
+            // find starting point of window
+            match inner_loop_needed {
```
Comment (ritchie46) [inline polars/polars-time/src/windows/groupby.rs:408]: This still adds a branch. 

Let's do the branch completely before `iter().enumerate()`. That makes all paths optimal.

Comment (MarcoGorelli) [reply polars/polars-time/src/windows/groupby.rs:408]: so something like
```rust
    match inner_loop_needed {
        true => {
            time[start_offset..upper_bound]
                .iter()
                .enumerate()
                .map(move |(mut i, lower)| {
                    i += start_offset;
                    let lower = add(&offset, *lower, tz.as_ref())?;
                    let upper = add(&period, lower, tz.as_ref())?;

                    let b = Bounds::new(lower, upper);

                    // find starting point of window
                    for &t in &time[i..] {
                        if b.is_member(t, closed_window) {
                            break;
                        }
                        i += 1;
                    }
                    if i >= time.len() {
                        return Ok((i as IdxSize, 0));
                    }
                    let slice = unsafe { time.get_unchecked(i..) };
                    let len = slice.partition_point(|v| b.is_member(*v, closed_window));

                    Ok((i as IdxSize, len as IdxSize))
                })
        }
        false => time[start_offset..upper_bound]
            .iter()
            .enumerate()
            .map(move |(mut i, lower)| {
                i += start_offset;
                let lower = add(&offset, *lower, tz.as_ref())?;
                let upper = add(&period, lower, tz.as_ref())?;

                let b = Bounds::new(lower, upper);

                debug_assert!(i < time.len());
                let slice = unsafe { time.get_unchecked(i..) };
                let len = slice.partition_point(|v| b.is_member(*v, closed_window));

                Ok((i as IdxSize, len as IdxSize))
            }),
    }
}
```
?

This would give
```rust
    = note: expected struct `std::iter::Map<std::iter::Enumerate<std::slice::Iter<'_, _>>, [closure@/home/marcogorelli/polars-dev/polars/polars-time/src/windows/groupby.rs:401:22: 401:43]>`
               found struct `std::iter::Map<std::iter::Enumerate<std::slice::Iter<'_, _>>, [closure@/home/marcogorelli/polars-dev/polars/polars-time/src/windows/groupby.rs:427:18: 427:39]>`
    = note: no two closures, even if identical, have the same type
    = help: consider boxing your closure and/or using it as a trait object
help: you could change the return type to be a boxed trait object
    |
381 | ) -> Box<dyn Iterator<Item = PolarsResult<(IdxSize, IdxSize)>> + TrustedLen + '_> {
    |      ~~~~~~~                                                                    +
help: if you change the return type to expect trait objects, box the returned expressions
    |
398 ~             Box::new(time[start_offset..upper_bound]
399 |                 .iter()
  ...
421 |                     Ok((i as IdxSize, len as IdxSize))
422 ~                 }))
423 |         }
424 ~         false => Box::new(time[start_offset..upper_bound]
425 |             .iter()
  ...
438 |                 Ok((i as IdxSize, len as IdxSize))
439 ~             })),
    |
```
, is that OK? Wouldn't the perf implications of using `Box` be worse than just matching a boolean?

Comment (ritchie46) [reply polars/polars-time/src/windows/groupby.rs:408]: Right, then we can do the branch on the caller location. Meaning we split into 2 functions. We already have done this earlier. We have a `full_lookahead`, a `partial_lookbehind` and a `full_lookbehind`. So now we need 1 extra, I believe?

**Comment by ritchie46** [comment]
Thanks @MarcoGorelli. Looking great now. :+1:

**Comment by MarcoGorelli** [comment]
cool, thanks for your review!
