### PR TITLE
fix: Verify `arr` namespace is called from array column

### LINKED ISSUE #25648: `collect_schema()` succeeds for `arr.*` functions on non-array columns
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue Description

Calls to `collect_schema()` when the `.arr` namespace is applied to non-array columns succeed when they should error.

```python
import polars as pl

lf = pl.LazyFrame({"a": ["a", "b", "c"]})

a = pl.col("a")

# The following raise an exception, as they should.
lf.select(a.arr.contains("z")).collect_schema()             # ERROR - OK
lf.select(a.arr.explode()).collect_schema()                 # ERROR - OK
lf.select(a.arr.agg(pl.element().len())).collect_schema()   # ERROR - OK
lf.select(a.arr.eval(pl.element().len())).collect_schema()  # ERROR - OK
lf.select(a.arr.sum()).collect_schema()                     # ERROR - OK
lf.select(a.arr.to_list()).collect_schema()                 # ERROR - OK
lf.select(a.arr.to_struct()).collect_schema()               # ERROR - OK
lf.select(a.arr.unique()).collect_schema()                  # ERROR - OK

# The following succeed when they should raise an exception.
lf.select(a.arr.all()).collect_schema()                     # Schema({'a': Boolean})
lf.select(a.arr.any()).collect_schema()                     # Schema({'a': Boolean})
lf.select(a.arr.arg_max()).collect_schema()                 # Schema({'a': UInt32})
lf.select(a.arr.arg_min()).collect_schema()                 # Schema({'a': UInt32})
lf.select(a.arr.count_matches("z")).collect_schema()        # Schema({'a': UInt32})
lf.select(a.arr.first()).collect_schema()                   # Schema({'a': Unknown})
lf.select(a.arr.get(0)).collect_schema()                    # Schema({'a': Unknown})
lf.select(a.arr.join("")).collect_schema()                  # Schema({'a': String})
lf.select(a.arr.last()).collect_schema()                    # Schema({'a': Unknown})
lf.select(a.arr.len()).collect_schema()                     # Schema({'a': Unknown})
lf.select(a.arr.max()).collect_schema()                     # Schema({'a': Unknown})
lf.select(a.arr.mean()).collect_schema()                    # Schema({'a': String})
lf.select(a.arr.median()).collect_schema()                  # Schema({'a': String})
lf.select(a.arr.min()).collect_schema()                     # Schema({'a': Unknown})
lf.select(a.arr.n_unique()).collect_schema()                # Schema({'a': UInt32})
lf.select(a.arr.reverse()).collect_schema()                 # Schema({'a': String})
lf.select(a.arr.shift(1)).collect_schema()                  # Schema({'a': String})
lf.select(a.arr.sort()).collect_schema()                    # Schema({'a': String})
lf.select(a.arr.std()).collect_schema()                     # Schema({'a': String})
lf.select(a.arr.var()).collect_schema()                     # Schema({'a': String})
```

### Installed versions

main

### PR DESCRIPTION
**Pull request by mcrumiller**
Fixes #25648.

I left out `arr.agg` and `arr.eval` from the unit test because these take a separate path and have a separate error message.

### CODE REVIEW

File: crates/polars-plan/src/plans/aexpr/function_expr/list.rs [hunk 1]
```diff
@@ -60,6 +60,18 @@ pub enum IRListFunction {
...
+    pub fn ensure_is_list(self) -> PolarsResult<Self> {
+        let dt = self.args()[0].dtype();
+        polars_ensure!(
+            dt.is_list(),
+            InvalidOperation: format!("expected List data type for list operation, got: {:?}", dt)
+        );
+        Ok(self)
+    }
+}
+
```
Comment (mcrumiller) [inline crates/polars-plan/src/plans/aexpr/function_expr/list.rs:74]: I moved this here since it's only ever referenced in this module, so it makes a bit more sense here. Also, we now use the debug formatting for the output datatype to better align with our polars datatypes, i.e. we now get `List(Int8)` instead of `list[i8]`.

**Review by nameexhaustion — APPROVED** [review]
