### PR TITLE
fix(rust, python): Fix struct get field by index out of bounds error.

### LINKED ISSUE #10096: `.struct[n]` raises "index out of bounds in `struct.field`" for a valid index
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"val": [{"a": 1, "b": 2}]})

df.select(pl.col("val").struct[0])
# shape: (1, 1)
# ┌─────┐
# │ a   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 1   │
# └─────┘

df.select(pl.col("val").struct[1])
# ComputeError: index out of bounds in `struct.field`

df.select(pl.col("val").struct[-1])
# shape: (1, 1)
# ┌─────┐
# │ b   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 2   │
# └─────┘
```

### Issue description

Trying to extract a struct field by index only seems to work for `0` or negative indexing e.g. `[-1]`

### Expected behavior

```
# shape: (1, 1)
# ┌─────┐
# │ b   │
# │ --- │
# │ i64 │
# ╞═════╡
# │ 2   │
# └─────┘
```

### Installed versions

<details>

```
Polars: 0.18.8
```

</details>

### PR DESCRIPTION
**Pull request by cmdlineluser**
fixes #10096

I've just copied the behaviour from the `FieldByName` block.

### CODE REVIEW

File: polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs [hunk 1]
```diff
@@ -177,9 +177,14 @@ impl FunctionExpr {
...
-                        fields.get(index).cloned().ok_or_else(
-                            || polars_err!(ComputeError: "index out of bounds in `struct.field`"),
-                        )
+                        if let DataType::Struct(flds) = &fields[0].dtype {
+                            let fld = flds.get(index).cloned().ok_or_else(
+                            || polars_err!(ComputeError: "index out of bounds in `struct.field`")
+                            )?;
+                            Ok(fld)
+                        } else {
+                            polars_bail!(ComputeError: "index out of bounds in `struct.field`");
```
Comment (ritchie46) [inline polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs:186]: I believe this should be `unreachable!`. We only get here via the `struct` namespace. 

If not, we must return an error indicating that we expected a struct.

File: polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs [hunk 2]
```diff
@@ -177,9 +177,14 @@ impl FunctionExpr {
                 match s {
                     FieldByIndex(index) => {
                         let (index, _) = slice_offsets(*index, 0, fields.len());
-                        fields.get(index).cloned().ok_or_else(
-                            || polars_err!(ComputeError: "index out of bounds in `struct.field`"),
-                        )
+                        if let DataType::Struct(flds) = &fields[0].dtype {
+                            let fld = flds.get(index).cloned().ok_or_else(
```
Comment (ritchie46) [inline polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs:181]: Don't need to assign to `fld` and unwrap the error with `?`.

We can directly return this expression.

**Comment by ritchie46** [comment]
Thanks you @cmdlineluser. Looks great.
