### PR TITLE
fix(rust, python): respect time zone in rolling_* functions

### LINKED ISSUE #7640: rolling_* functions don't respect time zone
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Time zones aren't respected in the `rolling_*` functions

The code below returns
```python
shape: (6, 3)
┌──────────────────────────┬─────────────────────┬───────┐
│ ts                       ┆ tsn                 ┆ value │
│ ---                      ┆ ---                 ┆ ---   │
│ datetime[μs, US/Central] ┆ datetime[μs]        ┆ f64   │
╞══════════════════════════╪═════════════════════╪═══════╡
│ 2021-11-05 00:00:00 CDT  ┆ 2021-11-05 00:00:00 ┆ null  │
│ 2021-11-06 00:00:00 CDT  ┆ 2021-11-06 00:00:00 ┆ 1.0   │
│ 2021-11-07 00:00:00 CDT  ┆ 2021-11-07 00:00:00 ┆ 2.0   │
│ 2021-11-08 00:00:00 CST  ┆ 2021-11-08 00:00:00 ┆ null  │
│ 2021-11-09 00:00:00 CST  ┆ 2021-11-09 00:00:00 ┆ 4.0   │
│ 2021-11-10 00:00:00 CST  ┆ 2021-11-10 00:00:00 ┆ 5.0   │
└──────────────────────────┴─────────────────────┴───────┘
shape: (6, 3)
┌──────────────────────────┬─────────────────────┬───────┐
│ ts                       ┆ tsn                 ┆ value │
│ ---                      ┆ ---                 ┆ ---   │
│ datetime[μs, US/Central] ┆ datetime[μs]        ┆ f64   │
╞══════════════════════════╪═════════════════════╪═══════╡
│ 2021-11-05 00:00:00 CDT  ┆ 2021-11-05 00:00:00 ┆ null  │
│ 2021-11-06 00:00:00 CDT  ┆ 2021-11-06 00:00:00 ┆ 1.0   │
│ 2021-11-07 00:00:00 CDT  ┆ 2021-11-07 00:00:00 ┆ 2.0   │
│ 2021-11-08 00:00:00 CST  ┆ 2021-11-08 00:00:00 ┆ 3.0   │
│ 2021-11-09 00:00:00 CST  ┆ 2021-11-09 00:00:00 ┆ 4.0   │
│ 2021-11-10 00:00:00 CST  ┆ 2021-11-10 00:00:00 ┆ 5.0   │
└──────────────────────────┴─────────────────────┴───────┘
```

Notice the extra null in the first case when DST is crossed

### Reproducible example

```python
ts = pl.date_range(
    datetime(2021, 11, 5), datetime(2021, 11, 10), "1d", time_zone="UTC"
).dt.replace_time_zone("US/Central")
df = pl.DataFrame(
    {"ts": ts, "tsn": ts.dt.replace_time_zone(None), "value": [1, 2, 3, 4, 5, 6]}
)
print(df.with_columns(pl.col("value").rolling_mean("1d", by="ts")))
print(df.with_columns(pl.col("value").rolling_mean("1d", by="tsn")))
```

### Expected behavior

```python
shape: (6, 3)
┌──────────────────────────┬─────────────────────┬───────┐
│ ts                       ┆ tsn                 ┆ value │
│ ---                      ┆ ---                 ┆ ---   │
│ datetime[μs, US/Central] ┆ datetime[μs]        ┆ f64   │
╞══════════════════════════╪═════════════════════╪═══════╡
│ 2021-11-05 00:00:00 CDT  ┆ 2021-11-05 00:00:00 ┆ null  │
│ 2021-11-06 00:00:00 CDT  ┆ 2021-11-06 00:00:00 ┆ 1.0   │
│ 2021-11-07 00:00:00 CDT  ┆ 2021-11-07 00:00:00 ┆ 2.0   │
│ 2021-11-08 00:00:00 CST  ┆ 2021-11-08 00:00:00 ┆ 3.0   │
│ 2021-11-09 00:00:00 CST  ┆ 2021-11-09 00:00:00 ┆ 4.0   │
│ 2021-11-10 00:00:00 CST  ┆ 2021-11-10 00:00:00 ┆ 5.0   │
└──────────────────────────┴─────────────────────┴───────┘
```

Will make a PR

### Installed versions

<details>

```
---Version info---
Polars: 0.16.14
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.8.16 (default, Dec  7 2022, 01:12:06)
[GCC 11.3.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 2.0.0rc1
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.6.2
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #7640 

one step closer towards full time zone support

example from the issue:
```python
In [1]: ts = pl.date_range(
   ...:     datetime(2021, 11, 5), datetime(2021, 11, 10), "1d", time_zone="UTC"
   ...: ).dt.replace_time_zone("US/Central")
   ...: df = pl.DataFrame(
   ...:     {"ts": ts, "tsn": ts.dt.replace_time_zone(None), "value": [1, 2, 3, 4, 5, 6]}
   ...: )
   ...: print(df.with_columns(pl.col("value").rolling_mean("1d", by="ts")))
   ...: print(df.with_columns(pl.col("value").rolling_mean("1d", by="tsn")))
shape: (6, 3)
┌──────────────────────────┬─────────────────────┬───────┐
│ ts                       ┆ tsn                 ┆ value │
│ ---                      ┆ ---                 ┆ ---   │
│ datetime[μs, US/Central] ┆ datetime[μs]        ┆ f64   │
╞══════════════════════════╪═════════════════════╪═══════╡
│ 2021-11-05 00:00:00 CDT  ┆ 2021-11-05 00:00:00 ┆ null  │
│ 2021-11-06 00:00:00 CDT  ┆ 2021-11-06 00:00:00 ┆ 1.0   │
│ 2021-11-07 00:00:00 CDT  ┆ 2021-11-07 00:00:00 ┆ 2.0   │
│ 2021-11-08 00:00:00 CST  ┆ 2021-11-08 00:00:00 ┆ 3.0   │
│ 2021-11-09 00:00:00 CST  ┆ 2021-11-09 00:00:00 ┆ 4.0   │
│ 2021-11-10 00:00:00 CST  ┆ 2021-11-10 00:00:00 ┆ 5.0   │
└──────────────────────────┴─────────────────────┴───────┘
shape: (6, 3)
┌──────────────────────────┬─────────────────────┬───────┐
│ ts                       ┆ tsn                 ┆ value │
│ ---                      ┆ ---                 ┆ ---   │
│ datetime[μs, US/Central] ┆ datetime[μs]        ┆ f64   │
╞══════════════════════════╪═════════════════════╪═══════╡
│ 2021-11-05 00:00:00 CDT  ┆ 2021-11-05 00:00:00 ┆ null  │
│ 2021-11-06 00:00:00 CDT  ┆ 2021-11-06 00:00:00 ┆ 1.0   │
│ 2021-11-07 00:00:00 CDT  ┆ 2021-11-07 00:00:00 ┆ 2.0   │
│ 2021-11-08 00:00:00 CST  ┆ 2021-11-08 00:00:00 ┆ 3.0   │
│ 2021-11-09 00:00:00 CST  ┆ 2021-11-09 00:00:00 ┆ 4.0   │
│ 2021-11-10 00:00:00 CST  ┆ 2021-11-10 00:00:00 ┆ 5.0   │
└──────────────────────────┴─────────────────────┴───────┘
```

### CODE REVIEW

File: polars/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs [hunk 1]
```diff
@@ -42,11 +46,29 @@ pub(crate) fn rolling_min<T>(
...
+        },
+        _ => groupby_values_iter(
+            period,
+            offset,
+            time,
+            closed_window,
+            tu,
+            NO_TIMEZONE.copied(),
+        ),
+    };
```
Comment (MarcoGorelli) [inline polars/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs:71]: I wanted to take this parsing one level up, but couldn't figure out how to satisfy the borrow checker in 

https://github.com/pola-rs/polars/blob/26305c1e6b91e90e387b371ef7f6b1a9a23ff10f/polars/polars-time/src/chunkedarray/rolling_window/mod.rs#L230-L240

File: polars/polars-time/src/windows/groupby.rs [hunk 2]
```diff
@@ -265,9 +267,8 @@ pub(crate) fn groupby_values_iter_full_lookbehind(
             }
             last = *lower;
             i += start_offset;
-            // TODO remove unwrap once time zone is respected
-            let lower = add(&offset, *lower, NO_TIMEZONE).unwrap();
-            let upper = add(&period, lower, NO_TIMEZONE).unwrap();
+            let lower = add(tu)(&offset, *lower, tz.as_ref()).unwrap();
+            let upper = add(tu)(&period, lower, tz.as_ref()).unwrap();
```
Comment (MarcoGorelli) [inline polars/polars-time/src/windows/groupby.rs:271]: I couldn't figure out how to remove the `unwrap` here - if I put `.collect()` after `map`, then I get an error saying that I need a type hint, but I couldn't figure out how to do that when the result type is
```
impl Iterator<Item = (IdxSize, IdxSize)> + TrustedLen + 'a
```

**Comment by ritchie46** [comment]
Thanks @MarcoGorelli. I can pull this in later and see if I can help please the bchk. :)

File: polars/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs (hunk 1 above)
Comment (ritchie46) [reply polars/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs:71]: I don't think we can parse it a level higher as the function is generic. E.g. `impl TimeZoneTrait` has two implementations.

To parse this a level higher means that the function we accept in `rolling_agg` must be generic over the timezone type. This is possible, but I'd leave that to an exercise after this PR.

File: polars/polars-time/src/windows/groupby.rs (hunk 2 above)
Comment (ritchie46) [reply polars/polars-time/src/windows/groupby.rs:271]: The `collect` would materialize this iterator, which is not the return type. We return a type that implements the iterator trait, so no collection. :)

Comment (MarcoGorelli) [reply polars/polars-time/src/windows/groupby.rs:271]: thanks for your review and for explaining!

Do you know of another way to propagate the error from here? Because `add(tu)(&offset, *lower, tz.as_ref())` could potentially land on an ambiguous or non-existent datetime, which would raise

Comment (MarcoGorelli) [reply polars/polars-time/src/windows/groupby.rs:271]: yup (though it would only be fallible in the tz-aware case)

OK, thanks, I'll take a look, might be a good exercise in getting better at Rust

Comment (ritchie46) [reply polars/polars-time/src/windows/groupby.rs:271]: Yes. I'd recommend understanding the impl and dyn trait difference here. As we probably must return an enum with dynamic trait implementors here.
