### PR TITLE
fix(rust, python): fix cse input schema

### LINKED ISSUE #10441: ColumnNotFound when CSE takes effect
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

Enable `comm_subexpr_elim`. 

Run the following code:

```rust
let df = df!("a" => [1,2,3], "b" => [3,2,1])?;
let lazy_frame = df.lazy().select(
               [col("a").sum() + col("a").sum() + col("b").sum()]
               ).collect()?;
```

You will get `Error: ColumnNotFound(ErrString("b"))`.

### Issue description

Through some investigation, I have found that this is due to the `alp's schema(i.e. project's schema)` is used when `find_cse`:

https://github.com/pola-rs/polars/blob/6634621bff01a0c2006c576c473b38c7a98741d1/crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs#L657-L670

This will prevent us from finding `b's Field` when we alias the expression:
https://github.com/pola-rs/polars/blob/6634621bff01a0c2006c576c473b38c7a98741d1/crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs#L604-L608

IIUC, this can be fixed by pass the `input schema` instead of `project schema / current alp's schema` to `find_cse`. 
BTW, for `HStack` and `Aggregate`, the same applies.

```rust
let input_schema = lp_arena.get(input.clone()).schema(lp_arena);
```

### Expected behavior

Get the same result as when `comm_subexpr_elim` is not disabled.
```
┌─────┐
│ a   │
│ --- │
│ i32 │
╞═════╡
│ 18  │
└─────┘
```

### Installed versions

<details>

Latetest `main` branch(commit: 6634621b).

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #10441

### CODE REVIEW

File: crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs [hunk 1]
```diff
@@ -684,7 +684,7 @@ impl<'a> RewritingVisitor for CommonSubExprOptimizer<'a> {
                     schema,
                     options,
                 } => {
-                    let input_schema = alp.schema(lp_arena);
+                    let input_schema = lp_arena.get(*input).schema(lp_arena);
```
Comment (reswqa) [inline crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs:687]: I wonder if `ALogicalPlan::Aggregate` also need the same fix? 🤔

Comment (ritchie46) [reply crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs:687]: You are right. Missed that one.

Comment (reswqa) [reply crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs:687]: I have an issue unrelated to this change, but I would like to receive quick confirmation here:

Do you think that `col ("b").sum() + col("a").sum().over ([col ("b")]) + col ("b").sum()` can be reused for `col("b").sum()`. If so, I would open an issue.
