### PR TITLE
fix(python): dont incorrectly infer Zulu time

### LINKED ISSUE #6375: Z directive ignored in strptime?
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Z can be used to signify `UTC`, but it looks like it's ignored

### Reproducible example

```python
In [1]: pl.Series(['2020-01-01T03:04:05Z']).str.strptime(pl.Datetime)
Out[1]:
shape: (1,)
Series: '' [datetime[μs]]
[
        2020-01-01 03:04:05
]
```

### Expected behavior

```python
shape: (1,)
Series: '' [datetime[μs, UTC]]
[
        2020-01-01 03:04:05 UTC
]
```

Python stdlib comparison:
```python
In [6]: dt.datetime.fromisoformat('2020-01-01T03:04:05Z')
Out[6]: datetime.datetime(2020, 1, 1, 3, 4, 5, tzinfo=datetime.timezone.utc)
```

---

Looking into this

### Installed versions

<details>

```
---Version info---
Polars: 0.15.16
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.1 (main, Dec  7 2022, 01:11:34) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #6375 

As mentioned in the issue, I don't think the current treatment of the `Z` suffix is correct (at least, it's inconsistent with the Python stdlib `datetime`), so rather than returning potentially unexpected results, I'd like to suggest it'd be better to not infer this and just raise - people can just specify `fmt` and set the timezone according to what they want

It would be nice to fix this, but I'd like to suggest to first remove the incorrect inference, and then to infer this properly (as tz-aware) in a separate PR: looks like chrono handles it properly already anyway:
```console
(.311venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ cat src/main.rs
use chrono::{DateTime};


fn main() {
    let parse_from_str = DateTime::parse_from_str;
    let ts = "2000-01-01T01:23:34Z";
    let fmt = "%+";
    let parsed = parse_from_str(ts, fmt);
    println!("{:?}", parsed);
}
(.311venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/tmp`
Ok(2000-01-01T01:23:34+00:00)
```

### CODE REVIEW

File: polars/polars-time/src/chunkedarray/utf8/patterns.rs [hunk 1]
```diff
@@ -59,22 +59,15 @@ pub(super) static DATETIME_Y_M_D: &[&str] = &[
...
     "%Y-%m-%d %H:%M:%S",
-    // 21/12/31 24:58:01
-    "%y/%m/%d %H:%M:%S",
     //210319 23:58:50
     "%y%m%d %H:%M:%S",
     // 2019-04-18T02:45:55
     // 2021/12/31 12:54:98
     "%Y/%m/%d %H:%M:%S",
-    // 2021-12-31 24:58:01
-    "%Y-%m-%d %H:%M:%S",
```
Comment (MarcoGorelli) [inline polars/polars-time/src/chunkedarray/utf8/patterns.rs:70]: already on line 61

File: polars/polars-time/src/chunkedarray/utf8/patterns.rs [hunk 2]
```diff
@@ -59,22 +59,15 @@ pub(super) static DATETIME_Y_M_D: &[&str] = &[
...
-    // 2021/12/31 24:58:01
-    "%Y/%m/%d %H:%M:%S",
```
Comment (MarcoGorelli) [inline polars/polars-time/src/chunkedarray/utf8/patterns.rs:72]: already on line 68 (now 66)

File: polars/polars-time/src/chunkedarray/utf8/patterns.rs [hunk 3]
```diff
@@ -94,10 +87,6 @@ pub(super) static DATETIME_Y_M_D: &[&str] = &[
     // 2021/12/31 11:54 PM
     "%Y/%m/%d %I:%M %p",
     "%Y-%m-%d %I:%M %p",
-    // --
```
Comment (ritchie46) [inline polars/polars-time/src/chunkedarray/utf8/patterns.rs:97]: Was this removed by accident?

Comment (MarcoGorelli) [reply polars/polars-time/src/chunkedarray/utf8/patterns.rs:97]: I wasn't really sure what the pattern of comment separators was, but I've put it back now

**Comment by ritchie46** [comment]
Thanks. Could you add a docstring maybe to educate users how to parse zulu time?

**Comment by MarcoGorelli** [comment]
sure, added

WIP, but I've included an example of this here too https://github.com/pola-rs/polars-book/pull/234/files

**Comment by alexander-beedie** [comment]
@MarcoGorelli: we have a long-standing joke at work that timezone-aware datetimes are where software and developer expectations/hopes/dreams collide and die, so it's great to see you tackling this stuff. (There's a reason we enforce UTC at the environment level in our platform - at least you have to _try_ to find yourself in the wrong timezone... :)
