### PR TITLE
fix: Properly handle `to_physical_repr` of nested types

### LINKED ISSUE #20308: Decimals in Lists fail to roundtrip the row encoding
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

dtype = pl.List(pl.Decimal(precision=3, scale=2))
df = pl.Series('a', [["0.1"]], dtype).to_frame()

print(df)
re = df._row_encode([(False, False, False)])
rt = re._row_decode([('a', dtype)], [(False, False, False)])
print(rt)
```

### Log output

```shell
shape: (1, 1)
┌────────────────────┐
│ a                  │
│ ---                │
│ list[decimal[3,2]] │
╞════════════════════╡
│ [0.10]             │
└────────────────────┘
shape: (1, 1)
┌────────────────────┐
│ a                  │
│ ---                │
│ list[decimal[3,2]] │
╞════════════════════╡
│ [0.00]             │
└────────────────────┘
```

### Issue description

Information is lost when putting a decimal in a list through the row encoding

### Expected behavior

Decimals in Lists should be able to roundtrip the row encoding

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

### PR DESCRIPTION
**Pull request by coastalwhite**
Fixes #20308.

### CODE REVIEW

File: crates/polars-core/src/chunked_array/ops/row_encode.rs [hunk 1]
```diff
@@ -70,7 +70,11 @@ pub fn encode_rows_vertical_par_unordered_broadcast_nulls(
     ))
 }
 
-pub fn get_row_encoding_dictionary(dtype: &DataType) -> Option<RowEncodingContext> {
+/// Get the [`RowEncodingContext`] for a certain [`DataType`].
+///
+/// This should be given the logical type in order to communicate Polars datatype information down
+/// into the row encoding / decoding.
+pub fn get_row_encoding_context(dtype: &DataType) -> Option<RowEncodingContext> {
```
Comment (coastalwhite) [inline crates/polars-core/src/chunked_array/ops/row_encode.rs:77]: This is a drive-by change. This name is much better for this function.
