### PR TITLE
fix: Refactor `BinaryExpr` in `group_by` dispatch logic

### LINKED ISSUE #16660: Filtering a columns while using 'over' doesnt work as expected
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
data_with_groups = pl.DataFrame({
        "year": [2020, 2021, 2022] * 3,
        "groups": ["A"] * 3 + ["B"] * 3 + ["C"] * 3, 
        "data": [1, 2, 3, 10, 20, 30, 20, 20, 40]
    })

print(data_with_groups)

print(
    data_with_groups
    .with_columns(
        pl.col('data')
        .truediv(pl.col('data').filter(pl.col('year') == 2021))
        .over('groups')
        .alias('ratio')
    )
)
```

### Log output

_No response_

### Issue description

Hi! found this issue the other week, not sure if its a bug or a feature, however it does not seem to make sense if intentional. 

When using a 'filter' within an 'over' expression, it doesn't create the correct groupings. I'm not really sure what it selects but it doesn't seem to work correctly.

When doing a similar thing without grouping, it works as intended.

Thankfully you can use the `first` method which then corrects the odd behavior. However, if this is the intentional way of achieving the goal, it feels very clunky and there is nothing in place to prevent filtering too many items (multiple years in this examples case) and the `first` selecting the incorrect item.

### Expected behavior

This is the expected behavior without grouping:
```
>>> data_no_groups = pl.DataFrame({
        "year": [2020, 2021, 2022],
        "data": [1, 2, 3]
    })

>>> print(data_no_groups)
shape: (3, 2)
┌──────┬──────┐
│ year ┆ data │
│ ---  ┆ ---  │
│ i64  ┆ i64  │
╞══════╪══════╡
│ 2020 ┆ 1    │
│ 2021 ┆ 2    │
│ 2022 ┆ 3    │
└──────┴──────┘

>>> print(
    data_no_groups
    .with_columns(
        pl.col('data')
        .truediv(pl.col('data').filter(pl.col('year') == 2021))
        .alias('ratio')
    )
)
shape: (3, 3)
┌──────┬──────┬───────┐
│ year ┆ data ┆ ratio │
│ ---  ┆ ---  ┆ ---   │
│ i64  ┆ i64  ┆ f64   │
╞══════╪══════╪═══════╡
│ 2020 ┆ 1    ┆ 0.5   │
│ 2021 ┆ 2    ┆ 1.0   │
│ 2022 ┆ 3    ┆ 1.5   │
└──────┴──────┴───────┘
```

And as mentioned, you can get the expected behavior with grouping by using `.first()`. 
```
>>> data_with_groups = pl.DataFrame({
        "year": [2020, 2021, 2022] * 3,
        "groups": ["A"] * 3 + ["B"] * 3 + ["C"] * 3, 
        "data": [1, 2, 3, 10, 20, 30, 20, 20, 40]
    })

>>> print(
    data_with_groups
    .with_columns(
        pl.col('data')
        .truediv(pl.col('data').filter(pl.col('year') == 2021).first())
        .over('groups')
        .alias('ratio')
    )
)

shape: (9, 4)
┌──────┬────────┬──────┬───────┐
│ year ┆ groups ┆ data ┆ ratio │
│ ---  ┆ ---    ┆ ---  ┆ ---   │
│ i64  ┆ str    ┆ i64  ┆ f64   │
╞══════╪════════╪══════╪═══════╡
│ 2020 ┆ A      ┆ 1    ┆ 0.5   │
│ 2021 ┆ A      ┆ 2    ┆ 1.0   │
│ 2022 ┆ A      ┆ 3    ┆ 1.5   │
│ 2020 ┆ B      ┆ 10   ┆ 0.5   │
│ 2021 ┆ B      ┆ 20   ┆ 1.0   │
│ 2022 ┆ B      ┆ 30   ┆ 1.5   │
│ 2020 ┆ C      ┆ 20   ┆ 1.0   │
│ 2021 ┆ C      ┆ 20   ┆ 1.0   │
│ 2022 ┆ C      ┆ 40   ┆ 2.0   │
└──────┴────────┴──────┴───────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.31
Index type:           UInt32
Platform:             Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
Python:               3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.2.0
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               2.2.0
pyarrow:              15.0.0
pydantic:             2.6.1
pyiceberg:            <not installed>
pyxlsb:               1.0.10
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             0.8.1
xlsxwriter:           <not installed>
```

</details>

### LINKED ISSUE #19991: Filter on the right hand side of a binary operation on expression is ignored in `group_by` context.
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

def sub(lhs: pl.Expr, rhs: pl.Expr | int) -> pl.Expr:
    return lhs - rhs

def sub2(lhs: pl.Expr, rhs: pl.Expr | int) -> pl.Expr:
    return -rhs + lhs

grouped_df = pl.DataFrame(
    {
        "id": ["a", "a", "a", "b", "b"],
        "x": [0, 1, 1, 1, 1],
        "y": range(5),
    }
).group_by("id")

x_pos = pl.col("x") > 0

grouped_df.agg(sub(pl.col("y").filter(x_pos), pl.lit(2)))
grouped_df.agg(sub(pl.col("y").filter(x_pos), 2))
#  ┌─────┬───────────┐
#  │ id  ┆ y         │
#  │ --- ┆ ---       │
#  │ str ┆ list[i64] │
#  ╞═════╪═══════════╡
#  │ b   ┆ [1, 2]    │
#  │ a   ┆ [-1, 0]   │
#  └─────┴───────────┘

grouped_df.agg(sub2(pl.col("y").filter(x_pos), pl.lit(2)))
grouped_df.agg(sub2(pl.col("y").filter(x_pos), 2))
#  ┌─────┬─────────────┐
#  │ id  ┆ literal     │
#  │ --- ┆ ---         │
#  │ str ┆ list[i64]   │
#  ╞═════╪═════════════╡
#  │ a   ┆ [-2, -1, 0] │
#  │ b   ┆ [1, 2]      │
#  └─────┴─────────────┘

grouped_df.agg(sub2(pl.col("y"), pl.lit(2).filter(x_pos)))
#  ┌─────┬───────────┐
#  │ id  ┆ y         │
#  │ --- ┆ ---       │
#  │ str ┆ list[i64] │
#  ╞═════╪═══════════╡
#  │ b   ┆ [1, 2]    │
#  │ a   ┆ [-1, 0]   │
#  └─────┴───────────┘

```

### Log output

```shell
keys/aggregates are not partitionable: running default HASH AGGREGATION
```

### Issue description

When creating a new expression inside a `.group_by` context by applying a binary operation to two existing expression with one containing a `.filter` expression, then the `.filter` is used only if it appears on the left hand side. If it appears on the right hand side, it is silently dropped.

* The `.group_by` context is essential here: using one of the above expressions in a `.select` context yields a `ShapeError: cannot evaluate two Series of different lengths (4 and 5)`.
* The behavior is not tied to the `pl.lit`. Using `pl.col("x")` in place of `pl.lit(2)` above essentially yields the same behavior.

### Expected behavior

In general, I guess a `ShapeError`. However, in case of a unfiltered literal it would be nice for the length of the implicit literal column to adapt to the filtered part.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.15.0
Index type:          UInt32
Platform:            Linux-6.8.0-109048-tuxedo-x86_64-with-glibc2.39
Python:              3.12.7 (main, Oct 20 2024, 10:55:11) [GCC 13.2.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          3.1.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         <not installed>
numpy                2.0.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### LINKED ISSUE #24504: Sort in `add` expr in `group_by` context propagates to other column
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"g": [10, 10, 10], "a": [2, 1, 3], "b": [100, 200, 300]})

# NotAgg, NotAgg
out = df.group_by("g").agg(pl.col("a").sort() + pl.col("b"))
print(out)

# more info
print(df)
out = df.group_by("g").agg(
    [
        pl.col("a").sort(),
        pl.col("b"),
        (pl.col("a").sort() + pl.col("b")).alias("add"),
    ]
)
print(out)

```

### Log output

```shell
shape: (1, 2)
┌─────┬─────────────────┐
│ g   ┆ a               │
│ --- ┆ ---             │
│ i64 ┆ list[i64]       │
╞═════╪═════════════════╡
│ 10  ┆ [201, 102, 303] │
└─────┴─────────────────┘
shape: (3, 3)
┌─────┬─────┬─────┐
│ g   ┆ a   ┆ b   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 10  ┆ 2   ┆ 100 │
│ 10  ┆ 1   ┆ 200 │
│ 10  ┆ 3   ┆ 300 │
└─────┴─────┴─────┘
shape: (1, 4)
┌─────┬───────────┬─────────────────┬─────────────────┐
│ g   ┆ a         ┆ b               ┆ add             │
│ --- ┆ ---       ┆ ---             ┆ ---             │
│ i64 ┆ list[i64] ┆ list[i64]       ┆ list[i64]       │
╞═════╪═══════════╪═════════════════╪═════════════════╡
│ 10  ┆ [1, 2, 3] ┆ [100, 200, 300] ┆ [201, 102, 303] │
└─────┴───────────┴─────────────────┴─────────────────┘
```

### Issue description

Sorting one column in the argument of a binary expression propagates to the other column.

Code insight: groups mismatch in all `NotAggregated` states in `BinaryExpr`.

### Expected behavior

Sort should be contained to the appropriate expression.

```
shape: (1, 2)
┌─────┬─────────────────┐
│ g   ┆ a               │
│ --- ┆ ---             │
│ i64 ┆ list[i64]       │
╞═════╪═════════════════╡
│ 10  ┆ [101, 202, 303] │
└─────┴─────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.33.1
Index type:          UInt32
Platform:            Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
Python:              3.13.5 (main, Jul 18 2025, 09:47:32) [GCC 13.3.0]
LTS CPU:             False
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #24504
fixes #19991 
fixes #16660 
fixed undocumented issues (e.g. mismatching groups similar to #24500 but for BinaryExpr)

This PR is a refactor similar to https://github.com/pola-rs/polars/pull/24520/ but for `BinaryExpr` instead of `ApplyExpr`. It includes regression tests for all combinations of aggstates, with and without partial sort, as well as raising an error on groups mismatch.

*Edit 2025-10-10: ready for review and merge
Ping @coastalwhite

### CODE REVIEW

File: crates/polars-expr/src/expressions/binary.rs [hunk 1]
```diff
@@ -125,19 +125,66 @@ impl BinaryExpr {
...
 
-        // Drop lhs so that we might operate in place.
-        drop(ac_l.take());
+        // The first non-LiteralScalar AC will be used as the base AC to retain the context
+        let left_is_literal = ac_l.is_literal();
 
-        let out = apply_operator_owned(lhs, rhs, self.op)?;
-        ac_l.with_values(out, aggregated, Some(&self.expr))?;
-        Ok(ac_l)
+        match if !left_is_literal {
```
Comment (coastalwhite) [inline crates/polars-expr/src/expressions/binary.rs]: I would usually consider this quite an anti-pattern.

What you probably want is:

```rust
match (ac_l.agg_state(), ac_r.agg_state()) {
    (AggState::Literal(lit), AggState::AggregatedList(lst)) | (AggState::AggregatedList(lst), AggState::Literal(lit)) => {
        // ...
    },
    _ => {
    },
}
```

File: crates/polars-expr/src/expressions/binary.rs [hunk 2]
```diff
@@ -125,19 +125,66 @@ impl BinaryExpr {
...
+            ac_l.agg_state()
+        } else {
+            ac_r.agg_state()
+        } {
+            AggState::AggregatedList(s) => {
+                let ca = s.list().unwrap();
+                let cols = [&ac_l, &ac_r]
```
Comment (coastalwhite) [inline crates/polars-expr/src/expressions/binary.rs]: Why does this need to be collected into a vec?

Comment (kdn36) [reply crates/polars-expr/src/expressions/binary.rs]: It does not. Updated.

File: crates/polars-expr/src/expressions/binary.rs (hunk 1 above)
Comment (kdn36) [reply crates/polars-expr/src/expressions/binary.rs]: Thanks, ack. Updated. Note that 2x AggList also matches this branch.
