### PR TITLE
fix: Make `meta.pop` operate on `Expr` only

### LINKED ISSUE #23760: Regression in 1.32.0-beta.1, `meta.pop` fails for pushed down predicate in custom io source
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
batches_expr = pl.col("int_value").map_batches(lambda x: x > 5, return_dtype=pl.Boolean, is_elementwise=True)
print(f'{batches_expr.meta.pop() = }')
```

### Log output

```shell
Traceback (most recent call last):
  File "test_file.py", line 3, in <module>
    print(f'{batches_expr.meta.pop() = }')
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/polars/expr/meta.py", line 237, in pop
    return [wrap_expr(e) for e in self._pyexpr.meta_pop(schema)]
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ColumnNotFoundError: int_value
```

### Issue description

In the new pre-release version of polars, I get an error when a predicate with `map_batches` has`.meta.pop()` called on it.  The error generated is a `ColumnNotFoundError`

### Expected behavior

On polars `1.31.0` I get this output

```python
batches_expr.meta.pop() = [<Expr ['col("int_value")'] at 0x152699295250>]
```

And that works as expected

### Installed versions

<details>

```
--------Version info---------
Polars:              1.32.0-beta.1
Index type:          UInt32
Platform:            Linux-4.18.0-553.46.1.el8_10.x86_64-x86_64-with-glibc2.28
Python:              3.11.11 | packaged by conda-forge | (main, Dec  5 2024, 14:17:24) [GCC 13.3.0]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  1.6.0
altair               5.5.0
azure.identity       <not installed>
boto3                1.36.3
cloudpickle          2.2.1
connectorx           0.4.3
deltalake            0.24.0
fastexcel            <not installed>
fsspec               2024.12.0
gevent               <not installed>
google.auth          2.38.0
great_tables         0.16.1
matplotlib           3.10.0
numpy                1.26.4
openpyxl             3.1.5
pandas               2.2.3
polars_cloud         <not installed>
pyarrow              19.0.1
pydantic             2.10.6
pyiceberg            <not installed>
sqlalchemy           2.0.37
torch                2.5.1.post107
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by coastalwhite**
Fixes #23760.

### CODE REVIEW

File: crates/polars-plan/src/plans/iterator.rs [hunk 1]
```diff
@@ -141,9 +141,9 @@ impl Expr {
         push_expr!(self, container, push, push, iter);
     }
 
-    pub fn nodes_owned(self, container: &mut UnitVec<Expr>) {
-        let push_arc = |c: &mut UnitVec<Expr>, e: Arc<Expr>| c.push(Arc::unwrap_or_clone(e));
-        let push_owned = |c: &mut UnitVec<Expr>, e: Expr| c.push(e);
+    pub fn nodes_owned(self, container: &mut Vec<Expr>) {
```
Comment (coastalwhite) [inline crates/polars-plan/src/plans/iterator.rs:144]: Note, this was not used anywhere else yet and it would throw an assertion error when used because UnitVec is not allowed with types that are larger than `usize`.
