### PR TITLE
fix(rust, python): parse single-digit months and dates when code would have gone down fastpath

### LINKED ISSUE #7390: Failure to parse single-digit months or dates
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Chrono allows single-digit months to be parsed with `'%m'`

But Polar's fastpath parser doesn't allow that, so it fails:

### Reproducible example

```python
In [6]: pl.Series(['2020-1-1']).str.strptime(pl.Datetime, '%Y-%m-%d')
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In [6], line 1
----> 1 pl.Series(['2020-1-1']).str.strptime(pl.Datetime, '%Y-%m-%d')


ComputeError: strict conversion to dates failed, maybe set strict=False
```

### Expected behavior

```python
In [1]: pl.Series(['2020-1-1']).str.strptime(pl.Datetime, '%Y-%m-%d')
Out[1]: 
shape: (1,)
Series: '' [datetime[μs]]
[
        2020-01-01 00:00:00
]
```

Looks like the fallback couldn't be removed, as was done in https://github.com/pola-rs/polars/pull/7369 (apologies!) - so here I'm restoring it, but using `transform` so it'll handle the cases which https://github.com/pola-rs/polars/pull/7373 addressed

### Installed versions

<details>

```
---Version info---
Polars: 0.16.11
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.8.16 (default, Dec  7 2022, 01:12:06)
[GCC 11.3.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 2.0.0rc0
numpy: 1.24.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.6.2
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #7390

This is a very small change, but the diff is making it look much larger than it really is because of a change in the indentation level

If reviewing, I'd suggest setting "ignore whitespace" option by appending "?w=1" to the URL, i.e.: https://github.com/pola-rs/polars/pull/7391/files?w=1

### CODE REVIEW

File: polars/polars-time/src/chunkedarray/utf8/mod.rs [hunk 1]
```diff
@@ -475,60 +475,63 @@ pub trait Utf8Methods: AsUtf8 {
...
+            let mut ca: Int64Chunked = if let Some(fmt_len) =
+                self::strptime::fmt_len(fmt.as_bytes())
+            {
+                let convert = |s: &str| {
+                    // Safety:
+                    // fmt_len is correct, it was computed with this `fmt` str.
+                    match unsafe { self::strptime::parse(s.as_bytes(), fmt.as_bytes(), fmt_len) } {
+                        None => transform(s, &fmt),
+                        Some(ndt) => Some(func(ndt)),
                     }
```
Comment (MarcoGorelli) [inline polars/polars-time/src/chunkedarray/utf8/mod.rs:493]: making this (almost) the same as is done for dates:

https://github.com/pola-rs/polars/blob/05136cde684cf346214c6da0e9b1e5184707f689/polars/polars-time/src/chunkedarray/utf8/mod.rs#L331-L336
