### PR TITLE
Fix(rust, python) Fix silent failure in read_ndjson with invalid value

### LINKED ISSUE #10041: pl.read_ndjson silently drops the rest of the file when it encounters invalid json
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from pathlib import Path

import polars as pl

path: Path = Path('./test_data')
with open(path, 'wt') as file:
    for i in range(0, 100):
        file.write('{"a": "1", "b": 2.0}\n')
    file.write('{"a": "3", "b": NaN}\n')
    for i in range(0, 100):
        file.write('{"a": "5", "b": 6.0}\n')

df = pl.read_ndjson(path)
print(df)

shape: (100, 2)  # <--------- This should be 200
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ str ┆ f64 │
╞═════╪═════╡
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
│ …   ┆ …   │
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
│ 1   ┆ 2.0 │
└─────┴─────┘
```

### Issue description

When an ndjson file has a line of invalid json (e.g. `NaN` or `.1`) `read_ndjson` will read up to the invalid line and silently discard the rest of the file.

### Expected behavior

My expectation would be something like:
- If `ignore_errors=False`, raise an error
- If `ignore_errors=True`, ignore the line and keep processing

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.24.3
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            1.10.7
sqlalchemy:          1.4.48
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by rikkaka**
Fix #10041 by raising an error when encountering invalid row.
Cause of the bug and method for solving: https://github.com/pola-rs/polars/issues/10041#issuecomment-1647386806

### CODE REVIEW

File: polars/polars-io/src/ndjson/core.rs [hunk 1]
```diff
@@ -305,11 +305,20 @@ fn parse_lines(bytes: &[u8], buffers: &mut PlIndexMap<BufferKey, Buffer>) -> Pol
...
-        parse_impl(bytes, buffers, &mut buf)?;
+    for value_result in iter {
+        match value_result {
+            Ok(value) => {
+                let bytes = value.get().as_bytes();
+                parse_impl(bytes, buffers, &mut buf)?;
+            }
+            Err(e) => {
+                return Err(PolarsError::ComputeError(
+                    format!("error parsing line: {}", e).into(),
```
Comment (ritchie46) [inline polars/polars-io/src/ndjson/core.rs:318]: can you use the `polars_bail` macro here? `polars_bail!(ComputeError: "error parsing ndjson {}", e)`

Comment (rikkaka) [reply polars/polars-io/src/ndjson/core.rs]: Sure. I've updated to using `polars_bail`

**Comment by ritchie46** [comment]
Thanks for the fix!
