### PR TITLE
fix(rust,python): Improve error message in DataFrame constructor

### LINKED ISSUE #6714: Badly formatted error message when invalid data passed to `DataFrame` constructor
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

See example.

### Reproducible example

```python
import polars as pl

data = {"a": [100, 101], "b": [102], "c": [103, 104, 105]}

df = pl.DataFrame(data)
```

Results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stijn/.cache/pypoetry/virtualenvs/bakplan-calculator-TjseP0Di-py3.11/lib/python3.11/site-packages/polars/utils.py", line 393, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/stijn/.cache/pypoetry/virtualenvs/bakplan-calculator-TjseP0Di-py3.11/lib/python3.11/site-packages/polars/internals/dataframe/frame.py", line 329, in __init__
    self._df = dict_to_pydf(
               ^^^^^^^^^^^^^
  File "/home/stijn/.cache/pypoetry/virtualenvs/bakplan-calculator-TjseP0Di-py3.11/lib/python3.11/site-packages/polars/internals/construction.py", line 697, in dict_to_pydf
    return PyDataFrame(data_series)
           ^^^^^^^^^^^^^^^^^^^^^^^^
exceptions.ShapeError: Could not create a new DataFrame from Series. The Series have different lengths. Got [shape: (2,)
Series: 'a' [i64]
[
        100
        101
], shape: (1,)
Series: 'b' [i64]
[
        102
], shape: (3,)
Series: 'c' [i64]
[
        103
        104
        105
]]
```

It prints all the data! Now imagine you actually pass some larger dataframe, it will consume your whole logs.

### Expected behavior

The error message shouldn't print all the data. It should probably only print the fact that the Series have different lengths.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.1
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.0 (main, Nov  1 2022, 09:16:00) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.24.0
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: 0.8.1
deltalake: <version not detected>
matplotlib: <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by stinodego**
Fixes #6714 

New error message reads:

> exceptions.ShapeError: Could not create a new DataFrame from Series. The Series have different lengths: found length 2 for Series named "a" and length 1 for Series named "b".

Comments on my Rust implementation are very welcome - I'm sure there's a cleaner way to do this.

### CODE REVIEW

File: polars/polars-core/src/frame/mod.rs [hunk 1]
```diff
@@ -240,15 +240,19 @@ impl DataFrame {
             let mut names = PlHashSet::with_capacity(series_cols.len());
 
             for s in &series_cols {
+                let name = s.name();
```
Comment (ritchie46) [inline polars/polars-core/src/frame/mod.rs:243]: I think we should get the first name only during raising an error. The happy path should not be slowed down by giving extra error information.

Comment (stinodego) [reply polars/polars-core/src/frame/mod.rs:242]: You're right. Changed it around, should be good to go now!

**Review by ritchie46 — APPROVED** [review]
