### PR TITLE
fix: Ensure `sample()` respects `shuffle=False`

### LINKED ISSUE #23537: `shuffle` parameter to `sample` is ignored when `n` is less than the length of the DataFrame
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"a": [1, 2, 3, 4]})

N = 3 # 4

for i in range(10):
    shuffle_true  = df.sample(n=N, shuffle=True, seed=i).get_column("a").to_list()
    shuffle_false = df.sample(n=N, shuffle=False, seed=i).get_column("a").to_list()
    print(f"Shuffle True: {shuffle_true}, shuffle False: {shuffle_false}")
```

### Log output

```shell

```

### Issue description

t.b.d.

### Expected behavior

t.b.d.

### Installed versions

t.b.d.

### PR DESCRIPTION
**Pull request by Kevin-Patyk**
Resolves https://github.com/pola-rs/polars/issues/23537 and also resolves the second point of https://github.com/pola-rs/polars/issues/23557.

The issue was that, in `create_rand_index_no_replacement`, when `n == len`, it would just select all the rows and then shuffles or not based on `shuffle`. In the `else` arm, the `shuffle` parameter was not considered at all. The code would just immediately sample, which is random and provides no order, and return immediately, always providing shuffled results even if `shuffle = False` was provided.

The added fix ensures that the `shuffle` parameter is taken into account in the `else` arm. If `shuffle = True`, it just samples and returns immediately, as before. If `shuffle = False`, it will sort the Vector of sampled indices before returning, ensuring relative row ordering. 

✏️ Note: I used `.sort_unstable()` because sampled indices are always unique when sampling with no replacement so there is no need for preserving their relative order and because it is faster. 

🧪 Lastly, I had to change some old tests that were relying on the incorrect behavior.

🤖 Claude Sonnet 4.6 for navigating code and fixing the old unit tests.

### CODE REVIEW

**Comment by Kevin-Patyk** [comment]
@nameexhaustion Friendly ping since it's been some time and completion of this PR would allow me to finish https://github.com/pola-rs/polars/issues/23557 in a following PR. Thanks!

File: crates/polars-core/src/chunked_array/random.rs [hunk 1]
```diff
@@ -41,9 +41,25 @@ fn create_rand_index_no_replacement(
         // should get rid of the extra copy already if IdxSize matches the IndexVec
         // size returned.
         buf = match rand::seq::index::sample(&mut rng, len, n) {
-            IndexVec::U32(v) => v.into_iter().map(|x| x as IdxSize).collect(),
+            IndexVec::U32(v) => {
+                if shuffle {
+                    v.into_iter().map(|x| x as IdxSize).collect()
+                } else {
+                    let mut v: Vec<_> = v.into_iter().map(|x| x as IdxSize).collect();
+                    v.sort_unstable();
```
Comment (orlp) [inline crates/polars-core/src/chunked_array/random.rs]: This can be significantly simpler if you just do

```rust
if !shuffle {
    buf.sort_unstable();
}
```

after the original code, rather than inserting it into the `match` for both branches.

**Review by orlp — CHANGES_REQUESTED** [review]

File: crates/polars-core/src/chunked_array/random.rs (hunk 1 above)
Comment (Kevin-Patyk) [reply crates/polars-core/src/chunked_array/random.rs]: @orlp Thanks, done!

**Review by orlp — APPROVED** [review]
