### PR TITLE
fix(rust): string to decimal parsing 

### LINKED ISSUE #10118: `str.to_decimal()` weird behaviour
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
decimal_data = ['12.34', 'ABC12.34', '1ABC2.34', '12ABC.34', '12.ABC.34', '12.3ABC4', '12.34ABC']

# crashes like I would expect
pl.Series(decimal_data, dtype=pl.Decimal)

# somehow works
pl.Series(decimal_data).str.to_decimal()
┌────────────┐
│            │
│ ---        │
│ decimal[5] │
╞════════════╡
│ 12.34      │
│ null       │
│ 1.34       │
│ 12.34      │
│ null       │
│ 12.00003   │
│ 12.00034   │
└────────────┘
```

### Issue description

nothing to add :D

### Expected behavior

error

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.0
connectorx:          0.3.1
deltalake:           0.9.0
fsspec:              2022.11.0
matplotlib:          3.6.2
numpy:               1.23.5
pandas:              2.0.3
pyarrow:             8.0.0
pydantic:            1.10.2
sqlalchemy:          1.4.47
xlsx2csv:            0.8.1
xlsxwriter:          3.0.9
```

</details>

### PR DESCRIPTION
**Pull request by c-peters**
Avoid incorrect parsing of trailing characters 12ABC.123BC

See fix #10118

### CODE REVIEW

File: crates/polars-arrow/src/compute/decimal.rs [hunk 1]
```diff
@@ -9,12 +9,17 @@ fn leading_zeros(bytes: &[u8]) -> u8 {
 }
 
 fn split_decimal_bytes(bytes: &[u8]) -> (Option<&[u8]>, Option<&[u8]>) {
-    let mut a = bytes.split(|x| *x == b'.');
+    let mut a = bytes.splitn(2,|x| *x == b'.');
```
Comment (ritchie46) [inline crates/polars-arrow/src/compute/decimal.rs:12]: What is the rationale of this change?

Comment (orlp) [reply crates/polars-arrow/src/compute/decimal.rs:12]: @ritchie46 I suggested it to Chiel, the old code would erroneously accept `3.2.foobar` as a number since it split it in arbitrarily many pieces but only accessed the first two.

Comment (ritchie46) [reply crates/polars-arrow/src/compute/decimal.rs:12]: Right. :+1:

**Comment by ritchie46** [comment]
A `rust fmt` run and it is good to go.

**Comment by c-peters** [comment]
Simplified the match a little bit, since the first option must be Some (`splitn` returns `Some('')` for examples like `.5`.
