### PR TITLE
fix: Implements `gt/lt` cmp for null dtype

### LINKED ISSUE #14118: Comparison on `Null` is not implemented
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [None, None], "b": [None, None]})
df.select(pl.when(pl.col("a") > pl.col("b")).then(pl.col("a").otherwise(pl.col("b")))
```

### Log output

```shell
pyo3_runtime.PanicException: not implemented
```

### Issue description

Comparison on `None` columns should return `None` instead of failing out.

### Expected behavior

Return `None`.

### Installed versions

<details>

```
v0.20.6
```

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This fixes #14118.

### CODE REVIEW

File: crates/polars-core/src/series/comparison.rs [hunk 1]
```diff
@@ -137,22 +137,42 @@ impl ChunkCompare<&Series> for Series {
 
     /// Create a boolean mask by checking if self > rhs.
     fn gt(&self, rhs: &Series) -> PolarsResult<BooleanChunked> {
-        impl_compare!(self, rhs, gt)
+        match (self.dtype(), rhs.dtype()) {
+            (DataType::Null, DataType::Null) => {
+                Ok(BooleanChunked::full_null(self.name(), self.len()))
```
Comment (stinodego) [inline crates/polars-core/src/series/comparison.rs:142]: Just wondering: does this handle broadcasting correctly?

**Review by ritchie46 — APPROVED** [review]
