### PR TITLE
fix: improve replace on categoricals

### LINKED ISSUE #13215: Make `replace` work for local Categoricals
Following up on #13164

In `replace`, we cast the `old` input to the type of the expression. This currently doesn't work for local Categoricals, but I think it theoretically _could_ work. Example:

```python
s = pl.Series(["a", "b"], dtype=pl.Categorical)
s.replace("a", "c", default=None)
# InvalidOperationError: casting to a non-enum variant with rev map is not supported for the user
```

It fails because it's trying to strict cast `lit("a")` to the original series dtype (Categorical). Can we allow this somehow?
Expected output would be:
```python
expected = pl.Series(["c", None], dtype=pl.Utf8)
```

Next step would be to allow replacements _by_ a local categorical and returning a categorical, avoiding strings altogether:

```python
s = pl.Series(["a", "b"], dtype=pl.Categorical)
old = pl.Series(["a"])  # gets cast to the dtype of `s`
new = pl.Series(["c"], dtype=pl.Categorical)

r = s.replace(old, new)

expected = pl.Series(["c", "b"], dtype=pl.Categorical)  # supertype of `s` and `new` is still a Categorical
```

@c-peters would you mind taking a look at this?

### PR DESCRIPTION
**Pull request by c-peters**
fix #13215

Ideally, we find a way to improve the casting to one step. For strings, we now cast str -> categorical and then do the remapping. We should use the existing mapping in the first cast.

### CODE REVIEW

File: crates/polars-ops/src/series/ops/replace.rs [hunk 1]
```diff
@@ -33,7 +33,20 @@ pub fn replace(
         return Ok(default);
     }
 
-    let old = old.strict_cast(s.dtype())?;
+    let old = match (s.dtype(), old.dtype()) {
+        (s_dt, old_dt) if s_dt == old_dt => old.clone(),
+        #[cfg(feature = "dtype-categorical")]
+        (DataType::Categorical(opt_rev_map, ord), DataType::Utf8) => {
+            let dt = opt_rev_map
```
Comment (ritchie46) [inline crates/polars-ops/src/series/ops/replace.rs:40]: I read this as a `clone_if_enum`. Do we have this pattern more often? Might make a dedicate method for that.

File: crates/polars-ops/src/series/ops/replace.rs [hunk 2]
```diff
@@ -89,8 +102,12 @@ fn replace_by_multiple(
             replaced.zip_with(mask, default)
         },
         Err(_) => {
-            let mask = &replaced.is_not_null();
-            replaced.zip_with(mask, default)
+            if replaced.null_count() > 0 {
```
Comment (ritchie46) [inline crates/polars-ops/src/series/ops/replace.rs:105]: Ai.. good fast path.

Comment (stinodego) [reply crates/polars-ops/src/series/ops/replace.rs:105]: Yes, but it can be moved outside of the match block! We can do the check directly after line 97 and early return.

File: crates/polars-ops/src/series/ops/replace.rs [hunk 3]
```diff
@@ -33,7 +33,20 @@ pub fn replace(
         return Ok(default);
     }
 
-    let old = old.strict_cast(s.dtype())?;
+    let old = match (s.dtype(), old.dtype()) {
+        (s_dt, old_dt) if s_dt == old_dt => old.clone(),
```
Comment (stinodego) [inline crates/polars-ops/src/series/ops/replace.rs:37]: Isn't this logic already in `strict_cast` / `cast`? I think it should be implemented there, rather than before every cast everywhere else.

File: py-polars/tests/unit/operations/test_replace.py [hunk 4]
```diff
@@ -503,3 +478,60 @@ def test_map_dict_deprecated() -> None:
...
+        for old, new, expected in [
+            ("a", "c", pl.Series("s", ["c", None], dtype=pl.Utf8)),
+            (["a", "b"], ["c", "d"], pl.Series("s", ["c", "d"], dtype=pl.Utf8)),
+            (pl.lit("a", dtype=dtype), "c", pl.Series("s", ["c", None], dtype=pl.Utf8)),
+            (
+                pl.Series(["a", "b"], dtype=dtype),
+                ["c", "d"],
+                pl.Series("s", ["c", "d"], dtype=pl.Utf8),
+            ),
+        ]:
```
Comment (stinodego) [inline py-polars/tests/unit/operations/test_replace.py:505]: You can just add a second `parametrize` decorator to the test to check all the permutations.

File: crates/polars-ops/src/series/ops/replace.rs [hunk 5]
```diff
@@ -33,7 +33,20 @@ pub fn replace(
...
+        #[cfg(feature = "dtype-categorical")]
+        (DataType::Categorical(opt_rev_map, ord), DataType::Utf8) => {
```
Comment (stinodego) [inline crates/polars-ops/src/series/ops/replace.rs:39]: I imagine this could also work when `old` is a (local) Categorical rather than a `Utf8`?

File: crates/polars-ops/src/series/ops/replace.rs (hunk 1 above)
Comment (c-peters) [reply crates/polars-ops/src/series/ops/replace.rs:40]: For this PR, I would like to leave this as. But in the future I would like to tackle the cast to Categorical which is compatible instead of first casting to Categorical(None) and then remapping

File: crates/polars-ops/src/series/ops/replace.rs (hunk 3 above)
Comment (c-peters) [reply crates/polars-ops/src/series/ops/replace.rs:37]: @ritchie46 , I don't think it is right now. Would it be sensible to create a fastpath in `strict_cast` / `cast`?

File: crates/polars-ops/src/series/ops/replace.rs (hunk 5 above)
Comment (c-peters) [reply crates/polars-ops/src/series/ops/replace.rs:39]: For Categorical -> Enum conversion you mean?

For Utf8, I think it is fair to cast to a Categorical / Enum in the background. However, casting from Categorical to ENUM, I don't think it is a good idea to mix & match these types in the background

File: py-polars/tests/unit/operations/test_replace.py (hunk 4 above)
Comment (c-peters) [reply py-polars/tests/unit/operations/test_replace.py:505]: The values depend on the values in the first parametrize (e.g. `pl.lit("a",dtype=dtype`). Do you know how to do that?

File: crates/polars-ops/src/series/ops/replace.rs (hunk 3 above)
Comment (ritchie46) [reply crates/polars-ops/src/series/ops/replace.rs:37]: It is in `Series::cast`. I think we should dispatch `strict_cast` via that. Done that in #13255.

So this cane be rebased and this branch can be removed.

File: crates/polars-ops/src/series/ops/replace.rs (hunk 5 above)
Comment (stinodego) [reply crates/polars-ops/src/series/ops/replace.rs:39]: Nevermind, I was thinking the following should work, but it already does on the main branch!

```python
s = pl.Series(["a", "b"], dtype=pl.Categorical)
old = pl.Series(["a"], dtype=pl.Categorical)
new = pl.Series(["c"], dtype=pl.Categorical)

result = s.replace(old, new)
```
```
/home/stijn/code/polars/py-polars/repro.py:7: CategoricalRemappingWarning: Local categoricals have different encodings, expensive re-encoding is done to perform this merge operation. Consider using a StringCache or an Enum type if the categories are known in advance
  result = s.replace(old, new)
shape: (2,)
Series: '' [cat]
[
        "c"
        "b"
]
```

File: py-polars/tests/unit/operations/test_replace.py (hunk 4 above)
Comment (stinodego) [reply py-polars/tests/unit/operations/test_replace.py:505]: It's possible, let me double check...

Comment (stinodego) [reply py-polars/tests/unit/operations/test_replace.py:505]: Hm, not trivially, it seems. The other test can be rewritten though with a parametrize like below.

I guess it's fine as it is 👍 

```python
@pytest.mark.parametrize(
    "context", [pl.StringCache(), pytest.warns(CategoricalRemappingWarning)]
)
@pytest.mark.parametrize(
    ("old", "new", "expected"),
    [
        (
            "a",
            pl.lit("c", dtype=pl.Categorical),
            pl.Series("s", ["c", None], dtype=pl.Categorical),
        ),
        (
            ["a", "b"],
            pl.Series(["c", "d"], dtype=pl.Categorical),
            pl.Series("s", ["c", "d"], dtype=pl.Categorical),
        ),
    ],
)
def test_replace_cat_cat(
    context: contextlib.AbstractContextManager,  # type: ignore[type-arg]
    old: str | list[str],
    new: pl.Series | pl.Expr,
    expected: pl.Series,
) -> None:
```

**Review by stinodego — APPROVED** [review]
Great! This should make `replace` a lot easier to use for categoricals.

File: py-polars/tests/unit/operations/test_replace.py (hunk 4 above)
Comment (c-peters) [reply py-polars/tests/unit/operations/test_replace.py:505]: The expected still depends on the context, so I'm affraid this won't work

Comment (stinodego) [reply py-polars/tests/unit/operations/test_replace.py:505]: You're right!

**Review by ritchie46 — APPROVED** [review]
