### PR TITLE
fix: Ensure out-of-range integers and other edge case values don't give wrong results for index_of()

### LINKED ISSUE #23476: Out-of-range integers give wrong results in index_of() in some cases
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# This is wrong:
>>> pl.Series([0, 2, 255, None], dtype=pl.UInt8).index_of(np.uint16(256))
3


# This is fine:
>>> pl.Series([0, 2, 255, None], dtype=pl.UInt8).index_of(256)
# ...
polars.exceptions.InvalidOperationError: conversion from `i128` to `u8` failed in column 'scalar' for 1 out of 1 values: [256]
```

### Log output

```shell

```

### Issue description

My guess is that out-of-range integers get cast to Null in some cases, and then `index_of()` search for Null, and if you have a Null you get the wrong answer.

### Expected behavior

Result should be either `InvalidOperationError` or `None` (i.e. not found), it shouldn't ever find the wrong index. Ideally behavior would be consistent but that may be difficult.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.31.0
Index type:          UInt32
Platform:            Linux-6.12.10-76061203-generic-x86_64-with-glibc2.39
Python:              3.13.5 (main, Jun 12 2025, 08:56:14) [GCC 13.3.0]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.3.1
openpyxl             <not installed>
pandas               <not installed>
polars_cloud         <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #23476 

Previously out-of-range integers would be cast to Null, and then if there was a Null in the series its index would be returned. I.e. `index_of()` was giving wrong results.

```python
# Previous behavior, before the fix:
>>> pl.Series([0, 2, 255, None], dtype=pl.UInt8).index_of(np.uint16(256))
3
```

Now it does the right thing and errors out. Similarly for other cases of lossy casting, not all of which were caught when FirstArgLossLess was first implemented.

### CODE REVIEW

**Comment by itamarst** [comment]
Anyone have a chance to look at this bug fix?

**Comment by nameexhaustion** [comment]
Could you fix lint? It should be good afterwards

**Comment by itamarst** [comment]
@nameexhaustion done.

**Review by nameexhaustion — APPROVED** [review]

File: crates/polars-plan/src/plans/conversion/type_coercion/mod.rs [hunk 1]
```diff
@@ -1279,3 +1267,121 @@ fn inline_implode(expr: Node, expr_arena: &mut Arena<AExpr>) -> PolarsResult<Opt
...
+        (DataType::Decimal(p_to, s_to), DataType::Decimal(p_from, s_from)) => {
+            // 1. The numbers in `from` should fit in `to`'s range.
+            // 2. The scale in `from` should fit in `to`'s scale.
+            ((p_to - s_to) >= (p_from - s_from)) && (s_to >= s_from)
+        },
+        #[cfg(feature = "dtype-decimal")]
+        (DataType::Decimal(p_to, _), dt) if dt.is_primitive_numeric() => {
+            // Match numbers in DataType::try_to_arrow():
+            let max_value = 10i128.pow(*p_to as u32) - 1;
+            let min_value = max_value - 1;
```
Comment (nameexhaustion) [inline crates/polars-plan/src/plans/conversion/type_coercion/mod.rs]: This doesn't seem right - is it supposed to be `-max_value`?

Comment (itamarst) [reply crates/polars-plan/src/plans/conversion/type_coercion/mod.rs]: Yeah... Need some more tests too I guess.

Comment (itamarst) [reply crates/polars-plan/src/plans/conversion/type_coercion/mod.rs]: Found a few more decimal issues along the way, but hopefully correct now.

**Comment by itamarst** [comment]
@nameexhaustion back to you.
