### PR TITLE
fix: Implement `agg_arg_min`/`agg_arg_max` for `boolean` data type

### LINKED ISSUE #26978: Boolean arg_max/arg_min returns null in group_by().agg() and .over() since 1.38
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({
    "group": ["A"] * 5,
    "val": [False, False, True, True, True],
})

# Works standalone
assert df.select(pl.col("val").arg_max()).item() == 2

# Returns null in grouped contexts
assert df.group_by("group").agg(pl.col("val").arg_max()).item(0, 1) == 2  # fails: null
```

### Log output

```shell
async thread count: 29
blocking thread count: 512
keys/aggregates are not partitionable: running default HASH AGGREGATION
```

### Issue description

I guess this may not be a bug but rather an unexpected behaviour that the first index is returned in a group

### Expected behavior

I would expect this to return the first index of the max value (`2`), this is what polars<1.38 did 

### Installed versions

<details>

```
pl.show_versions()
--------Version info---------
Polars:              1.39.2
Index type:          UInt32
Platform:            Linux-5.15.0-91-generic-x86_64-with-glibc2.35
Python:              3.12.12 (main, Jan 14 2026, 19:35:58) [Clang 21.1.4 ]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
polars_cloud         <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by azimafroozeh**
Fixes #26978

### CODE REVIEW

File: crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs [hunk 1]
```diff
@@ -2,89 +2,93 @@
 use super::*;
 
 /// Take kernel for single chunk and an iterator as index.
+/// Returns the position of the minimum value within the group.
```
Comment (orlp) [inline crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs]: `s/within the group/within the iterator`.

File: crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs [hunk 2]
```diff
@@ -2,89 +2,93 @@
...
-        } else {
-            null_count += 1;
         }
     }
-    if null_count == len { None } else { Some(true) }
+    first_non_null_pos
 }
 
 /// Take kernel for single chunk and an iterator as index.
+/// Returns the position of the minimum value within the group.
```
Comment (orlp) [inline crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs]: `s/within the group/within the iterator`.

File: crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs [hunk 3]
```diff
@@ -2,89 +2,93 @@
...
+    let mut first_non_null_pos = None;
 
-    for idx in indices {
+    for (pos, idx) in indices.into_iter().enumerate() {
         if validity.get_bit_unchecked(idx) {
             if !arr.value_unchecked(idx) {
-                return Some(false);
+                return Some(pos);
+            }
+            if first_non_null_pos.is_none() {
```
Comment (orlp) [inline crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs]: This `if` block can be

```rust
first_non_null_pos.get_or_insert(pos);
```

Up to you what your prefer, just letting you know about that function :)

File: crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs [hunk 4]
```diff
@@ -2,89 +2,93 @@
...
     arr: &BooleanArray,
     indices: I,
-) -> Option<bool> {
+) -> Option<usize> {
     if arr.is_empty() {
         return None;
     }
 
-    for idx in indices {
+    for (pos, idx) in indices.into_iter().enumerate() {
```
Comment (orlp) [inline crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs]:
```rust
indices.into_iter().position(|i| !arr.value_unchecked(i))
```

I'm not sure whether you can remove the `array.is_empty()` case, do we allow out-of-bounds indices when the array is empty?

File: crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs [hunk 5]
```diff
@@ -2,89 +2,93 @@
...
-            return Some(false);
+            return Some(pos);
         }
     }
-    Some(true)
+    Some(0)
 }
 
 /// Take kernel for single chunk and an iterator as index.
+/// Returns the position of the maximum value within the group.
```
Comment (orlp) [inline crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs]: `s/within the group/within the iterator`.

File: crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs [hunk 6]
```diff
@@ -2,89 +2,93 @@
...
-        } else {
-            null_count += 1;
         }
     }
-    if null_count == len { None } else { Some(false) }
+    first_non_null_pos
 }
 
 /// Take kernel for single chunk and an iterator as index.
+/// Returns the position of the maximum value within the group.
```
Comment (orlp) [inline crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs]: `s/within the group/within the iterator`.

File: crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs [hunk 7]
```diff
@@ -2,89 +2,93 @@
...
     arr: &BooleanArray,
     indices: I,
-) -> Option<bool> {
+) -> Option<usize> {
     if arr.is_empty() {
         return None;
     }
 
-    for idx in indices {
+    for (pos, idx) in indices.into_iter().enumerate() {
```
Comment (orlp) [inline crates/polars-arrow/src/legacy/kernels/take_agg/boolean.rs]:
```rust
indices.into_iter().position(|i| !arr.value_unchecked(i))
```

I'm not sure whether you can remove the `array.is_empty()` case, do we allow out-of-bounds indices when the array is empty?
