### PR TITLE
fix: Allow for date/datetime subclasses (e.g. pd.Timestamp, FreezeGun) in pl.lit

### LINKED ISSUE #18447: Can no longer pass pd.Timestamp objects into places/expressions that take datetime64
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

This code worked in 1.5, but crashes in 1.6
```python
pl.datetime_range(pd.to_datetime('12/31/2020'),
                              pd.to_datetime('12/31/2022'),
                              interval="1d",
                              eager=True)

TypeError: cannot create expression literal for value of type Timestamp: Timestamp('2020-12-31 00:00:00+0000', tz='UTC')
Hint: Pass `allow_object=True` to accept any value and create a literal of type Object.
```
This fixes it:
```python
pl.datetime_range(pd.to_datetime('12/31/2020').to_datetime64(),
                  pd.to_datetime('12/31/2022').to_datetime64(),
                  interval="1d",
                  eager=True)
```
Understand the documentation does not explicitly say that you can pass it a pandas Timestamp, but once again, seemed a reasonable user assumption and used to work.

Also, this crashes now with similar error.
```python
df = pl.DataFrame({"dates": pd.date_range(pd.to_datetime('12/31/2020'), pd.to_datetime('12/31/2021'), freq='B')})
df.filter(pl.col('dt') < pd.to_datetime('12/31/2020'))
```

### Log output

_No response_

### Issue description

Cannot pass pd.Timestamp to functions that expect datetime.

### Expected behavior

Would be nice to automatically cast the Timestamp to datetime64 on entry to polars

### Installed versions

didn't get a chance to do this... it's on my work computer

### LINKED ISSUE #18470: FreezeGun / Temporal subclasses not working in filter
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import datetime

from freezegun import freeze_time
import polars as pl
from polars import Datetime

with freeze_time("2000-01-01"):
    df = pl.DataFrame(
        [datetime.datetime.now()],
        schema={"timestamp": Datetime}
    )
    df.filter(pl.col("timestamp") > pl.datetime(2000,1,1)) # works
    df.filter(pl.col("timestamp") > datetime.datetime.now()) # does not work since 1.6.0
```

### Log output

```shell
Traceback (most recent call last):
  File "/test.py", line 12, in <module>
    df.filter(pl.col("timestamp") > datetime.datetime.now()) # does not work
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../venv/lib/python3.12/site-packages/polars/expr/expr.py", line 194, in __gt__
    other = parse_into_expression(other, str_as_lit=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../venv/lib/python3.12/site-packages/polars/_utils/parse/expr.py", line 60, in parse_into_expression
    expr = F.lit(input, dtype=dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../venv/lib/python3.12/site-packages/polars/functions/lit.py", line 105, in lit
    expr = wrap_expr(plr.lit(dt_utc, allow_object=False)).cast(Datetime(time_unit))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot create expression literal for value of type FakeDatetime: FakeDatetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)

Hint: Pass `allow_object=True` to accept any value and create a literal of type Object.
```

### Issue description

With mocked datetime objects using Freezegun, the df filter expression raises an error while Freezegun classes are already supported on init of dataframes since this PR https://github.com/pola-rs/polars/pull/7819

### Expected behavior

FreezeGun subclasses of datetime objects can be used to filter dataclasses with datetime types

### Installed versions

<details>

```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            macOS-14.5-arm64-arm-64bit
Python:              3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.0
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             2.8.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #18470
closes #18447

### CODE REVIEW

File: crates/polars-python/src/functions/lazy.rs [hunk 1]
```diff
@@ -442,12 +442,24 @@ pub fn lit(value: &Bound<'_, PyAny>, allow_object: bool) -> PyResult<PyExpr> {
...
-        )))
+        Python::with_gil(|py| {
+            // One final attempt before erroring. Do we have a date/datetime subclass?
+            // E.g. pd.Timestamp, or Freezegun.
+            let datetime_module = PyModule::import_bound(py, "datetime")?;
+            let datetime_class = datetime_module.getattr("datetime")?;
+            let date_class = datetime_module.getattr("date")?;
+            if value.is_instance(&datetime_class)? || value.is_instance(&date_class)? {
+                let av = py_object_to_any_value(value, true)?;
+                Ok(Expr::Literal(LiteralValue::try_from(av).unwrap()).into())
```
Comment (MarcoGorelli) [inline crates/polars-python/src/functions/lazy.rs:453]: Pyo3 does have `PyDateTime`, but it's limited to:

> Available on non-Py_LIMITED_API only

**Comment by mcrumiller** [comment]
Ahh sorry Marco dropped the ball on this one. I was looking for a way to avoid acquiring the gil again since `py_object_to_any_value` does this check already when it traverses the ancestor types.

File: crates/polars-python/src/functions/lazy.rs (hunk 1 above)
Comment (ritchie46) [reply crates/polars-python/src/functions/lazy.rs:453]: This should come before the `allow_object` check. 

I am thinking aloud here. Why don't we go via `AnyValue` directly for all branches? This seems like code duplication.

Comment (MarcoGorelli) [reply crates/polars-python/src/functions/lazy.rs:448]: yup, thanks for catching that, and sorry for not having spotted it myself

fixed, and I've added a test which would've on my previous commit to make sure this doesn't regress

Comment (MarcoGorelli) [reply crates/polars-python/src/functions/lazy.rs:448]: > Why don't we go via AnyValue directly for all branches?

Tried then, but then a float would become
```
[crates/polars-python/src/functions/lazy.rs:429:9] &newret = Ok(
    PyExpr {
        inner: 2.0,
    },
)
```
instead of
```
[crates/polars-python/src/functions/lazy.rs:432:9] &oldret = Ok(
    PyExpr {
        inner: dyn float: 2.0,
    },
)
```
, and I haven't (yet) dived deeper here

Comment (ritchie46) [reply crates/polars-python/src/functions/lazy.rs:448]: Ah, yeap.. That's a good reason.

**Review by ritchie46 — APPROVED** [review]
