### PR TITLE
fix: Fix comparison of categoricals

### LINKED ISSUE #13110: Cannot compare any categoricals with `<`, `<=`, `=>`, `>`
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

with pl.StringCache():
    s1 = pl.Series(["a", "a", "a", "a"], dtype=pl.Categorical("lexical"))
    s2 = pl.Series(["b", "b", "b", "b"], dtype=pl.Categorical("lexical"))
s1 > s2 # fails
```
```
polars.exceptions.ComputeError: can not compare (<, <=, >, >=) two categoricals, unless they are of Enum type
```

These were created under the same string cache and have an ordering, so they should be comparable.  This issue also prevents calling `is_sorted()` on a categorical series:

```python
pl.Series(["a", "b"], dtype=pl.Categorical).is_sorted()
```
```
polars.exceptions.ComputeError: can not compare (<, <=, >, >=) two categoricals, unless they are of Enum type
```

### Expected behavior

Comparison operators should work as long as series use same revmap.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.1
Index type:           UInt32
Platform:             Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.11.3 (main, Apr 15 2023, 14:44:51) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_manager:  0.5.1
cloudpickle:          2.2.1
connectorx:           0.3.2a7
deltalake:            0.10.1
fsspec:               2023.6.0
gevent:               <not installed>
matplotlib:           3.7.2
numpy:                1.25.2
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              13.0.0
pydantic:             2.2.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.20
xlsx2csv:             0.8.1
xlsxwriter:           3.1.2
```

</details>

### PR DESCRIPTION
**Pull request by c-peters**
fix #13110

### CODE REVIEW

File: crates/polars-core/src/chunked_array/comparison/categorical.rs [hunk 1]
```diff
@@ -30,20 +30,68 @@ where
...
 ) -> PolarsResult<BooleanChunked>
 where
     Compare: Fn(&'a UInt32Chunked, &'a UInt32Chunked) -> BooleanChunked,
+    CompareString: Fn(&str, &str) -> bool,
 {
     let rev_map_l = lhs.get_rev_map();
     let rev_map_r = rhs.get_rev_map();
-    polars_ensure!(rev_map_l.is_enum() && rev_map_r.is_enum(), ComputeError: "can not compare (<, <=, >, >=) two categoricals, unless they are of Enum type");
-    polars_ensure!(rev_map_l.same_src(rev_map_r), ComputeError: "can only compare Enum types with the same categories {:?} vs {:?}", rev_map_l.get_categories(), rev_map_r.get_categories());
+    polars_ensure!(rev_map_l.same_src(rev_map_r), ComputeError: "can only compare categoricals of the same type and the same categories {:?} vs {:?}", rev_map_l.get_categories(), rev_map_r.get_categories());
```
Comment (mcrumiller) [inline crates/polars-core/src/chunked_array/comparison/categorical.rs:45]: There might be lots of categories, should we maybe refrain from printing the categories themselves?

Comment (ritchie46) [reply crates/polars-core/src/chunked_array/comparison/categorical.rs:45]: Yeap, good point.

**Review by ritchie46 — APPROVED** [review]

**Review by ritchie46 — APPROVED** [review]
