### PR TITLE
fix: Consistently round half-way points down in dt.round

### LINKED ISSUE #18239: `dt.round()` slow/fast path use different rounding
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

@MarcoGorelli 
This is an example case produced in the hypothesis test for `test_dt_round_fast_path_vs_slow_path`:

```python
from datetime import datetime
import polars as pl

datetimes = [
    datetime(1980, 1, 1, 0, 0, 0, 0),
    datetime(1969, 1, 1, 0, 0, 0, 1),
    datetime(1969, 1, 1, 0, 0, 0, 2),
    datetime(1969, 1, 1, 0, 0, 0, 3),
    datetime(1969, 1, 1, 0, 0, 0, 4),
    datetime(1969, 1, 1, 0, 0, 0, 5),
]
every = "2us"
s = pl.Series(datetimes)

out = pl.select(
    s.dt.round(every).alias("fast"),
    s.dt.round(pl.Series([every] * len(datetimes))).alias("slow"),
)

print(out)
```
```shell
shape: (6, 2)
┌────────────────────────────┬────────────────────────────┐
│ fast                       ┆ slow                       │
│ ---                        ┆ ---                        │
│ datetime[μs]               ┆ datetime[μs]               │
╞════════════════════════════╪════════════════════════════╡
│ 1980-01-01 00:00:00        ┆ 1980-01-01 00:00:00        │
│ 1969-01-01 00:00:00        ┆ 1969-01-01 00:00:00.000002 │
│ 1969-01-01 00:00:00.000002 ┆ 1969-01-01 00:00:00.000002 │
│ 1969-01-01 00:00:00.000002 ┆ 1969-01-01 00:00:00.000004 │
│ 1969-01-01 00:00:00.000004 ┆ 1969-01-01 00:00:00.000004 │
│ 1969-01-01 00:00:00.000004 ┆ 1969-01-01 00:00:00.000006 │
└────────────────────────────┴────────────────────────────┘
```

### Issue description

The fast path rounds down and the slow path rounds up.

### Expected behavior

Both should use same rounding.

### Installed versions

main

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #18239

### CODE REVIEW

File: crates/polars-time/src/round.rs [hunk 1]
```diff
@@ -5,6 +5,11 @@ use polars_core::prelude::*;
 use polars_utils::cache::FastFixedCache;
 
 use crate::prelude::*;
+use crate::truncate::fast_truncate;
+
+fn fast_round(t: i64, every: i64) -> i64 {
```
Comment (ritchie46) [inline crates/polars-time/src/round.rs:10]: can you tag this with `inline(always)`?

**Review by ritchie46 — APPROVED** [review]
