### PR TITLE
fix(python): Fix cast Float to String where Float is not turn to Integer before turning to String

### LINKED ISSUE #17773: Casting literal floats to strings rounds the value down.
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.select(pl.lit(3.2, dtype=pl.Utf8))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ 3       │
└─────────┘
>>> pl.select(pl.lit(str(3.2)))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ 3.2     │
└─────────┘
>>> print(pl.build_info()["version"])
1.1.0
>>> pl.select(pl.lit(3.2).cast(pl.Utf8))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ 3       │
└─────────┘
>>> pl.select(pl.lit(3.2).cast(pl.Utf8).cast(pl.Float64))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ f64     │
╞═════════╡
│ 3.0     │
└─────────┘
>>> pl.select(pl.lit(3.2))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ f64     │
╞═════════╡
│ 3.2     │
└─────────┘
```

Another example, from 1.2.1, which also highlights that the issue is unique to literals.

```python
>>> pl.select(pl.lit(3.2, dtype=pl.Utf8))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ 3       │
└─────────┘
>>> pl.select((pl.lit(3.2)**2).cast(pl.Utf8))
shape: (1, 1)
┌────────────────────┐
│ literal            │
│ ---                │
│ str                │
╞════════════════════╡
│ 10.240000000000002 │
└────────────────────┘
>>> pl.select(pl.lit(3.2).cast(pl.Utf8))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ 3       │
└─────────┘
>>> pl.select(((pl.lit(3.2)**2)**0.5).cast(pl.Utf8))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ 3.2     │
└─────────┘
>>> pl.build_info()["version"]
'1.2.1'
```

### Log output

_No response_

### Issue description

When I make a literal of a floating point value then cast it to a string, the value is rounded down to the nearest integer.

### Expected behavior

I expect the string version of the float to retain the decimal points, much like python's `str` function does.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.1.0
Index type:           UInt32
Platform:             Linux-5.15.0-116-generic-x86_64-with-glibc2.35
Python:               3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                2.0.0
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              16.1.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by EricTulowetzke**
closes #17773 

Fixed:
```
>>> pl.select(pl.lit(3.2, dtype=pl.Utf8))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ 3.2     │
└─────────┘
```

This is my first time doing a PR for this project so set it to draft to hear feedback. If I keep the below line in test where we use agg, max, min break for Categorical data.
` (_, DataType::String) => {
  AnyValue::StringOwned(format_smartstring!("{}", self.extract::<i64>()?))
},`

I can add more cases for string casting if that is wanted so we define all types.

### CODE REVIEW

File: crates/polars-core/src/datatypes/any_value.rs [hunk 1]
```diff
@@ -536,8 +536,40 @@ impl<'a> AnyValue<'a> {
             (AnyValue::Float64(v), DataType::Boolean) => AnyValue::Boolean(*v != f64::default()),
 
             // to string
-            (av, DataType::String) => {
-                AnyValue::StringOwned(format_smartstring!("{}", av.extract::<i64>()?))
+            (AnyValue::UInt8(_v), DataType::String) => {
```
Comment (ritchie46) [inline crates/polars-core/src/datatypes/any_value.rs:539]: I don't think we need full code branches for every type.

We can check if the `av` is float and in that case extract `f64`. We should add a case for `u64`. For the other cases we can keep `i64` extraction.

Comment (EricTulowetzke) [reply crates/polars-core/src/datatypes/any_value.rs:539]: Ok I can do, but as I was testing edge cases I found this issue in polars 1.2.1:

```
>>> pl.select(pl.lit(-3, dtype=pl.UInt32).cast(pl.Utf8))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eric/miniconda3/envs/polar/lib/python3.12/site-packages/polars/functions/lazy.py", line 1899, in select
    return pl.DataFrame().select(*exprs, **named_exprs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric/miniconda3/envs/polar/lib/python3.12/site-packages/polars/dataframe/frame.py", line 8618, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric/miniconda3/envs/polar/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 1942, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: conversion from `i32` to `u32` failed in column 'literal' for 1 out of 1 values: [-3]
```

From my understand this should be allowed? Should I fill another issue or fix it then this PR?

**Review by ritchie46 — APPROVED** [review]
Much cleaner! Thanks @EricTulowetzke
