### PR TITLE
fix(python): strptime now respects pl.Datetime's time_unit

### LINKED ISSUE #6228: .str.strptime(pl.Datetime('ns')) loses nanoseconds
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`.str.strptime` loses nanoseconds, even if I put `Datetime('ns')`

### Reproducible example

```python
>>> pl.Series(['2020-01-01 00:00:00.123456789']).str.strptime(pl.Datetime('ns'))
shape: (1,)

datetime[μs]

2020-01-01 00:00:00.123456
```

### Expected behavior

```
shape: (1,)

datetime[ns]

2020-01-01 00:00:00.123456789
```

If you agree that this would be the expected behaviour, mind if I try making a PR?

### Installed versions

<details>

```
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.8.16 (default, Dec  7 2022, 01:12:06)
[GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.2
numpy: 1.23.5
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.6.2
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #6228 

Here's my attempt at fixing the linked issue - I'm new to rust so apologies if I've done anything illegal here, I'll study it properly now

### CODE REVIEW

**Comment by alexander-beedie** [comment]
I think you should probably make the `tu` an Option on the Rust side and keep the existing logic in place if no explicit timeunit is supplied - that way it can continue to be auto-inferred if not coming from Python?

File: py-polars/src/lazy/dsl.rs [hunk 1]
```diff
@@ -562,28 +562,33 @@ impl PyExpr {
...
+                        TimeUnit::Milliseconds
+                    } else {
+                        TimeUnit::Microseconds
+                    }
                 }
+                None => TimeUnit::Microseconds,
             }
-            None => TimeUnit::Microseconds,
+        } else {
+            tu.unwrap().0
```
Comment (MarcoGorelli) [inline py-polars/src/lazy/dsl.rs:585]: I couldn't figure out how to do this

If I write `tu.0`, then `make build` gives:
```
   Compiling py-polars v0.15.14 (/home/marcogorelli/polars-dev/py-polars)
error[E0609]: no field `0` on type `std::option::Option<conversion::Wrap<polars::prelude::TimeUnit>>`                                          
   --> src/lazy/dsl.rs:585:16
    |
585 |             tu.0
    |                ^


error: aborting due to previous error> ] 334/335: py-polars                                                                                    


For more information about this error, try `rustc --explain E0609`.

error: could not compile `py-polars` due to 2 previous errors
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `"cargo" "rustc" "--message-format" "json" "--lib"`
```

On the other hand, if I put `tu.unwrap().0`, then `make build` works fine, but `make pre-commit` gives:

```
    Checking py-polars v0.15.14 (/home/marcogorelli/polars-dev/py-polars)
error: called `unwrap` on `tu` after checking its variant with `is_none`
   --> src/lazy/dsl.rs:585:13
    |
567 |         let result_tu = if tu.is_none() {
    |                         --------------- help: try: `if let Some(..) = tu`
...
585 |             tu.unwrap().0
    |             ^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_unwrap
    = note: `-D clippy::unnecessary-unwrap` implied by `-D warnings`

error: could not compile `py-polars` due to previous error
make: *** [Makefile:38: clippy] Error 101
```

Looking into this now (apologies, I'm new to rust!)

File: py-polars/src/lazy/dsl.rs [hunk 2]
```diff
@@ -562,28 +562,33 @@ impl PyExpr {
...
+                        TimeUnit::Nanoseconds
+                    } else if fmt.contains("%.3f") || fmt.contains("%3f") {
+                        TimeUnit::Milliseconds
+                    } else {
+                        TimeUnit::Microseconds
+                    }
                 }
+                None => TimeUnit::Microseconds,
             }
-            None => TimeUnit::Microseconds,
```
Comment (MarcoGorelli) [inline py-polars/src/lazy/dsl.rs:580]: I wanted to try to write ths as
```
        let result_tu = match (fmt, tu) {
            (_, Some(tu)) => tu.0,
            (Some(ref fmt), None) => {
                if fmt.contains("%.9f")
                    || fmt.contains("%9f")
                    || fmt.contains("%f")
                    || fmt.contains("%.f")
                {
                    TimeUnit::Nanoseconds
                } else if fmt.contains("%.3f") || fmt.contains("%3f") {
                    TimeUnit::Milliseconds
                } else {
                    TimeUnit::Microseconds
                }
            }
            (None, None) => TimeUnit::Microseconds,
        };
```

but then I get

```
   Compiling py-polars v0.15.14 (/home/marcogorelli/polars-dev/py-polars)
error[E0382]: use of moved value: `fmt`] 334/335: py-polars                                                                                    
   --> src/lazy/dsl.rs:589:17
    |
560 |         fmt: Option<String>,
    |         --- move occurs because `fmt` has type `std::option::Option<std::string::String>`, which does not implement the `Copy` trait
...
567 |         let result_tu = match (fmt, tu) {
    |                                --- value moved here
...
589 |                 fmt,
    |                 ^^^ value used here after move


error: aborting due to previous error> ] 334/335: py-polars                                                                                    


For more information about this error, try `rustc --explain E0382`.

```

**Comment by ritchie46** [comment]
Thank you @MarcoGorelli!
