### PR TITLE
fix: `rolling_*_by was throwing incorrect error when dataframe was sorted by contained multiple chunks

### LINKED ISSUE #16246: Incorrect ``by` column should not have null values in 'rolling by' expression` error
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import date, datetime

import polars as pl

df = pl.concat([pl.DataFrame({'a': [datetime(2020, 1, 1)], 'b': [1]}), pl.DataFrame({'a': [datetime(2021, 1, 1)]
   , 'b': [1]})], rechunk=False)
print(df.select(pl.col('b').rolling_max_by('a', '1d')))
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/marcogorelli/scratch/t.py", line 8, in <module>
    df.select(pl.col('b').rolling_max_by('a', '1d'))
  File "/home/marcogorelli/scratch/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 8137, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/scratch/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1816, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: `by` column should not have null values in 'rolling by' expression
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/scratch$ POLARS_VERBOSE=1 python t.py
Traceback (most recent call last):
  File "/home/marcogorelli/scratch/t.py", line 8, in <module>
    df.select(pl.col('b').rolling_max_by('a', '1d'))
  File "/home/marcogorelli/scratch/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 8137, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/scratch/.venv/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1816, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: `by` column should not have null values in 'rolling by' expression
```

### Issue description

there's no nulls

### Expected behavior

```
shape: (2, 1)
┌─────┐
│ b   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 1   │
└─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.26
Index type:           UInt32
Platform:             Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:               3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               0.9.2
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.0
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #16246

### CODE REVIEW

File: crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs [hunk 1]
```diff
@@ -82,6 +82,7 @@ where
         return Ok(Series::new_empty(ca.name(), ca.dtype()));
     }
     let ca = ca.rechunk();
+    let by = by.rechunk();
```
Comment (MarcoGorelli) [inline crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs:85]: The error comes from L112
```rust
    let by_values = by.cont_slice().map_err(|_| {
        polars_err!(
            ComputeError:
            "`by` column should not have null values in 'rolling by' expression"
        )
    })?;
```

The values already get re-chunked, so the `by` ones probably should too?
