### PR TITLE
fix: Support grouped `{arg_,}_{min,max}` for Categoricals

### LINKED ISSUE #25906: Add support for grouped min/max(_by) for Categoricals in the in-memory engine
### Description

Currently this is unimplemented:

```python
df  = pl.Series(["a", "b"], dtype=pl.Categorical).to_frame("cat")
df.with_columns(g=1).group_by("g").agg(pl.col.cat.min())
```

```
thread 'polars-0' (26877982) panicked at crates/polars-core/src/series/implementations/categorical.rs:354:1:
not implemented
```

### PR DESCRIPTION
**Pull request by coastalwhite**
Fixes #25906.

This implements `arg_min`, `arg_max`, `min` and `max` for categoricals in aggregation contexts. Each function gets its own specialized kernel, which is almost the same as existing kernels for numerics, but just with category lookups.

The test mentioned in the issue was fixed up, and I added some tests for `list.agg` and `arr.agg` because they also go through this code path.

I used Claude to write the code and tests. I looked at the code and think it is correct and relevant.

### CODE REVIEW

File: crates/polars-core/src/frame/group_by/aggregations/mod.rs [hunk 1]
```diff
@@ -192,6 +194,22 @@ where
     ca.into_series()
 }
 
+pub fn _agg_helper_idx_idx<'a, F>(groups: &'a GroupsIdx, f: F) -> Series
```
Comment (coastalwhite) [inline crates/polars-core/src/frame/group_by/aggregations/mod.rs:197]: Moved over because it is now also used by `categorical`
