### PR TITLE
fix: Correctly return min and max for enums in groupby aggregation

### LINKED ISSUE #18394: min and max return all nulls in pl.Enum
### Description

As of polars 1.5.0

```python
import polars as pl

df = pl.DataFrame(
    {'id': ['a', 'a', 'b', 'b', 'c', 'c'],
     'degree': ['low', 'high', 'high', 'mid', 'mid', 'low']}
).with_columns(
    pl.col('degree').cast(pl.Enum(['low', 'mid', 'high']))
).with_columns(
    # returns all nulls
    pl.col('degree').min().over('id').alias('lowest_degree')
)
```
```
shape: (6, 3)
┌─────┬────────┬───────────────┐
│ id  ┆ degree ┆ lowest_degree │
│ --- ┆ ---    ┆ ---           │
│ str ┆ enum   ┆ enum          │
╞═════╪════════╪═══════════════╡
│ a   ┆ low    ┆ null          │
│ a   ┆ high   ┆ null          │
│ b   ┆ high   ┆ null          │
│ b   ┆ mid    ┆ null          │
│ c   ┆ mid    ┆ null          │
│ c   ┆ low    ┆ null          │
└─────┴────────┴───────────────┘
```

expecting: 
```
shape: (6, 3)
┌─────┬────────┬───────────────┐
│ id  ┆ degree ┆ lowest_degree │
│ --- ┆ ---    ┆ ---           │
│ str ┆ enum   ┆ enum          │
╞═════╪════════╪═══════════════╡
│ a   ┆ low    ┆ low           │
│ a   ┆ high   ┆ low           │
│ b   ┆ high   ┆ mid           │
│ b   ┆ mid    ┆ mid           │
│ c   ┆ mid    ┆ low           │
│ c   ┆ low    ┆ low           │
└─────┴────────┴───────────────┘
```

At this point, one has to use `.to_physical()` for comparison, Btw, Some expressions such as `.first()` would work.

### PR DESCRIPTION
**Pull request by borchero**
Fixes #18394

### CODE REVIEW

File: crates/polars-core/src/series/implementations/categorical.rs [hunk 1]
```diff
@@ -99,6 +99,18 @@ macro_rules! impl_cat_series {
                 Ok(())
             }
 
+            #[cfg(feature = "algorithm_group_by")]
+            unsafe fn agg_min(&self, groups: &GroupsType) -> Series {
+                self.apply_on_phys(|phys| phys.agg_min(groups).$ca_fn().unwrap().clone())
```
Comment (nameexhaustion) [inline crates/polars-core/src/series/implementations/categorical.rs]: This seems incorrect - categoricals must return a min/max following lexical ordering rather than physical - you can see this here:

```python
print(
    pl.Series("cat", ["B", "A"], dtype=pl.Categorical(pl.Categories.random()))
    .to_frame()
    .with_columns(
        cat_phys=pl.col("cat").to_physical(),
        cat_min=pl.col("cat").min(),
        cat_min_by_phys=pl.col("cat").get(pl.col("cat").to_physical().arg_min()),
    )
)
# shape: (2, 4)
# ┌─────┬──────────┬─────────┬─────────────────┐
# │ cat ┆ cat_phys ┆ cat_min ┆ cat_min_by_phys │
# │ --- ┆ ---      ┆ ---     ┆ ---             │
# │ cat ┆ u32      ┆ cat     ┆ cat             │
# ╞═════╪══════════╪═════════╪═════════════════╡
# │ B   ┆ 0        ┆ A       ┆ B               │
# │ A   ┆ 1        ┆ A       ┆ B               │
# └─────┴──────────┴─────────┴─────────────────┘
```

Comment (borchero) [reply crates/polars-core/src/series/implementations/categorical.rs]: Ah makes sense 😅 I'll update

Comment (borchero) [reply crates/polars-core/src/series/implementations/categorical.rs]: Fwiw, I think I was confused because the behavior is different for enums (for whose sake I started working on this), see

```python
import polars as pl

df = pl.DataFrame(
    {"a": ["foo", "bar"], "b": ["foo", "bar"]},
    schema={"a": pl.Enum(["foo", "bar"]), "b": pl.Categorical(pl.Categories.random())},
)
print(df.select(pl.all().min()))
# shape: (1, 2)
# ┌──────┬─────┐
# │ a    ┆ b   │
# │ ---  ┆ --- │
# │ enum ┆ cat │
# ╞══════╪═════╡
# │ foo  ┆ bar │
# └──────┴─────┘
```

Anyways, it should work correctly for both lexical and physical ordering now :)

Comment (nameexhaustion) [reply crates/polars-core/src/series/implementations/categorical.rs]: > Fwiw, I think I was confused because the behavior is different for enums

That's indeed the case

File: crates/polars-core/src/series/implementations/categorical.rs [hunk 2]
```diff
@@ -99,6 +99,48 @@ macro_rules! impl_cat_series {
                 Ok(())
             }
 
+            #[cfg(feature = "algorithm_group_by")]
+            unsafe fn agg_min(&self, groups: &GroupsType) -> Series {
+                if self.0.uses_lexical_ordering() {
+                    let s = self
+                        .0
+                        .cast(&DataType::String)
```
Comment (nameexhaustion) [inline crates/polars-core/src/series/implementations/categorical.rs]: The implementation should not cast to string here, that can end up being extremely inefficient. There should be a dedicated codepath.

It may not be a trivial implementation to make. Given that this already fixes the Enum case, it's also fine for this PR if you want to just leave an error with a message saying it's not implemented for categoricals.

Comment (borchero) [reply crates/polars-core/src/series/implementations/categorical.rs]: Makes sense... I think the categorical case would then be plenty more work; I simply replaced this with `unimplemented!()` for now 😅
