### PR TITLE
fix(rust): Ensure index column is sorted in streaming rolling aggs

### LINKED ISSUE #27231: streaming engine does not raise for `rolling` when index_column is unsorted
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.LazyFrame({"orderby": [1, 2, 4, 2], "values": [1, 2, 3, 4]})
q = df.rolling("orderby", period="2i").agg(pl.sum("values"))

q.collect(engine="in-memory")
# => InvalidOperationError: argument in operation 'rolling' is not sorted, please sort the 'expr/series/column' first

q.collect(engine="streaming")
shape: (4, 2)
┌─────────┬────────┐
│ orderby ┆ values │
│ ---     ┆ ---    │
│ i64     ┆ i64    │
╞═════════╪════════╡
│ 1       ┆ 1      │
│ 2       ┆ 3      │
│ 4       ┆ 7      │
│ 2       ┆ 7      │
└─────────┴────────┘
```

### Log output

```shell

```

### Issue description

The index column of a rolling expression is required to be sorted in ascending order. If I pass an unsorted column as the index when collecting with the in-memory engine, I get an error.

In contrast, in the streaming engine, no such error is raised.

### Expected behavior

I am not sure this is actually a bug really. To check for unsortedness in the streaming requires some amount of extra logic: checking sortedness of each incoming morsel and then propagating the max value from that morsel to the producer of "overlapped" morsels so that that max can be checked against the min of the next morsel. Maybe that is not worth the effort.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.39.3
Index type:          UInt32
Platform:            Linux-6.8.0-107-generic-x86_64-with-glibc2.39
Python:              3.14.3 | packaged by conda-forge | (main, Feb  9 2026, 21:56:02) [GCC 14.3.0]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                1.40.70
cloudpickle          3.1.2
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2026.3.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.10.8
numpy                2.4.3
openpyxl             3.1.5
pandas               2.3.3
polars_cloud         <not installed>
pyarrow              21.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           2.0.48
torch                2.10.0
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by wence-**
Previously, the streaming engine would not surface an error if the index
column for a rolling aggregation was not sorted. Do so by ensuring each
morsel is sorted, and that the maximum observed value of a previous morsel
is ordered before the minimum value of the next morsel.

- Closes https://github.com/pola-rs/polars/issues/27231

### CODE REVIEW

**Review by orlp — CHANGES_REQUESTED** [review]
Could you do it without unsafe? I don't think this is performance sensitive at all.

**Comment by wence-** [comment]
> Could you do it without unsafe? I don't think this is performance sensitive at all.

Done.

File: crates/polars-stream/src/nodes/rolling_group_by.rs [hunk 1]
```diff
@@ -327,7 +329,20 @@ impl ComputeNode for RollingGroupBy {
                     morsel_index_column.null_count() == 0,
                     ComputeError: "null values in `rolling` not supported, fill nulls."
                 );
-
+                if !morsel_index_column.is_empty() {
```
Comment (wence-) [inline crates/polars-stream/src/nodes/rolling_group_by.rs]: question: On line 323 we check that the height of the dataframe is zero and if so `continue`. But, I _think_ it is the case that a non-zero height dataframe may still be empty?

Comment (orlp) [reply crates/polars-stream/src/nodes/rolling_group_by.rs]: `is_empty` on a column checks the length of the column. The width of a column is always 1. I think this check is unnecessary. As you say, we do the zero-height check earlier.

Sorry I didn't catch this earlier :)

**Review by orlp — CHANGES_REQUESTED** [review]

File: crates/polars-stream/src/nodes/rolling_group_by.rs (hunk 1 above)
Comment (wence-) [reply crates/polars-stream/src/nodes/rolling_group_by.rs]: Removed the redundant check and rebased.

**Comment by wence-** [comment]
@orlp Anything else here? Thanks!

**Review by orlp — APPROVED** [review]

**Comment by orlp** [comment]
@wence- Sorry, I let it slip a bit then went on holiday :)

**Comment by wence-** [comment]
> @wence- Sorry, I let it slip a bit then went on holiday :)

Hope it was fun!
