### PR TITLE
fix: Don't null on oob in `list.get` for column index

### LINKED ISSUE #17252: `pl.Expr.list.get` raises error on null values.
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
    import polars as pl

    df = pl.DataFrame({
        'name': ['BOB-3', 'BOB', None],
    })

    split = df.with_columns(
        pl.col('name').str.split('-')
    )
    res = split.with_columns(pl.col('name').list.get(0))

```

### Log output

_No response_

### Issue description

Previously `pl.Expr.list.get` would propagate `null` values. Now it errors with `ComputeError: get index is out of bounds`. 

### Expected behavior

I would expect `pl.Expr.list.get` to not error on null list values.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0-rc.2
Index type:           UInt32
Platform:             Linux-6.9.6-arch1-1-x86_64-with-glibc2.39
Python:               3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          3.0.0
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.5.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               0.9.2.post8+g4cb29ba
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             3.1.2
pandas:               3.0.0.dev0+756.ge8e6be071c
pyarrow:              17.0.0.dev225+g72e7e4c6c
pydantic:             2.7.2
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Followup to #17262, closes #17252. Fixes the column idx case.

Added more test coverage.

### CODE REVIEW

File: crates/polars-plan/src/dsl/function_expr/list.rs [hunk 1]
```diff
@@ -427,28 +427,54 @@ pub(super) fn get(s: &mut [Series], null_on_oob: bool) -> PolarsResult<Option<Se
...
+                                    polars_bail!(ComputeError: "get index is out of bounds");
+                                }
+                            } else {
+                                Ok(Some(offset as IdxSize))
+                            }
+                        },
+                        _ => Ok(None),
+                    })
+                    .collect::<Result<IdxCa, _>>()?
+            };
```
Comment (mcrumiller) [inline crates/polars-plan/src/dsl/function_expr/list.rs:477]: @ritchie46 there's probably a better way to do this without duplicated code, maybe using something like `iter::repeat(true)` in place of the validity map, but my grasp of polars iterators is not up to snuff.

Comment (ritchie46) [reply crates/polars-plan/src/dsl/function_expr/list.rs:477]: I think its fine fo rnow. Thanks!

**Review by ritchie46 — APPROVED** [review]
