### PR TITLE
fix: Reset `is_count_star` flag between queries in collect_all

### LINKED ISSUE #26097: Panic exception when using scan_parquet + collect_all
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
data = pl.DataFrame({"A" : [1]})
tmp_file = "/tmp/polars-bug-repr.parquet"

data.write_parquet(tmp_file)

df = pl.scan_parquet(tmp_file).select(
    [
        pl.col("A")
    ]
)
print(df.collect())
dummy_df = pl.DataFrame({"v" : [1]}).lazy().select(pl.count())

results = pl.collect_all(
    [
        dummy_df,
        df
    ]
)

print(results)
```

### Log output

```shell
pyo3_runtime.PanicException: no valid schema can be derived for the query: ColumnNotFound(ErrString("A")
```

### Issue description

Calling `collect_all()` on a parquet-based lazy frame triggers panic. 

1) write a simple dataframe as parquet, read it back as LazyFrame
2) create another simple LazyFrame
3) call `collect_all` on the list of these frames

Polars crashes with a message: _pyo3_runtime.PanicException: no valid schema can be derived for the query: ColumnNotFound(ErrString("A")_

### Expected behavior

Shouldn't crash

### Installed versions

<details>

```
Polars:              1.37.1
Index type:          UInt32
Platform:            macOS-15.7.3-arm64-arm-64bit-Mach-O
Python:              3.14.2 (main, Dec  5 2025, 16:49:16) [Clang 17.0.0 (clang-1700.4.4.1)]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                1.42.25
cloudpickle          3.1.2
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.10.3
numpy                2.4.1
openpyxl             <not installed>
pandas               <not installed>
polars_cloud         <not installed>
pyarrow              <not installed>
pydantic             2.12.5
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by azimafroozeh**
Fixes #26097

### CODE REVIEW

File: crates/polars-plan/src/plans/optimizer/projection_pushdown/generic.rs [hunk 1]
```diff
@@ -19,6 +19,8 @@ pub(super) fn process_generic(
     let new_inputs = inputs
         .into_iter()
         .map(|node| {
+            proj_pd.is_count_star = false;
```
Comment (orlp) [inline crates/polars-plan/src/plans/optimizer/projection_pushdown/generic.rs]: This smells to me. `proj_pd` only contains `is_count_star`. If we do this, why is `proj_pd` even an argument to `process_generic`?

I'm not too sure what this does but I think removing the `proj_pd` argument and just using `ProjectionPushdown::new()` here makes more sense.

@ritchie46 wrote this (three years ago) so perhaps he has a better idea, but I wouldn't blame him for forgetting why this is the case.

Comment (ritchie46) [reply crates/polars-plan/src/plans/optimizer/projection_pushdown/generic.rs]: Let me check. The last touch was certainly not three years ago ;)

Comment (ritchie46) [reply crates/polars-plan/src/plans/optimizer/projection_pushdown/generic.rs]: This should be higher up.

It should be reset on every input of `IR::SinkMultiple`. Technically this is the first call-stack, so the bug is fixed, but semantically it should not be reset for other paths.

`SinkMultiple` is the root node of otherwise unrelated queries that are collected in a single batch. Though unrelated, they do scan sharing.

Specifically here: https://github.com/pola-rs/polars/blob/bfb06e4d6709bdd44a96ce6c68e4ec3f6975192c/crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs#L707
