### PR TITLE
fix(rust): Increase precision when constructing `float` Series

### LINKED ISSUE #25257: polars series truncates digits if reading a number as string
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.Series("name", ["a string", 0.123456789012345], strict=False)
```

### Log output

```shell
shape: (2,)
Series: 'name' [str]
[
	"a string"
	"0.123457"
]
```

### Issue description

The creation of a polars series from mixed types (string and float) truncates the float number by many digits.

### Expected behavior

No truncation, i.e. output:
shape: (2,)
Series: 'name' [str]
[
	"a string"
	"0.123456789012345"
]

### Installed versions

<details>

```
--------Version info---------
Polars:              1.35.2
Index type:          UInt32
Platform:            macOS-15.7.2-x86_64-i386-64bit
Python:              3.12.9 (main, Feb  4 2025, 14:38:38) [Clang 16.0.0 (clang-1600.0.26.6)]
Runtime:             rt32
```

</details>

### PR DESCRIPTION
**Pull request by camriddell**
Constructing a new Series with an unspecified datatype/string supertype led to a naive translation of passed floats to strings that was constrained by `polars.Config(float_precision=…)`
    
Float64 & Float32 are now handled in the same fashion as `PySeries.cast` when constructing new Series to preserve as much precision as possible for this style of representation.

Resolves #25257

### CODE REVIEW

**Comment by camriddell** [comment]
I assume that the drop in coverage is likely due to never internally casting to `Float32` when digesting PyObjects. If this is always the case shall I remove the `AnyValue::Float32` branch?

File: crates/polars-core/src/series/any_value.rs [hunk 1]
```diff
@@ -285,6 +286,18 @@ fn any_values_to_string(values: &[AnyValue], strict: bool) -> PolarsResult<Strin
                 AnyValue::StringOwned(s) => builder.append_value(s),
                 AnyValue::Null => builder.append_null(),
                 AnyValue::Binary(_) | AnyValue::BinaryOwned(_) => builder.append_null(),
+                AnyValue::Float64(f) => {
+                    let mut tmp = vec![];
```
Comment (orlp) [inline crates/polars-core/src/series/any_value.rs]: Can you re-use the buffer like `let mut owned` is at the start?

**Review by orlp — CHANGES_REQUESTED** [review]

**Comment by orlp** [comment]
> I assume that the drop in coverage is likely due to never internally casting to Float32 when digesting PyObjects. If this is always the case shall I remove the AnyValue::Float32 branch?

No don't worry about it.

File: crates/polars-core/src/series/any_value.rs (hunk 1 above)
Comment (camriddell) [reply crates/polars-core/src/series/any_value.rs]: This should be resolved now, let me know if the implementation looks correct- I'm still pretty new to Rust.

**Comment by camriddell** [comment]
> The implementation as-is is correct for pure floats, but I think it still goes wrong for nested types which recursively contain floats (like structs and lists).

Does this cover the cases you expressed concern about? I just parameterized with a few more cases to test against which all passed locally with out any further source changes.

**Comment by orlp** [comment]
@camriddell No that doesn't satisfy my concerns because the test case you added doesn't test the mixed string/struct case. This still loses precision:

```python
>>> pl.Series("name", ["a string", {"a": 0.123456789012345}], strict=False, dtype=pl.String)
shape: (2,)
Series: 'name' [str]
[
        "a string"
        "{0.123457}"
]
```

There needs to be a dedicated path for `struct`/`list`/`array` to handle it recursively, rather than using the `Display` implementation.

**Comment by camriddell** [comment]
> @camriddell No that doesn't satisfy my concerns because the test case you added doesn't test the mixed string/struct case. This still loses precision:
> 
> ```python
> >>> pl.Series("name", ["a string", {"a": 0.123456789012345}], strict=False, dtype=pl.String)
> shape: (2,)
> Series: 'name' [str]
> [
>         "a string"
>         "{0.123457}"
> ]
> ```
> 
> There needs to be a dedicated path for `struct`/`list`/`array` to handle it recursively, rather than using the `Display` implementation.

Thank you for the clarification and MRE, I'll look into this to recurse through nested data structures.

**Comment by camriddell** [comment]
Hi @orlp I think I have a working solution here. I did a bit of refactoring to keep recursive allocations minimal and added some more tests to cover the cases you highlighted.

The nested data structure formatting code is based on the code in `crates/polars-core/src/fmt.rs::{fmt_struct,fmt_list}`. Let me know if this seems like the right direction to move in.

**Comment by camdell** [comment]
@orlp just got the Float16 path up. I believe the test failure is unrelated?

**Comment by camriddell** [comment]
@orlp got the Float16 path up! The failure seems unrelated, but perhaps you can confirm this?

**Review by orlp — APPROVED** [review]

**Comment by orlp** [comment]
Thanks!

**Comment by lorentzenchr** [comment]
@camriddell Thanks for the fix!
