### PR TITLE
fix: Add support for float inputs for duration types

### LINKED ISSUE #11625: Polars duration silently truncates floats
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.select(pl.duration(hours=2.5))
shape: (1, 1)
┌──────────────┐
│ duration     │
│ ---          │
│ duration[ns] │
╞══════════════╡
│ 2h           │
└──────────────┘
```

### Log output

_No response_

### Issue description

`pl.duration` silently truncates floats to integers.

### Expected behavior

I would expect a duration of 2.5 hours to be 2 hours and 30 minutes, not 2 hours.

### Installed versions

0.19.7

### PR DESCRIPTION
**Pull request by dsprenkels**
This patch implements floating points as inputs to duration constructors.

Closes #11625

### CODE REVIEW

File: crates/polars-plan/src/dsl/functions/temporal.rs [hunk 1]
```diff
@@ -327,73 +328,66 @@ impl DurationArgs {
...
-            &self.minutes,
-            &self.milliseconds,
-            &self.microseconds,
-            &self.nanoseconds,
-        ]
-        .iter()
-        .all(|e| matches!(e, Literal(_)))
-    }
-
     fn as_literal(&self) -> Option<Expr> {
```
Comment (orlp) [inline crates/polars-plan/src/dsl/functions/temporal.rs:331]: If I read the code right, mixing integer and float literals will now cause `as_literal` to fail? I don't think that's intended?

File: py-polars/tests/unit/datatypes/test_duration.py [hunk 2]
```diff
@@ -214,3 +219,30 @@ def test_comparison_with_string_raises_9461() -> None:
...
+)
+@pytest.mark.parametrize(
+    "value",
+    [0.5, 0.0625, 0.00390625, 0.000244140625],
+)
+def test_duration_float_types_11625(
+    time_unit: TimeUnit, digit: str, multiplier: int, value: int | float
+) -> None:
+    s = pl.select(
+        pl.duration(**{digit: value}, time_unit=time_unit).alias("a")
```
Comment (orlp) [inline py-polars/tests/unit/datatypes/test_duration.py:249]: You only tested with literals? What about an actual dataframe with an expression of columns?

**Comment by dsprenkels** [comment]
@orlp Yes. Good points. I'll fix that

File: crates/polars-plan/src/dsl/functions/temporal.rs (hunk 1 above)
Comment (dsprenkels) [reply crates/polars-plan/src/dsl/functions/temporal.rs:331]: I updated this: Now it will always fall back to using Float64 if any of the arguments was not an integer.

File: py-polars/tests/unit/datatypes/test_duration.py (hunk 2 above)
Comment (dsprenkels) [reply py-polars/tests/unit/datatypes/test_duration.py:249]: I added a test that calls `pl.duration()` with a bunch of parametrized `Series` as inputs
