### PR TITLE
fix(rust): correct agg_sum for ChunkedArray.

### LINKED ISSUE #10242: DataFrame.groupBy().agg_mean() produce unexpected result if agg_col has more than one chunks.
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
#[test]
fn test_agg_mean() -> PolarsResult<()> {
    let series_a = Series::new("a", &[1, 1, 2, 2]);
    let mut series_b = Series::new("b", &[3.0, 3.0]);
    series_b.append(&Series::new("c", &[4.0, 4.0]));
    let df = DataFrame::new(vec![series_a, series_b])?;
    let mean = df.groupby(["a"])?.mean();
    dbg!(&mean?);
    Ok(())
}
```

image

### Issue description

After #8294, we uses the first chunkedArray to call `take_agg_no_null_primitive_iter_unchecked` or `take_agg_primitive_iter_unchecked_count_nulls`. If this series has more than one chunks, the result will be UB.

### Expected behavior

image

### Installed versions

<details>

Replace this line with a list of feature gates

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This closes #10242

### CODE REVIEW

File: crates/polars-core/src/frame/groupby/aggregations/mod.rs [hunk 1]
```diff
@@ -662,10 +662,10 @@ where
                     let out = if idx.is_empty() {
                         None
                     } else if idx.len() == 1 {
-                        self.get(first as usize).map(|sum| sum.to_f64().unwrap())
+                        arr.get(first as usize).map(|sum| sum.to_f64().unwrap())
```
Comment (ritchie46) [inline crates/polars-core/src/frame/groupby/aggregations/mod.rs:665]: Ai, that's a painful mistake that we didn't use the rechunked array.

**Review by ritchie46 — APPROVED** [review]

**Comment by ritchie46** [comment]
Thanks for the fix!

**Comment by reswqa** [comment]
Thanks for the review!
