### PR TITLE
fix: Nested dtypes in streaming `first`/`last`

### LINKED ISSUE #24936: Panic in streaming engine when aggregating over `Struct` with `Enum`
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
s = (
    pl.Series(
        "a",
        [{"f0": "c0"}],
        dtype=pl.Struct({"f0": pl.Enum(categories=["c0"])}),
    ),
)
df = pl.DataFrame(s)

q = df.lazy().select(pl.all(ignore_nulls=False).first())
assert_frame_equal(q.collect(engine="streaming"), df)
```

### Log output

```shell
thread '<unnamed>' (377604) panicked at crates/polars-arrow/src/array/struct_/mod.rs:204:5:
validity must be equal to the array's length
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/f2824da98d44c4a4e17bf39eb45103c8fc249117/library/std/src/panicking.rs:698:5
   1: core::panicking::panic_fmt
             at /rustc/f2824da98d44c4a4e17bf39eb45103c8fc249117/library/core/src/panicking.rs:75:14
   2: polars_arrow::array::struct_::StructArray::set_validity
             at /home/amber/git/polars/crates/polars-arrow/src/array/mod.rs:494:17
   3: polars_arrow::array::struct_::StructArray::with_validity
             at /home/amber/git/polars/crates/polars-arrow/src/array/mod.rs:484:18
   4: <polars_arrow::array::struct_::StructArray as polars_arrow::array::Array>::with_validity
             at /home/amber/git/polars/crates/polars-arrow/src/array/struct_/mod.rs:271:31
   5: polars_core::chunked_array::struct_::<impl polars_core::chunked_array::ChunkedArray<polars_core::datatypes::StructType>>::set_outer_validity
             at /home/amber/git/polars/crates/polars-core/src/chunked_array/struct_/mod.rs:452:24
   6: polars_core::chunked_array::struct_::<impl polars_core::chunked_array::ChunkedArray<polars_core::datatypes::StructType>>::with_outer_validity
             at /home/amber/git/polars/crates/polars-core/src/chunked_array/struct_/mod.rs:459:14
   7: polars_core::frame::row::av_buffer::AnyValueBufferTrusted::reset
             at /home/amber/git/polars/crates/polars-core/src/frame/row/av_buffer.rs:667:22
   8: polars_core::frame::row::av_buffer::AnyValueBufferTrusted::into_series
             at /home/amber/git/polars/crates/polars-core/src/frame/row/av_buffer.rs:688:14
   9: <polars_expr::reduce::first_last::GenericFirstLastGroupedReduction<P> as polars_expr::reduce::GroupedReduction>::finalize
             at /home/amber/git/polars/crates/polars-expr/src/reduce/first_last.rs:377:20
  10: <polars_stream::nodes::reduce::ReduceNode as polars_stream::nodes::ComputeNode>::update_state::{{closure}}
             at /home/amber/git/polars/crates/polars-stream/src/nodes/reduce.rs:134:27
  11: core::iter::adapters::map::map_try_fold::{{closure}}
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:95:28
  12: core::iter::traits::iterator::Iterator::try_fold
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2426:21
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:121:19
  14: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:192:14
  15: core::iter::traits::iterator::Iterator::try_for_each
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2487:14
  16: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:174:14
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs:25:41
  18: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs:34:9
  19: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3683:9
  20: core::iter::traits::iterator::Iterator::collect
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2027:9
  21: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:2141:51
  22: core::iter::adapters::try_process
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:160:17
  23: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:2141:9
  24: core::iter::traits::iterator::Iterator::collect
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2027:9
  25: polars_utils::itertools::Itertools::try_collect_vec
             at /home/amber/git/polars/crates/polars-utils/src/itertools/mod.rs:32:14
  26: <polars_stream::nodes::reduce::ReduceNode as polars_stream::nodes::ComputeNode>::update_state
             at /home/amber/git/polars/crates/polars-stream/src/nodes/reduce.rs:139:22
  27: polars_stream::graph::Graph::update_all_states
             at /home/amber/git/polars/crates/polars-stream/src/graph.rs:110:18
  28: polars_stream::execute::execute_graph
             at /home/amber/git/polars/crates/polars-stream/src/execute.rs:332:15
  29: polars_stream::skeleton::StreamingQuery::execute
             at /home/amber/git/polars/crates/polars-stream/src/skeleton.rs:148:27
  30: polars_stream::skeleton::run_query
             at /home/amber/git/polars/crates/polars-stream/src/skeleton.rs:35:56
  31: polars_lazy::frame::LazyFrame::collect_with_engine
             at /home/amber/git/polars/crates/polars-lazy/src/frame/mod.rs:686:30
  32: polars_python::lazyframe::general::<impl polars_python::lazyframe::PyLazyFrame>::collect::{{closure}}
             at /home/amber/git/polars/crates/polars-python/src/lazyframe/general.rs:619:21
  33: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  34: std::panicking::catch_unwind::do_call
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:590:40
  35: __rust_try
  36: std::panicking::catch_unwind
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:553:19
  37: std::panic::catch_unwind
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
  38: polars_error::signals::catch_keyboard_interrupt
             at /home/amber/git/polars/crates/polars-error/src/signals.rs:83:15
  39: <pyo3::marker::Python as polars_python::utils::EnterPolarsExt>::enter_polars::{{closure}}
             at /home/amber/git/polars/crates/polars-python/src/utils.rs:107:34
  40: pyo3::marker::Python::detach
             at /home/amber/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.26.0/src/marker.rs:595:9
  41: <pyo3::marker::Python as polars_python::utils::EnterPolarsExt>::enter_polars
             at /home/amber/git/polars/crates/polars-python/src/utils.rs:107:24
  42: polars_python::utils::EnterPolarsExt::enter_polars_df
             at /home/amber/git/polars/crates/polars-python/src/utils.rs:83:14
  43: polars_python::lazyframe::general::<impl polars_python::lazyframe::PyLazyFrame>::collect
             at /home/amber/git/polars/crates/polars-python/src/lazyframe/general.rs:612:12
  44: polars_python::lazyframe::general::<impl polars_python::lazyframe::PyLazyFrame>::__pymethod_collect__
             at /home/amber/git/polars/crates/polars-python/src/lazyframe/general.rs:74:1
  45: pyo3::impl_::trampoline::cfunction_with_keywords::{{closure}}
             at /home/amber/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.26.0/src/impl_/trampoline.rs:44:37
  46: pyo3::impl_::trampoline::trampoline::{{closure}}
             at /home/amber/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.26.0/src/impl_/trampoline.rs:190:54
  47: std::panicking::catch_unwind::do_call
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:590:40
  48: __rust_try
  49: std::panicking::catch_unwind
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:553:19
  50: std::panic::catch_unwind
             at /home/amber/.rustup/toolchains/nightly-2025-08-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
  51: pyo3::impl_::trampoline::trampoline
             at /home/amber/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.26.0/src/impl_/trampoline.rs:190:9
  52: pyo3::impl_::trampoline::cfunction_with_keywords
             at /home/amber/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.26.0/src/impl_/trampoline.rs:44:21
  53: polars_python::lazyframe::general::_::__INVENTORY::trampoline
             at /home/amber/git/polars/crates/polars-python/src/lazyframe/general.rs:74:1
  54: <unknown>
  55: PyObject_Vectorcall
  56: _PyEval_EvalFrameDefault
  57: PyEval_EvalCode
  58: <unknown>
  59: <unknown>
  60: <unknown>
  61: <unknown>
  62: <unknown>
  63: Py_RunMain
  64: Py_BytesMain
  65: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  66: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  67: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/home/amber/git/polars/py-polars/../scratch/test.py", line 36, in <module>
    assert_frame_equal(q.collect(engine="streaming"), df)
                       ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/amber/git/polars/py-polars/src/polars/_utils/deprecation.py", line 97, in wrapper
    return function(*args, **kwargs)
  File "/home/amber/git/polars/py-polars/src/polars/lazyframe/opt_flags.py", line 328, in wrapper
    return function(*args, **kwargs)
  File "/home/amber/git/polars/py-polars/src/polars/lazyframe/frame.py", line 2422, in collect
    return wrap_df(ldf.collect(engine, callback))
                   ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: validity must be equal to the array's length
```

### Issue description

`df.lazy().select(pl.all(ignore_nulls=False).first())` panics in the streaming engine when the dataframe contains a `Struct` with an `Enum` field

### Expected behavior

No error

### Installed versions

<details>

```
--------Version info---------
Polars:              1.35.0-beta.1
Index type:          UInt32
Platform:            Linux-6.14.0-33-generic-x86_64-with-glibc2.41
Python:              3.13.3 (main, Aug 14 2025, 11:53:40) [GCC 14.2.0]
Runtime:             unknown

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  1.8.0
altair               5.5.0
azure.identity       1.25.1
boto3                1.40.49
cloudpickle          3.1.1
connectorx           0.4.4
deltalake            1.2.0
fastexcel            0.16.0
fsspec               2025.9.0
gevent               25.9.1
google.auth          2.41.1
great_tables         0.19.0
matplotlib           3.10.7
numpy                2.3.4
openpyxl             3.1.5
pandas               2.3.3
polars_cloud         0.3.1
pyarrow              21.0.0
pydantic             2.12.3
pyiceberg            0.10.0
sqlalchemy           2.0.44
torch                <not installed>
xlsx2csv             0.8.4
xlsxwriter           3.2.5
```

</details>

### LINKED ISSUE #25297: Panic in streaming `first`
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

dtype = pl.Struct({"x": pl.Enum(["c0", "c1"])})
s = pl.Series("a", [{"x": "c0"}, {"x": "c1"}], dtype)
s.to_frame().lazy().select(pl.col.a.first()).collect(engine="streaming")
```

### Log output

```shell
thread '<unnamed>' (590967) panicked at crates/polars-arrow/src/array/struct_/mod.rs:204:5:
validity must be equal to the array's length
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/johndoe/Projects/polars-etc/polars/py-polars/t2.py", line 10, in <module>
    sl_first = df.lazy().select(pl.col.a.first()).collect(engine="streaming")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johndoe/Projects/polars-etc/polars/py-polars/src/polars/_utils/deprecation.py", line 97, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johndoe/Projects/polars-etc/polars/py-polars/src/polars/lazyframe/opt_flags.py", line 328, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johndoe/Projects/polars-etc/polars/py-polars/src/polars/lazyframe/frame.py", line 2423, in collect
    return wrap_df(ldf.collect(engine, callback))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: validity must be equal to the array's length
```

### Issue description

Panic when calling first on enum or categorical in a struct

### Expected behavior

No panic.

### Installed versions

<details>

```
1.35.2
```

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Fixes #25297.
Fixes #24936.

OP example:

```pycon
>>> import polars as pl
>>> dtype = pl.Struct({"x": pl.Enum(["c0", "c1"])})
>>> s = pl.Series("a", [{"x": "c0"}, {"x": "c1"}], dtype)
>>> s.to_frame().lazy().select(pl.col.a.first()).collect(engine="streaming")
shape: (1, 1)
┌───────────┐
│ a         │
│ ---       │
│ struct[1] │
╞═══════════╡
│ {"c0"}    │
└───────────┘
```

### CODE REVIEW

File: crates/polars-expr/src/reduce/first_last.rs [hunk 1]
```diff
@@ -447,13 +447,21 @@ impl<P: Policy + 'static> GroupedReduction for GenericFirstLastGroupedReduction<
                 );
             }
         }
-        unsafe {
+        let s = if self.in_dtype.is_nested() {
```
Comment (orlp) [inline crates/polars-expr/src/reduce/first_last.rs]: I don't understand why this branch is necessary. `add_unchecked_owned_physical` already has a path matching for structs, so why does it not work? I'd rather you fix the underlying issue than hide the symptoms here.

**Review by orlp — CHANGES_REQUESTED** [review]

File: crates/polars-expr/src/reduce/first_last.rs (hunk 1 above)
Comment (mcrumiller) [reply crates/polars-expr/src/reduce/first_last.rs]: Yep will look into this, sorry I didn't notice the struct path.

**Comment by mcrumiller** [comment]
@orlp I think I've found the issue--I'm not sure if what I've done is the proper fix, would you mind taking a look? In summary, it looks like an `AnyValueBufferTrusted::Struct` can only store physical fields.

The `Struct` variant of the `AnyValueBufferTrusted` is:

```rust
Struct(BitmapBuilder, Vec<(AnyValueBuffer<'a>, PlSmallStr)>)
```

and the `AnyValueBuffer` doesn't have a Categorical/Enum variant ([AnyValueBuffer](https://github.com/pola-rs/polars/blob/main/crates/polars-core/src/frame/row/av_buffer.rs#L15-L46)). 

So when this is constructed for a struct containing Enums, the `AnyValueBuffer` used by the struct is the `UInt8` variant.

So in `first_last.rs` when we finally go to call `buf.add_unchecked_owned_physical(&v)`, we encounter [this section](https://github.com/pola-rs/polars/blob/main/crates/polars-core/src/frame/row/av_buffer.rs#L508-L514):

```rust
for i in 0..avs.len() {
    let (builder, _) = builders.get_unchecked_mut(i);  // WARNING!! builder is AnyValueBuffer::UInt8
    let av = avs.get_unchecked(i).clone();
    // lifetime is bound to 'a
    let av = std::mem::transmute::<AnyValue<'_>, AnyValue<'a>>(av);
    builder.add(av.clone())  // ERROR!! av is AnyValue::Enum, cannot add to AnyValueBuffer::UInt8
}
```
See my in-lined comments.

I'm not sure the best way to approach this is.

**Comment by orlp** [comment]
Ah, can you try the following (undoing your change in `add_unchecked_owned_physical`)?

```rust
let phys_type = self.in_dtype.to_physical();
let mut buf = AnyValueBufferTrusted::new(&phys_type, self.values.len());
for v in core::mem::take(&mut self.values) {
    buf.add_unchecked_owned_physical(&v.to_physical());
}
Ok(buf.into_series().from_physical_unchecked(&self.in_dtype)?)
```

**Comment by mcrumiller** [comment]
Yep, I had tried something similar but not exactly the same (didn't supply the `phys_type` to the buffer constructor), let's see if your version works.

**Comment by mcrumiller** [comment]
This is giving me a core dump somewhere in `py-polars/tests/unit/operations/aggregation/test_aggregations.py`. Let me see if I can find out what's going on. It's not my new test/Gijs's example from the issue.

**Comment by mcrumiller** [comment]
Ok, the segfault is from calling `item` when we're dealing with enums, but not other logicals, and not nested types with logicals/enums. Here's a quick set of examples:

```python
from datetime import date
import polars as pl
from polars import col

s1 = pl.Series([{"a": "x"}], dtype=pl.Struct({"a": pl.Enum(["x"])}))  # Struct { "a": Enum }
s2 = pl.Series([date(2025, 1, 1)])                                    # Date
s3 = pl.Series(["a"], dtype=pl.Enum(["a"]))                           # Enum

lf = pl.LazyFrame({ "a": s1 })  # works
lf = pl.LazyFrame({ "a": s2 })  # works
lf = pl.LazyFrame({ "a": s3 })  # error

result = lf.select(col("a").item()).collect(engine="streaming")
```

I know that `item()` uses the same streaming impl we're dealing with here.

Edit: also happens with `first()`.

**Comment by mcrumiller** [comment]
Ok, another update. I think `AnyValue::Enum` uses `u32`, whereas the actual categoricals can be 8/16/32-bit depending on the mapping size.

image

So the core dump is happening in `add_physical` here:

```rust
            #[cfg(feature = "dtype-u8")]
            UInt8(builder) => {
                let AnyValue::UInt8(v) = val else {
                    unreachable_unchecked()  # core dump
                };
                builder.append_value(*v)
            },
```

**Comment by mcrumiller** [comment]
@orlp sorry for the stream of though. I've made it a step farther by making an exception here::

```rust
let phys_type = match &self.in_dtype {
    // AnyValue::Enum/Cat is always u32, we must ensure our builder does not use u8/u16.
    DataType::Enum(..) | DataType::Categorical(..) => DataType::UInt32,
    dt => dt.to_physical(),
};
```
The `add_unchecked_owned_physical()` now succeeds, but the `buf.into_series().from_physical_unchecked(&self.in_dtype)` now fails because `&self.in_dtype` is a Categorical/Enum mapping using `u8`. I'm trying to see how to make a new categorical dtype with `u32` instead but I'm not too familiar with the new categorical code--can you help out here?

This does feel like a quick patch and it's probably not the best ultimate solution, the `AnyValue` paths probably need a categorical update to go along with the new categorical implementation.

**Comment by mcrumiller** [comment]
@orlp I've put in a stopgap with:

```rust
unsafe {
    buf.into_series()
        .from_physical_unchecked(&phys_type)?
        .cast(&self.in_dtype)
}
```
So, we'll have an extra cast here, but I think we will have to do that no matter what. In most cases the cast will be a no-op, unless we are dealing with categoricals.

**Comment by orlp** [comment]
@mcrumiller No, that cast absolutely shouldn't be there as it will break extension types. I'm making a PR real quick to see if I can fix `AnyValue::to_physical` for categoricals.

**Comment by mcrumiller** [comment]
I think that does it. Thanks for all the help @orlp.

**Comment by mcrumiller** [comment]
Actually I think this might fix #24936 too, let me add a test.

Edit: yup it does.

**Review by orlp — APPROVED** [review]
