### PR TITLE
fix(rust): Fix lazy evaluation of replace_strict by making it fallible

### LINKED ISSUE #25865: replace_strict fails for lazy evaluation when used in  a filter
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df: pl.LazyFrame = pl.DataFrame([True, True, True, False], schema=["x"]).lazy()
df = df.filter(pl.col("x"))
df = df.filter(pl.col("x").replace_strict({True: True}))
df.collect()
```

### Log output

```shell
Traceback (most recent call last):
  File "./polars_replace_strict_bug.py", line 8, in <module>
    df.collect()
  File "./.venv/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 97, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/polars/lazyframe/opt_flags.py", line 328, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2429, in collect
    return wrap_df(ldf.collect(engine, callback))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: incomplete mapping specified for `replace_strict`

Hint: Pass a `default` value to set unmapped values.
```

### Issue description

``.replace_strict`` fails on a column containing only values specified in the replacement mapping ``old`` during lazy evaluation.

This happens when ``.replace_strict`` is used as an expression within ``.filter`` and the column in question was already used for filtering the data frame before calling ``.replace_strict``

### Expected behavior

The code should run without raising the ``InvalidOperationError`` error without the following workaround which temporarily adds the column to the data frame:

```python
import polars as pl

df: pl.LazyFrame = pl.DataFrame([True, True, True, False], schema=["x"]).lazy()
df = df.filter(pl.col("x"))
df = df.with_columns(
    pl.col("x").replace_strict({True: True}).alias("temp")
)
df = df.filter(pl.col("temp"))
df = df.drop("temp")
df.collect()
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.36.1
Index type:          UInt32
Platform:            macOS-26.1-arm64-arm-64bit
Python:              3.12.12 (main, Nov  4 2025, 08:53:00) [Clang 17.0.0 (clang-1700.0.13.5)]
Runtime:             rt32
```

</details>

### PR DESCRIPTION
**Pull request by sweb**
to avoid merging of conditions in lazy evaluation, we mark `replace_strict` as fallible - fixes #25865

### CODE REVIEW

File: crates/polars-lazy/src/tests/predicate_queries.rs [hunk 1]
```diff
@@ -314,3 +314,19 @@ fn test_push_join_col_predicates_to_both_sides_semi_12565() -> PolarsResult<()>
     assert_eq!(out, expected);
     Ok(())
 }
+
+#[test]
+fn test_replace_strict_filter_issue() -> PolarsResult<()> {
```
Comment (orlp) [inline crates/polars-lazy/src/tests/predicate_queries.rs]: Could you write this test in Python instead?

Comment (sweb) [reply crates/polars-lazy/src/tests/predicate_queries.rs]: I removed the Rust test - is the existing Python test enough, or should I move it to another place / change it?

**Comment by orlp** [comment]
Thanks.
