### PR TITLE
fix(rust, python): Correct field dtype of string concat

### LINKED ISSUE #11050: Wrong projection after alias
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

table = pl.LazyFrame({'a': [0]})
decoding = (
    pl.LazyFrame({'a': [0], 'repr': ['Zero']})
    .select('a', pl.concat_str(['a', 'repr'], separator=' - ').suffix('_repr'))   
    
    # .collect().lazy() # <- one way to fix the bug
)

decoded_item = (
    table
    .join(decoding, on = 'a')
    
    # use the decoding if exists else keep it like this
    .select(
        pl.col('a_repr')
        .fill_null(
            pl.col('a')
            # .cast(pl.Utf8) # <- another way to fix the bug
        ).alias('a')
    )
    .collect().item()
)

print(f'The first decoded value is: {decoded_item}') # Should print "Zero" but print 0

```

### Log output

```shell
The first decoded value is: 0
```

### Issue description

polars fails to project the good column here with the aliases going on

### Expected behavior

The first decoded value is: 0 - Zero

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.2
Index type:          UInt32
Platform:            Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.17
Python:              3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.1
deltalake:           <not installed>
fsspec:              2023.1.0
matplotlib:          <not installed>
numpy:               1.24.1
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.8
sqlalchemy:          2.0.1
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This try to fix #11050.

### CODE REVIEW

File: crates/polars-plan/src/dsl/function_expr/strings.rs [hunk 1]
```diff
@@ -89,7 +89,7 @@ impl StringFunction {
         use StringFunction::*;
         match self {
             #[cfg(feature = "concat_str")]
-            ConcatVertical(_) | ConcatHorizontal(_) => mapper.with_same_dtype(),
+            ConcatVertical(_) | ConcatHorizontal(_) => mapper.with_dtype(DataType::Utf8),
```
Comment (reswqa) [inline crates/polars-plan/src/dsl/function_expr/strings.rs:92]: I'm not 100% certain that this change is correct as I found that we specifically changed the dtype from `mapper.with_dtype(DataType::Utf8)` to ` mapper.with_same_dtype()` in #9457.

@ritchie46 Do you still remember the purpose of making that change. 🤔

Comment (ritchie46) [reply crates/polars-plan/src/dsl/function_expr/strings.rs:92]: Yes this is correct. I didn't think the input types would be non-string.

**Review by ritchie46 — APPROVED** [review]
