### PR TITLE
fix(rust, python): Reading an only-header csv file in streaming mode should not panic

### LINKED ISSUE #10792: Collect using streaming on empty LazyFrame returns `called 'Option::unwrap()' on a 'None' value`
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

`empty.csv`
```csv
Name, Address
```

```python
import polars as pl
e_pl = pl.scan_csv('empty.csv')
e_pl.collect(streaming=True)
```

### Issue description

Collecting data using streaming on an empty LazyFrame returns an `called 'Option::unwrap()' on a 'None' value` 

### Expected behavior

Should not return PanicException and work the same as LazyFrame with rows

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Darwin-22.6.0-x86_64-i386-64bit
Python:      3.7.16 (default, Mar 28 2023, 11:28:19) 
[Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
numpy:       1.16.5
pandas:      0.24.2
pyarrow:     <not installed>
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>```

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This fixes #10792.

### CODE REVIEW

File: crates/polars-pipe/src/executors/sinks/ordered.rs [hunk 1]
```diff
@@ -10,11 +12,15 @@ use crate::operators::{
 #[derive(Clone)]
 pub struct OrderedSink {
```
Comment (reswqa) [inline crates/polars-pipe/src/executors/sinks/ordered.rs:13]: If we want to add lifecycle parameter here and then change the `SchemaRef` to `&Schema`, it is also ok to me.

Comment (ritchie46) [reply crates/polars-pipe/src/executors/sinks/ordered.rs:13]: On streaming queries a single schema clone is fine. They are meant for huge data sets. ^^

**Review by ritchie46 — APPROVED** [review]
