### PR TITLE
fix: invalid predicate optimization

### LINKED ISSUE #13300: Cannot filter aliased column after `join` (in lazy mode)
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
lf = polars.LazyFrame({"col1": [True, False, True, False], "col2": range(4), "col3": range(10,14)})
lf_other = polars.LazyFrame({"col4": [0, 11, 2, 13], "col5": range(20, 24)})

lf = lf.with_columns(
    polars.when(polars.col("col1") == True)
    .then(polars.col("col2"))
    .otherwise(polars.col("col3"))
    .alias("new_col"))

# filtering by aliased column works
print(lf.filter(polars.col("new_col") < 12).collect())
# ┌───────┬──────┬──────┬─────────┐
# │ col1  ┆ col2 ┆ col3 ┆ new_col │
# │ ---   ┆ ---  ┆ ---  ┆ ---     │
# │ bool  ┆ i64  ┆ i64  ┆ i64     │
# ╞═══════╪══════╪══════╪═════════╡
# │ true  ┆ 0    ┆ 10   ┆ 0       │
# │ false ┆ 1    ┆ 11   ┆ 11      │
# │ true  ┆ 2    ┆ 12   ┆ 2       │
# └───────┴──────┴──────┴─────────┘

lf = lf.join(lf_other, left_on="new_col", right_on="col4", how="left")
df = lf.collect()
print(df)
# ┌───────┬──────┬──────┬─────────┬──────┐
# │ col1  ┆ col2 ┆ col3 ┆ new_col ┆ col5 │
# │ ---   ┆ ---  ┆ ---  ┆ ---     ┆ ---  │
# │ bool  ┆ i64  ┆ i64  ┆ i64     ┆ i64  │
# ╞═══════╪══════╪══════╪═════════╪══════╡
# │ true  ┆ 0    ┆ 10   ┆ 0       ┆ 20   │
# │ false ┆ 1    ┆ 11   ┆ 11      ┆ 21   │
# │ true  ┆ 2    ┆ 12   ┆ 2       ┆ 22   │
# │ false ┆ 3    ┆ 13   ┆ 13      ┆ 23   │
# └───────┴──────┴──────┴─────────┴──────┘

# after `join`, filtering by original column name works
lf_selection = lf.select(["col5", "col2", "col3"])
lf_selection_filtered = lf_selection.filter(polars.col("col5") < 23)
lf_selection.collect()
lf_selection_filtered.collect()

# after `join`, selecting by aliased column name works
lf_selection_with_aliased_col = lf.select(["new_col", "col2", "col3"])
print(lf_selection_with_aliased_col.collect())  # works even with `streaming=True`
# ┌─────────┬──────┬──────┐
# │ new_col ┆ col2 ┆ col3 │
# │ ---     ┆ ---  ┆ ---  │
# │ i64     ┆ i64  ┆ i64  │
# ╞═════════╪══════╪══════╡
# │ 0       ┆ 0    ┆ 10   │
# │ 11      ┆ 1    ┆ 11   │
# │ 2       ┆ 2    ┆ 12   │
# │ 13      ┆ 3    ┆ 13   │
# └─────────┴──────┴──────┘

print("Eager mode seems to work nicely: ", df.select(["new_col", "col2", "col3"]).filter(polars.col("new_col") < 12))

# exception: after `join`, filtering by aliased column name stops working
lf_selection_with_aliased_col_and_filter = lf_selection_with_aliased_col.filter(polars.col("new_col") < 12)
lf_selection_with_aliased_col_and_filter.collect()  # `ColumnNotFoundError: new_col`
```

### Log output

```shell
join parallel: true
LEFT join dataframes finished
join parallel: true
LEFT join dataframes finished
join parallel: true
LEFT join dataframes finished
dataframe filtered
join parallel: true
LEFT join dataframes finished
join parallel: true
dataframe filtered
---------------------------------------------------------------------------
ColumnNotFoundError                       Traceback (most recent call last)
Cell In[41], line 49
     36 # ┌─────────┬──────┬──────┐
     37 # │ new_col ┆ col2 ┆ col3 │
     38 # │ ---     ┆ ---  ┆ ---  │
   (...)
     46 
     47 # exception: filter by aliased column
     48 lf_selection_with_aliased_col_and_filter = lf_selection_with_aliased_col.filter(polars.col("new_col") < 12)
---> 49 lf_selection_with_aliased_col_and_filter.collect()  # `ColumnNotFoundError: new_col`

File ~/mambaforge-pypy3/envs/quantlab/lib/python3.10/site-packages/polars/lazyframe/frame.py:1706, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, _eager)
   1693     comm_subplan_elim = False
   1695 ldf = self._ldf.optimization_toggle(
   1696     type_coercion,
   1697     predicate_pushdown,
   (...)
   1704     _eager,
   1705 )
-> 1706 return wrap_df(ldf.collect())

ColumnNotFoundError: new_col
```

### Issue description

It looks like after a join (in lazy mode), we cannot filter by column that we created before using `.with_columns` and `.alias` anymore.

### Expected behavior

Would expect the same behavior of `.filter` as before the `.join` operation.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-6.1.68-1-MANJARO-x86_64-with-glibc2.38
Python:               3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           0.3.2
deltalake:            <not installed>
fsspec:               2023.12.2
gevent:               23.9.1
matplotlib:           3.6.0
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               1.5.3
pyarrow:              14.0.2
pydantic:             1.10.13
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.50
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #13300

### CODE REVIEW

File: crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/join.rs [hunk 1]
```diff
@@ -117,24 +117,26 @@ pub(super) fn process_join(
 
         debug_assert_aexpr_allows_predicate_pushdown(predicate, expr_arena);
 
-        if check_input_node(predicate, &schema_left, expr_arena) && !block_pushdown_left {
+        if !block_pushdown_left && check_input_node(predicate, &schema_left, expr_arena) {
```
Comment (ritchie46) [inline crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/join.rs:120]: Do the cheap check first.
