### PR TITLE
fix: Make sum on strings error in group_by context

### LINKED ISSUE #24659: Group-by sum on strings does not error as it should
```python
>>> pl.DataFrame({"str": ["a", "b"]}).group_by(1).agg(pl.col.str.sum())
shape: (1, 2)
┌─────────┬──────┐
│ literal ┆ str  │
│ ---     ┆ ---  │
│ i32     ┆ str  │
╞═════════╪══════╡
│ 1       ┆ null │
└─────────┴──────┘
```

This should return an error like the normal sum on strings:

```python
>>> pl.DataFrame({"str": ["a", "b"]}).select(pl.col.str.sum())
Traceback (most recent call last):
    ...
polars.exceptions.InvalidOperationError: `sum` operation not supported for dtype `str`

Hint: you may mean to call `str.join` or `list.join`
```

### PR DESCRIPTION
**Pull request by wtn**
Fixes #24659.

Calling `sum()` on string columns in `group_by` context silently returned null instead of raising an error.

### Reproduction
```python
pl.DataFrame({"str": ["a", "b"]}).group_by(1).agg(pl.col.str.sum())
# Returns null instead of erroring
```

Expected behavior (as in select context):
```python
pl.DataFrame({"str": ["a", "b"]}).select(pl.col.str.sum())
# InvalidOperationError: `sum` operation not supported for dtype `str`
```

### Cause

String type implements `sum_reduce()` which correctly raises an error, but was missing an `agg_sum()` override in the `PrivateSeries` impl. The default `agg_sum()` implementation returns null for unsupported types, causing silent failure in `group_by` aggregations.

### Fix

Add `agg_sum()` override for String type that raises the same error as `sum_reduce()`, ensuring consistent behavior across select and `group_by` contexts.

### CODE REVIEW

**Comment by ritchie46** [comment]
Thanks for the PR. This should be handled on the IR conversion and raise an InvalidOperation. We shouldn't panic.

**Comment by wtn** [comment]
Moved the check to `AExpr::to_field_impl` during schema inference. Raises `InvalidOperationError`, no panic.

File: crates/polars-plan/src/plans/aexpr/schema.rs [hunk 1]
```diff
@@ -147,6 +147,29 @@ impl AExpr {
                     Item { input: expr, .. } => ctx.arena.get(*expr).to_field_impl(ctx),
                     Sum(expr) => {
                         let mut field = ctx.arena.get(*expr).to_field_impl(ctx)?;
+                        match field.dtype() {
```
Comment (orlp) [inline crates/polars-plan/src/plans/aexpr/schema.rs]: Can you merge this match into the match just below `let dt = match`?

Comment (wtn) [reply crates/polars-plan/src/plans/aexpr/schema.rs]: I made the change and rebased.

**Review by orlp — APPROVED** [review]
