### PR TITLE
fix: Parquet several smaller issues

### LINKED ISSUE #18303: Parquet nested slice pushdown gives incorrect results
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from polars.testing import assert_frame_equal

df = pl.DataFrame({
    'a': [{ 'x': "" }, { 'x': "0" }],
})

df.write_parquet('/tmp/t.parquet')
df2 = pl.scan_parquet('/tmp/t.parquet').slice(1, 1).collect()

assert_frame_equal(df, df2)
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/johndoe/Projects/polars/py-polars/polars/testing/asserts/frame.py", line 114, in assert_frame_equal
    _assert_series_values_equal(
  File "/home/johndoe/Projects/polars/py-polars/polars/testing/asserts/series.py", line 182, in _assert_series_values_equal
    raise_assertion_error(
  File "/home/johndoe/Projects/polars/py-polars/polars/testing/asserts/utils.py", line 12, in raise_assertion_error
    raise AssertionError(msg) from cause
AssertionError: Series are different (exact value mismatch)
[left]:  [{'x': '0'}]
[right]: [{'x': ''}]
```

### Issue description

Nested parquet structures don't interact well with tail slice pushdown.

### Expected behavior

This should give the same output.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

### LINKED ISSUE #18304: pl.LazyDataFrame.slice has a buggy behaviour with non scalar columns.
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import tempfile
df = pl.DataFrame(
    {
        "list_struct": [[{"value": i} for _ in range(2)] for i in range(50)],
        "list": [[i for _ in range(2)] for i in range(50)],
        "struct": [{"value": i}for i in range(50)],
        "int": [i for i in range(50)],
        "str": [str(i) for i in range(50)]
     }
)
file = tempfile.mktemp(".parquet")
df.write_parquet(file)
print(pl.scan_parquet(file).collect().slice(10, 2)) # Works properly and return 10 -> 12
print(pl.scan_parquet(file).select(pl.all().slice(10, 2)).collect())  # Works properly and return 10 -> 12
# Error
print(pl.scan_parquet(file).slice(10, 2).collect())  # Works properly and return 10 -> 12 for the int and string but not for list & struct
```

### Log output

_No response_

### Issue description

`pl.LazyDataFrame.slice` returns bugged values for non scalar values by not taking offset into account.
Typically, list & struct combination will return the first element without the offset.

# Input DF
| list_struct  | list     | struct | int | str |
|--------------|----------|--------|-----|-----|
| [{0}, {0}]   | [0, 0]   | {0}    | 0   | 0   |
| [{1}, {1}]   | [1, 1]   | {1}    | 1   | 1   |
| [{2}, {2}]   | [2, 2]   | {2}    | 2   | 2   |
| [{3}, {3}]   | [3, 3]   | {3}    | 3   | 3   |
| [{4}, {4}]   | [4, 4]   | {4}    | 4   | 4   |
| …            | …        | …      | …   | …   |
| [{45}, {45}] | [45, 45] | {45}   | 45  | 45  |
| [{46}, {46}] | [46, 46] | {46}   | 46  | 46  |
| [{47}, {47}] | [47, 47] | {47}   | 47  | 47  |
| [{48}, {48}] | [48, 48] | {48}   | 48  | 48  |
| [{49}, {49}] | [49, 49] | {49}   | 49  | 49  |
# ✅ pl.scan_parquet(file).collect().slice(10, 2)
| list_struct  | list     | struct | int | str |
|--------------|----------|--------|-----|-----|
| [{10}, {10}] | [10, 10] | {10}   | 10  | 10  |
| [{11}, {11}] | [11, 11] | {11}   | 11  | 11  |
# ✅ pl.scan_parquet(file).select(pl.all().slice(10, 2)).collect()
| list_struct  | list     | struct | int | str |
|--------------|----------|--------|-----|-----|
| [{10}, {10}] | [10, 10] | {10}   | 10  | 10  |
| [{11}, {11}] | [11, 11] | {11}   | 11  | 11  |
# 💣 pl.scan_parquet(file).slice(10, 2).collect()
list(struct), list and struct ignores the offset but not int & str
| list_struct | list   | struct | int | str |
|-------------|--------|--------|-----|-----|
| [{0}, {0}]  | [0, 0] | {0}    | 10  | 10  |
| [{1}, {1}]  | [1, 1] | {1}    | 11  | 11  |

### Expected behavior

`pl.LazyDataframe.slice` behave similarly:
- with scalar and struct, list columns
- than `pl.Dataframe.slice` & `pl.LazyDataframe.select(pl.all().slice)`

### Installed versions

<details>

```

--------Version info---------
Polars:               1.5.0
Index type:           UInt32
Platform:             macOS-14.6.1-arm64-arm-64bit
Python:               3.10.13 (main, Oct 30 2023, 14:05:33) [Clang 14.0.3 (clang-1403.0.22.14.1)]
----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2024.5.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.9.1
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              17.0.0
pydantic:             2.8.2
pyiceberg:            <not installed>
sqlalchemy:           2.0.31
torch:                2.3.1
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by coastalwhite**
This fixes several small parquet problems.

I would recommend reviewing this PR commit by commit.

Fixes #18304.
Fixes #18303.

### CODE REVIEW

File: crates/polars-parquet/src/arrow/read/deserialize/nested.rs [hunk 1]
```diff
@@ -202,6 +202,17 @@ pub fn columns_to_iter_recursive(
             )?
             .collect_n(filter)?
         },
+        Binary | Utf8 => {
```
Comment (ritchie46) [inline crates/polars-parquet/src/arrow/read/deserialize/nested.rs:205]: We don't support those types. I think we directly use `BinviewDecoder` here if we can.

Comment (ritchie46) [reply crates/polars-parquet/src/arrow/read/deserialize/nested.rs:205]: We will leave this for this PR. But we should be able to remove the code that generates `(Large)Utf8`, `(LargeBinary)` in favor of `BinaryView`.
