### PR TITLE
fix(rust, python): fix `is_in` on empty series

### LINKED ISSUE #10171: Panic with invalid `is_in`
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.Series([1]).is_in(pl.Series([[]]))
# => PanicException: called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("cannot unpack series, data types don't match"))
```

### Issue description

See example 

### Expected behavior

Better error message or boolean result.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.9
Index type:          UInt32
Platform:            macOS-13.5-arm64-arm-64bit
Python:              3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  0.5.1
cloudpickle:         2.2.1
connectorx:          0.3.2a7
deltalake:           0.10.0
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.1
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            1.10.11
sqlalchemy:          2.0.19
xlsx2csv:            0.8.1
xlsxwriter:          3.1.2
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #10171

### CODE REVIEW

File: crates/polars-plan/src/dsl/mod.rs [hunk 1]
```diff
@@ -1045,16 +1045,7 @@ impl Expr {
     #[cfg(feature = "is_in")]
     pub fn is_in<E: Into<Expr>>(self, other: E) -> Self {
         let other = other.into();
-        let has_literal = has_root_literal_expr(&other);
```
Comment (ritchie46) [inline crates/polars-plan/src/dsl/mod.rs:1048]: This produced the wrong length and didn't keep the left sides name. We must go through the engine.
