### PR TITLE
fix: Group-By aggregation problems caused by `AmortSeries`

### LINKED ISSUE #25036: Bug/Regression in rolling forward fill with group_by
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
frame = pl.DataFrame({
        "date": [datetime.date(2013, 1, 1), datetime.date(2013, 1, 2), datetime.date(2013, 1, 3)],
        "value": [4, None, None]
    })

actual = frame.rolling(index_column="date", period="2d").agg(pl.col("value").forward_fill(limit=None).last())
print(actual)
>>> shape: (3, 2)
┌────────────┬───────┐
│ date       ┆ value │
│ ---        ┆ ---   │
│ date       ┆ i64   │
╞════════════╪═══════╡
│ 2013-01-01 ┆ 4     │
│ 2013-01-02 ┆ 4     │
│ 2013-01-03 ┆ 4     │
└────────────┴───────┘

frame = pl.DataFrame({
        "date": [datetime.date(2013, 1, 1), datetime.date(2013, 1, 2), datetime.date(2013, 1, 3)] * 2,
        "group": ["A"] * 3 + ["B"] * 3,
        "value": [None, None, 3, 4, None, None],
})
actual = frame.rolling(
    index_column="date", period="2d", group_by="group"
).agg(pl.col("value").forward_fill(limit=None).last())
print(actual)
>>> 
shape: (6, 3)
┌───────┬────────────┬───────┐
│ group ┆ date       ┆ value │
│ ---   ┆ ---        ┆ ---   │
│ str   ┆ date       ┆ i64   │
╞═══════╪════════════╪═══════╡
│ A     ┆ 2013-01-01 ┆ null  │
│ A     ┆ 2013-01-02 ┆ null  │
│ A     ┆ 2013-01-03 ┆ null  │
│ B     ┆ 2013-01-01 ┆ null  │
│ B     ┆ 2013-01-02 ┆ null  │
│ B     ┆ 2013-01-03 ┆ null  │
└───────┴────────────┴───────┘
```

### Log output

```shell

```

### Issue description

Rolling forward fill with `group_by` returns all `null` frame.

### Expected behavior

Expectation would be that the forward fill also works correctly for `group_by="group"`.

Not sure if this is in any way linked to this [PR](https://github.com/pola-rs/polars/pull/24859)?

### Installed versions

<details>

```
--------Version info---------
Polars:              1.35.0
Index type:          UInt32
Platform:            macOS-26.0.1-arm64-arm-64bit
Python:              3.12.12 | packaged by conda-forge | (main, Oct 22 2025, 23:34:53) [Clang 19.1.7 ]
Runtime:             rt32
----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          3.1.1
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.16.0
fsspec               2025.9.0
gevent               <not installed>
google.auth          2.41.1
great_tables         <not installed>
matplotlib           3.10.7
numpy                2.3.4
openpyxl             <not installed>
pandas               2.3.3
polars_cloud         <not installed>
pyarrow              20.0.0
pydantic             2.12.3
pyiceberg            <not installed>
sqlalchemy           2.0.44
torch                2.5.1
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by coastalwhite**
Fixes #25036.

### CODE REVIEW

File: crates/polars-core/src/chunked_array/list/iterator.rs [hunk 1]
```diff
@@ -93,9 +93,7 @@ impl<I: Iterator<Item = Option<ArrayBox>>> Iterator for AmortizedListIter<'_, I>
 
                 // SAFETY:
```
Comment (ritchie46) [inline crates/polars-core/src/chunked_array/list/iterator.rs]: Comment not needed anymore.

**Comment by btschroer** [comment]
Thanks @coastalwhite for fixing and amending with an additional test 🚀
