### PR TITLE
fix(python, rust): don't move right endpoint of windows in rolling in default `offset==-period` case

### LINKED ISSUE #12218: Unexpected behavior from the “_saturating” suffix
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import date

# Create a Polars DataFrame
data = {
    "customer_id": [1],
    "sales_sum": [100.50],
    "booking_date": [date(2020, 7, 31)],
    "merchant_id":["13"]
}

df = pl.DataFrame(data)

(df
.sort(["booking_date", "customer_id"])
.rolling(index_column="booking_date", period="1mo_saturating", by="customer_id")
.agg(
    pl.col("sales_sum").sum().alias("sales_sum_1mo"),
    pl.col("merchant_id").n_unique().alias("merchants_for_cust_1mo"),
)
)
```

### Log output

```shell
┌─────────────┬──────────────┬───────────────┬────────────────────────┐
│ customer_id ┆ booking_date ┆ sales_sum_1mo ┆ merchants_for_cust_1mo │
│ ---         ┆ ---          ┆ ---           ┆ ---                    │
│ i64         ┆ date         ┆ f64           ┆ u32                    │
╞═════════════╪══════════════╪═══════════════╪════════════════════════╡
│ 1           ┆ 2020-07-31   ┆ 0.0           ┆ null                   │
└─────────────┴──────────────┴───────────────┴────────────────────────┘
```

### Issue description

I'm doing some rolling aggregations on different time periods. When using the “_saturating”-suffix for months in the period-argument of polars.DataFrame.rolling I'm seeing some unexpected behavior.

This may not be a "bug" per se, but I do believe most would agree that it's unexpected behavior. Though I'm not 100% sure what expected behvaior would be in this case.

In the provided example we are using .rolling where a date column is the index and the grouping is done of customer.

In the cases where the customer has only one order in the rolling period under consideration, and that order was placed on the last day of a month (where the end day number of the month is higher than the enda day number of the month we are rolling back to) zeroes and nulls are returned. I.e. the order(s) on the date we are looking back from are omitted from the aggregations.

It makes sense from one point of view (from July 31 we go back to the last day of the previous month, June 30, and then forward one month, to July 30), but I can't think of any usecase where this is actually what the user wants.

### Expected behavior

Unsure. June 30 - July 31 or July 1 - July 31?

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-4.14.326-245.539.amzn2.x86_64-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #12218

### CODE REVIEW

File: crates/polars-time/src/windows/group_by.rs [hunk 1]
```diff
@@ -242,7 +242,7 @@ pub(crate) fn group_by_values_iter_lookbehind(
     // Use binary search to find the initial start as that is behind.
     let mut start = if let Some(&t) = time.get(start_offset) {
         let lower = add(&offset, t, tz.as_ref())?;
-        let upper = add(&period, lower, tz.as_ref())?;
+        let upper = t; // period == -offset, so `t + offset + period` is equal to `t`
```
Comment (ritchie46) [inline crates/polars-time/src/windows/group_by.rs:245]: Is this commented out or a comment? If a comment, can it be moved above with some additional explanation?

**Review by ritchie46 — APPROVED** [review]

**Comment by MarcoGorelli** [comment]
thanks!
