### PR TITLE
fix: Parquet predicate pushdown for `lit(_) !=`

### LINKED ISSUE #19238: Parquet filtering incorrect if left operand of binop is literal for `!=` filter
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from pathlib import Path
import polars as pl
p = Path("file.pq")
df = pl.DataFrame(
        {
            "a": [1, 2, 3, None, 4, 5],
            "b": [None, None, 3, None, 4, 0],
        }
    )

df.write_parquet(p)

lf = pl.scan_parquet(p)

q_bad = lf.filter(pl.lit(0) != pl.col("a"))

q_good = lf.filter(pl.col("a") != pl.lit(0))

expect = df.filter(pl.lit(0) != pl.col("a"))

print("Expected")
print(expect)
print("Good")
print(q_good.collect())
print("Bad")
print(q_bad.collect())
```
Output:
```
Expected
shape: (5, 2)
┌─────┬──────┐
│ a   ┆ b    │
│ --- ┆ ---  │
│ i64 ┆ i64  │
╞═════╪══════╡
│ 1   ┆ null │
│ 2   ┆ null │
│ 3   ┆ 3    │
│ 4   ┆ 4    │
│ 5   ┆ 0    │
└─────┴──────┘
Good
shape: (5, 2)
┌─────┬──────┐
│ a   ┆ b    │
│ --- ┆ ---  │
│ i64 ┆ i64  │
╞═════╪══════╡
│ 1   ┆ null │
│ 2   ┆ null │
│ 3   ┆ 3    │
│ 4   ┆ 4    │
│ 5   ┆ 0    │
└─────┴──────┘
Bad
shape: (0, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
└─────┴─────┘
```

### Log output

```shell
dataframe filtered
parquet file must be read, statistics not sufficient for predicate.
parquet file can be skipped, the statistics were sufficient to apply the predicate.
```

### Issue description

If a literal is the left operand in a binop, parquet filters appear to be applied incorrectly.

### Expected behavior

Both orderings should produce the same result.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Linux-6.8.0-45-generic-x86_64-with-glibc2.35
Python:              3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                2.0.2
openpyxl             3.1.5
pandas               2.2.3
pyarrow              17.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           2.0.35
torch                2.4.1.post100
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by coastalwhite**
Fixes #19238.

### CODE REVIEW

File: crates/polars-expr/src/expressions/binary.rs [hunk 1]
```diff
@@ -354,7 +354,7 @@ mod stats {
         use ChunkCompareIneq as C;
         match op {
             Operator::Eq => apply_operator_stats_eq(min_max, literal),
-            Operator::NotEq => apply_operator_stats_eq(min_max, literal),
+            Operator::NotEq => apply_operator_stats_neq(min_max, literal),
```
Comment (coastalwhite) [inline crates/polars-expr/src/expressions/binary.rs:357]: This is the actual fix. The rest are all drive-by's.

Comment (ritchie46) [reply crates/polars-expr/src/expressions/binary.rs:357]: auch.

**Review by ritchie46 — APPROVED** [review]
