### PR TITLE
fix: Make `struct.with_fields` data model coherent

### LINKED ISSUE #18461: Unexpected behaviour when applying `struct.with_fields` to multiple columns
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

(
    pl.DataFrame({"X": [("1",)], "Y": [("3",)]})
    .select(pl.all().list.to_struct(fields=("a",)))
    .select(pl.all().struct.with_fields(pl.field("a").cast(pl.Int32)))
)
```

The above code creates two struct columns and tries to cast their fields from strings to integers. From v1.2.1–1.6.0 this results in:

| X |
| - |
| struct[2] |
| {3, {"3"}} |

### Log output

_No response_

### Issue description

The result of calling `struct.with_fields` on a multi-column expression seems to have changed since version 1.1.0. Instead of applying the `with_fields` transformation to each column independently, the current implementation seems to nest all of the updated fields in the first column with unexpected values.

### Expected behavior

With 1.1.0 the above example does what I would expect: it casts the first field of each struct to an integer:

| X | Y |
| - | - |
| struct[1] | struct[1] |
| {1} | {3} |

### Installed versions

<details>

```
--------Version info---------
Polars:              1.6.0
Index type:          UInt32
Platform:            macOS-14.5-arm64-arm-64bit
Python:              3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.1.0
openpyxl             <not installed>
pandas               2.2.2
pyarrow              17.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

```

</details>

### LINKED ISSUE #24568: Combining `value_counts()` with `with_fields(..)` yields wrong results non-deterministically
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame(data=dict(x=[-1,-2,-2]), schema=dict(x=pl.Int64))
df.select(pl.col("x").value_counts().struct.with_fields(pl.field("count")*2))
# Yields
# shape: (2, 1)
# ┌───────────┐
# │ x         │
# │ ---       │
# │ struct[2] │
# ╞═══════════╡
# │ {-2,2}    │
# │ {-1,4}    │
# └───────────┘
# or 
# ┌───────────┐
# │ x         │
# │ ---       │
# │ struct[2] │
# ╞═══════════╡
# │ {-1,2}    │
# │ {-2,4}    │
# └───────────┘
```

### Log output

```shell

```

### Issue description

In around half of the cases the above query yields a wrong result. It looks like the order of only the first field is randomly switched around. It would be fine if both were ordered consistently non-deterministically (since `value_counts` is non-deterministic itself).

### Expected behavior

It should always yield
```
# ┌───────────┐
# │ x         │
# │ ---       │
# │ struct[2] │
# ╞═══════════╡
# │ {-2,4}    │
# │ {-1,2}    │
# └───────────┘
```
or
```
# ┌───────────┐
# │ x         │
# │ ---       │
# │ struct[2] │
# ╞═══════════╡
# │ {-1,2}    │
# │ {-2,4}    │
# └───────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.33.1
Index type:          UInt32
Platform:            macOS-15.7-arm64-arm-64bit-Mach-O
Python:              3.13.5 | packaged by conda-forge | (main, Jun 16 2025, 08:24:05) [Clang 18.1.8 ]
LTS CPU:             False
----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                1.40.21
cloudpickle          3.1.1
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.14.0
fsspec               2025.7.0
gevent               <not installed>
google.auth          2.40.3
great_tables         <not installed>
matplotlib           3.10.5
numpy                2.2.6
openpyxl             3.1.5
pandas               2.3.2
polars_cloud         <not installed>
pyarrow              20.0.0
pydantic             2.11.7
pyiceberg            <not installed>
sqlalchemy           2.0.43
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.5
```

</details>

### LINKED ISSUE #24687: Unexpected behavior in `struct.with_fields()` for multiple selected struct columns
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import datasets
import polars as pl

dict_data = [
    {"key": "key1", "value1": {"c": 3, "b": 3}, "value2": {"c": 3, "b": 3}},
    {"key": "key2", "value1": {"c": 7, "b": 4}, "value2": {"c": 3, "b": 3}},
    {"key": "key3", "value1": {"c": 3, "b": 4}, "value2": {"c": 3, "b": 9}},
]

data = pl.from_dicts(dict_data)
print(data)
data = data.with_columns(
    pl.selectors.struct().struct.with_fields(pl.field("b").replace(3, 5))
)
print(data)
hf_data = datasets.Dataset.from_polars(data)
print(hf_data[0])
```

### Log output

```shell
$ POLARS_VERBOSE=1 python test_polars.py 
shape: (3, 3)
┌──────┬───────────┬───────────┐
│ key  ┆ value1    ┆ value2    │
│ ---  ┆ ---       ┆ ---       │
│ str  ┆ struct[2] ┆ struct[2] │
╞══════╪═══════════╪═══════════╡
│ key1 ┆ {3,3}     ┆ {3,3}     │
│ key2 ┆ {7,4}     ┆ {3,3}     │
│ key3 ┆ {3,4}     ┆ {3,9}     │
└──────┴───────────┴───────────┘
CSE turned on because of struct expansion
shape: (3, 3)
┌──────┬─────────────┬───────────┐
│ key  ┆ value1      ┆ value2    │
│ ---  ┆ ---         ┆ ---       │
│ str  ┆ struct[3]   ┆ struct[2] │
╞══════╪═════════════╪═══════════╡
│ key1 ┆ {3,5,{3,3}} ┆ {3,3}     │
│ key2 ┆ {7,4,{3,3}} ┆ {3,3}     │
│ key3 ┆ {3,4,{3,9}} ┆ {3,9}     │
└──────┴─────────────┴───────────┘
{'key': 'key1', 'value1': {'c': 3, 'b': 5, 'value2': {'c': 3, 'b': 3}}, 'value2': {'c': 3, 'b': 3}}
```

### Issue description

I'm now trying to replace column `"b"` values in multiple struct columns (`value1` and `value2`),
but the output turns out that `value2` column `b` field is not changed,
and there appears to be a `value2` field in `value1` column, which is confusing.

### Expected behavior

```
shape: (3, 3)
┌──────┬───────────┬───────────┐
│ key  ┆ value1    ┆ value2    │
│ ---  ┆ ---       ┆ ---       │
│ str  ┆ struct[2] ┆ struct[2] │
╞══════╪═══════════╪═══════════╡
│ key1 ┆ {3,5}     ┆ {3,5}     │
│ key2 ┆ {7,4}     ┆ {3,5}     │
│ key3 ┆ {3,4}     ┆ {3,9}     │
└──────┴───────────┴───────────┘

{'key': 'key1', 'value1': {'c': 3, 'b': 5, 'value2': {'c': 3, 'b': 5}}
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.33.1
Index type:          UInt32
Platform:            Linux-6.1.147-172.259.amzn2023.x86_64-x86_64-with-glibc2.34
Python:              3.13.7 (main, Sep 18 2025, 19:47:49) [Clang 20.1.4 ]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2025.9.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.3.3
openpyxl             <not installed>
pandas               2.3.2
polars_cloud         <not installed>
pyarrow              21.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #24687
fixes #24568
fixes #18461

This PR introduces changes in the DSL, IR and Physical engines (both in-memory and streaming) for `struct.with_fields()`, such that its data model is coherent.

Pending performance regression analysis.
*Update: with the latest changes, performance is close (~3%) to the baseline, using ad hoc micro-benchmark with 1000 fields, and a mix of elementwise and non-elementwise operations.

### CODE REVIEW

File: crates/polars-expr/src/expressions/structeval.rs [hunk 1]
```diff
@@ -0,0 +1,385 @@
...
+
+    fn apply_group_aware<'a>(
+        &self,
+        mut acs: Vec<AggregationContext<'a>>,
+    ) -> PolarsResult<AggregationContext<'a>> {
+        let mut iters = acs
+            .iter_mut()
+            .map(|ac| ac.iter_groups(true))
+            .collect::<Vec<_>>();
+        let len = iters[0].size_hint().0;
```
Comment (nameexhaustion) [inline crates/polars-expr/src/expressions/structeval.rs]: Source `groups.len()` instead of using `size_hint().0`

File: crates/polars-expr/src/expressions/structeval.rs [hunk 2]
```diff
@@ -0,0 +1,385 @@
...
+                    has_not_agg = true;
+                    if let Some(p) = previous {
+                        not_agg_groups_may_diverge |= !p.groups.is_same(&ac.groups)
+                    }
+                    previous = Some(ac);
+                    if ac.groups.is_overlapping() {
+                        has_not_agg_with_overlapping_groups = true;
+                    }
+                },
+                _ => {},
```
Comment (nameexhaustion) [inline crates/polars-expr/src/expressions/structeval.rs]: Can you explicitly state the remaining match case

File: crates/polars-plan/src/utils.rs [hunk 3]
```diff
@@ -363,3 +363,37 @@ pub fn rename_columns(
...
+        type Node = AexprNode;
+        type Arena = Arena<AExpr>;
+
+        fn mutate(
+            &mut self,
+            node: Self::Node,
+            arena: &mut Self::Arena,
+        ) -> PolarsResult<Self::Node> {
+            if let AExpr::StructField(name) = arena.get(node.node()) {
+                let mut new_name = self.0.clone().to_string();
```
Comment (nameexhaustion) [inline crates/polars-plan/src/utils.rs]: `format_pl_smallstr!("{}{}")`

File: py-polars/Makefile [hunk 4]
```diff
@@ -57,6 +57,7 @@ lint: .venv  ## Run lint checks (only)
 .PHONY: fmt
 fmt: .venv  ## Run autoformatting (python and rust)
 	$(VENV_BIN)/ruff format
+# 	$(VENV_BIN)/typos ..
```
Comment (nameexhaustion) [inline py-polars/Makefile]:
```suggestion
```

File: crates/polars-expr/src/expressions/field.rs [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+            .with_fields_ac
+            .as_ref()
+            .as_ref()
+            .ok_or_else(|| polars_err!(invalid_field_use))?;
+
+        let col = ac.flat_naive().clone();
+        let ca = col.struct_()?;
+        let out = ca.field_by_name(self.name.as_str()).map(Column::from)?;
+
+        // Ok(AggregationContext::new(out, ac.groups.clone(), false))
```
Comment (nameexhaustion) [inline crates/polars-expr/src/expressions/field.rs]:
```suggestion
```

File: crates/polars-expr/src/state/execution_state.rs [hunk 6]
```diff
@@ -122,6 +123,10 @@ pub struct ExecutionState {
     // every join/union split gets an increment to distinguish between schema state
     pub branch_idx: usize,
     pub flags: RelaxedCell<u8>,
+    #[cfg(feature = "dtype-struct")]
+    pub with_fields: Arc<Option<StructChunked>>,
```
Comment (nameexhaustion) [inline crates/polars-expr/src/state/execution_state.rs]: Can this be `Option<Arc<`

**Comment by nameexhaustion** [comment]
The length check doesn't work on an edge case in streaming -

```python
print(
    pl.DataFrame({"a": [{"field": 1}]})
    .lazy()
    .select(pl.col("a").struct.with_fields(pl.field("field").head(0)))
    .collect(engine="in-memory")
)
# ShapeError: struct.with_fields expressions must have matching or unit length

print(
    pl.DataFrame({"a": [{"field": 1}]})
    .lazy()
    .select(pl.col("a").struct.with_fields(pl.field("field").head(0)))
    .collect(engine="streaming")
)
# shape: (0, 1)
# ┌───────────┐
# │ a         │
# │ ---       │
# │ struct[1] │
# ╞═══════════╡
# └───────────┘
```

**Comment by kdn36** [comment]
> The length check doesn't work on an edge case in streaming -
> 
> ```python
> print(
>     pl.DataFrame({"a": [{"field": 1}]})
>     .lazy()
>     .select(pl.col("a").struct.with_fields(pl.field("field").head(0)))
>     .collect(engine="in-memory")
> )
> # ShapeError: struct.with_fields expressions must have matching or unit length
> 
> print(
>     pl.DataFrame({"a": [{"field": 1}]})
>     .lazy()
>     .select(pl.col("a").struct.with_fields(pl.field("field").head(0)))
>     .collect(engine="streaming")
> )
> # shape: (0, 1)
> # ┌───────────┐
> # │ a         │
> # │ ---       │
> # │ struct[1] │
> # ╞═══════════╡
> # └───────────┘
> ```

Investigating. Fwiw, this was already broken before (1.36.1), not a regression.
