### PR TITLE
fix: Prevent `Boolean` arithmetic with integer literals producing `Unknown` type in streaming engine

### LINKED ISSUE #24609: Streaming engine: multiplying a `Boolean` column gives an `Unknown` type, leading to an error when `unique()` is used
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

(
    pl.LazyFrame({"a": [True]})
    .with_columns(x=pl.col("a") * 2)
    .unique("a")
    .collect(engine="streaming")
)
# SchemaError: failed to materialize unknown type
```
This is because `x` is of `Unknown` type (but I suppose its type should be known):
```python
    ...
    .collect_schema()
)
 # Schema([('a', Boolean), ('x', Unknown)])
```

### Log output

```shell
---------------------------------------------------------------------------
SchemaError                               Traceback (most recent call last)
Cell In[14], line 7
      1 import polars as pl
      3 (
      4     pl.LazyFrame({"a": [True]})
      5     .with_columns(x=pl.col("a") * 2)
      6     .unique("a", keep="first")
----> 7     .collect(engine="streaming")
      8 )

File c:\Users\etienne\Desktop\foo\.venv\Lib\site-packages\polars\_utils\deprecation.py:97, in deprecate_streaming_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
     93         kwargs["engine"] = "in-memory"
     95     del kwargs["streaming"]
---> 97 return function(*args, **kwargs)

File c:\Users\etienne\Desktop\foo\.venv\Lib\site-packages\polars\lazyframe\opt_flags.py:328, in forward_old_opt_flags.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325         optflags = cb(optflags, kwargs.pop(key))  # type: ignore[no-untyped-call,unused-ignore]
    327 kwargs["optimizations"] = optflags
--> 328 return function(*args, **kwargs)

File c:\Users\etienne\Desktop\foo\.venv\Lib\site-packages\polars\lazyframe\frame.py:2415, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, collapse_joins, no_optimization, engine, background, optimizations, **_kwargs)
   2413 # Only for testing purposes
   2414 callback = _kwargs.get("post_opt_callback", callback)
-> 2415 return wrap_df(ldf.collect(engine, callback))

SchemaError: failed to materialize unknown type
```

### Issue description

Multiplying  the boolean column gives an `Unknown` type that leads to an error when the pipeline includes `unique()`. Note that removing the `unique()` call doesn't error anymore.

This works fine with `collect(engine="in-memory")`.

This is present on 1.33.0 and 1.34.0-beta1.

### Expected behavior

Same as with the in-memory engine.

```python
shape: (1, 2)
┌──────┬─────┐
│ a    ┆ x   │
│ ---  ┆ --- │
│ bool ┆ i32 │
╞══════╪═════╡
│ true ┆ 2   │
└──────┴─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.34.0-beta.1
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.13.7 (main, Aug 18 2025, 19:16:27) [MSC v.1944 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.3.2
openpyxl             <not installed>
pandas               2.3.2
polars_cloud         <not installed>
pyarrow              21.0.0
pydantic             2.11.7
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by Kevin-Patyk**
Resolves https://github.com/pola-rs/polars/issues/24609.

Some iterations were required on this fix, but if this is still not the right solution, open to suggestions. Thanks!

## The Issue:

The input in the MRE is a situation where `pl.col("a") * 2` where `a` is `Boolean` and the literal `2` is typed as an `Unknown(UnknownKind::Int(v))`. This goes into `get_arithmetic_field` in `schema.rs` and none of the explicit match arms catch `Boolean, Unknown(Int))` so it falls through to `try_get_supertype(&left_field.dtype, &right_type`. 

Inside of `get_supertype_with_options`, the `(dt, Unknown(kind))` arm is matched where `dt` is `Boolean` and `kind` is `UnknownKind::Int(v)`. The inner match tries `UnknownKind::Int(v) if dt.is_primitive_numeric()` but `Boolean` fails this guard since `is_primitive_numeric` only returns `true` for floats and integers. Thus, it falls to the catch-all `_ => Some(Unknown(UnknownKind::Any))`. 

In `into_reduction` in `convert.rs`, it calls `get_dt` which calls `materialize_unknown(false)` on the `Unknown(Any)` type. `UnknownKind::Any.materialize()` returns `None` and since `allow_unknown = false`, `materialize_unkown` throws `SchemaError: failed to materialize unknown type`.

## The Fix:

In `supertype.rs`, added `UnknownKind::Int(_) if dt.is_bool() => Some(Int32)` so `Boolean * literal_int` resolves to `Int32` instead of `Unknown(Any)` matching the in-memory engine behavior. In `schema.rs`, added an explicit `(Boolean, _) | (_, Boolean) if op == Operator::FloorDivide` arm to reject floor division with booleans at type inference time, since the broader `get_supertype` fix would otherwise allow `Boolean // Int` which was previously and intentionally unsupported.

🤖 Claude Sonnet 4.6 for navigating the codebase and explaining relationships between files.

### CODE REVIEW

File: crates/polars-core/src/utils/supertype.rs [hunk 1]
```diff
@@ -486,6 +486,9 @@ pub fn get_supertype_with_options(
                             }
                         }
                     }
+                    UnknownKind::Int(_) if dt.is_bool() => {
```
Comment (nameexhaustion) [inline crates/polars-core/src/utils/supertype.rs]: Shouldn't we materialize the unknown kind to a concrete datatype and compare against that? What happens if the `UnknownKind::Int` contains a value larger than Int32?

File: crates/polars-plan/src/plans/aexpr/schema.rs [hunk 2]
```diff
@@ -722,6 +722,12 @@ fn get_arithmetic_field(
                     left_field.coerce(dtype);
                     return Ok(left_field);
                 },
+                (Boolean, _) | (_, Boolean) if op == Operator::FloorDivide => {
+                    polars_bail!(
+                        InvalidOperation:
+                        "floor_div operation not supported for dtype `bool`"
```
Comment (nameexhaustion) [inline crates/polars-plan/src/plans/aexpr/schema.rs]: Why are we making this error now? Floor divide with booleans works perfectly fine - 

```python
>>> pl.DataFrame({'a': [(1<<127)-1]}).select(pl.col('a') // True)
shape: (1, 1)
┌─────────────────────────────────┐
│ a                               │
│ ---                             │
│ i128                            │
╞═════════════════════════════════╡
│ 170141183460469231731687303715… │
└─────────────────────────────────┘
```

Comment (Kevin-Patyk) [reply crates/polars-plan/src/plans/aexpr/schema.rs]: I'll need your guidance on this one. This check was included since then this test, which was written 21 months ago, fails:

```
def test_bool_floordiv() -> None:
    df = pl.DataFrame({"x": [True]})

    with pytest.raises(
        InvalidOperationError,
        match="floor_div operation not supported for dtype `bool`",
    ):
        df.with_columns(pl.col("x").floordiv(2))
```

I wanted to preserve the behaviour of this test. Since, with my change in `try_get_supertype_with_options` would convert to an integer supertype and then this condition would not be met in `floor_div_series` in `polars-ops/src/series/ops/floor_divide.rs`:

```
    if !a.dtype().is_primitive_numeric() {
        polars_bail!(op = "floor_div", a.dtype());
    }
```

If this should generally work, I can remove the check in `get_arithmetic_field` along with the above test.

File: crates/polars-core/src/utils/supertype.rs (hunk 1 above)
Comment (Kevin-Patyk) [reply crates/polars-core/src/utils/supertype.rs]: So I changed this line to:

```
UnknownKind::Int(v) if dt.is_bool() => {
    let int_dtype = materialize_dyn_int(*v).dtype();
    get_supertype(dt, &int_dtype)
},
```

Was a mistake on my end since I used `materialize_smallest_dyn_int()` first and realized it was making it too small and did not match the in-memory engine of defaulting to `i32` so I used `Some(i32)` hard-coded. Just double checked and `materialize_dyn_int()` starts at `i32`.

**Comment by Kevin-Patyk** [comment]
Added an additional test to make sure both engines have the same output type with the fix.

File: crates/polars-plan/src/plans/aexpr/schema.rs (hunk 2 above)
Comment (nameexhaustion) [reply crates/polars-plan/src/plans/aexpr/schema.rs]: Right. That test was added by https://github.com/pola-rs/polars/pull/16578. Given that PR didn't close any reported/known issue, we can just remove this check.

**Comment by Kevin-Patyk** [comment]
@nameexhaustion So I removed the check from `schema.rs`, removed the outdated test, and rebased. Should be good to go 👍

**Review by nameexhaustion — APPROVED** [review]
