### PR TITLE
fix: Support Datetime broadcast in `list.concat`

### LINKED ISSUE #23102: Broadcast issue when trying to add a literal Datetime to a list
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import datetime

import polars as pl

# Create DataFrame with one column: a list of timestamps
df = pl.DataFrame(
    {
        "timestamps": [
            [datetime(2024, 1, 1).replace(tzinfo=None)],
            [datetime(2024, 1, 2).replace(tzinfo=None)],
        ]
    },
    schema={"timestamps": pl.List(pl.Datetime(time_unit="ms", time_zone=None))},
)

# Create literal timestamp to append
new_timestamp = pl.lit(
    [datetime(2024, 2, 1).replace(tzinfo=None)], dtype=pl.List(pl.Datetime(time_unit="ms", time_zone=None))
)

# This fails with: SchemaMismatch("type Int64 is incompatible with expected type Datetime(Milliseconds, None)")
result = df.with_columns(pl.col("timestamps").list.concat(new_timestamp))

```

### Log output

```shell
thread '<unnamed>' panicked at /Users/runner/work/polars/polars/crates/polars-ops/src/chunked_array/list/namespace.rs:759:42:
called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("type Int64 is incompatible with expected type Datetime(Milliseconds, None)"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/carlmajor/repos/polars-testing/minimal_list_concat_bug.py", line 29, in <module>
    result = df.with_columns(pl.col("timestamps").list.concat(new_timestamp))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlmajor/.pyenv/versions/3.11.4/envs/polars-testing/lib/python3.11/site-packages/polars/dataframe/frame.py", line 9938, in with_columns
    .collect(optimizations=QueryOptFlags._eager())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlmajor/.pyenv/versions/3.11.4/envs/polars-testing/lib/python3.11/site-packages/polars/_utils/deprecation.py", line 97, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlmajor/.pyenv/versions/3.11.4/envs/polars-testing/lib/python3.11/site-packages/polars/lazyframe/opt_flags.py", line 331, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlmajor/.pyenv/versions/3.11.4/envs/polars-testing/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2300, in collect
    return wrap_df(ldf.collect(engine, callback))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("type Int64 is incompatible with expected type Datetime(Milliseconds, None)"))
```

### Issue description

I have a Dataframe, where each row contains a list of Datetimes. I want to add a literal Datetime to each of those rows, representing the time I'm running this process. However, when I attempt to concatenate my literal value onto each of those lists, it fails, complaining that it encountered an Int64 where it expected a Datetime.

This happens with both DataFrames and LazyFrames, I tried with both.

This appears to be an issue with the broadcasting behaviour. If my Dataframe only contains a single row, then I'm able to perform this Concatenation just fine. Can be tested by changing the `df` in the example, or simply commenting out one of the rows, to get:
```python
# Create DataFrame with only one row
df = pl.DataFrame(
    {
        "timestamps": [
            [datetime(2024, 1, 1).replace(tzinfo=None)],
        ]
    },
    schema={"timestamps": pl.List(pl.Datetime(time_unit="ms", time_zone=None))},
)
```

I suspect something in the Broadcast is reverting my literal Datetime to an Int64, then attempting to Concatenate an Int64 to the list of Datetimes, which fails.

### Expected behavior

Should output a 2-row Dataframe, with each row having my literal value added to it:
```
shape: (2, 1)
┌─────────────────────────────────┐
│ timestamps                      │
│ ---                             │
│ list[datetime[ms]]              │
╞═════════════════════════════════╡
│ [2024-01-01 00:00:00, 2024-02-… │
│ [2024-01-02 00:00:00, 2024-02-… │
└─────────────────────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.30.0
Index type:          UInt32
Platform:            macOS-15.5-x86_64-i386-64bit
Python:              3.11.4 (main, Jul  6 2023, 15:56:09) [Clang 14.0.3 (clang-1403.0.22.14.1)]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                1.34.90
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.25.5
fastexcel            <not installed>
fsspec               2024.6.1
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.10.1
numpy                1.26.4
openpyxl             <not installed>
pandas               <not installed>
polars_cloud         <not installed>
pyarrow              20.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #23102

Pending review, see issue for solution strategies.

Works for Datetime and Duration, but not for Decimal as cast behaves differently. Should we use `from_physical_unchecked` instead?

*edit: latest commit uses `from_physical_unchecked` and works for Decimal as well.

### CODE REVIEW

File: crates/polars-ops/src/chunked_array/list/namespace.rs [hunk 1]
```diff
@@ -726,13 +726,21 @@ pub trait ListNameSpaceImpl: AsList {
...
-            let to_append = other
+            let mut to_append = other
                 .iter()
                 .flat_map(|s| {
                     let lst = s.list().unwrap();
                     lst.get_as_series(0)
                 })
                 .collect::<Vec<_>>();
+
+            // we may need to recast back from physical dtype
```
Comment (nameexhaustion) [inline crates/polars-ops/src/chunked_array/list/namespace.rs]: nit: move this into the above loop?

Comment (kdn36) [reply crates/polars-ops/src/chunked_array/list/namespace.rs]: ok - as a conditional extra `map` or unconditional inside the `flat_map`? (unconditional sounds right and consistent, however it is unsafe)

Comment (nameexhaustion) [reply crates/polars-ops/src/chunked_array/list/namespace.rs]: > ok - as a conditional extra `map` or unconditional inside the `flat_map`? (unconditional sounds right and consistent, however it is unsafe)

I think this is up to your personal preference.

One other thing, can you as a drive-by change that to use `filter_map` instead of `flat_map`.

Comment (kdn36) [reply crates/polars-ops/src/chunked_array/list/namespace.rs]: ack & done - ended up keeping the to/from_physical calls close together
