### PR TITLE
fix: Clone shared GroupBy node before mutation in physical plan creation

### LINKED ISSUE #26296: `pl.collect_all` Query Optimization Issue Introduced in Polars 1.37.0
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
"""
Polars bug: collect_all with group_by + lazy sink fails with ColumnNotFoundError

Introduced in: 1.37.0 (works in 1.36.1)
Tested on: 1.37.0, 1.37.1
"""
import polars as pl

df = pl.DataFrame({"g": ["A"], "v": [1]})
result = df.lazy().group_by("g").agg(pl.col("v").sum())
sink = result.sink_parquet("/tmp/bug.parquet", lazy=True)
other = result.select(pl.lit(1))
pl.collect_all([other, sink])  # ColumnNotFoundError: v
```

### Workarounds
Any of these three options seem to resolve the issue (if that helps you debug)
```python
  pl.collect_all([other, sink], comm_subplan_elim=False)

  pl.collect_all([other, sink], engine="streaming")

  pl.collect_all([sink, other])
```

### Log output

```shell
2176, in collect_all
    out = plr.collect_all(lfs, engine, optimizations._pyoptflags)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ColumnNotFoundError: v
```

### Issue description

Seems like some query optimization change introduced this bug. You can see that in the MRE that `other` shouldn't depend on `v` at all, but it fails.

### Expected behavior

Should just work.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.37.1
Index type:          UInt32
Platform:            Linux-5.10.247-246.989.x86_64-x86_64-with-glibc2.26
Python:              3.12.9 (main, Feb  5 2025, 19:10:45) [Clang 19.1.6 ]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                1.42.19
cloudpickle          3.1.2
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2026.1.0
gevent               <not installed>
google.auth          <not installed>
great_tables         0.20.0
matplotlib           3.10.8
numpy                2.2.6
openpyxl             <not installed>
pandas               2.3.3
polars_cloud         <not installed>
pyarrow              20.0.0
pydantic             2.12.5
pyiceberg            0.10.0
sqlalchemy           2.0.45
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by azimafroozeh**
Fixes #26296

### CODE REVIEW

File: crates/polars-mem-engine/src/planner/lp.rs [hunk 1]
```diff
@@ -544,10 +544,17 @@ fn create_physical_plan_impl(
                 let builder = get_streaming_executor_builder();
 
                 let input = recurse!(input, state)?;
+
+                let gb_root = if state.has_cache_parent {
```
Comment (nameexhaustion) [inline crates/polars-mem-engine/src/planner/lp.rs:548]: Could we perform this clone inside of `GroupByStreamingExec::new`, next to where the mutation takes place? That would make it clearer why we're performing the clone.

Comment (azimafroozeh) [reply crates/polars-mem-engine/src/planner/lp.rs:548]: Moving the clone inside would require always cloning. Currently, it only clones when the node is actually shared, avoiding redundant clones in the common case.
we can push has_cache_parent to GroupByStreamingExec::new though.
