### PR TITLE
fix(rust, python): fix incorrect state in projection pushdown with joins

### LINKED ISSUE #9955: Incorrect optimization leads to missing columns
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
In [31]: import polars as pl

In [32]: batting = pl.scan_parquet("batting.parquet")

In [33]: awards_players = pl.scan_parquet("awards_players.parquet")

In [34]: left = batting.filter(pl.col("yearID") == 2015)

In [35]: right = awards_players.filter(pl.col("lgID") == "NL").select(
    ...:     [
    ...:         col for col in awards_players.columns if col not in ("yearID", "lgID")
    ...:     ]  # equivalent to .drop
    ...: )

In [36]: res = left.join(
    ...:     right,
    ...:     left_on=[pl.col("playerID")],
    ...:     right_on=[pl.col("playerID")],
    ...:     how="inner",
    ...: )

In [37]: res.select(left.columns + [c for c in right.columns if c != "playerID"]).collect()
Traceback (most recent call last):
  ...
ColumnNotFoundError: lgID
```

without optimization the code executes:

```
In [38]: res.select(left.columns + [c for c in right.columns if c != "playerID"]).collect(no_optimization=True)
Out[38]:
shape: (278, 25)
┌───────────┬────────┬───────┬────────┬───┬──────┬────────────────────┬─────┬───────┐
│ playerID  ┆ yearID ┆ stint ┆ teamID ┆ … ┆ GIDP ┆ awardID            ┆ tie ┆ notes │
│ ---       ┆ ---    ┆ ---   ┆ ---    ┆   ┆ ---  ┆ ---                ┆ --- ┆ ---   │
│ str       ┆ i64    ┆ i64   ┆ str    ┆   ┆ i64  ┆ str                ┆ str ┆ str   │
╞═══════════╪════════╪═══════╪════════╪═══╪══════╪════════════════════╪═════╪═══════╡
│ pujolal01 ┆ 2015   ┆ 1     ┆ LAA    ┆ … ┆ 15   ┆ Rookie of the Year ┆     ┆       │
│ pujolal01 ┆ 2015   ┆ 1     ┆ LAA    ┆ … ┆ 15   ┆ Silver Slugger     ┆     ┆ 3B    │
│ pujolal01 ┆ 2015   ┆ 1     ┆ LAA    ┆ … ┆ 15   ┆ Hank Aaron Award   ┆     ┆       │
│ pujolal01 ┆ 2015   ┆ 1     ┆ LAA    ┆ … ┆ 15   ┆ Silver Slugger     ┆     ┆ OF    │
│ …         ┆ …      ┆ …     ┆ …      ┆ … ┆ …    ┆ …                  ┆ …   ┆ …     │
│ gonzaca01 ┆ 2015   ┆ 1     ┆ COL    ┆ … ┆ 11   ┆ Silver Slugger     ┆     ┆ OF    │
│ mccutan01 ┆ 2015   ┆ 1     ┆ PIT    ┆ … ┆ 9    ┆ Silver Slugger     ┆     ┆ OF    │
│ bumgama01 ┆ 2015   ┆ 1     ┆ SFN    ┆ … ┆ 1    ┆ Silver Slugger     ┆     ┆ P     │
│ crawfbr01 ┆ 2015   ┆ 1     ┆ SFN    ┆ … ┆ 18   ┆ Silver Slugger     ┆     ┆ SS    │
└───────────┴────────┴───────┴────────┴───┴──────┴────────────────────┴─────┴───────┘
```

Data can be found here: https://github.com/ibis-project/testing-data/tree/master/parquet.

### Issue description

May be equivalent to https://github.com/pola-rs/polars/issues/8847, not sure.

Polars is incorrectly discarding columns that are present.

### Expected behavior

The optimized query is equal to the unoptimized query.

### Installed versions

<details>

```
In [39]: pl.show_versions()
--------Version info---------
Polars:              0.18.7
Index type:          UInt32
Platform:            Linux-6.1.38-x86_64-with-glibc2.37
Python:              3.10.12 (main, Jun  6 2023, 22:43:10) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           0.10.0
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.1
pandas:              2.0.3
pyarrow:             10.0.1
pydantic:            <not installed>
sqlalchemy:          1.4.49
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #9955

### CODE REVIEW

File: polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs [hunk 1]
```diff
@@ -226,16 +226,18 @@ impl ProjectionPushDown {
         let root_projections = aexpr_to_leaf_nodes(proj, expr_arena);
 
         for (name, root_projection) in names.into_iter().zip(root_projections) {
-            let was_not_in_left = names_left.insert(name.clone());
-            let was_not_in_right = names_right.insert(name.clone());
```
Comment (ritchie46) [inline polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs:230]: This inserted the name even if the column was not projected. 

That way a `filter` deeper down in the query with not add its column to the projection accumulations if the name was the hash table (incorrectly)

**Review by alexander-beedie — APPROVED** [review]
