### PR TITLE
fix(rust, python): add file path to io error in scan_csv

### LINKED ISSUE #10043: pl.scan_csv should report name of non-existent file
### Problem description

`pl.read_csv` reports the filename if the file doesn't exist, but `pl.scan_csv` doesn't do that

```ipython
In [1]: pl.read_csv("does.not.exist")
...
FileNotFoundError: No such file or directory: does.not.exist

In [2]: pl.scan_csv("does.not.exist")
OSError: No such file or directory (os error 2)
```

This makes it harder to debug issues in my code

EDIT: sorry for empty issue, I pressed enter key accidentally before writing the description

### PR DESCRIPTION
**Pull request by rikkaka**
fix #10043 
Add the file path to the error reporting in scan_csv when fail to open the file.

### CODE REVIEW

File: polars/polars-lazy/polars-plan/src/logical_plan/builder.rs [hunk 1]
```diff
@@ -253,7 +253,15 @@ impl LogicalPlanBuilder {
         try_parse_dates: bool,
     ) -> PolarsResult<Self> {
         let path = path.into();
-        let mut file = std::fs::File::open(&path)?;
+        let mut file = std::fs::File::open(&path).map_err(|e| {
```
Comment (ritchie46) [inline polars/polars-lazy/polars-plan/src/logical_plan/builder.rs:256]: Can you make this as an `open_file() -> PolarsResult<File>` function in `polars-utils` and use that function everywhere we open a file and return an error if it not exists?

**Comment by ritchie46** [comment]
Nice! Thank you @rikkaka
