### PR TITLE
fix(python): Fix list to numpy conversion

### LINKED ISSUE #18986: to_numpy returns the same list for all rows
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl

df = pl.DataFrame({"a": [[4, 5, 6], [7, 8, 9, 10]]})
assert (df[1].to_numpy()[0][0] == np.array([4, 5, 6, 7])).all()
```

### Log output

_No response_

### Issue description

When storing lists in the dataframe, indexing via square brackets combined with to_numpy returns an element of correct length, but with the first values of all lists concatenated

### Expected behavior

The given example should return [7, 8, 9. 10] instead of weirdly concatenating [4, 5, 6] to [7, 8, 9, 10] and taking the length of the element.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.8.2
Index type:          UInt32
Platform:            Linux-5.15.0-94-generic-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.2.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.8.3
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             <not installed>
pandas               2.2.1
pyarrow              15.0.0
pydantic             2.9.1
pyiceberg            <not installed>
sqlalchemy           2.0.34
torch                2.2.1+cu121
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #18986

### CODE REVIEW

File: crates/polars-python/src/interop/numpy/to_numpy_series.rs [hunk 1]
```diff
@@ -340,26 +340,14 @@ where
...
     PyArray1::<T>::from_iter_bound(py, values).into_py(py)
 }
-/// Convert lists by flattening first, converting the flat Series, and then splitting by offsets.
 fn list_series_to_numpy(py: Python, s: &Series, writable: bool) -> PyObject {
     let ca = s.list().unwrap();
-    let s_inner = ca.get_inner();
-
-    let np_array_flat = series_to_numpy(py, &s_inner, writable, true).unwrap();
 
-    // Split the NumPy array into subarrays by offset.
```
Comment (ritchie46) [inline crates/polars-python/src/interop/numpy/to_numpy_series.rs:350]: This is wrong for 2 reasons. The slicing was incorrect, but it also doesn't include null values and can show masked out values.
