### PR TITLE
fix: Allow excess bytes on IPC bitmap compressed length

### LINKED ISSUE #26126: Fail to read arrow-go generated compressed ipc file with column has null value
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

generate a compressed arrow file with [arrow-go](https://github.com/apache/arrow-go) v18.5

```go
package main

import (
	"fmt"
	"os"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/apache/arrow-go/v18/arrow/ipc"
	"github.com/apache/arrow-go/v18/arrow/memory"
)

func main() {
	// 1. Initialize the allocator for memory management
	pool := memory.NewGoAllocator()

	// 2. Define the Schema
	schema := arrow.NewSchema(
		[]arrow.Field{
			{Name: "id", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
			{Name: "user", Type: arrow.BinaryTypes.String, Nullable: true},
		},
		nil,
	)

	// 3. Build the Data Arrays
	b := array.NewRecordBuilder(pool, schema)
	defer b.Release()

	// Populate Column 1 (ID)

	i64b := b.Field(0).(*array.Int64Builder)
	i64b.Append(1)
	i64b.Append(2)
	i64b.AppendNull()
	i64b.Append(3)
	// Populate Column 2 (User)
	b.Field(1).(*array.StringBuilder).AppendValues([]string{"Alice", "Bob", "Charlie", "David"}, nil)


	// Create a Record Batch
	rec := b.NewRecordBatch()
	defer rec.Release()

	// 4. Create the File
	f, err := os.Create("data.arrow")
	if err != nil {
		fmt.Printf("failed to create file: %v\n", err)
		return
	}
	defer f.Close()

	// 5. Initialize the IPC Writer with Zstd Compression
	// We use ipc.WithZstd() to enable the compression codec.
	writer, err := ipc.NewFileWriter(f,
		ipc.WithSchema(schema),
		ipc.WithZstd(), // This triggers the Zstd compressor
		// ipc.WithMinSpaceSavings(0.2),
	)
	if err != nil {
		fmt.Printf("failed to create writer: %v\n", err)
		return
	}
	defer writer.Close()

	// 6. Write the record to the file
	err = writer.Write(rec)
	if err != nil {
		fmt.Printf("failed to write record: %v\n", err)
		return
	}

	fmt.Println("Arrow file 'data.arrow' written successfully with Zstd compression.")
}

```

polars can not read the column with null value after v1.34.0

```python
pl.read_ipc('data.arrow')
```
will raise exception like `polars.exceptions.ComputeError: Malformed IPC file: got unexpected decompressed output length 4, expected 1`

I can read the ipc with pyarrow or only select column without null value

```python
pl.read_ipc('data.arrow', use_pyarrow=True)
```

```python
pl.scan_ipc('data.arrow').select('user').collect() # works fine
pl.scan_ipc('data.arrow').select('id').collect() # will raise exception
```

### Log output

```shell
>>> import polars as pl;pl.scan_ipc('data.arrow').select('user', 'id').collect()
_init_credential_provider_builder(): credential_provider_init = None
sourcing ipc scan file schema from: 'data.arrow'
polars-stream: updating graph state
async thread count: 4
polars-stream: running in-memory-sink in subgraph
polars-stream: running multi-scan[ipc] in subgraph
[IpcReaderBuilder]: prefetch_limit: 96
[MultiScanTaskInit]: 1 sources, reader name: ipc, ReaderCapabilities(ROW_INDEX | PRE_SLICE), n_readers_pre_init: 1, max_concurrent_scans: 1
[MultiScanTaskInit]: predicate: None, skip files mask: None, predicate to reader: None
[MultiScanTaskInit]: scan_source_idx: 0, extra_ops: ExtraOperations { row_index: None, row_index_col_idx: 18446744073709551615, pre_slice: None, include_file_paths: None, file_path_col_idx: 18446744073709551615, predicate: None }
[MultiScanTaskInit]: Readers init: 1 / (1 total) (range: 0..1, filtered out: 0)
[MultiScan]: Initialize source 0
[IpcFileReader]: reading dictionaries (0)
[ReaderStarter]: scan_source_idx: 0
[ReaderStarter]: scan_source_idx: 0: pre_slice_to_reader: None, external_filter_mask: None, file_iceberg_schema: None
[IpcFileReader]: project: 2 / 2, pre_slice: None
[ReaderStarter]: max_concurrent_scans is 1, waiting..
[AttachReaderToBridge]: received reader (n_readers_received: 1)
memory prefetch function: madvise_willneed
[IpcFileReader]: num_pipelines: 48, record_batch_prefetch_size: 1, ideal_morsel_size: 100000
[IpcFileReader]: record batch count: 1
start_reader_impl: scan_source_idx: 0, ApplyExtraOps::Noop, first_morsel_position: RowCounter { physical_rows: 0, deleted_rows: 0 }
[ReaderStarter]: Stopping (no more readers)
[MultiScanState]: Readers disconnected
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import polars as pl;pl.scan_ipc('data.arrow').collect()
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/data/notebook/yangg/mercatus/.venv/lib/python3.13/site-packages/polars/_utils/deprecation.py", line 97, in wrapper
    return function(*args, **kwargs)
  File "/data/notebook/yangg/mercatus/.venv/lib/python3.13/site-packages/polars/lazyframe/opt_flags.py", line 324, in wrapper
    return function(*args, **kwargs)
  File "/data/notebook/yangg/mercatus/.venv/lib/python3.13/site-packages/polars/lazyframe/frame.py", line 2429, in collect
    return wrap_df(ldf.collect(engine, callback))
                   ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: Malformed IPC file: got unexpected decompressed output length 4, expected 1
```

### Issue description

read uncompressed ipc file works fine.

### Expected behavior

polars should read the ipc file  properly

### Installed versions

<details>

--------Version info---------
Polars:              1.37.1
Index type:          UInt32
Platform:            Linux-5.15.0-164-generic-x86_64-with-glibc2.35
Python:              3.13.5 (main, Jul 11 2025, 22:43:46) [Clang 20.1.4 ]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.4.1
openpyxl             <not installed>
pandas               2.3.3
polars_cloud         <not installed>
pyarrow              22.0.0
pydantic             2.12.5
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.9ace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #26126

ping @nameexhaustion

### CODE REVIEW

File: crates/polars-arrow/src/io/ipc/read/read_basic.rs [hunk 1]
```diff
@@ -313,7 +313,11 @@ fn read_compressed_bitmap<R: Read + Seek>(
         })?
     };
 
-    polars_ensure!(length.div_ceil(8) == decompressed_bytes, ComputeError: "Malformed IPC file: got unexpected decompressed output length {decompressed_bytes}, expected {}", length.div_ceil(8));
+    // We allow for untruncated buffers up to 8-byte alignment (this includes 1-byte, 4-byte, 8-byte alignment)
+    // See https://github.com/pola-rs/polars/issues/26126
+    // and https://github.com/apache/arrow/issues/48883
+    polars_ensure!(length.div_ceil(8).div_ceil(8) == decompressed_bytes.div_ceil(8),
```
Comment (nameexhaustion) [inline crates/polars-arrow/src/io/ipc/read/read_basic.rs]: I think it's better to just do `decompressed_bytes >= length.div_ceil(8)` to make it more robust (and in the comment note that some writers would write excess bytes).

**Comment by nameexhaustion** [comment]
Could we avoid checking in the binary file? It's alright to remove the test case as well if it can't work without the binary file.
