### PR TITLE
fix(rust, python): Set correct dtype for `.extract_groups()`

### LINKED ISSUE #10305: str.extract_groups wrong lazy dtype
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.LazyFrame(
    data={
        "url": [
            "http://vote.com/ballon_dor?candidate=messi&ref=python",
            "http://vote.com/ballon_dor?candidate=weghorst&ref=polars",
            "http://vote.com/ballon_dor?error=404&ref=rust",
        ]
    }
)
pattern = r"candidate=(?<candidate>\w+)&ref=(?<ref>\w+)"
df = df.select(captures=pl.col("url").str.extract_groups(pattern)).unnest("captures")

assert df.schema == {"candidate": pl.Utf8, "ref": pl.Utf8}
```

### Issue description

Super cool that `str.extract_groups` finally made it in PR #10179!

However it's broken on lazy frames due to a incorrect return dtype.

In the example, the `unnest` crashes because `extract_groups` is returning the default `{'captures': pl.Utf8}` dtype.

```
Traceback (most recent call last):
  File "bug.py", line 18, in <module>
    assert df.schema == {"candidate": pl.Utf8, "ref": pl.Utf8}
           ^^^^^^^^^
  File "/usr/local/python/3.11.3/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 628, in schema
    return self._ldf.schema()
           ^^^^^^^^^^^^^^^^^^
exceptions.SchemaError: expected struct dtype, got: `str`
```

### Expected behavior

`df.schema` should be `{"candidate": pl.Utf8, "ref": pl.Utf8}`

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.12
Index type:          UInt32
Platform:            Linux-5.15.0-1042-azure-x86_64-with-glibc2.31
Python:              3.11.3 (main, Apr 14 2023, 19:54:24) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.2
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by cmdlineluser**
Fixes #10305

### CODE REVIEW

**Review by stinodego — APPROVED** [review]
Yep looks good to me! Thanks for the fix.

File: crates/polars-plan/src/dsl/function_expr/strings.rs [hunk 1]
```diff
@@ -95,7 +95,27 @@ impl StringFunction {
             Extract { .. } => mapper.with_same_dtype(),
             ExtractAll => mapper.with_dtype(DataType::List(Box::new(DataType::Utf8))),
             #[cfg(feature = "extract_groups")]
-            ExtractGroups { .. } => mapper.with_same_dtype(),
+            ExtractGroups { pat } => {
```
Comment (ritchie46) [inline crates/polars-plan/src/dsl/function_expr/strings.rs:98]: Can we do this in the expression function and then put the DataType in the enum variant?

We can use the datatype in the expression implementation to get the names.

File: py-polars/tests/unit/namespaces/test_string.py [hunk 2]
```diff
@@ -793,3 +793,21 @@ def test_string_replace_with_nulls_10124() -> None:
         "n_1": ["O", "O", "O", None, "O", "O", "O", "O"],
         "n_3": ["O", "O", "O", None, "O", "O", "O", "O"],
     }
+
+
+def test_string_extract_groups_lazy_schema_10305() -> None:
```
Comment (ritchie46) [inline py-polars/tests/unit/namespaces/test_string.py:798]: We can make the test more lean by just testing the schema after the expression is selected.

Comment (cmdlineluser) [reply py-polars/tests/unit/namespaces/test_string.py:798]: Ah, okay. I've changed it to:
```python
    dtype = pl.Struct([pl.Field('candidate', pl.Utf8), pl.Field('ref', pl.Utf8)])
    assert (
        df.select(captures=pl.col("url").str.extract_groups(pattern)).schema
        == {'captures': dtype}
    )
```

File: crates/polars-plan/src/dsl/function_expr/strings.rs (hunk 1 above)
Comment (cmdlineluser) [reply crates/polars-plan/src/dsl/function_expr/strings.rs:98]: Is there an example I can refer to in order to try and understand what that means?

It's above my current rust knowledge level.

File: crates/polars-plan/src/dsl/string.rs [hunk 3]
```diff
@@ -63,10 +63,35 @@ impl StringNameSpace {
 
     #[cfg(feature = "extract_groups")]
     // Extract all captures groups from a regex pattern as a struct
-    pub fn extract_groups(self, pat: &str) -> Expr {
-        let pat = pat.to_string();
-        self.0
-            .map_private(StringFunction::ExtractGroups { pat }.into())
+    pub fn extract_groups(self, pat: &str) -> PolarsResult<Expr> {
```
Comment (ritchie46) [inline crates/polars-plan/src/dsl/string.rs:66]: determining the data type here, means we only do that computation of the data type once. 

The regex is compiled twice, because we cannot send the regex in the logical plan.

In the previous commit we would compile the regex every time we ask the schema, which we do a lot.

File: crates/polars-plan/src/dsl/function_expr/strings.rs [hunk 4]
```diff
@@ -302,11 +303,9 @@ pub(super) fn extract(s: &Series, pat: &str, group_index: usize) -> PolarsResult
 
 #[cfg(feature = "extract_groups")]
 /// Extract all capture groups from a regex pattern as a struct
-pub(super) fn extract_groups(s: &Series, pat: &str) -> PolarsResult<Series> {
-    let pat = pat.to_string();
```
Comment (ritchie46) [inline crates/polars-plan/src/dsl/function_expr/strings.rs:306]: No need to allocate a string here?

File: crates/polars-ops/src/chunked_array/strings/extract.rs [hunk 5]
```diff
@@ -51,22 +55,15 @@ pub(super) fn extract_groups(ca: &Utf8Chunked, pat: &str) -> PolarsResult<Series
             .map(|ca| ca.into_series());
     }
 
-    let names = reg
```
Comment (ritchie46) [inline crates/polars-ops/src/chunked_array/strings/extract.rs:54]: We now can use the names available in the `DataType::Struct`

**Review by ritchie46 — APPROVED** [review]

File: crates/polars-plan/src/dsl/string.rs (hunk 3 above)
Comment (cmdlineluser) [reply crates/polars-plan/src/dsl/string.rs:66]: Thanks @ritchie46 - makes sense once you see it.

I think one of the issues I was having was not understanding the order of operations fully.

`dsl/string.rs` -> `function_expr/strings.rs`

So I wasn't able to figure out at what point one could manipulate the dtype (other than what I initially tried)

File: crates/polars-plan/src/dsl/function_expr/strings.rs (hunk 4 above)
Comment (cmdlineluser) [reply crates/polars-plan/src/dsl/function_expr/strings.rs:306]: Yep, thanks. Need to become more aware regarding allocations.
