### PR TITLE
fix: Merge categorical rev-map in `unpivot`

### LINKED ISSUE #19285: Panic after unpivot of DataFrame with pl.string_cache_enabled()
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import polars.selectors as cs

def reproducer():
    df = pl.DataFrame({
        "index": [0, 1],
        "series1": pl.Series(["a", "b"], dtype=pl.Categorical),
        "series2": pl.Series(["b", "c"], dtype=pl.Categorical),
    })
    df = df.unpivot(cs.categorical(), index="index")
    print(df)

pl.enable_string_cache()
reproducer()

```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/chunked_array/logical/categorical/revmap.rs:103:42:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/tmp/ipykernel_311/2485256769.py in ?()
     16     df = df.unpivot(cs.categorical(), index="index")
     17     print(df)
     18 
     19 pl.enable_string_cache()
---> 20 reproducer()

/tmp/ipykernel_311/2485256769.py in ?()
     13         "series2": pl.Series(["b", "c"], dtype=pl.Categorical),
     14 
     15     })
     16     df = df.unpivot(cs.categorical(), index="index")
---> 17     print(df)

/opt/conda/lib/python3.11/site-packages/polars/dataframe/frame.py in ?(self)
   1174     def __str__(self) -> str:
-> 1175         return self._df.as_str()

PanicException: called `Option::unwrap()` on a `None` value
```

### Issue description

I am seeing a panic after an unpivot of a dataframe with `pl.Categorical` dtypes with the polars string cache enabled. This problem does not occur if the string cache is not enabled or if using string dtypes during the unpivot operation.

While chasing this down, I noticed that after the unpivot, I could sometimes access portions of the resulting DataFrame using things like `head(5)`, but that operations that would print, store, or access the full DataFrame would panic. It suggests to me that after the unpivot, a particular category perhaps did not have a mapping in the string cache that existed before the unpivot.

### Expected behavior

I expect no panic to happen and the DataFrame to look equivalent to the output of `reproduce()` without `pl.enable_string_cache()`

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Linux-5.14.0-284.69.1.el9_2.x86_64-x86_64-with-glibc2.34
Python:              3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.3.1
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.8.4
nest_asyncio         1.6.0
numpy                1.26.4
openpyxl             <not installed>
pandas               2.2.2
pyarrow              13.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           2.0.30
torch                2.4.1+cu121
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #19285

### CODE REVIEW

File: crates/polars-core/src/datatypes/dtype.rs [hunk 1]
```diff
@@ -115,9 +115,10 @@ impl PartialEq for DataType {
         use DataType::*;
         {
             match (self, other) {
-                // Don't include rev maps in comparisons
                 #[cfg(feature = "dtype-categorical")]
-                (Categorical(_, _), Categorical(_, _)) => true,
+                // Don't include rev maps in comparisons
+                // TODO: include ordering in comparison
```
Comment (ritchie46) [inline crates/polars-core/src/datatypes/dtype.rs:120]: Requires Dyn str
