### PR TITLE
fix: `is_in` operator for categoricals

### LINKED ISSUE #13201: is_in operator on Categoricals is overly restrictive
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Inspired by #13165, the `is_in` operator is overly restrictive on Categorical types

The following codes errors

```python
import polars as pl
s = pl.Series(["a","b"],dtype=pl.Categorical)
s.is_in(["b"])
```

also the following code breaks as well

```python
import polars as pl
s = pl.Series(["a","b"],dtype=pl.Categorical)
s2 = pl.Series(["b"],dtype=pl.Categorical)
s.is_in(s2)
```

### Log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chiel/.local/lib/python3.10/site-packages/polars/series/utils.py", line 100, in wrapper
    return s.to_frame().select_seq(f(*args, **kwargs)).to_series()
  File "/home/chiel/.local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 8034, in select_seq
    return self.lazy().select_seq(*exprs, **named_exprs).collect(_eager=True)
  File "/home/chiel/.local/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
polars.exceptions.StringCacheMismatchError: cannot compare categoricals coming from different sources, consider setting a global StringCache.

Help: if you're using Python, this may look something like:

    with pl.StringCache():
        # Initialize Categoricals.
        df1 = pl.DataFrame({'a': ['1', '2']}, schema={'a': pl.Categorical})
        df2 = pl.DataFrame({'a': ['1', '3']}, schema={'a': pl.Categorical})
    # Your operations go here.
    pl.concat([df1, df2])

Alternatively, if the performance cost is acceptable, you could just set:

    import polars as pl
    pl.enable_string_cache()

on startup.

polars.exceptions.StringCacheMismatchError: cannot compare categoricals coming from different sources, consider setting a global StringCache.

Help: if you're using Python, this may look something like:

    with pl.StringCache():
        # Initialize Categoricals.
        df1 = pl.DataFrame({'a': ['1', '2']}, schema={'a': pl.Categorical})
        df2 = pl.DataFrame({'a': ['1', '3']}, schema={'a': pl.Categorical})
    # Your operations go here.
    pl.concat([df1, df2])

Alternatively, if the performance cost is acceptable, you could just set:

    import polars as pl
    pl.enable_string_cache()

on startup.
```

### Issue description

-

### Expected behavior

Should be able to handle strings and categorical types with a different mapping

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.2
Index type:           UInt32
Platform:             Linux-6.2.0-39-generic-x86_64-with-glibc2.35
Python:               3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager:  0.7.0
cloudpickle:          2.2.1
connectorx:           0.3.2
deltalake:            0.11.0
fsspec:               2023.9.2
gevent:               <not installed>
matplotlib:           3.7.2
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               2.0.3
pyarrow:              12.0.0
pydantic:             2.4.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.21
xlsx2csv:             0.8.1
xlsxwriter:           3.1.6

```

</details>

### PR DESCRIPTION
**Pull request by c-peters**
fix #13201

### CODE REVIEW

File: crates/polars-ops/src/series/ops/is_in.rs [hunk 1]
```diff
@@ -335,15 +337,55 @@ fn is_in_struct(ca_in: &StructChunked, other: &Series) -> PolarsResult<BooleanCh
...
+            let ca_other = other.utf8().unwrap();
+            let categories = ca_in.get_rev_map().get_categories();
+            if ca_other.len() > categories.len() {
+                let categories_set: PlHashMap<&str, u32> = categories
+                    .values_iter()
+                    .enumerate_idx()
+                    .map(|(idx, s)| (s, idx as u32))
+                    .collect();
+
+                let idx: UInt32Chunked = ca_other
```
Comment (ritchie46) [inline crates/polars-ops/src/series/ops/is_in.rs:359]: `downcast_iter().flatten().flatten()`

File: crates/polars-ops/src/series/ops/is_in.rs [hunk 2]
```diff
@@ -335,15 +337,55 @@ fn is_in_struct(ca_in: &StructChunked, other: &Series) -> PolarsResult<BooleanCh
...
+        DataType::Categorical(_, _) => {
+            let (ca_in, other_in) =
+                make_categoricals_compatible(ca_in, other.categorical().unwrap())?;
+            let s = other_in.physical().clone().into_series();
+            is_in_numeric(ca_in.physical(), &s)
+        },
+        DataType::Utf8 => {
+            let ca_other = other.utf8().unwrap();
+            let categories = ca_in.get_rev_map().get_categories();
+            if ca_other.len() > categories.len() {
```
Comment (ritchie46) [inline crates/polars-ops/src/series/ops/is_in.rs:352]: Can you add a comment here behind the rationale to take either branch?

**Comment by stinodego** [comment]
This was noticed in https://github.com/pola-rs/polars/issues/13164#issuecomment-1866250821 as well. Nice to have this fixed!

**Review by ritchie46 — APPROVED** [review]
