### PR TITLE
fix: Disallow cast from boolean to categorical/enum

### LINKED ISSUE #21680: Casting `bool` to `Enum` results in `u32`
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.select(pl.lit(False).cast(pl.Enum(["foo"])))
# shape: (1, 1)
# ┌─────────┐
# │ literal │
# │ ---     │
# │ u32     │
# ╞═════════╡
# │ 0       │
# └─────────┘
```

### Log output

```shell
␤
```

### Issue description

Not sure on the exact rules, but casting 0 is allowed.

```python
pl.select(pl.lit(0).cast(pl.Enum(["foo"])))
# shape: (1, 1)
# ┌─────────┐
# │ literal │
# │ ---     │
# │ enum    │
# ╞═════════╡
# │ foo     │
# └─────────┘
```

The bool example should probably do the same - or else error?

### Expected behavior

Error or enum result.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.24.0
Index type:          UInt32
Platform:            macOS-13.6.1-arm64-arm-64bit-Mach-O
Python:              3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 15.0.0 (clang-1500.1.0.2.5)]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.12.0
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         0.14.0
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.3
openpyxl             3.1.5
pandas               2.2.3
pyarrow              18.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0
```

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Fixes #21680.

### CODE REVIEW

**Review by ritchie46 — APPROVED** [review]

**Comment by ritchie46** [comment]
Thanks! A rebase away.

File: crates/polars-core/src/chunked_array/cast.rs [hunk 1]
```diff
@@ -303,7 +303,7 @@ impl ChunkCast for StringChunked {
             #[cfg(feature = "dtype-categorical")]
             DataType::Enum(rev_map, ordering) => {
                 let Some(rev_map) = rev_map else {
-                    polars_bail!(ComputeError: "can not cast / initialize Enum without categories present")
+                    polars_bail!(InvalidOperation: "cannot cast / initialize Enum without categories present")
```
Comment (mcrumiller) [inline crates/polars-core/src/chunked_array/cast.rs:306]: I changed this from `ComputeError` to `InvalidOperation` for consistency. I think that this type of error makes more sense.

**Comment by mcrumiller** [comment]
@ritchie46 good to go.
