### PR TITLE
fix: Properly load nested Parquet Statistics

### LINKED ISSUE #20510: `scan_parquet` raises PanicError when using `collect` after `filter`
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl


data = {
    "name": ["a", "b"],
    "data": [
        {"title": "Title", "data": [0, 1, 3]},
        {"title": "Title", "data": [0, 1, 3]},
    ],
}

pl.DataFrame(data).write_parquet("data.parquet")

ldf = pl.scan_parquet("data.parquet")

print(ldf.collect())
# shape: (2, 2)
# ┌──────┬─────────────────────┐
# │ name ┆ data                │
# │ ---  ┆ ---                 │
# │ str  ┆ struct[2]           │
# ╞══════╪═════════════════════╡
# │ a    ┆ {"Title",[0, 1, 3]} │
# │ b    ┆ {"Title",[0, 1, 3]} │
# └──────┴─────────────────────┘

print(ldf.collect().filter(pl.col("name") == "b"))
# shape: (1, 2)
# ┌──────┬─────────────────────┐
# │ name ┆ data                │
# │ ---  ┆ ---                 │
# │ str  ┆ struct[2]           │
# ╞══════╪═════════════════════╡
# │ b    ┆ {"Title",[0, 1, 3]} │
# └──────┴─────────────────────┘

print(ldf.collect().lazy().filter(pl.col("name") == "b").collect())
# shape: (1, 2)
# ┌──────┬─────────────────────┐
# │ name ┆ data                │
# │ ---  ┆ ---                 │
# │ str  ┆ struct[2]           │
# ╞══════╪═════════════════════╡
# │ b    ┆ {"Title",[0, 1, 3]} │
# └──────┴─────────────────────┘

with pl.Config(verbose=True):
    print(ldf.filter(pl.col("name") == "b").collect())


```

### Log output

```shell
parquet scan with parallel = Columns
thread 'polars-0' panicked at crates/polars-arrow/src/array/struct_/mod.rs:120:56:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("The children DataTypes of a StructArray must equal the children data types.\n                         However, the field 1 has data type LargeList(Field { name: \"item\", dtype: UInt64, is_nullable: true, metadata: None }) but the value has data type UInt64"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/xomnia/repos/alliander/delta-lake-test/example.py", line 38, in <module>
    print(ldf.filter(pl.col("name") == "b").collect())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xomnia/repos/alliander/delta-lake-test/.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2043, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("The children DataTypes of a StructArray must equal the children data types.\n                         However, the field 1 has data type LargeList(Field { name: \"item\", dtype: UInt64, is_nullable: true, metadata: None }) but the value has data type UInt64"))
```

### Issue description

If I scan a simple parquet file with a Struct column, I get a `PanicException` when I filter the LazyFrame and collect. I don't get the error if I collect first and then filter, nor do I get the error when I turn the full DataFrame into a LazyFrame first, and then filter and collect again.

(Not sure whether this is a bug or just not supported)

### Expected behavior

To be able to do:

```python
print(ldf.filter(pl.col("name") == "b").collect())
# shape: (1, 2)
# ┌──────┬─────────────────────┐
# │ name ┆ data                │
# │ ---  ┆ ---                 │
# │ str  ┆ struct[2]           │
# ╞══════╪═════════════════════╡
# │ b    ┆ {"Title",[0, 1, 3]} │
# └──────┴─────────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.18.0
Index type:          UInt32
Platform:            macOS-14.7-arm64-arm-64bit
Python:              3.12.6 (main, Sep  9 2024, 21:36:32) [Clang 18.1.8 ]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                1.35.90
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.22.3
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.10.0
nest_asyncio         <not installed>
numpy                2.2.1
openpyxl             <not installed>
pandas               <not installed>
pyarrow              18.1.0
pydantic             2.10.4
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by coastalwhite**
This fixes a bug where nested statistics were incorrectly being loaded as if they were proper values.

Fixes #20510.

### CODE REVIEW

File: crates/polars-parquet/src/arrow/read/statistics/binary.rs
Comment (coastalwhite) [inline crates/polars-parquet/src/arrow/read/statistics/binary.rs:1]: All these files are now just merged into statistics.rs

File: crates/polars/tests/it/io/parquet/arrow/write.rs [hunk 1]
```diff
@@ -19,24 +19,12 @@ fn round_trip_opt_stats(
     compression: CompressionOptions,
     encodings: Vec<Encoding>,
 ) -> PolarsResult<()> {
-    let (array, _statistics) = match file {
```
Comment (coastalwhite) [inline crates/polars/tests/it/io/parquet/arrow/write.rs:22]: The statistics were ignored here anyway, so I just removed them.
