### PR TITLE
fix: Fix boolean `min()` in `group_by` aggregation (streaming)

### LINKED ISSUE #23343: boolean `min()` in `group_by` aggregation may return incorrect result
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
$ export POLARS_MAX_THREADS=4
```
```python
import polars as pl

n_rows = pl.thread_pool_size() + 1

df = pl.DataFrame({"k": [i for i in range(n_rows)], "a": [True] * n_rows})
out = df.lazy().group_by("k").agg(pl.col("a").min()).collect(engine="streaming")

print(out.sort("k"))
```

### Log output

```shell
polars-stream: updating graph state
polars-stream: running group-by in subgraph
polars-stream: running in-memory-source in subgraph
polars-stream: running simple-projection in subgraph
polars-stream: running select in subgraph
async thread count: 4
polars-stream: done running graph phase
polars-stream: updating graph state
polars-stream: running in-memory-sink in subgraph
polars-stream: running select in subgraph
polars-stream: running group-by in subgraph
polars-stream: done running graph phase
polars-stream: updating graph state
polars-stream: running group-by in subgraph
polars-stream: running in-memory-sink in subgraph
polars-stream: running select in subgraph
polars-stream: done running graph phase
polars-stream: updating graph state
run sink_mem
run SortExec
shape: (5, 2)
┌─────┬───────┐
│ k   ┆ a     │
│ --- ┆ ---   │
│ i64 ┆ bool  │
╞═════╪═══════╡
│ 0   ┆ false │
│ 1   ┆ false │
│ 2   ┆ false │
│ 3   ┆ false │
│ 4   ┆ true  │
└─────┴───────┘
```

### Issue description

When there are more groups than threads, boolean `min()` will return an incorrect result.

Raising issue for tracking purposes. Fix known and PR coming.

### Expected behavior

Return correct result
```
shape: (5, 2)
┌─────┬──────┐
│ k   ┆ a    │
│ --- ┆ ---  │
│ i64 ┆ bool │
╞═════╪══════╡
│ 0   ┆ true │
│ 1   ┆ true │
│ 2   ┆ true │
│ 3   ┆ true │
│ 4   ┆ true │
└─────┴──────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.31.0
Index type:          UInt32
Platform:            Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.13.3 (main, Apr 29 2025, 12:20:45) [GCC 11.4.0]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  1.6.0
altair               5.5.0
azure.identity       <not installed>
boto3                1.38.27
cloudpickle          3.1.1
connectorx           0.4.3
deltalake            1.0.2
fastexcel            0.14.0
fsspec               2025.5.1
gevent               25.5.1
google.auth          2.40.3
great_tables         0.17.0
matplotlib           3.10.3
numpy                2.2.5
openpyxl             3.1.5
pandas               2.2.3
polars_cloud         0.0.9
pyarrow              20.0.0
pydantic             2.11.7
pyiceberg            0.9.1
sqlalchemy           2.0.41
torch                2.7.1+cu126
xlsx2csv             0.8.4
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #23343

### CODE REVIEW

File: crates/polars-arrow/src/bitmap/mutable.rs [hunk 1]
```diff
@@ -184,7 +184,8 @@ impl MutableBitmap {
     /// It's undefined behavior if index >= self.len().
     #[inline]
     pub unsafe fn and_pos_unchecked(&mut self, index: usize, value: bool) {
-        *self.buffer.get_unchecked_mut(index / 8) &= (value as u8) << (index % 8);
+        *self.buffer.get_unchecked_mut(index / 8) &=
+            (0xfe + (value as u8)).rotate_left(index as u32);
```
Comment (coastalwhite) [inline crates/polars-arrow/src/bitmap/mutable.rs]: nit: for clarity, this should probably be `0xFE | u8::from(value)`. The `+` acts as an OR here.

Comment (kdn36) [reply crates/polars-arrow/src/bitmap/mutable.rs]: Ack, done. Compiles to the same.
