### PR TITLE
fix(rust, python): respect `null_on_oob=False` in `list.take` when pa…

### LINKED ISSUE #10079: `null_on_oob` set to False in `list.take` with single indices doesn't return error
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame(
    {
        "a": [[1, 2, 3], [], [None, 3], [5, 6, 7]],
        "b": [['2'], ['3'], [None], ['3','Hi']],
        
    }
)
print(df.select(pl.col("a").list.take([999], null_on_oob=False)))

shape: (4, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [null]    │
│ [null]    │
│ [null]    │
│ [null]    │
└───────────┘

print(df.select(pl.col("a").list.take(999, null_on_oob=False)))
shape: (4, 1)
┌───────────┐
│ a         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [null]    │
│ [null]    │
│ [null]    │
│ [null]    │
└───────────┘
```

### Issue description

Null_on_oob set to False doesn't work when you pass a one integer wrapped in a list as indices. Same thing happens when you only pass a single integer (which also isn't mentioned in type hints that it accepts an integer).

### Expected behavior

```python
print(df.select(pl.col("a").list.take([999], null_on_oob=False)))
```
```python
ComputeError: take indices are out of bounds
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.8
Index type:          UInt32
Platform:            Windows-10-10.0.22000-SP0
Python:              3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           0.10.0
fsspec:              2023.6.0
matplotlib:          3.7.1
numpy:               1.23.5
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          2.0.17
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by cmdlineluser**
…ssed a single index

Attempts to fix #10079

There was a fast path check for `len == 1` which dispatched to `lst_get()` but this does not take `null_on_oob` into consideration.

I have just removed the fast path check/branch and defaulted to always dispatching to `lst_take()`

### CODE REVIEW

File: polars/polars-lazy/polars-plan/src/dsl/function_expr/list.rs [hunk 1]
```diff
@@ -226,15 +226,7 @@ pub(super) fn take(args: &[Series], null_on_oob: bool) -> PolarsResult<Series> {
     let idx = &args[1];
     let ca = ca.list()?;
 
-    if idx.len() == 1 {
```
Comment (ritchie46) [inline polars/polars-lazy/polars-plan/src/dsl/function_expr/list.rs:229]: You can keep the `fast_path` but set this condition

```
if idx.len() == 1 && null_on_oob
```

Comment (cmdlineluser) [reply polars/polars-lazy/polars-plan/src/dsl/function_expr/list.rs:229]: Thanks @ritchie46 - should have been able to figure that one out, d'oh.

File: py-polars/tests/unit/namespaces/test_list.py [hunk 2]
```diff
@@ -508,3 +508,14 @@ def test_list_set_operations() -> None:
...
+
+
+def test_list_take_oob_10079() -> None:
+    df = pl.DataFrame(
+        {
+            "a": [[1, 2, 3], [], [None, 3], [5, 6, 7]],
+            "b": [["2"], ["3"], [None], ["3", "Hi"]],
+        }
+    )
+    with pytest.raises(pl.ComputeError, match="take indices are out of bounds"):
```
Comment (ion-elgreco) [inline py-polars/tests/unit/namespaces/test_list.py:520]: @cmdlineluser Shouldn't the test check for take with null_on_oob set to False?
