### PR TITLE
fix: Return null instead of 0. for rolling_std when window contains a single element and ddof=1 and there are nulls elsewhere in the Series

### LINKED ISSUE #20076: bug: rolling_std with nulls shows 0 for single-element (instead of null)
spotted here in Narwhals: https://github.com/narwhals-dev/narwhals/pull/1451#discussion_r1864304034

```python
In [37]: pl.Series([1,2,None,4]).rolling_std(3, min_periods=1)
Out[37]:
shape: (4,)
Series: '' [f64]
[
        0.0
        0.707107
        0.707107
        1.414214
]

In [38]: pl.Series([1,2,1,4]).rolling_std(3, min_periods=1)
Out[38]:
shape: (4,)
Series: '' [f64]
[
        null
        0.707107
        0.57735
        1.527525
]
```

Expected output from the first one:
```python
shape: (4,)
Series: '' [f64]
[
        null
        0.707107
        0.707107
        1.414214
]
```

```
----Optional dependencies----
adbc_driver_manager  <not installed>
altair               5.5.0
boto3                <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.9.0
gevent               <not installed>
google.auth          <not installed>
great_tables         0.14.0
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.1.3
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #20076

### CODE REVIEW

File: crates/polars-arrow/src/legacy/kernels/rolling/nulls/variance.rs [hunk 1]
```diff
@@ -178,10 +178,10 @@ impl<
 
         let denom = count - ddof;
 
-        if count == T::zero() {
+        if denom <= T::zero() {
             None
         } else if count == T::one() {
-            NumCast::from(0)
+            Some(T::zero())
```
Comment (MarcoGorelli) [inline crates/polars-arrow/src/legacy/kernels/rolling/nulls/variance.rs:184]: like this it matches what's done for the `no_nulls/variance.rs` kernel

https://github.com/pola-rs/polars/blob/b6187346238f5d72fbe2a5a529817dbadc1b7c32/crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/variance.rs#L121-L125

File: crates/polars-arrow/src/legacy/kernels/rolling/nulls/mod.rs [hunk 2]
```diff
@@ -168,38 +168,29 @@ mod test {
...
         let out = rolling_var(arr, 3, 1, false, None, None);
         let out = out.as_any().downcast_ref::<PrimitiveArray<f64>>().unwrap();
-        let out = out
-            .into_iter()
-            .map(|v| v.copied().unwrap())
-            .collect::<Vec<_>>();
+        let out = out.into_iter().map(|v| v.copied()).collect::<Vec<_>>();
 
-        assert_eq!(out, &[0.0, 0.0, 2.0, 12.5]);
+        assert_eq!(out, &[None, None, Some(2.0), Some(12.5)]);
```
Comment (MarcoGorelli) [inline crates/polars-arrow/src/legacy/kernels/rolling/nulls/mod.rs:173]: here the original series is `[1, null, -1, 4]`, and the operation is rolling variance with window of 3 and min_periods 1 and ddof=1

So the windows are:
- [1]
- [1, null]
- [1, null, -1]
- [null, -1, 4]

and so it's correct that the first two need to output `None`, as they only have a single valid value and ddof=1:
```python
In [50]: print(pl.Series([1]).std())
None
```
