### PR TITLE
fix(rust, python): Keep min/max and arg_min/arg_max consistent.

### LINKED ISSUE #10707: series arg_min & arg_max seems inconsistent with min & max
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

The following comments about whether it is okay are just my intuition and may not necessarily be correct.

```python
    int_has_null = pl.Series("a", [None, 1], dtype=pl.Int32)
    assert int_has_null.max() == 1 # ok
    assert int_has_null.min() == 1 # ok 
    assert int_has_null.arg_max() == 1 # ok
    assert int_has_null.arg_min() == 0 # weird

    int_all_null = pl.Series("a", [None], dtype=pl.Int32)
    assert int_all_null.max() is None # ok 
    assert int_all_null.min() is None # ok 
    assert int_all_null.arg_max() == 0 # ok
    assert int_all_null.arg_min() == 0 # ok

    boolean_has_null_true = pl.Series("a", [None, True], dtype=pl.Boolean)
    assert boolean_has_null_true.max() is True # ok
    assert boolean_has_null_true.min() is True # ok, maybe.
    assert boolean_has_null_true.arg_max() == 1 # ok
    assert boolean_has_null_true.arg_min() == 0 # weird

    boolean_has_null_false = pl.Series("a", [None, False], dtype=pl.Boolean)
    assert boolean_has_null_false.max() is False # ok
    assert boolean_has_null_false.min() is False # ok
    assert boolean_has_null_false.arg_max() is None # weird
    assert boolean_has_null_false.arg_min() == 0 # weird

    boolean_all_null = pl.Series("a", [None], dtype=pl.Boolean)
    assert boolean_all_null.max() is None # ok
    assert boolean_all_null.min() is None # ok
    assert boolean_all_null.arg_max() == 0 # ok
    assert boolean_all_null.arg_min() == 0 # ok

```

### Issue description

I believe part of the reason is that we did not consider null value when calculating `min` & `max`, but we did consider this when calculating the `arg` counterpart, and we used the comparison rule for `Option<T>` in rust (i.e. `None < Some (_)`).

### Expected behavior

Not very sure which behavior is right(though I tend to the behavior of `min&max`), but at least they should be consistent.

### Installed versions

<details>

Main branch.

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This based on #10708 and fixes #10707.

Some tests may fail because we changed `arg_min` and `arg_max` behavior. I will fix that cases one by one.

### CODE REVIEW

**Comment by reswqa** [comment]
You can take a look at `unit.series.test_series.test_arg_min_and_arg_max` first to confirm it is our expected behavior.

File: crates/polars-ops/src/series/ops/arg_min_max.rs [hunk 1]
```diff
@@ -74,33 +74,50 @@ impl ArgAgg for Series {
...
     else if ca.null_count() == 0 && ca.chunks().len() == 1 {
         let arr = ca.downcast_iter().next().unwrap();
         let mask = arr.values();
         Some(first_set_bit(mask))
     } else {
+        let mut first_false_idx: Option<usize> = None;
         ca.into_iter()
-            .position(|opt_val| matches!(opt_val, Some(true)))
+            .enumerate()
+            .find_map(|(idx, val)| match val {
```
Comment (reswqa) [inline crates/polars-ops/src/series/ops/arg_min_max.rs:89]: The logic is: we first find `true`, and if it does not exist, we return the first `false` encountered. Is this what we want?

File: crates/polars-ops/src/series/ops/arg_min_max.rs [hunk 2]
```diff
@@ -195,24 +212,38 @@ fn first_unset_bit(mask: &Bitmap) -> usize {
 }
 
 fn arg_min_str(ca: &Utf8Chunked) -> Option<usize> {
+    if ca.is_empty() || ca.null_count() == ca.len() {
+        return None;
+    }
     match ca.is_sorted_flag() {
-        IsSorted::Ascending => Some(0),
-        IsSorted::Descending => Some(ca.len() - 1),
+        IsSorted::Ascending => ca.first_non_null(),
```
Comment (reswqa) [inline crates/polars-ops/src/series/ops/arg_min_max.rs:219]: Perhaps we can test `ca.null_count() == 0`, and if it doesn't hold up, we can go here. Otherwise, we will still follow the previous logic?

File: crates/polars-ops/src/series/ops/arg_min_max.rs [hunk 3]
```diff
@@ -195,24 +212,38 @@ fn first_unset_bit(mask: &Bitmap) -> usize {
...
+        IsSorted::Descending => ca.last_non_null(),
         IsSorted::Not => ca
             .into_iter()
             .enumerate()
+            .filter_map(|(idx, val)| match val {
```
Comment (reswqa) [inline crates/polars-ops/src/series/ops/arg_min_max.rs:224]: Maybe we can remove this and do a match in reduce?

File: crates/polars-ops/src/series/ops/arg_min_max.rs [hunk 4]
```diff
@@ -195,24 +212,32 @@ fn first_unset_bit(mask: &Bitmap) -> usize {
...
+    }
     match ca.is_sorted_flag() {
-        IsSorted::Ascending => Some(0),
-        IsSorted::Descending => Some(ca.len() - 1),
+        IsSorted::Ascending => ca.first_non_null(),
+        IsSorted::Descending => ca.last_non_null(),
         IsSorted::Not => ca
             .into_iter()
             .enumerate()
+            .flat_map(|(idx, val)| val.map(|val| (idx, val)))
```
Comment (reswqa) [inline crates/polars-ops/src/series/ops/arg_min_max.rs:224]: Maybe I should remove this and perform a `match` in `reduce`?

File: crates/polars-ops/src/series/ops/arg_min_max.rs [hunk 5]
```diff
@@ -224,45 +249,35 @@ where
...
-                    let chunk_min_val: Option<T::Native>;
-                    if arr.null_count() > 0 {
-                        // When there are nulls, we should compare Option<T::Native>
-                        chunk_min_val = None; // because None < Some(_)
-                        chunk_min_idx = arr
-                            .into_iter()
+                    let chunk_min: Option<(usize, T::Native)> = if arr.null_count() > 0 {
+                        arr.into_iter()
                             .enumerate()
+                            .flat_map(|(idx, val)| val.map(|val| (idx, *val)))
```
Comment (reswqa) [inline crates/polars-ops/src/series/ops/arg_min_max.rs:263]: The previous implementation involved many comparisons of `Options<T>`, and it is important to pay great attention to `None < Some(_)`. I filtered out the `None` value directly here. I'm not very sure if this will have a negative impact, but the previous logic was a bit too complicated.

File: crates/polars-ops/src/series/ops/arg_min_max.rs (hunk 4 above)
Comment (ritchie46) [reply crates/polars-ops/src/series/ops/arg_min_max.rs:224]: Match in reduce will be faster as we have less indirection. I think we should first loop over `downcast_iter` and then loop over the array.

File: crates/polars-ops/src/series/ops/arg_min_max.rs (hunk 5 above)
Comment (ritchie46) [reply crates/polars-ops/src/series/ops/arg_min_max.rs:262]: Can we rewrite this one in `downcast_iter` as well?

Comment (reswqa) [reply crates/polars-ops/src/series/ops/arg_min_max.rs:262]: Sorry, I didn't quite understand what you meant. Could you please explain it in more detail? Thanks!

File: crates/polars-ops/src/series/ops/arg_min_max.rs (hunk 4 above)
Comment (reswqa) [reply crates/polars-ops/src/series/ops/arg_min_max.rs:224]: > Match in reduce will be faster as we have less indirection.
 Make sense, will rewrite this.

> I think we should first loop over downcast_iter and then loop over the array.
Does this means rewriting it to the same pattern of `arg_max_numeric` 🤔

File: crates/polars-ops/src/series/ops/arg_min_max.rs (hunk 5 above)
Comment (ritchie46) [reply crates/polars-ops/src/series/ops/arg_min_max.rs:262]: Oh sorry, my bad. This one is good. :+1:  (missed the context due to github collapsing)

File: crates/polars-ops/src/series/ops/arg_min_max.rs (hunk 2 above)
Comment (ritchie46) [reply crates/polars-ops/src/series/ops/arg_min_max.rs:219]: I don't think it would matter much in performance. I leave this up to you.

File: crates/polars-ops/src/series/ops/arg_min_max.rs (hunk 4 above)
Comment (ritchie46) [reply crates/polars-ops/src/series/ops/arg_min_max.rs:224]: They are similar. We could even share a same generic if you are up for that. ^^

But that is maybe a nice follow up PR. :)

**Review by ritchie46 — APPROVED** [review]

File: crates/polars-ops/src/series/ops/arg_min_max.rs (hunk 1 above)
Comment (orlp) [reply crates/polars-ops/src/series/ops/arg_min_max.rs:89]: @reswqa Yes, that's the correct behavior, although I think we can do a faster implementation more explicitly iterating over the bitmap. But that doesn't have to be in this PR.

**Comment by reswqa** [comment]
Thanks @ritchie46 and @orlp for the Patient review! 

> that is maybe a nice follow up PR
Agree with this, we can merge this first to ensure that it works correctly. The optimization suggestions you have put forward are very helpful, and I will try opening a new `perf` PR on the weekend to do these things. :)

**Comment by ritchie46** [comment]
> he optimization suggestions you have put forward are very helpful, and I will try opening a new perf PR on the weekend to do these things. :)

:rocket: Thanks!

File: crates/polars-ops/src/series/ops/arg_min_max.rs (hunk 4 above)
Comment (reswqa) [reply crates/polars-ops/src/series/ops/arg_min_max.rs:224]: I am trying to do this refactoring: Let them both share a same generic function as they are almost similar. The only difference is that for numerical types, we have a fast path with the following bound:

https://github.com/pola-rs/polars/blob/ecb819a6541cbc53bee1bf100d2abc87bb9d0962/crates/polars-ops/src/series/ops/arg_min_max.rs#L248

But for `Utf8ChunkedArray`: we do not have this bound, also we doesn't have this branch:

https://github.com/pola-rs/polars/blob/ecb819a6541cbc53bee1bf100d2abc87bb9d0962/crates/polars-ops/src/series/ops/arg_min_max.rs#L264-L268

I can think of some hack solution (such as a magical macro), but I don't really like this way. Do we have a good solution for this that looks simpler and cleaner 🤔.
