### PR TITLE
fix: Improve identification of "non group-key" aggregates in SQL `GROUP BY` queries

### LINKED ISSUE #23134: Applying function to a column of group_by results in a list
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
use polars::{prelude::*, sql::SQLContext};

fn main() {
    let mut df = DataFrame::new(vec![
        Series::new("a".into(), vec!["a", "a", "b"]).into(),
        Series::new("b".into(), vec![1, 1, 2]).into(),
    ])
    .unwrap();

    println!("{:?}", df);

    let mut file = std::fs::File::create("test.parquet").unwrap();
    ParquetWriter::new(&mut file).finish(&mut df).unwrap();

    let ldf = LazyFrame::scan_parquet("test.parquet", ScanArgsParquet::default()).unwrap();

    let mut ctx = SQLContext::new();
    ctx.register("test", ldf);
    println!(
        "First: {:?}",
        ctx.execute("SELECT a, b FROM test group by a, b")
            .unwrap()
            .collect()
            .unwrap()
    );
    println!(
        "Second: {:?}",
        ctx.execute("SELECT concat(a, ' kek') as c, b FROM test group by a, b")
            .unwrap()
            .collect()
            .unwrap()
    );
    println!(
        "Third: {:?}",
        ctx.execute("SELECT concat(a, ' kek'), b FROM test group by a, b")
            .err()
            .unwrap()
    );
}

```

### Log output

```shell
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ str ┆ i32 │
╞═════╪═════╡
│ a   ┆ 1   │
│ a   ┆ 1   │
│ b   ┆ 2   │
└─────┴─────┘
PREFILL CACHES
CachePrefiller: concurrent streaming scan exec limit: 32
async thread count: 4
CachePrefiller: wait for 1 scans executors
CACHE SET: cache id: UniqueId::MemoryRef(94715479852784)
polars-stream: updating graph state
polars-stream: running in-memory-sink in subgraph
polars-stream: running multi-scan[parquet] in subgraph
[MultiScanTaskInitializer]: spawn_background_tasks(), 1 sources, reader name: parquet, ReaderCapabilities(ROW_INDEX | PRE_SLICE | NEGATIVE_PRE_SLICE | PARTIAL_FILTER | FULL_FILTER)
[MultiScanTaskInitializer]: n_readers_pre_init: 1, max_concurrent_scans: 1
[MultiScanTaskInitializer]: predicate: None, skip files mask: None, predicate to reader: None
[MultiScanTaskInitializer]: scan_source_idx: 0 extra_ops: ExtraOperations { row_index: None, pre_slice: None, cast_columns_policy: CastColumnsPolicy { integer_upcast: false, float_upcast: false, float_downcast: false, datetime_nanoseconds_downcast: false, datetime_microseconds_downcast: false, datetime_convert_timezone: false, missing_struct_fields: Raise, extra_struct_fields: Raise }, missing_columns_policy: Raise, include_file_paths: None, predicate: None } 
[MultiScanTaskInitializer]: Readers init: 1 / (1 total) (range: 0..1, filtered out: 0)
[MultiScan]: Initialize source 0
[ReaderStarter]: scan_source_idx: 0
[ReaderStarter]: scan_source_idx: 0: pre_slice_to_reader: None, external_filter_mask: None
[ReaderStarter]: max_concurrent_scans is 1, waiting..
[AttachReaderToBridge]: received reader (n_readers_received: 1)
memory prefetch function: madvise_willneed
[ParquetFileReader]: project: 2 / 2, pre_slice: None, resolved_pre_slice: None, row_index: None, predicate: None 
[ParquetFileReader]: Config { num_pipelines: 32, row_group_prefetch_size: 128, min_values_per_thread: 16777216 }
[ParquetFileReader]: ideal_morsel_size: 100000
start_reader_impl: scan_source_idx: 0, first_morsel_position: RowCounter { physical_rows: 0, deleted_rows: 0 }
start_reader_impl: scan_source_idx: 0, ApplyExtraOps::Noop, first_morsel_position: RowCounter { physical_rows: 0, deleted_rows: 0 }
[ReaderStarter]: Stopping (no more readers)
[MultiScanState]: Readers disconnected
polars-stream: done running graph phase
polars-stream: updating graph state
EXECUTE PHYS PLAN
run sink_mem
run PartitionGroupbyExec
CACHE HIT: cache id: UniqueId::MemoryRef(94715479852784)
CACHE DROP: cache id: UniqueId::MemoryRef(94715479852784)
FOUND SORTED KEY: running default HASH AGGREGATION
First: shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ str ┆ i32 │
╞═════╪═════╡
│ b   ┆ 2   │
│ a   ┆ 1   │
└─────┴─────┘
PREFILL CACHES
CachePrefiller: concurrent streaming scan exec limit: 32
CachePrefiller: wait for 1 scans executors
CACHE SET: cache id: UniqueId::MemoryRef(94715480014768)
polars-stream: updating graph state
polars-stream: running in-memory-sink in subgraph
polars-stream: running multi-scan[parquet] in subgraph
[MultiScanTaskInitializer]: spawn_background_tasks(), 1 sources, reader name: parquet, ReaderCapabilities(ROW_INDEX | PRE_SLICE | NEGATIVE_PRE_SLICE | PARTIAL_FILTER | FULL_FILTER)
[MultiScanTaskInitializer]: n_readers_pre_init: 1, max_concurrent_scans: 1
[MultiScanTaskInitializer]: predicate: None, skip files mask: None, predicate to reader: None
[MultiScanTaskInitializer]: scan_source_idx: 0 extra_ops: ExtraOperations { row_index: None, pre_slice: None, cast_columns_policy: CastColumnsPolicy { integer_upcast: false, float_upcast: false, float_downcast: false, datetime_nanoseconds_downcast: false, datetime_microseconds_downcast: false, datetime_convert_timezone: false, missing_struct_fields: Raise, extra_struct_fields: Raise }, missing_columns_policy: Raise, include_file_paths: None, predicate: None } 
[MultiScanTaskInitializer]: Readers init: 1 / (1 total) (range: 0..1, filtered out: 0)
[MultiScan]: Initialize source 0
[ReaderStarter]: scan_source_idx: 0
[ReaderStarter]: scan_source_idx: 0: pre_slice_to_reader: None, external_filter_mask: None
[ReaderStarter]: max_concurrent_scans is 1, waiting..
[AttachReaderToBridge]: received reader (n_readers_received: 1)
memory prefetch function: madvise_willneed
[ParquetFileReader]: project: 2 / 2, pre_slice: None, resolved_pre_slice: None, row_index: None, predicate: None 
[ParquetFileReader]: Config { num_pipelines: 32, row_group_prefetch_size: 128, min_values_per_thread: 16777216 }
[ParquetFileReader]: ideal_morsel_size: 100000
start_reader_impl: scan_source_idx: 0, first_morsel_position: RowCounter { physical_rows: 0, deleted_rows: 0 }
start_reader_impl: scan_source_idx: 0, ApplyExtraOps::Noop, first_morsel_position: RowCounter { physical_rows: 0, deleted_rows: 0 }
[ReaderStarter]: Stopping (no more readers)
[MultiScanState]: Readers disconnected
polars-stream: done running graph phase
polars-stream: updating graph state
EXECUTE PHYS PLAN
run sink_mem
run GroupbyExec
keys/aggregates are not partitionable: running default HASH AGGREGATION
CACHE HIT: cache id: UniqueId::MemoryRef(94715480014768)
CACHE DROP: cache id: UniqueId::MemoryRef(94715480014768)
Second: shape: (2, 2)
┌────────────────────┬─────┐
│ c                  ┆ b   │
│ ---                ┆ --- │
│ list[str]          ┆ i32 │
╞════════════════════╪═════╡
│ ["b kek"]          ┆ 2   │
│ ["a kek", "a kek"] ┆ 1   │
└────────────────────┴─────┘
Third: Duplicate(ErrString("column with name 'a' has more than one occurrence\n\nResolved plan until failure:\n\n\t---> FAILED HERE RESOLVING 'select' <---\nParquet SCAN [test.parquet] [id: 94715480023936]\nPROJECT */2 COLUMNS"))
```

### Issue description

After updating to the commit with the deadlock fixed (#23075) some queries running group_by and then applying function to the column under group_by, started returning arrays instead of a single value. 

I've also checked the latest commit to the moment this PR is open, the issue still persists.

### Expected behavior

"Second" df's `c` column should contain `a kek` and `b kek`, not arrays.

"Third" query should not return an error, but work the same way as the second query.

### Installed versions

<details>

polars = { git = "https://github.com/pola-rs/polars", rev = "b110d17a1c8dd7d188b8db965b467606317bb95a", features = [
    "sql",
    "lazy",
    "performant",
    "nightly",
    "cse",
    "parquet",
    "json",
    "dtype-full",
] }

</details>

### PR DESCRIPTION
**Pull request by pomo-mondreganto**
This fixes #23134 while not breaking corr and covar tests

### CODE REVIEW

**Comment by pomo-mondreganto** [comment]
cc @alexander-beedie, this seems like a more correct implementation of checking for an arbitrary aggregate function

**Comment by pomo-mondreganto** [comment]
@ritchie46 @orlp I believe it's unfortunate to release a stable version with this issue unfixed. PTAL

**Comment by orlp** [comment]
@pomo-mondreganto The SQL interface is mostly maintained by @alexander-beedie , perhaps he could take a look?

**Comment by pomo-mondreganto** [comment]
@orlp doesn't seem like Alexander was active for more than a month now 😢

File: crates/polars-sql/src/context.rs [hunk 1]
```diff
@@ -1308,11 +1308,22 @@ impl SQLContext {
         for mut e in projections {
             // `Len` represents COUNT(*) so we treat as an aggregation here.
             let is_agg_or_window = has_expr(e, |e| {
-                matches!(e, Expr::Agg(_) | Expr::Len | Expr::Window { .. })
+                match e {
+                    Expr::Agg(_) | Expr::Len | Expr::Window { .. } => true,
+                    Expr::Function { function: func, .. }
+                        if !matches!(func, FunctionExpr::StructExpr(_)) =>
```
Comment (orlp) [inline crates/polars-sql/src/context.rs:1316]: Why is struct excluded? What if the struct contains a non-key column?

Comment (pomo-mondreganto) [reply crates/polars-sql/src/context.rs:1316]: That exact condition is here because `struct.field` is a function too (StructExpr). Imagine a case when both `field` and `struct.field` exist in the dataframe. We want to find function calls that have any field not in `group by` and consider them an aggregate. If we don't exclude the struct, for the query `select field, struct.field from df group by field` we'd consider `struct.field` a non-aggregate function call with a `field` argument, which is incorrect.

In general, the current system seems a bit odd around aggregations: there's a separate `AggExpr` enum containing some subset of functions, while most others can participate in an aggregation as well. The good example is in the test for the issue — `concat` is not an `AggExpr`, but if it's fed the series, it turns into a HorizontalConcat aggregation. 

That's why I've implemented the check like that — I consider any function called with argument not under `group by` an aggregation. 

Struct fields are a separate issue altogether, we might need to implement a better matching engine than a simple map for the `group_by_keys_schema` to support structs better.

**Comment by alexander-beedie** [comment]
> @orlp doesn't seem like Alexander was active for more than a month now 😢

Yup; I had to take a bit of a break recently - back now 👍

I think your change makes sense as a more generic way to distinguish between group/non-group columns; thanks for taking a look and for coming up with a PR, that's always appreciated.

We should definitely add more testing (though not required for this patch) to see if we can identify any other issues here; I would not be completely surprised if other edge-cases are lurking, be it literals, struct fields, other non-trivial constructs, etc... But being "_more_ correct" is reasonable, and sufficient justification to merge.

**Comment by pomo-mondreganto** [comment]
> is_non_group_key_expr

Sounds good, will merge master & rename

**Comment by pomo-mondreganto** [comment]
@alexander-beedie seems ready to merge from my part

**Review by alexander-beedie — APPROVED** [review]
Thanks :)
