### PR TITLE
fix: Rolling mean with weights incorrect when min_samples < window_size

### LINKED ISSUE #22868: Rolling mean / sum incorrect behavior when min_samples < window
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.DataFrame({"a": [1, 2, 3, 4, 5]}).with_columns(
    pl.col("a").rolling_mean(2, weights=[1, 2], min_samples=1)
)
```

### Log output

```shell
shape: (5, 1)
┌──────────┐
│ a        │
│ ---      │
│ f64      │
╞══════════╡
│ 0.333333 │
│ 1.666667 │
│ 2.666667 │
│ 3.666667 │
│ 4.666667 │
└──────────┘
```

### Issue description

For rolling functions with weights supplied, when min_samples is set smaller than the window size, then the left most values of weights are applied in calculations to the sub-windows, when in fact it should be the right-most.

### Expected behavior

In the example above, the first value should either be 1 (as the mean over on sample point is the sample point itsefl), or 0.6666... if we normalize by the total sum of weights. Having the option for both outputs is useful fwiw.

### Installed versions

<details>

```
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          2.23.3
great_tables         <not installed>
matplotlib           3.8.0
numpy                1.26.0
openpyxl             3.1.4
pandas               2.2.3
polars_cloud         <not installed>
pyarrow              19.0.1
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           2.0.0
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

```

</details>

### PR DESCRIPTION
**Pull request by agossard**
Fixed #22868

We need to slice the weights window to be the same size as the values window if min_periods < window_size. We need to make sure that the weights are correctly truncated on the left or right side to match the values. Finally, we need to renormalize the weights to 1 if we have had to truncate the weights (for rolling_mean, rolling_std, rolling_var only).

### CODE REVIEW

File: crates/polars-compute/src/rolling/no_nulls/mod.rs [hunk 1]
```diff
@@ -93,8 +94,32 @@ where
...
+                // Renormalize weights so they sum to 1
+                let wsum = weights_slice
+                    .iter()
+                    .copied()
+                    .fold(T::zero(), |acc, x| acc + x);
+                if wsum == T::zero() {
+                    panic!("Weighted mean is undefined if weights sum to 0");
+                }
+                let normed_weights: Vec<T> = weights_slice.iter().map(|&w| w / wsum).collect();
+                aggregator(vals, &normed_weights)
```
Comment (orlp) [inline crates/polars-compute/src/rolling/no_nulls/mod.rs]: I'm *really* not a fan of normalizing the weights for each call. Instead the inner aggregator if necessary (`mean` / `var`) should not assume the weights have been pre-normalized and calculate the total weight themselves and divide by it.

**Review by orlp — CHANGES_REQUESTED** [review]

**Review by orlp — APPROVED** [review]

**Comment by orlp** [comment]
Thanks :)
