### PR TITLE
fix(rust, python): get_single_leaf can't handle Expr::Count

### LINKED ISSUE #10783: `ComputeError` on `count` on `over` operations on `list` column
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
(
    pl.DataFrame({
        "a": [["a", "c", "b"], ["a", "b", "c"], ["a", "d", "c"], ["c", "a", "b"]],
        "b": [["a", "c", "b"], ["a", "b", "c"], ["a", "d", "c"], ["c", "a", "b"]]})
    .with_columns(
        pl.count().over(pl.col("a").list.sort().list.join("").hash()).suffix("_cnt"))
)
```

### Issue description

This fails without a descriptive error message:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("unable to find a single leaf column in {expr:?}"))', /Users/runner/work/polars/polars/crates/polars-plan/src/logical_plan/projection.rs:53:51
```

I am aiming to calculate the number of cases where `a` (and `b`) have identical elements, whether or not they are in the same order.

### Expected behavior

Output should be:

```py
(
    pl.DataFrame({
        "a": [["a", "c", "b"], ["a", "b", "c"], ["a", "d", "c"], ["c", "a", "b"]],
        "b": [["a", "c", "b"], ["a", "b", "c"], ["a", "d", "c"], ["c", "a", "b"]]})
    .with_columns(
        pl.Series("a_cnt", [3, 3, 1, 3]))
)
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            macOS-13.4.1-arm64-arm-64bit
Python:              3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]

----Optional dependencies----
adbc_driver_sqlite:  0.5.1
cloudpickle:         2.0.0
connectorx:          0.3.1
deltalake:           0.10.0
fsspec:              2023.3.0
matplotlib:          3.7.1
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             11.0.0
pydantic:            1.10.7
sqlalchemy:          1.4.39
xlsx2csv:            0.8.1
xlsxwriter:          3.0.9
```

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This fixes #10783.

### CODE REVIEW

File: crates/polars-plan/src/utils.rs [hunk 1]
```diff
@@ -192,11 +192,12 @@ pub(crate) fn get_single_leaf(expr: &Expr) -> PolarsResult<Arc<str>> {
             Expr::SortBy { expr, .. } => return get_single_leaf(expr),
             Expr::Window { function, .. } => return get_single_leaf(function),
             Expr::Column(name) => return Ok(name.clone()),
+            Expr::Count => return Ok(Arc::from(COUNT)),
             _ => {},
         }
     }
     polars_bail!(
-        ComputeError: "unable to find a single leaf column in {expr:?}"
```
Comment (reswqa) [inline crates/polars-plan/src/utils.rs:199]: Seems that we did not format the error message correctly before

File: crates/polars-plan/src/utils.rs [hunk 2]
```diff
@@ -192,11 +192,12 @@ pub(crate) fn get_single_leaf(expr: &Expr) -> PolarsResult<Arc<str>> {
             Expr::SortBy { expr, .. } => return get_single_leaf(expr),
             Expr::Window { function, .. } => return get_single_leaf(function),
             Expr::Column(name) => return Ok(name.clone()),
+            Expr::Count => return Ok(Arc::from(COUNT)),
```
Comment (reswqa) [inline crates/polars-plan/src/utils.rs:195]: IIUC, `Expr::Count` is a leaf expr, It is different from `AggExpr` which does have an input.

**Review by ritchie46 — APPROVED** [review]

File: crates/polars-plan/src/utils.rs (hunk 2 above)
Comment (ritchie46) [reply crates/polars-plan/src/utils.rs:195]: Good catch!
