### PR TITLE
fix: Incorrect output order for order sensitive operations after join_asof

### LINKED ISSUE #25973: `maintain_order=True` not valid when lazy evaluate `group_by` after `join_asof`
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# Example Data Construction
import polars as pl 
import datetime as dt 

targettime = pl.DataFrame({
    "targettime":pl.time_range(dt.time(0),dt.time(23,59),interval="10m",closed="both",eager=True)
}).with_columns(
    targettime = pl.lit(dt.date(2026,1,1)).dt.combine(pl.col("targettime")),
    grp = pl.lit(1)
).lazy()
df = pl.DataFrame({
    "time":pl.time_range(dt.time(0),dt.time(23,59),interval="1s",closed="both",eager=True)
}).with_row_index("value").with_columns(
    time=pl.lit(dt.date(2026,1,1)).dt.combine(pl.col("time")),
    grp = pl.lit(1)
).lazy()
```

Unexpected behavier:
```python
df.join_asof(
    targettime, 
    left_on="time", right_on="targettime", strategy="forward"
).drop_nulls("targettime").group_by(
    "targettime", maintain_order=True
).agg(pl.col("value").last()).collect()
```

The order of result is not maintained(actually random): 
targettime | value
-- | --
datetime[μs] | u32
2026-01-01 09:20:00 | 33600
2026-01-01 20:00:00 | 72000
2026-01-01 22:50:00 | 82200
2026-01-01 03:10:00 | 11400
2026-01-01 18:20:00 | 66000
… | …
2026-01-01 21:10:00 | 76200
2026-01-01 12:10:00 | 43800
2026-01-01 07:40:00 | 27600
2026-01-01 16:40:00 | 60000
2026-01-01 06:00:00 | 21600

### Log output

```shell

```

### Issue description

While using lazy evaluate for `join_asof().group_by(maintain_order=True)`, the order of result is not maintained. 

However, if you do as below, the order is still maintained as expected:
First:
```python
res=df.join_asof(
    targettime, 
    left_on="time", right_on="targettime", strategy="forward"
).drop_nulls("targettime").collect()
res.group_by(
    "targettime", maintain_order=True
).agg(pl.col("value").last())
```
Second, use the same code as example, but with polars 1.24.0

### Expected behavior

The order of result should be the same as `df`, which is well ordered.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.36.1
Index type:          UInt32
Platform:            Windows-10-10.0.19045-SP0
Python:              3.12.12 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 20:05:38) [MSC v.1929 64 bit (AMD64)]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.3.5
openpyxl             <not installed>
pandas               2.3.3
polars_cloud         <not installed>
pyarrow              21.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by azimafroozeh**
Fixes #25973

### CODE REVIEW

File: crates/polars-plan/src/plans/optimizer/set_order/ir_pullup.rs [hunk 1]
```diff
@@ -61,24 +61,14 @@ pub(super) fn pullup_orders(
...
-                        .iter()
-                        .any(|k| is_output_ordered(expr_arena.get(k.node()), expr_arena, false));
-                    if !keys_produce_order {
-                        *maintain_order = false;
-                    }
-                }
+                // If maintain_order is false, the outputs are considered unordered.
+                // If maintain_order is true, we keep it – this was explicitly requested
+                // (e.g. group_by_stable / with_maintain_order(true)), even if the input
+                // itself is not guaranteed to be ordered.
```
Comment (orlp) [inline crates/polars-plan/src/plans/optimizer/set_order/ir_pullup.rs]: This makes no sense to me, why would we be maintaining the order of unordered input? This is removing a useful optimization (since order-maintaining group-by's are slower).

Why is the input unordered in the first place in the bug example? I believe the problem is that (for whatever reason) the `asof_join` output is marked as unordered when it shouldn't be.

Comment (azimafroozeh) [reply crates/polars-plan/src/plans/optimizer/set_order/ir_pullup.rs]: Well, then my guess is that since as-of joins produce output in the order of the left input, the issue likely comes from the fact that this was not reflected in JoinOptionsIR, causing the optimizer to treat the as-of join output as unordered. As a result, a downstream GroupBy(maintain_order=True) could silently lose its stable ordering guarantee.

Comment (orlp) [reply crates/polars-plan/src/plans/optimizer/set_order/ir_pullup.rs]: This is the right solution I think, but a fragile implementation. Rather than update the `maintain_order` flags (which are more of an *override* than a description of the operator), I think we should update wherever the order optimizer looks at joins to determine if they are order-preserving to specifically handle as-of joins.

Comment (orlp) [reply crates/polars-plan/src/plans/optimizer/set_order/ir_pullup.rs]: I'm not 100% certain but I think it should be modified in `crates/polars-plan/src/plans/optimizer/set_order/ir_pushdown.rs` around line 200 as well as `ir_pullup.rs` next to it around line 100.

File: crates/polars-plan/src/plans/optimizer/set_order/ir_pushdown.rs [hunk 2]
```diff
@@ -185,6 +185,10 @@ pub(super) fn pushdown_orders(
                 // sensitivity.
                 [false, false].into()
             },
+            #[cfg(feature = "asof_join")]
+            IR::Join { options, .. } if matches!(options.args.how, JoinType::AsOf(_)) => {
+                [true, false].into()
```
Comment (orlp) [inline crates/polars-plan/src/plans/optimizer/set_order/ir_pushdown.rs]: The [`join_asof`](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.join_asof.html) documentation states that both inputs need to be sorted. I think that implies they always both need to be ordered. By returning `false` for the second argument you can make the optimizer accidentally delete a `sort` call downstream I believe, as a `sort` into an unordered input is useless.

File: crates/polars-plan/src/plans/optimizer/set_order/ir_pullup.rs [hunk 3]
```diff
@@ -99,6 +101,12 @@ pub(super) fn pullup_orders(
                     }
                 }
             },
+            #[cfg(feature = "asof_join")]
+            IR::Join { options, .. } if matches!(options.args.how, JoinType::AsOf(_)) => {
+                if !inputs_ordered[0] {
```
Comment (orlp) [inline crates/polars-plan/src/plans/optimizer/set_order/ir_pullup.rs]: I think we should just do nothing in this branch. If the inputs aren't ordered it should probably give an error (since the asof join relies on order) but there's no mechanic yet for returning errors from here.

Can you add such a comment?

File: crates/polars-plan/src/plans/optimizer/set_order/ir_pushdown.rs (hunk 2 above)
Comment (nameexhaustion) [reply crates/polars-plan/src/plans/optimizer/set_order/ir_pushdown.rs]: I don't think we need to add this here btw, there's already a branch for this above -

Screenshot_2026-01-08-20-17-58-06_40deb401b9ffe8e1df2f1cc5ba480b12

I think we just need to add the asof match to "ir_pullup" to fix the issue

Comment (orlp) [reply crates/polars-plan/src/plans/optimizer/set_order/ir_pushdown.rs]: Oh I hadn't seen that one my bad.

File: py-polars/tests/unit/lazyframe/test_optimizations.py [hunk 4]
```diff
@@ -459,3 +460,64 @@ def test_slice_pushdown_expr_25473() -> None:
...
+        )
+        .drop_nulls("targettime")
+        .group_by("targettime", maintain_order=True)
+        .agg(pl.col("value").last())
+        .collect()
+    )
+
+    # Now should maintain order; just check monotonicity of the targettime key
+    times = result["targettime"].to_list()
+    assert times == sorted(times)
```
Comment (nameexhaustion) [inline py-polars/tests/unit/lazyframe/test_optimizations.py]: Could we ensure to assert the length of the Series here.

(Further suggestion) I'd prefer we used `assert_frame_equal` to assert equality against a statically declared DataFrame with the expected result values (if it's not too big), up to you.

File: py-polars/tests/unit/lazyframe/test_optimizations.py [hunk 5]
```diff
@@ -459,3 +460,64 @@ def test_slice_pushdown_expr_25473() -> None:
...
+            strategy="forward",
+        )
+        .drop_nulls("targettime")
+        .group_by("targettime", maintain_order=True)
+        .agg(pl.col("value").last())
+        .collect()
+    )
+
+    # Now should maintain order; just check monotonicity of the targettime key
+    times = result["targettime"].to_list()
```
Comment (nameexhaustion) [inline py-polars/tests/unit/lazyframe/test_optimizations.py]:
```suggestion
    assert result["targettime"].is_sorted()
```

File: py-polars/tests/unit/lazyframe/test_optimizations.py (hunk 4 above)
Comment (azimafroozeh) [reply py-polars/tests/unit/lazyframe/test_optimizations.py]: Thanks for the suggestion. This is indeed better. I simplified the test to use a very small input (4 rows total) and now assert the full result against a statically declared DataFrame via `assert_frame_equal`.

**Comment by nameexhaustion** [comment]
@azimafroozeh one last thing, could you assert that `maintain_order: true` exists in the query plan? You can see an example of how to do this here -

https://github.com/pola-rs/polars/blob/2115e98d19a7a63a0d18ee5c6eeeab48ca33abc6/py-polars/tests/unit/lazyframe/test_order_observability.py#L554-L556

**Review by nameexhaustion — APPROVED** [review]
