### PR TITLE
fix: Fix filter scalar nulls

### LINKED ISSUE #19771: A no-op filter errors when the dataframe has an all null column
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({"a": [None, None]})
df.filter(pl.lit(True))
```

Produces an error:

```python-traceback
---------------------------------------------------------------------------
ShapeError                                Traceback (most recent call last)
Cell In[25], line 3
      1 import polars as pl
      2 df = pl.DataFrame({"a": [None, None]})
----> 3 df.filter(pl.lit(True))

File ~/.cache/pypoetry/virtualenvs/ski-bearings-cIphqNWs-py3.12/lib/python3.12/site-packages/polars/dataframe/frame.py:4769, in DataFrame.filter(self, *predicates, **constraints)
   4615 def filter(
   4616     self,
   4617     *predicates: (
   (...)
   4624     **constraints: Any,
   4625 ) -> DataFrame:
   4626     """
   4627     Filter the rows in the DataFrame based on one or more predicate expressions.
   4628 
   (...)
   4767 
   4768     """
-> 4769     return self.lazy().filter(*predicates, **constraints).collect(_eager=True)

File ~/.cache/pypoetry/virtualenvs/ski-bearings-cIphqNWs-py3.12/lib/python3.12/site-packages/polars/lazyframe/frame.py:2021, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, collapse_joins, no_optimization, streaming, engine, background, _eager, **_kwargs)
   2019 # Only for testing purposes
   2020 callback = _kwargs.get("post_opt_callback", callback)
-> 2021 return wrap_df(ldf.collect(callback))

ShapeError: filter's length: 1 differs from that of the series: 2
```

### Log output

```shell
parquet scan with parallel = None
dataframe filtered
```

### Issue description

I'm looking for a way to apply a no-op filter. `.filter(pl.lit(True))` would seem to be the most obvious way. Assume that I must call filter and I only control the arguments to filter.

This fails when there is an all null column.

### Expected behavior

No fails.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.13.0
Index type:          UInt32
Platform:            Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Python:              3.12.7 (main, Oct 13 2024, 20:43:25) [GCC 11.4.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         0.13.0
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.1.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              17.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #19771

### CODE REVIEW

File: crates/polars-core/src/series/implementations/null.rs [hunk 1]
```diff
@@ -280,6 +280,11 @@ impl SeriesTrait for NullChunked {
             // We still allow a length of `1` because it could be `lit(true)`.
             polars_ensure!(filter.len() <= 1, ShapeMismatch: "filter's length: {} differs from that of the series: 0", filter.len());
             0
+        } else if filter.len() == 1 {
+            return match filter.get(0) {
+                None | Some(true) => Ok(self.clone().into_series()),
```
Comment (orlp) [inline crates/polars-core/src/series/implementations/null.rs:285]: I believe that `None` should be in the `false` branch, not behave like `true`.

**Review by orlp — CHANGES_REQUESTED** [review]

File: crates/polars-core/src/series/implementations/null.rs (hunk 1 above)
Comment (ritchie46) [reply crates/polars-core/src/series/implementations/null.rs]: Yeap, good catch.
