### PR TITLE
fix(rust): Fix to_integer panicing on invalid base

### LINKED ISSUE #22033: `str.to_integer` with `2 > base > 36` panics
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame([
    pl.Series('a', [
        "1", "2", "3"
    ], pl.String),
])
df.select(pl.col.a.str.to_integer(base=0))
```

### Log output

```shell
thread '<unnamed>' panicked at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs:1603:1](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs#line=1602):
from_ascii_radix: radix must lie in the range `[2, 36]` - found 1
stack backtrace:
   0: rust_begin_unwind
             at [/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/std/src/panicking.rs:695:5](http://127.0.0.1:8888/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/std/src/panicking.rs#line=694)
   1: core::panicking::panic_fmt
             at [/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panicking.rs:75:14](http://127.0.0.1:8888/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panicking.rs#line=74)
   2: core::num::from_ascii_radix_panic::do_panic::runtime
             at [/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panic.rs:218:21](http://127.0.0.1:8888/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panic.rs#line=217)
   3: core::num::from_ascii_radix_panic::do_panic
             at [/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/intrinsics/mod.rs:3089:9](http://127.0.0.1:8888/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/intrinsics/mod.rs#line=3088)
   4: core::num::from_ascii_radix_panic
             at [/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panic.rs:223:9](http://127.0.0.1:8888/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panic.rs#line=222)
   5: core::num::<impl i64>::from_ascii_radix
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs:1515:21](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs#line=1514)
   6: core::num::<impl i64>::from_str_radix
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs:1430:17](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs#line=1429)
   7: <i64 as num_traits::Num>::from_str_radix
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/lib.rs:169:17](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/lib.rs#line=168)
   8: polars_ops::chunked_array::strings::namespace::StringNameSpaceImpl::to_integer::{{closure}}
             at [./crates/polars-ops/src/chunked_array/strings/namespace.rs:71:42](http://127.0.0.1:8888/crates/polars-ops/src/chunked_array/strings/namespace.rs#line=70)
   9: polars_core::chunked_array::ops::arity::broadcast_binary_elementwise::{{closure}}
             at [./crates/polars-core/src/chunked_array/ops/arity.rs:705:40](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/ops/arity.rs#line=704)
  10: polars_core::chunked_array::ops::arity::unary_elementwise::{{closure}}::{{closure}}
             at [./crates/polars-core/src/chunked_array/ops/arity.rs:87:50](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/ops/arity.rs#line=86)
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/ops/function.rs:305:13](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/ops/function.rs#line=304)
  12: core::option::Option<T>::map
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/option.rs:1119:29](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/option.rs#line=1118)
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:107:26](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=106)
  14: <polars_arrow::array::primitive::PrimitiveArray<T> as polars_arrow::array::static_array_collect::ArrayFromIter<core::option::Option<T>>>::arr_from_iter
             at [./crates/polars-arrow/src/array/static_array_collect.rs:249:24](http://127.0.0.1:8888/crates/polars-arrow/src/array/static_array_collect.rs#line=248)
  15: polars_arrow::array::static_array_collect::ArrayCollectIterExt::collect_arr
             at [./crates/polars-arrow/src/array/static_array_collect.rs:138:9](http://127.0.0.1:8888/crates/polars-arrow/src/array/static_array_collect.rs#line=137)
  16: polars_core::chunked_array::ops::arity::unary_elementwise::{{closure}}
             at [./crates/polars-core/src/chunked_array/ops/arity.rs:87:24](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/ops/arity.rs#line=86)
  17: core::iter::adapters::map::map_fold::{{closure}}
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:88:28](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=87)
  18: core::iter::adapters::map::map_fold::{{closure}}
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:88:21](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=87)
  19: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:255:27](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs#line=254)
  20: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:128:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=127)
  21: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:128:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=127)
  22: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:128:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=127)
  23: core::iter::traits::iterator::Iterator::for_each
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:800:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=799)
  24: alloc::vec::Vec<T,A>::extend_trusted
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3577:17](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs#line=3576)
  25: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_extend.rs:29:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_extend.rs#line=28)
  26: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs:62:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs#line=61)
  27: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs:34:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs#line=33)
  28: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3436:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs#line=3435)
  29: core::iter::traits::iterator::Iterator::collect
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1971:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=1970)
  30: polars_core::chunked_array::from::<impl polars_core::chunked_array::ChunkedArray<T>>::from_chunk_iter
             at [./crates/polars-core/src/chunked_array/from.rs:122:22](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/from.rs#line=121)
  31: polars_core::chunked_array::ops::arity::unary_elementwise
             at [./crates/polars-core/src/chunked_array/ops/arity.rs:88:9](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/ops/arity.rs#line=87)
  32: polars_core::chunked_array::ops::arity::broadcast_binary_elementwise
             at [./crates/polars-core/src/chunked_array/ops/arity.rs:705:13](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/ops/arity.rs#line=704)
  33: polars_ops::chunked_array::strings::namespace::StringNameSpaceImpl::to_integer
             at [./crates/polars-ops/src/chunked_array/strings/namespace.rs:75:19](http://127.0.0.1:8888/crates/polars-ops/src/chunked_array/strings/namespace.rs#line=74)
  34: polars_plan::dsl::function_expr::strings::to_integer
             at [./crates/polars-plan/src/dsl/function_expr/strings.rs:1019:5](http://127.0.0.1:8888/crates/polars-plan/src/dsl/function_expr/strings.rs#line=1018)
  35: polars_plan::dsl::function_expr::strings::<impl core::convert::From<polars_plan::dsl::function_expr::strings::StringFunction> for polars_plan::dsl::expr_dyn_fn::SpecialEq<alloc::sync::Arc<dyn polars_plan::dsl::expr_dyn_fn::ColumnsUdf>>>::from::{{closure}}
             at [./crates/polars-plan/src/dsl/function_expr/mod.rs:838:13](http://127.0.0.1:8888/crates/polars-plan/src/dsl/function_expr/mod.rs#line=837)
  36: <F as polars_plan::dsl::expr_dyn_fn::ColumnsUdf>::call_udf
             at [./crates/polars-plan/src/dsl/expr_dyn_fn.rs:102:9](http://127.0.0.1:8888/crates/polars-plan/src/dsl/expr_dyn_fn.rs#line=101)
  37: polars_expr::expressions::apply::ApplyExpr::eval_and_flatten
             at [./crates/polars-expr/src/expressions/apply.rs:117:28](http://127.0.0.1:8888/crates/polars-expr/src/expressions/apply.rs#line=116)
  38: <polars_expr::expressions::apply::ApplyExpr as polars_expr::expressions::PhysicalExpr>::evaluate
             at [./crates/polars-expr/src/expressions/apply.rs:344:16](http://127.0.0.1:8888/crates/polars-expr/src/expressions/apply.rs#line=343)
  39: polars_mem_engine::executors::projection_utils::run_exprs_seq::{{closure}}
             at [./crates/polars-mem-engine/src/executors/projection_utils.rs:250:29](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/projection_utils.rs#line=249)
  40: core::iter::adapters::map::map_try_fold::{{closure}}
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:95:28](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=94)
  41: core::iter::traits::iterator::Iterator::try_fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2370:21](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=2369)
  42: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:121:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=120)
  43: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:191:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs#line=190)
  44: core::iter::traits::iterator::Iterator::try_for_each
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2431:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=2430)
  45: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:174:14](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs#line=173)
  46: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs:25:32](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs#line=24)
  47: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs:34:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs#line=33)
  48: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3436:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs#line=3435)
  49: core::iter::traits::iterator::Iterator::collect
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1971:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=1970)
  50: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/result.rs:1985:51](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/result.rs#line=1984)
  51: core::iter::adapters::try_process
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:160:17](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs#line=159)
  52: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/result.rs:1985:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/result.rs#line=1984)
  53: core::iter::traits::iterator::Iterator::collect
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1971:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=1970)
  54: polars_mem_engine::executors::projection_utils::run_exprs_seq
             at [./crates/polars-mem-engine/src/executors/projection_utils.rs:250:5](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/projection_utils.rs#line=249)
  55: polars_mem_engine::executors::projection_utils::evaluate_physical_expressions
             at [./crates/polars-mem-engine/src/executors/projection_utils.rs:268:28](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/projection_utils.rs#line=267)
  56: polars_mem_engine::executors::projection::ProjectionExec::execute_impl
             at [./crates/polars-mem-engine/src/executors/projection.rs:49:33](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/projection.rs#line=48)
  57: <polars_mem_engine::executors::projection::ProjectionExec as polars_mem_engine::executors::executor::Executor>::execute
             at [./crates/polars-mem-engine/src/executors/projection.rs:100:13](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/projection.rs#line=99)
  58: <polars_mem_engine::executors::executor::SinkExecutor as polars_mem_engine::executors::executor::Executor>::execute
             at [./crates/polars-mem-engine/src/executors/executor.rs:31:18](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/executor.rs#line=30)
  59: polars_lazy::frame::LazyFrame::collect_with_engine
             at [./crates/polars-lazy/src/frame/mod.rs:811:17](http://127.0.0.1:8888/crates/polars-lazy/src/frame/mod.rs#line=810)
  60: polars_python::lazyframe::general::<impl polars_python::lazyframe::PyLazyFrame>::collect::{{closure}}
             at [./crates/polars-python/src/lazyframe/general.rs:688:17](http://127.0.0.1:8888/crates/polars-python/src/lazyframe/general.rs#line=687)
  61: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs#line=271)
  62: std::panicking::try::do_call
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs:587:40](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs#line=586)
  63: __rust_try
  64: std::panicking::try
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs:550:19](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs#line=549)
  65: std::panic::catch_unwind
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panic.rs:359:14](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panic.rs#line=358)
  66: polars_error::signals::catch_keyboard_interrupt
             at [./crates/polars-error/src/signals.rs:83:15](http://127.0.0.1:8888/crates/polars-error/src/signals.rs#line=82)
  67: <pyo3::marker::Python as polars_python::utils::EnterPolarsExt>::enter_polars::{{closure}}
             at [./crates/polars-python/src/utils.rs:106:41](http://127.0.0.1:8888/crates/polars-python/src/utils.rs#line=105)
  68: pyo3::marker::Python::allow_threads
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/marker.rs:520:9](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/marker.rs#line=519)
  69: <pyo3::marker::Python as polars_python::utils::EnterPolarsExt>::enter_polars
             at [./crates/polars-python/src/utils.rs:106:19](http://127.0.0.1:8888/crates/polars-python/src/utils.rs#line=105)
  70: polars_python::utils::EnterPolarsExt::enter_polars_df
             at [./crates/polars-python/src/utils.rs:82:9](http://127.0.0.1:8888/crates/polars-python/src/utils.rs#line=81)
  71: polars_python::lazyframe::general::<impl polars_python::lazyframe::PyLazyFrame>::collect
             at [./crates/polars-python/src/lazyframe/general.rs:681:9](http://127.0.0.1:8888/crates/polars-python/src/lazyframe/general.rs#line=680)
  72: polars_python::lazyframe::general::<impl polars_python::lazyframe::PyLazyFrame>::__pymethod_collect__
             at [./crates/polars-python/src/lazyframe/general.rs:69:1](http://127.0.0.1:8888/crates/polars-python/src/lazyframe/general.rs#line=68)
  73: pyo3::impl_::trampoline::cfunction_with_keywords::{{closure}}
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs:44:29](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs#line=43)
  74: pyo3::impl_::trampoline::trampoline::{{closure}}
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs:188:54](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs#line=187)
  75: std::panicking::try::do_call
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs:587:40](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs#line=586)
  76: __rust_try
  77: std::panicking::try
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs:550:19](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs#line=549)
  78: std::panic::catch_unwind
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panic.rs:359:14](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panic.rs#line=358)
  79: pyo3::impl_::trampoline::trampoline
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs:188:9](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs#line=187)
  80: pyo3::impl_::trampoline::cfunction_with_keywords
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs:44:13](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs#line=43)
  81: polars_python::lazyframe::general::_::__INVENTORY::trampoline
             at [./crates/polars-python/src/lazyframe/general.rs:69:1](http://127.0.0.1:8888/crates/polars-python/src/lazyframe/general.rs#line=68)
  82: method_vectorcall_VARARGS_KEYWORDS
  83: PyObject_Vectorcall
  84: _PyEval_EvalFrameDefault
  85: _PyEval_Vector
  86: _PyVectorcall_Call
  87: _PyEval_EvalFrameDefault
  88: _PyEval_Vector.constprop.0
  89: PyEval_EvalCode.localalias
  90: builtin_exec
  91: _PyEval_EvalFrameDefault
  92: PyGen_am_send
  93: _PyEval_EvalFrameDefault
  94: PyGen_am_send
  95: _PyEval_EvalFrameDefault
  96: gen_send
  97: _PyEval_EvalFrameDefault
  98: _PyEval_Vector
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.thread '<unnamed>' panicked at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs:1603:1](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs#line=1602):
from_ascii_radix: radix must lie in the range `[2, 36]` - found 1
stack backtrace:
   0: rust_begin_unwind
             at [/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/std/src/panicking.rs:695:5](http://127.0.0.1:8888/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/std/src/panicking.rs#line=694)
   1: core::panicking::panic_fmt
             at [/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panicking.rs:75:14](http://127.0.0.1:8888/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panicking.rs#line=74)
   2: core::num::from_ascii_radix_panic::do_panic::runtime
             at [/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panic.rs:218:21](http://127.0.0.1:8888/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panic.rs#line=217)
   3: core::num::from_ascii_radix_panic::do_panic
             at [/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/intrinsics/mod.rs:3089:9](http://127.0.0.1:8888/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/intrinsics/mod.rs#line=3088)
   4: core::num::from_ascii_radix_panic
             at [/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panic.rs:223:9](http://127.0.0.1:8888/rustc/b74da9613a8cb5ba67a985f71325be0b7b16c0dd/library/core/src/panic.rs#line=222)
   5: core::num::<impl i64>::from_ascii_radix
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs:1515:21](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs#line=1514)
   6: core::num::<impl i64>::from_str_radix
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs:1430:17](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/num/mod.rs#line=1429)
   7: <i64 as num_traits::Num>::from_str_radix
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/lib.rs:169:17](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-traits-0.2.19/src/lib.rs#line=168)
   8: polars_ops::chunked_array::strings::namespace::StringNameSpaceImpl::to_integer::{{closure}}
             at [./crates/polars-ops/src/chunked_array/strings/namespace.rs:71:42](http://127.0.0.1:8888/crates/polars-ops/src/chunked_array/strings/namespace.rs#line=70)
   9: polars_core::chunked_array::ops::arity::broadcast_binary_elementwise::{{closure}}
             at [./crates/polars-core/src/chunked_array/ops/arity.rs:705:40](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/ops/arity.rs#line=704)
  10: polars_core::chunked_array::ops::arity::unary_elementwise::{{closure}}::{{closure}}
             at [./crates/polars-core/src/chunked_array/ops/arity.rs:87:50](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/ops/arity.rs#line=86)
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/ops/function.rs:305:13](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/ops/function.rs#line=304)
  12: core::option::Option<T>::map
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/option.rs:1119:29](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/option.rs#line=1118)
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:107:26](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=106)
  14: <polars_arrow::array::primitive::PrimitiveArray<T> as polars_arrow::array::static_array_collect::ArrayFromIter<core::option::Option<T>>>::arr_from_iter
             at [./crates/polars-arrow/src/array/static_array_collect.rs:249:24](http://127.0.0.1:8888/crates/polars-arrow/src/array/static_array_collect.rs#line=248)
  15: polars_arrow::array::static_array_collect::ArrayCollectIterExt::collect_arr
             at [./crates/polars-arrow/src/array/static_array_collect.rs:138:9](http://127.0.0.1:8888/crates/polars-arrow/src/array/static_array_collect.rs#line=137)
  16: polars_core::chunked_array::ops::arity::unary_elementwise::{{closure}}
             at [./crates/polars-core/src/chunked_array/ops/arity.rs:87:24](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/ops/arity.rs#line=86)
  17: core::iter::adapters::map::map_fold::{{closure}}
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:88:28](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=87)
  18: core::iter::adapters::map::map_fold::{{closure}}
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:88:21](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=87)
  19: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:255:27](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs#line=254)
  20: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:128:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=127)
  21: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:128:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=127)
  22: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:128:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=127)
  23: core::iter::traits::iterator::Iterator::for_each
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:800:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=799)
  24: alloc::vec::Vec<T,A>::extend_trusted
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3577:17](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs#line=3576)
  25: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_extend.rs:29:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_extend.rs#line=28)
  26: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs:62:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs#line=61)
  27: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs:34:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs#line=33)
  28: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3436:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs#line=3435)
  29: core::iter::traits::iterator::Iterator::collect
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1971:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=1970)
  30: polars_core::chunked_array::from::<impl polars_core::chunked_array::ChunkedArray<T>>::from_chunk_iter
             at [./crates/polars-core/src/chunked_array/from.rs:122:22](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/from.rs#line=121)
  31: polars_core::chunked_array::ops::arity::unary_elementwise
             at [./crates/polars-core/src/chunked_array/ops/arity.rs:88:9](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/ops/arity.rs#line=87)
  32: polars_core::chunked_array::ops::arity::broadcast_binary_elementwise
             at [./crates/polars-core/src/chunked_array/ops/arity.rs:705:13](http://127.0.0.1:8888/crates/polars-core/src/chunked_array/ops/arity.rs#line=704)
  33: polars_ops::chunked_array::strings::namespace::StringNameSpaceImpl::to_integer
             at [./crates/polars-ops/src/chunked_array/strings/namespace.rs:75:19](http://127.0.0.1:8888/crates/polars-ops/src/chunked_array/strings/namespace.rs#line=74)
  34: polars_plan::dsl::function_expr::strings::to_integer
             at [./crates/polars-plan/src/dsl/function_expr/strings.rs:1019:5](http://127.0.0.1:8888/crates/polars-plan/src/dsl/function_expr/strings.rs#line=1018)
  35: polars_plan::dsl::function_expr::strings::<impl core::convert::From<polars_plan::dsl::function_expr::strings::StringFunction> for polars_plan::dsl::expr_dyn_fn::SpecialEq<alloc::sync::Arc<dyn polars_plan::dsl::expr_dyn_fn::ColumnsUdf>>>::from::{{closure}}
             at [./crates/polars-plan/src/dsl/function_expr/mod.rs:838:13](http://127.0.0.1:8888/crates/polars-plan/src/dsl/function_expr/mod.rs#line=837)
  36: <F as polars_plan::dsl::expr_dyn_fn::ColumnsUdf>::call_udf
             at [./crates/polars-plan/src/dsl/expr_dyn_fn.rs:102:9](http://127.0.0.1:8888/crates/polars-plan/src/dsl/expr_dyn_fn.rs#line=101)
  37: polars_expr::expressions::apply::ApplyExpr::eval_and_flatten
             at [./crates/polars-expr/src/expressions/apply.rs:117:28](http://127.0.0.1:8888/crates/polars-expr/src/expressions/apply.rs#line=116)
  38: <polars_expr::expressions::apply::ApplyExpr as polars_expr::expressions::PhysicalExpr>::evaluate
             at [./crates/polars-expr/src/expressions/apply.rs:344:16](http://127.0.0.1:8888/crates/polars-expr/src/expressions/apply.rs#line=343)
  39: polars_mem_engine::executors::projection_utils::run_exprs_seq::{{closure}}
             at [./crates/polars-mem-engine/src/executors/projection_utils.rs:250:29](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/projection_utils.rs#line=249)
  40: core::iter::adapters::map::map_try_fold::{{closure}}
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:95:28](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=94)
  41: core::iter::traits::iterator::Iterator::try_fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2370:21](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=2369)
  42: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:121:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs#line=120)
  43: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:191:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs#line=190)
  44: core::iter::traits::iterator::Iterator::try_for_each
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2431:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=2430)
  45: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:174:14](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs#line=173)
  46: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs:25:32](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs#line=24)
  47: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs:34:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs#line=33)
  48: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3436:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs#line=3435)
  49: core::iter::traits::iterator::Iterator::collect
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1971:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=1970)
  50: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/result.rs:1985:51](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/result.rs#line=1984)
  51: core::iter::adapters::try_process
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:160:17](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs#line=159)
  52: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/result.rs:1985:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/result.rs#line=1984)
  53: core::iter::traits::iterator::Iterator::collect
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1971:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs#line=1970)
  54: polars_mem_engine::executors::projection_utils::run_exprs_seq
             at [./crates/polars-mem-engine/src/executors/projection_utils.rs:250:5](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/projection_utils.rs#line=249)
  55: polars_mem_engine::executors::projection_utils::evaluate_physical_expressions
             at [./crates/polars-mem-engine/src/executors/projection_utils.rs:268:28](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/projection_utils.rs#line=267)
  56: polars_mem_engine::executors::projection::ProjectionExec::execute_impl
             at [./crates/polars-mem-engine/src/executors/projection.rs:49:33](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/projection.rs#line=48)
  57: <polars_mem_engine::executors::projection::ProjectionExec as polars_mem_engine::executors::executor::Executor>::execute
             at [./crates/polars-mem-engine/src/executors/projection.rs:100:13](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/projection.rs#line=99)
  58: <polars_mem_engine::executors::executor::SinkExecutor as polars_mem_engine::executors::executor::Executor>::execute
             at [./crates/polars-mem-engine/src/executors/executor.rs:31:18](http://127.0.0.1:8888/crates/polars-mem-engine/src/executors/executor.rs#line=30)
  59: polars_lazy::frame::LazyFrame::collect_with_engine
             at [./crates/polars-lazy/src/frame/mod.rs:811:17](http://127.0.0.1:8888/crates/polars-lazy/src/frame/mod.rs#line=810)
  60: polars_python::lazyframe::general::<impl polars_python::lazyframe::PyLazyFrame>::collect::{{closure}}
             at [./crates/polars-python/src/lazyframe/general.rs:688:17](http://127.0.0.1:8888/crates/polars-python/src/lazyframe/general.rs#line=687)
  61: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs#line=271)
  62: std::panicking::try::do_call
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs:587:40](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs#line=586)
  63: __rust_try
  64: std::panicking::try
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs:550:19](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs#line=549)
  65: std::panic::catch_unwind
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panic.rs:359:14](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panic.rs#line=358)
  66: polars_error::signals::catch_keyboard_interrupt
             at [./crates/polars-error/src/signals.rs:83:15](http://127.0.0.1:8888/crates/polars-error/src/signals.rs#line=82)
  67: <pyo3::marker::Python as polars_python::utils::EnterPolarsExt>::enter_polars::{{closure}}
             at [./crates/polars-python/src/utils.rs:106:41](http://127.0.0.1:8888/crates/polars-python/src/utils.rs#line=105)
  68: pyo3::marker::Python::allow_threads
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/marker.rs:520:9](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/marker.rs#line=519)
  69: <pyo3::marker::Python as polars_python::utils::EnterPolarsExt>::enter_polars
             at [./crates/polars-python/src/utils.rs:106:19](http://127.0.0.1:8888/crates/polars-python/src/utils.rs#line=105)
  70: polars_python::utils::EnterPolarsExt::enter_polars_df
             at [./crates/polars-python/src/utils.rs:82:9](http://127.0.0.1:8888/crates/polars-python/src/utils.rs#line=81)
  71: polars_python::lazyframe::general::<impl polars_python::lazyframe::PyLazyFrame>::collect
             at [./crates/polars-python/src/lazyframe/general.rs:681:9](http://127.0.0.1:8888/crates/polars-python/src/lazyframe/general.rs#line=680)
  72: polars_python::lazyframe::general::<impl polars_python::lazyframe::PyLazyFrame>::__pymethod_collect__
             at [./crates/polars-python/src/lazyframe/general.rs:69:1](http://127.0.0.1:8888/crates/polars-python/src/lazyframe/general.rs#line=68)
  73: pyo3::impl_::trampoline::cfunction_with_keywords::{{closure}}
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs:44:29](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs#line=43)
  74: pyo3::impl_::trampoline::trampoline::{{closure}}
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs:188:54](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs#line=187)
  75: std::panicking::try::do_call
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs:587:40](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs#line=586)
  76: __rust_try
  77: std::panicking::try
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs:550:19](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panicking.rs#line=549)
  78: std::panic::catch_unwind
             at [/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panic.rs:359:14](http://127.0.0.1:8888/nix/store/2ymqkvzwgr1aabg6wlfm92w8zg47v9kb-rust-default-1.87.0-nightly-2025-03-07/lib/rustlib/src/rust/library/std/src/panic.rs#line=358)
  79: pyo3::impl_::trampoline::trampoline
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs:188:9](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs#line=187)
  80: pyo3::impl_::trampoline::cfunction_with_keywords
             at [/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs:44:13](http://127.0.0.1:8888/home/johndoe/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.23.5/src/impl_/trampoline.rs#line=43)
  81: polars_python::lazyframe::general::_::__INVENTORY::trampoline
             at [./crates/polars-python/src/lazyframe/general.rs:69:1](http://127.0.0.1:8888/crates/polars-python/src/lazyframe/general.rs#line=68)
  82: method_vectorcall_VARARGS_KEYWORDS
  83: PyObject_Vectorcall
  84: _PyEval_EvalFrameDefault
  85: _PyEval_Vector
  86: _PyVectorcall_Call
  87: _PyEval_EvalFrameDefault
  88: _PyEval_Vector.constprop.0
  89: PyEval_EvalCode.localalias
  90: builtin_exec
  91: _PyEval_EvalFrameDefault
  92: PyGen_am_send
  93: _PyEval_EvalFrameDefault
  94: PyGen_am_send
  95: _PyEval_EvalFrameDefault
  96: gen_send
  97: _PyEval_EvalFrameDefault
  98: _PyEval_Vector
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

PanicException: from_ascii_radix: radix must lie in the range `[2, 36]` - found 1
```

### Issue description

panic.

### Expected behavior

no panic.

### Installed versions

<details>

```
Replace this line with the output of pl.show_versions(). Leave the backticks in place.
```

</details>

### PR DESCRIPTION
**Pull request by zachlefevre**
fixes #22033

https://github.com/pola-rs/polars/issues/22033

Attempting to parse a number with an invalid base will now produce a ComputeError.

### CODE REVIEW

File: crates/polars-ops/src/chunked_array/strings/namespace.rs [hunk 1]
```diff
@@ -66,12 +66,33 @@ pub trait StringNameSpaceImpl: AsString {
...
+                (None, None) => Err(PolarsError::ComputeError(
+                    "Cannot parse string without a numeric string and base".into(),
+                )),
             }
         };
+
+        let f = |opt_s: Option<&str>, opt_base: Option<u32>| -> Option<i64> {
+            parse(opt_s, opt_base).ok()
+        };
         let out = broadcast_binary_elementwise(ca, base, f);
```
Comment (zachlefevre) [inline crates/polars-ops/src/chunked_array/strings/namespace.rs:96]: I could not figure out how to inline `f`. Rust complains about FnOnce being insufficient...

File: crates/polars-ops/src/chunked_array/strings/namespace.rs [hunk 2]
```diff
@@ -66,12 +66,33 @@ pub trait StringNameSpaceImpl: AsString {
...
-        let f = |opt_s: Option<&str>, opt_base: Option<u32>| -> Option<i64> {
+
+        let parse = |opt_s: Option<&str>, opt_base: Option<u32>| -> PolarsResult<i64> {
             match (opt_s, opt_base) {
-                (Some(s), Some(base)) => <i64 as Num>::from_str_radix(s, base).ok(),
-                _ => None,
+                (Some(s), Some(base)) if (2..=36).contains(&base) => {
+                    match <i64 as Num>::from_str_radix(s, base) {
+                        Ok(t) => Ok(t),
+                        Err(parse_int_error) => Err(PolarsError::ComputeError(
```
Comment (zachlefevre) [inline crates/polars-ops/src/chunked_array/strings/namespace.rs:75]: In scala this would be `either.left.map(...)` but I don't know how to do that in Rust.

File: crates/polars-ops/src/chunked_array/strings/namespace.rs [hunk 3]
```diff
@@ -83,22 +104,21 @@ pub trait StringNameSpaceImpl: AsString {
...
-                        .and_then(|s| <i64 as Num>::from_str_radix(s, base).err())
+                        .and_then(|s| parse(Some(s), base).err())
                         .map_or_else(
                             || unreachable!("failed to extract ParseIntError"),
                             |e| format!("{}", e),
                         )
                 },
                 _ => {
-                    let base_filures = base.filter(&failure_mask)?;
+                    let base_failures = base.filter(&failure_mask)?;
```
Comment (zachlefevre) [inline crates/polars-ops/src/chunked_array/strings/namespace.rs:117]: simple typo

**Comment by zachlefevre** [comment]
@coastalwhite The change you've made would mean using an invalid base does _not_ return None when strict=False. Is that what y'all want?

**Comment by coastalwhite** [comment]
> @coastalwhite The change you've made would mean using an invalid base does _not_ return None when strict=False. Is that what y'all want?

I think it is. Let me discuss tomorrow with others on the team and then we'll be able to merge this.

**Comment by zachlefevre** [comment]
> > @coastalwhite The change you've made would mean using an invalid base does _not_ return None when strict=False. Is that what y'all want?
> 
> I think it is. Let me discuss tomorrow with others on the team and then we'll be able to merge this.

Radical, thanks!

**Review by coastalwhite — APPROVED** [review]
