### PR TITLE
fix(rust,python): Fix join validation

### LINKED ISSUE #10225: Join validate false negative
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

foo = pl.DataFrame({"id":[1,2,3,4]})
bar = pl.DataFrame({"id":[2,2,3,4]})
foo.join(bar, how="left", on="id", validate="1:m")
```

### Issue description

According to the documentation the "1:m" option for the `validate` parameter does the following

> check if join keys are unique in left dataset

The values in `foo` are obviously unique, so I would expect this code to work but instead it raises `ComputeError: the join keys did not fulfil 1:m validation`.

### Expected behavior

```python
import polars as pl

foo = pl.DataFrame({"id":[1,2,3,4]})
bar = pl.DataFrame({"id":[2,2,3,4]})
foo.join(bar, how="left", on="id")
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            Linux-5.15.0-52-generic-x86_64-with-glibc2.31
Python:              3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.23.5
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            2.0.3
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by CanglongCl**
Fixes #10225

Bug: both lhs' and rhs' checks are applied onto rhs, without checking lhs. 

Therefore the following examples are unexpected. 

```python
foo = pl.DataFrame({"id": [1, 2, 3, 4, 5, 6, 7, 8, 1]}) 
bar = pl.DataFrame({"id": [1, 2, 3, 4, 5, 6, 7, 8, 9]})
# Should fail because there are 2 '1' in left, but join succeeded. 
# Unique check on left was not applied. 
foo.join(bar, how="left", on="id", validate="1:1") 
``` 

```python
foo = pl.DataFrame({"id": [1, 2, 3, 4, 5, 6, 7, 8, 1]}) 
bar = pl.DataFrame({"id": [1, 2, 3, 4, 5, 6, 7, 8, 9]})
# Should fail because there are 2 '1' in left, but join succeeded. 
# Unique check on left was not applied. 
foo.join(bar, how="left", on="id", validate="1:m") 
```

```python
foo = pl.DataFrame({"id": [1, 2, 3, 4, 5, 6, 7, 8, 9]}) 
bar = pl.DataFrame({"id": [1, 2, 3, 4, 5, 6, 7, 8, 1]})
# Should succeed because there are 2 '1' in right, but join fail. 
# That's because unique check on right was applied on right
foo.join(bar, how="left", on="id", validate="1:m") 
```

Here are the bug codes: 

In the codes below, we should valid the left because left is the `probe`. However, in `validate_probe`, we valid the right. 

https://github.com/pola-rs/polars/blob/22a501d4702fcb127aa2b0fe36a140d10431279f/crates/polars-core/src/frame/hash_join/single_keys_dispatch.rs#L8-L17

In the codes below, we should valid the right because right is the `build`. However, in `validate_build`, we apply the validation of left to right. 

https://github.com/pola-rs/polars/blob/22a501d4702fcb127aa2b0fe36a140d10431279f/crates/polars-core/src/frame/hash_join/single_keys_left.rs#L101-L124

This is my first Pull Request on a large project. If anything is not suitable, I will fix that. ^^

### CODE REVIEW

**Comment by CanglongCl** [comment]
@stinodego

**Comment by stinodego** [comment]
Thanks @CanglongCl

I will have to look at the Rust code more closely, but I can already mention one thing: I would really like to see the test cases in Python rather than in Rust. Anything we can test in Python, we test there. Join validation can definitely be tested in Python.

You already have test cases in the PR description and in your Rust code, could you add these to the Python side? 
Tests could be added to `py-polars/tests/unit/operations/test_join.py`.

**Comment by CanglongCl** [comment]
> Thanks @CanglongCl
> 
> I will have to look at the Rust code more closely, but I can already mention one thing: I would really like to see the test cases in Python rather than in Rust. Anything we can test in Python, we test there. Join validation can definitely be tested in Python.
> 
> You already have test cases in the PR description and in your Rust code, could you add these to the Python side? Tests could be added to `py-polars/tests/unit/operations/test_join.py`.

Sure. I will add some python side tests.

File: crates/polars-core/src/frame/hash_join/single_keys.rs [hunk 1]
```diff
@@ -20,32 +20,26 @@ where
...
 
-                    let mut cnt = 0;
-                    keys.iter().for_each(|k| {
-                        let idx = cnt + offset;
-                        cnt += 1;
-
-                        if this_partition(k.as_u64(), partition_no, n_partitions) {
-                            let entry = hash_tbl.entry(*k);
+                keys.iter()
+                    .flat_map(|array| array.as_ref().iter())
```
Comment (ritchie46) [inline crates/polars-core/src/frame/hash_join/single_keys.rs:25]: Can you revert these changes. Flatmap is slower than the code we have as it has in indirection the double join doesn't have. 

I rather have you don't change code that is related to performance of joins in a PR that fixes the join validation.

Comment (CanglongCl) [reply crates/polars-core/src/frame/hash_join/single_keys.rs]: Reverted. 

However, I wonder why using `flat_map` is slower. Any suggestions?

Comment (ritchie46) [reply crates/polars-core/src/frame/hash_join/single_keys.rs]: Every iteration you do a loop over the nested iterators: https://doc.rust-lang.org/src/core/iter/adapters/flatten.rs.html#476

File: crates/polars-core/src/frame/hash_join/args.rs [hunk 2]
```diff
@@ -131,40 +131,62 @@ impl JoinValidation {
         Ok(())
     }
 
-    pub(super) fn validate_probe(
+    pub(super) fn validate_probe<'a, F, I, T>(
```
Comment (ritchie46) [inline crates/polars-core/src/frame/hash_join/args.rs:134]: I am not super happy with the amount of code this generates, as this will be compiled for every `T`. Was `s_unique() == s.len()` wrong?

Comment (CanglongCl) [reply crates/polars-core/src/frame/hash_join/args.rs:134]: > I am not super happy with the amount of code this generates, as this will be compiled for every `T`. Was `s_unique() == s.len()` wrong?

It not wrong, I will revert it. 

The reason I change this is that the this mod checked and swapped left and right multiple times, which makes it really confusing. But after looking into this, I should not change this function.

File: crates/polars/tests/it/core/joins.rs [hunk 3]
```diff
@@ -614,3 +614,503 @@ fn test_4_threads_bit_offset() -> PolarsResult<()> {
     assert_eq!(out.shape(), (1, 2));
     Ok(())
 }
+
```
Comment (ritchie46) [inline crates/polars/tests/it/core/joins.rs:617]: Can you remove those tests? We want to do as much tests in python as possible as our CI is slow enough as it is.

**Review by ritchie46 — COMMENTED** [review]
Looks great. Only a question about the tests in python and then it is good to go!

**Review by ritchie46 — APPROVED** [review]
Thanks a lot @CanglongCl :raised_hands:
