### PR TITLE
fix: Fix dtype for `slice` on `Literal` in agg context

### LINKED ISSUE #23999: Planner schema mismatch for `slice` in aggregation context
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

q = (
    pl.DataFrame({"idx": [1, 2, 3]})
    .lazy()
    .group_by(True)
    .agg(
        x=pl.lit(1),
        s=pl.lit(1).slice(0, 2),
    )
)

print(q.collect_schema())
print(q.collect().schema)
```

### Log output

```shell
Schema({'literal': Boolean, 'x': Int32, 's': List(Int32)})
Schema({'literal': Boolean, 'x': Int32, 's': Int32})
```

### Issue description

Schema's do not match when `slice` is used.

### Expected behavior

Schema's should match in all cases.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.32.0
Index type:          UInt32
Platform:            Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
Python:              3.13.5 (main, Jul 18 2025, 09:47:32) [GCC 13.3.0]
LTS CPU:             False
```

</details>

### LINKED ISSUE #24102: Planner schema mismatch for `head` on literal in agg context
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame(
    {
        "g": [10, 10, 10, 20, 20, 30],
        "b": [1, 1, 1, 1, 1, 1],
    }
)

lit = pl.lit(7)
idx = pl.col("b").first()

q = df.lazy().group_by("g").agg(lit.head(idx))

print(q.collect_schema())
print(q.collect().schema)

assert q.collect_schema() == q.collect().schema

```

### Log output

```shell
Schema({'g': Int64, 'literal': List(Int32)})
Schema({'g': Int64, 'literal': Int32})
```

### Issue description

Schema's don't match

### Expected behavior

Schema's should match

### Installed versions

<details>

```
--------Version info---------
Polars:              1.32.3
Index type:          UInt32
Platform:            Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
Python:              3.13.5 (main, Jul 18 2025, 09:47:32) [GCC 13.3.0]
LTS CPU:             False
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #23999
fixes #24102

Note (!), this PR changes the output dtype of the engine when `slice` is called on a `Literal` value, since `slice` does not meet the `is_scalar` criteria.

Overview of changes:
- Do not drop `Slice` on Literal in the optimizer.
- Triggerr aggregation for `LiteralScalar` in `slice.rs`.
- Adjust groups logic in `aggregated()`, from (*)
- Fix older test.
- Parametric type tests for `slice`, `gather`, `get`, `head` and `tail`. 

Builds upon: https://github.com/pola-rs/polars/pull/24078 (*)

Note that `slice` on an aggregated scalar value will raise per current behavior, but imo this could and should succeed with at most some minor changes.

More optimizations are possible.

*edit:
- Fixed regression in `sortby`
- clippy change

ping @coastalwhite

### CODE REVIEW

File: crates/polars-expr/src/expressions/slice.rs [hunk 1]
```diff
@@ -118,14 +118,22 @@ impl PhysicalExpr for SliceExpr {
...
         use AggState::*;
         let groups = match (&ac_offset.state, &ac_length.state) {
             (LiteralScalar(offset), LiteralScalar(length)) => {
                 let (offset, length) = extract_args(offset, length, &self.expr)?;
 
                 if let LiteralScalar(s) = ac.agg_state() {
                     let s1 = s.slice(offset, length);
-                    ac.with_literal(s1);
+                    let s1 = s1.implode()?;
+                    ac.with_literal(s1.into_column());
```
Comment (coastalwhite) [inline crates/polars-expr/src/expressions/slice.rs]: This seems weird to me. Why are we not aggregating here? Does this not create a scalar list literal AggregationContext?

File: py-polars/tests/unit/operations/test_slice.py [hunk 2]
```diff
@@ -368,3 +368,142 @@ def test_slice_slice_pushdown() -> None:
                         .slice(outer_offset, outer_len)
                         .collect(),
                     )
+
```
Comment (coastalwhite) [inline py-polars/tests/unit/operations/test_slice.py:371]: Nice!

File: crates/polars-expr/src/expressions/slice.rs (hunk 1 above)
Comment (kdn36) [reply crates/polars-expr/src/expressions/slice.rs]: Ack, new commit has it changed to `aggregated()`. Note, this was a literal prior, presumably for performance reasons, hence the `implode` workaround.

**Comment by kdn36** [comment]
Updated towards consistent handling of `LiteralScalar` and use of `aggregated`.

To investigate: can we drop the first `groups` call when calling `aggregated` on a `LiteralScalar`.
