### PR TITLE
fix: Clear index cache on stacked `df.filter` expressions

### LINKED ISSUE #24806: Using `.filter` with a window function multiple times fails
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from datetime import date, timedelta

import polars as pl

df = pl.DataFrame(
    {
        "date": [date(2001, 1, 1) + timedelta(days=i) for i in range(64)],
        "key": [1] * 32 + [2] * 32,
    }
).lazy()

condition = pl.col("date").is_between(date(2001, 1, 2), date(2001, 1, 30)).over("key")
df = df.filter(condition).filter(condition).collect()
```

### Log output

```shell
polars.exceptions.ShapeError: filter's length: 64 differs from that of the series: 29
```

### Issue description

This shouldn't fail, some weirdness with stacking filters going on here.

### Expected behavior

Successful collection

### Installed versions

<details>

```
--------Version info---------
Polars:              1.34.0
Index type:          UInt32
Platform:            Windows-10-10.0.26100-SP0
Python:              3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Runtime:             rt32

----Optional dependencies----
Azure CLI            'az' is not recognized as an internal or external command,
operable program or batch file.
<not installed>
adbc_driver_manager  <not installed>
altair               5.5.0
azure.identity       <not installed>
boto3                1.40.47
cloudpickle          3.1.1
connectorx           0.3.3
deltalake            <not installed>
fastexcel            0.14.0
fsspec               2025.9.0
gevent               23.9.1
google.auth          2.29.0
numpy                2.0.2
openpyxl             3.0.10
pandas               2.3.3
polars_cloud         <not installed>
pyarrow              20.0.0
pydantic             2.11.9
pyiceberg            <not installed>
sqlalchemy           2.0.43
torch                2.5.1+cu118
xlsx2csv             0.8.4
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #24806

### CODE REVIEW

File: crates/polars-expr/src/state/execution_state.rs [hunk 1]
```diff
@@ -25,8 +25,10 @@ impl WindowCache {
     pub(crate) fn clear(&self) {
         let mut g = self.groups.write().unwrap();
         g.clear();
-        let mut g = self.join_tuples.write().unwrap();
-        g.clear();
+        let mut t = self.join_tuples.write().unwrap();
+        t.clear();
+        let mut i = self.map_idx.write().unwrap();
```
Comment (nameexhaustion) [inline crates/polars-expr/src/state/execution_state.rs]: Could we use destructuring syntax here? That gives us a safety net in case new fields are added in the future.

Comment (kdn36) [reply crates/polars-expr/src/state/execution_state.rs]: Good point, makes sense. Updated - good?
