### PR TITLE
fix(rust): Validate column names in `unique()` for empty DataFrames

### LINKED ISSUE #20209: `DataFrame.unique()` should raise if any subset column doesn't exist on empty frame.
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame(
    {
        "ID": [],
        "Name": []
    },
    schema={"ID": pl.Int64, "Name": pl.String}
)
df = df.unique(subset="id")
print(df)
# shape: (0, 2)
# ┌──────┬──────┐
# │ ID   ┆ Name │
# │ ---  ┆ ---  │
# │ null ┆ null │
# ╞══════╪══════╡
# └──────┴──────┘

df = pl.DataFrame(
    {
        "ID": [1, 2, 1, 2],
        "Name": ["foo", "bar", "baz", "baa"]
    },
    schema={"ID": pl.Int64, "Name": pl.String}
)
df = df.unique(subset="id")
# raises `polars.exceptions.ColumnNotFoundError: "id" not found`
```

### Log output

_No response_

### Issue description

Using `.unique()` on an **empty** dataframe with a subset column which doesn't exist in the dataframe doesn't raise an error.

This is inconsistent with other methods, i.e. `.select()`

### Expected behavior

`.unique()` should raise an error if any subset column is not in the dataframe.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.16.0
Index type:          UInt32
Platform:            macOS-15.0.1-arm64-arm-64bit
Python:              3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 15.0.0 (clang-1500.3.9.4)]
LTS CPU:             True

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.21.0
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.3
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by Biswas-N**
This PR addresses an issue where the `unique() function` in Polars does not raise a `ColumnNotFoundError` when called on an empty DataFrame with an unknown subset of column names. The changes ensure that column names in the subset are validated before proceeding, thereby raising the appropriate exception.

### Changes Made:
1. **Rust**:
   - Added validation logic in `UniqueExec` executor to check the subset of column names provided exists in an empty DataFrame.

2. **Python Tests**:
   - Introduced a new test method, `test_unique_with_bad_subset` in `test_unique.py` to handle scenarios where `Subset column name(s) do not exist`.
   - Ensured invalid subset(s) raise a `ColumnNotFoundError` with appropriate message.

### Linked Issue:
Closes #20209 

### Checklist:
- [x] Changes rebased against the latest `main` branch.
- [x] All new and existing tests pass.
- [x] Verified using `pytest` for Python tests.
- [x] Code adheres to the repository's contribution guidelines.

### CODE REVIEW

**Comment by ritchie46** [comment]
These error should be raised during conversion to IR, not at the implementation level.

**Comment by Biswas-N** [comment]
@ritchie46 thanks for having a look. I am new to contributing to `pola-rs`, could you help me by pointing at some code that raises issues during `conversion to IR`. It could help me understand `pola-rs` way of doing things.

File: crates/polars-plan/src/plans/conversion/dsl_to_ir.rs [hunk 1]
```diff
@@ -664,8 +664,20 @@ pub fn to_alp_impl(lp: DslPlan, ctxt: &mut DslConversionContext) -> PolarsResult
 
             let subset = options
                 .subset
-                .map(|s| expand_selectors(s, input_schema.as_ref(), &[]))
+                .map(|s| {
+                    let cols = expand_selectors(s, input_schema.as_ref(), &[])?;
+
+                    // Checking if subset columns exist in the dataframe
+                    cols.iter()
```
Comment (ritchie46) [inline crates/polars-plan/src/plans/conversion/dsl_to_ir.rs:671]: A bit nitpicky, but I think this can be written a little bit less verbose.

```rust
for c in &cols {
   let _ = input_schema.try_get(name)?
}

```

Comment (Biswas-N) [reply crates/polars-plan/src/plans/conversion/dsl_to_ir.rs:671]: Haha no problem. My understanding was, if the subset column(s) does not exist we need to raise `polars.exceptions.ColumnNotFoundError`. This approach would raise `polars.exceptions.SchemaFieldNotFoundError`. On a high level look both seem appropriate to me, but if `SchemaFieldNotFoundError` is correct, I can update this piece to less verbose like you suggested.

Something like this:
```rust
let cols = expand_selectors(s, input_schema.as_ref(), &[])?;

// Checking if subset columns exist in the dataframe
for col in cols.iter() {
    let _ = input_schema.try_get(col)?;
}

Ok::<_, PolarsError>(cols)
```

Comment (ritchie46) [reply crates/polars-plan/src/plans/conversion/dsl_to_ir.rs:684]: We can `map_err`

**Review by ritchie46 — APPROVED** [review]
Thanks!
