### PR TITLE
fix(rust, python): Fix divided by zero error when read empty csv in streaming mode

### LINKED ISSUE #10818: Divided by zero error when read an empty csv in streaming mode
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

When I try to scan an `empty` csv file in streaming mode with `raise_if_empty=False` .
```python
df = pl.scan_csv("./empty.csv", raise_if_empty=False).collect(streaming=True)
```

Got the following error:

```
pyo3_runtime.PanicException: attempt to divide by zero
```

### Issue description

It works in non streaming mode.

### Expected behavior

It should get the same result as `collect(streaming=False)`.

```
shape: (0, 0)
┌┐
╞╡
└┘
```

### Installed versions

<details>

main branch.

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This fixes #10818.

### CODE REVIEW

File: crates/polars-pipe/src/pipeline/mod.rs [hunk 1]
```diff
@@ -28,6 +28,8 @@ pub(crate) fn determine_chunk_size(n_cols: usize, n_threads: usize) -> PolarsRes
         val.parse().map_err(
             |_| polars_err!(ComputeError: "could not parse 'POLARS_STREAMING_CHUNK_SIZE' env var"),
         )
+    } else if n_cols == 0 {
+        Ok(1)
```
Comment (reswqa) [inline crates/polars-pipe/src/pipeline/mod.rs:32]: I'm a bit unsure which `chunk_size` are suitable here, not choose `0` is to avoid introducing new division by 0 exception.

File: crates/polars-pipe/src/pipeline/mod.rs [hunk 2]
```diff
@@ -28,6 +28,8 @@ pub(crate) fn determine_chunk_size(n_cols: usize, n_threads: usize) -> PolarsRes
...
     } else {
         let thread_factor = std::cmp::max(12 / n_threads, 1);
         Ok(std::cmp::max(50_000 / n_cols * thread_factor, 1000))
```
Comment (orlp) [inline crates/polars-pipe/src/pipeline/mod.rs:35]: Instead of special-casing `n_cols == 0` could you instead just change this line to

    Ok(std::cmp::max(50_000 / n_cols.max(1) * thread_factor, 1000))

?

**Review by orlp — CHANGES_REQUESTED** [review]

File: crates/polars-pipe/src/pipeline/mod.rs (hunk 2 above)
Comment (reswqa) [reply crates/polars-pipe/src/pipeline/mod.rs]: You are right, updated.

**Review by orlp — APPROVED** [review]
