### PR TITLE
fix: Join revmaps for categoricals in `merge_sorted`

### LINKED ISSUE #21952: merge_sorted on categorical column panics in revmap when printing result
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.string_cache.enable_string_cache()
df1 = pl.DataFrame({
    "a": ["a", "b", "c"],
}).cast(pl.Categorical(ordering="lexical"))
df2 = pl.DataFrame({
    "a": ["a", "b", "d"],
}).cast(pl.Categorical(ordering="lexical"))

df = df1.merge_sorted(df2, key="a")
print(df) 
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-core/src/chunked_array/logical/categorical/revmap.rs:99:42:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/mag/repos/my_repo/testit.py", line 12, in <module>
    print(df)
  File "/home/mag/miniconda3/envs/myenv/lib/python3.12/site-packages/polars/dataframe/frame.py", line 1188, in __str__
    return self._df.as_str()
           ^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

### Issue description

Likely introduced recently, after 0.45.1 (Rust). 

### Expected behavior

```
shape: (6, 1)
┌─────┐
│ a   │
│ --- │
│ cat │
╞═════╡
│ a   │
│ a   │
│ b   │
│ b   │
│ c   │
│ d   │
└─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.26.0
Index type:          UInt32
Platform:            Linux-6.11.0-19-generic-x86_64-with-glibc2.39
Python:              3.12.8 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 16:31:09) [GCC 11.2.0]
LTS CPU:             False

----Optional dependencies----
Azure CLI            2.70.0
adbc_driver_manager  <not installed>
altair               5.5.0
azure.identity       1.21.0
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          2.38.0
great_tables         <not installed>
matplotlib           <not installed>
numpy                1.26.4
openpyxl             3.1.5
pandas               2.2.3
polars_cloud         <not installed>
pyarrow              16.1.0
pydantic             2.10.5
pyiceberg            <not installed>
sqlalchemy           2.0.39
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
None
```

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Closes #21952

### CODE REVIEW

**Comment by magbak** [comment]
Thank you for the quick turnaround. I have tried the latest commit in this pull request, but I am still having some issues that I am trying to reproduce. When trying to reproduce this issue I found that the new Python test may not be covering the original problem, which arises only on print, and not on the assert. 

Doing `result.cast(pl.String)` will also cause the panic. 

See code below: 

```python
from polars.testing import assert_frame_equal
import polars as pl

with pl.StringCache():
    df1 = pl.DataFrame(
        {"a": pl.Series(["a", "b", None], dtype=pl.Categorical(ordering="lexical"))}
    )
    df2 = pl.DataFrame(
        {"a": pl.Series(["a", "c", "d"], dtype=pl.Categorical(ordering="lexical"))}
    )
    expected = pl.DataFrame(
        {
            "a": pl.Series(
                ["a", "a", "b", None, "c", "d"],
                dtype=pl.Categorical(ordering="lexical"),
            )
        }
    )
result = df1.merge_sorted(df2, key="a")
assert_frame_equal(result, expected) #Goes through with latest Python Polars release. 
print(result) #Crashes here with latest Python Polars release! 
```

**Comment by mcrumiller** [comment]
Thanks @magbak, let me look into it.

**Comment by mcrumiller** [comment]
I see the issue.

File: crates/polars-core/src/chunked_array/logical/categorical/merge.rs [hunk 1]
```diff
@@ -201,7 +201,7 @@ impl CategoricalMergeOperation for DoNothing {
 }
 
 // Make the right categorical compatible with the left
-pub fn make_categoricals_compatible(
+pub fn make_rhs_categoricals_compatible(
```
Comment (mcrumiller) [inline crates/polars-core/src/chunked_array/logical/categorical/merge.rs:204]: @ritchie46 I renamed these functions because this tripped me up initially. Only the RHS is made compatible with the left. If the RHS has categories that don't exist in the LHS, the left series will not include these categories in its revmap.

**Comment by mcrumiller** [comment]
@magbak should be fixed now. I added a test ensuring the string output matches as well.

**Comment by magbak** [comment]
> @magbak should be fixed now. I added a test ensuring the string output matches as well.
Great work getting to the bottom of this! Thank you!

**Review by ritchie46 — APPROVED** [review]
