### PR TITLE
fix(rust): Raise error on out-of-range dates in temporal operations

### LINKED ISSUE #11991: .dt.year may silently throw wrong results
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example
```python
In [79]: n = -96_465_658; print(pl.Series([n]).cast(pl.Date()).dt.year())
shape: (1,)
Series: '' [i32]
[
        -262144
]

In [80]: n = -96_465_659; print(pl.Series([n]).cast(pl.Date()).dt.year())
shape: (1,)
Series: '' [i32]
[
        -96465659
]
```

### Log output

_No response_

### Issue description

Casting `-96_465_658` to Date, `.dt.year()` is correct

But for `-96_465_659`, it just returns the input

### Expected behavior

Something like an "out-of-range date" error

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.10
Index type:          UInt32
Platform:            Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           0.9.0
fsspec:              2023.6.0
gevent:              <not installed>
matplotlib:          3.7.1
numpy:               1.25.1
openpyxl:            <not installed>
pandas:              2.1.1
pyarrow:             12.0.1
pydantic:            2.0.2
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.20
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by wtn**
Fixes #11991.

Calling `.dt.year()` or other temporal operations on out-of-range dates silently returned the original integer value instead of raising an error.

### Cause

The `to_temporal_unit!` and `to_calendar_value!` macros used `unary()` which processes all values including nulls. The `.unwrap_or()` fallback (from #10114) correctly prevented panics on null values backed by out-of-range integers, but also incorrectly returned the original value for actually out-of-range non-null dates.

### Fix

Follow the pattern from PR #15420: replace `unary()` with `from_trusted_len_iter()` and `.iter().map()`. This handles both cases:
- Null values with out-of-range backing data remain null (no panic)
- Non-null out-of-range values panic with "out-of-range date" error

### CODE REVIEW

File: crates/polars/tests/it/time/date.rs [hunk 1]
```diff
@@ -1,44 +1,49 @@
...
+        .into_date()
+        .into_series();
+
+    let year_with_null = s_with_null.year().unwrap();
+    assert_eq!(year_with_null.get(0), Some(2021));
+    assert_eq!(year_with_null.get(1), None);
+}
 
 #[test]
-fn test_datetime_parse_overflow_7631() {
```
Comment (orlp) [inline crates/polars/tests/it/time/date.rs:4]: Why did you delete this test?

Comment (wtn) [reply crates/polars/tests/it/time/date.rs:4]: Sorry, that was not intended.

The test is restored in 0aae127fe33f16c506da02d3c1831f955a8755a8.

**Comment by orlp** [comment]
Thanks!
