### PR TITLE
fix(rust, python) validate tz in with_time_zone

### LINKED ISSUE #6416: Passing nonsense timezone to `with_time_zone` doesn't error, just sets elements to `'invalid timezone'`
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`.dt.with_time_zone('foo')` doesn't raise, it just sets everything to `'invalid timezone'`

### Reproducible example

```python
In [3]: pl.Series(['2020-01-01']*3).str.strptime(pl.Datetime).dt.with_time_zone('foo')
Out[3]:
shape: (3,)
Series: '' [datetime[μs, foo]]
[
        invalid timezone
        invalid timezone
        invalid timezone
]
```

### Expected behavior

I think it should probably raise?

### Installed versions

<details>

```
---Version info---
Polars: 0.15.16
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.11.1 (main, Dec  7 2022, 01:11:34) [GCC 11.3.0]
---Optional dependencies---
pyarrow: 10.0.1
pandas: 1.5.3
numpy: 1.24.1
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #6416 

I'm quite new to Rust, so apologies if this isn't the proper way to do it - constructive feedback would be appreciated, but feel free to close if it's too far off, no hard feelings 💚

### CODE REVIEW

File: polars/polars-lazy/polars-plan/src/dsl/dt.rs [hunk 1]
```diff
@@ -71,6 +72,17 @@ impl DateLikeNameSpace {
...
+                    match &tz {
+                        Some(tz) => match parse_offset(tz) {
+                            Ok(_) => (),
+                            Err(_) => match tz.parse::<chrono_tz::Tz>() {
+                                Ok(_) => (),
+                                Err(_) => panic!("invalid timezone!"),
+                            },
+                        },
+                        None => (),
+                    };
```
Comment (MarcoGorelli) [inline polars/polars-lazy/polars-plan/src/dsl/dt.rs:84]: maybe this should be its own function? it may be useful in other places

File: polars/polars-lazy/polars-plan/Cargo.toml [hunk 2]
```diff
@@ -10,6 +10,7 @@ description = "Lazy query engine for the Polars DataFrame library"
 
 [dependencies]
 ahash.workspace = true
+chrono-tz = "0.8.1"
```
Comment (ritchie46) [inline polars/polars-lazy/polars-plan/Cargo.toml:13]: This should be an optional dependency and only activate when the feature `"timezones"` is activated.

See the `Cargo.toml` in `polars-time` for an example of this.

File: polars/polars-lazy/polars-plan/src/dsl/dt.rs [hunk 3]
```diff
@@ -71,6 +82,10 @@ impl DateLikeNameSpace {
             move |s| match s.dtype() {
                 DataType::Datetime(_, _) => {
                     let mut ca = s.datetime().unwrap().clone();
+                    match &tz {
+                        None => (),
+                        Some(tz) => validate_time_zone(tz.to_string()),
+                    };
                     ca.set_time_zone(tz.clone());
```
Comment (ritchie46) [inline polars/polars-lazy/polars-plan/src/dsl/dt.rs:89]: I don't think the validation should be here. But rather in the most inner `set_time_zone`. This will ensure the validation is done everywhere.

File: polars/polars-core/src/chunked_array/temporal/datetime.rs [hunk 4]
```diff
@@ -11,6 +11,19 @@ use super::*;
...
 
+#[cfg(feature = "timezones")]
+fn validate_time_zone(tz: TimeZone) {
+    use arrow::temporal_conversions::parse_offset;
+    use chrono_tz::Tz;
+    match parse_offset(&tz) {
+        Ok(_) => (),
+        Err(_) => match tz.parse::<Tz>() {
+            Ok(_) => (),
+            Err(_) => panic!("time zone {tz} not supported"),
```
Comment (ritchie46) [inline polars/polars-core/src/chunked_array/temporal/datetime.rs:22]: We should return an error here and every function that calls this.

The return type will be `PolarsResult<()>` and end the function with `Ok(())`

File: polars/polars-core/src/chunked_array/temporal/datetime.rs [hunk 5]
```diff
@@ -210,6 +223,11 @@ impl DatetimeChunked {
 
     /// Change the underlying [`TimeZone`]. This does not modify the data.
     pub fn set_time_zone(&mut self, tz: Option<TimeZone>) {
```
Comment (ritchie46) [inline polars/polars-core/src/chunked_array/temporal/datetime.rs:225]: So this will return a `PolarsResult<()>`.

**Review by ritchie46 — COMMENTED** [review]
Almost there. I have left on comment about the panic. You will need to make that return an error and then follow the rust compilation errors until it is happy. :)

**Comment by MarcoGorelli** [comment]
Thanks @ritchie46 for your review! I tried doing as you said

**Comment by ritchie46** [comment]
Looks great @MarcoGorelli. Thanks a lot!
