### PR TITLE
fix: Prevent invalid type casts in `replace_strict()`

### LINKED ISSUE #26329: `replace_strict()` replaces `{"x": [None]}` while the mapping is completely different
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"x": [{"x": [None]}]})
df.with_columns(pl.col("x").replace_strict({"a": 1}))
```
```
shape: (1, 1)
┌─────┐
│ x   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
```

### Log output

```shell
/
```

### Issue description

`{"x": [None]}` is replaced by `1` while the mapping is `{"a": 1}`.

Ping @cmdlineluser since you found it on Discord.

### Expected behavior

An error I suppose.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.37.1
Index type:          UInt32
Platform:            Linux-6.14.0-36-generic-x86_64-with-glibc2.39
Python:              3.12.3 (main, Jan  8 2026, 11:30:50) [GCC 13.3.0]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.1.2
openpyxl             <not installed>
pandas               2.2.3
polars_cloud         <not installed>
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by Kevin-Patyk**
Resolves https://github.com/pola-rs/polars/issues/26329.

In accordance with the AI policy, Claude Sonnet 4.5 was used to help me go through the code base and refactor the code after I wrote it.

### CODE REVIEW

File: crates/polars-ops/src/series/ops/replace.rs [hunk 1]
```diff
@@ -166,7 +166,16 @@ pub fn replace_strict(
     }
     validate_old(&old)?;
 
+    if !matches!(old.dtype().can_cast_to(s.dtype()), Some(true)) {
```
Comment (orlp) [inline crates/polars-ops/src/series/ops/replace.rs]: This is a very strange way to write `old.dtype().can_cast_to(s.dtype()) != Some(true)`.

Anyway, can you explain how/why `old.dtype()can_cast_to(s.dtype())` can return something other than `Some(true)` while `old.strict_cast(s.dtype())` silently allows the conversion?

**Review by orlp — CHANGES_REQUESTED** [review]

File: crates/polars-ops/src/series/ops/replace.rs (hunk 1 above)
Comment (Kevin-Patyk) [reply crates/polars-ops/src/series/ops/replace.rs]: @orlp

For the first point, I am still learning Rust patterns and I wasn't aware you could do direct comparisons to something wrapped in `Some()`, like `!= Some(true)`. Thanks for pointing this out. I will make the change.

Below is some more in-depth reasoning about my decision and the answer to your questions. As a note, this is a high-level overview of my thinking and I won't say I understand every single line of code I looked through 100% fully.

-----

So, `replace_strict()` does some validations (length and empty checks) along with exploding the `ListChunked` into a Series for `old` and `new`, which are the value we are looking to replace and the replacement, respectively. After this is completed, the cast, using `old.strict_cast(s.dtype())?;` is performed prior to the comparison because the data types need to match before we can compare `old` values in the existing Series `s` to see if they are present. My suspicion that this was the offending line stems from the fact that, in the PR example, the String `"a"` is somehow being coerced (incorrectly) into a Struct and making the replacement. 

Next, I looked into `strict_cast()` specifically. It turns out `strict_cast()` just delegates to `cast_with_options(..., CastOptions::Strict)`, so I needed to look one level deeper. In `cast_with_options()`, none of the patterns match String to Struct conversion, so `do_clone` is `false` and we need to need to perform a cast. For the helper function `cast_dtype()`, it just returns our Struct unchanged since it doesn't need any transformation. After some null checking, the `CastOptions` are changed from `Strict` to `NonStrict` to improve error messages (as the comment says). Finally, we do the cast of `slf`, which is "a" (String), to a Struct with `NonStrict` using `.cast()`, which produces `out`. Then, since, in this case, the `options.is_strict()` flag is `true`, it runs `handle_casting_failures()`. 

In `handle_casting_failures()`, String to Struct is not a deprecated cast, so we go to `find_validity_mismatch()`. In `find_validity_mismatch()`, the validation does not cover situations when the array types are fundamentally different or nonsensical (like String to Struct). Thus, none of the blocks execute and the corrupted conversion is accepted and not prevented. 

Based on the above, I came to the conclusion that the solution should be to check if the cast should be validated before even being executed, meaning: Can `old.dtype()` be successfully cast to `s.dtype()`? That way, we can get a fast fail and don't have to go through all the `strict_cast()` code. After some searching of the Polars Rust API, I found `DataType::can_cast_to()`. Since String to Struct does not match any of the cases there, we hit the catch all `_ => return None` and conclude that the we are unsure about the cast (the comment above says it is because we are being conservative). By rejecting casts that we are unsure of (`None`) or that are explicitly incompatible (`Some(false)`), we prevent any potentially problematic casts from happening before they are even tried.

Lastly, I agree that the String to Struct conversion makes no sense, unless you  convert the String to a field containing an empty value, which I don't is logical. Thus, better to prevent it all together.

**Review by orlp — APPROVED** [review]
