### PR TITLE
fix(rust,python): ensure trailing quote is written for temporal data when CSV `quote_style` is non-numeric

### LINKED ISSUE #11324: write_csv does not properly quote datetime columns
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import datetime

data = [
    pl.Series("col1", [1, 2], dtype=pl.Int64),
    pl.Series("col2", [datetime.now(), datetime.now()]),
    pl.Series("col3", ["Hi", "Hey"]),
]
df = pl.DataFrame(data)

print(df.write_csv(has_header=True, separator=';', quote='"', line_terminator = '\r\n', quote_style = 'non_numeric'))
```

### Log output

```shell
"col1";"col2";"col3"
1;"2023-09-26T11:22:29.136304;"Hi"
2;"2023-09-26T11:22:29.136304;"Hey"
```

### Issue description

Closing quote for the second column is missing.
from what I have tested it is only when the column is of type datetime that this is happening

### Expected behavior

"col1";"col2";"col3"
1;"2023-09-26T11:22:29.136304";"Hi"
2;"2023-09-26T11:22:29.136304";"Hey"

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.0
pandas:              <not installed>
pyarrow:             13.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #11324.

We missed writing the trailing quote for datetime values in CSV output when `quote_style` was "non_numeric". Fixed, and extended the related test-coverage to include date/datetime values.

## Example
```python
import polars as pl
from datetime import datetime
df = pl.DataFrame({"dtm": [datetime.now(), datetime.now()]})
```

#### Before
_(datetime values are missing trailing quotes)_
```python
print( df.write_csv( has_header=True, quote_style = 'non_numeric') )
# "dtm"
# "2023-09-26T11:59:34.345885
# "2023-09-26T11:59:34.345931
```
#### After
```python
print( df.write_csv( has_header=True, quote_style = 'non_numeric') )
# "dtm"
# "2023-09-26T11:59:34.345885"
# "2023-09-26T11:59:34.345931"
```

### CODE REVIEW

File: crates/polars-io/src/csv/write_impl.rs [hunk 1]
```diff
@@ -186,18 +186,21 @@ unsafe fn write_anyvalue(
...
-                ComputeError: "cannot format {} with format '{}'", type_name, datetime_format,
-            )
-                            });
+                                    ComputeError: "cannot format {} with format '{}'", type_name, datetime_format,
+                                )
+                            })?;
+                            if end_with_quote {
+                                write!(f, "{quote}")?
+                            }
+                            return Ok(())
```
Comment (stinodego) [inline crates/polars-io/src/csv/write_impl.rs:203]: I think we can just omit this? Just removing the return should be enough, right? :thinking:

Comment (alexander-beedie) [reply crates/polars-io/src/csv/write_impl.rs:203]: There may be a more streamlined way to do it, but you can't just omit or it won't satisfy the `match` arms (I started off that way but it started becoming somewhat contorted; was probably written using `return` originally for much the same reason).

File: py-polars/tests/unit/io/test_csv.py [hunk 2]
```diff
@@ -1460,30 +1460,41 @@ def test_csv_9929() -> None:
...
+    dt = date(1999, 12, 31)
+    dtm = datetime(2077, 7, 5, 3, 1, 0)
     df = pl.DataFrame(
         {
             "float": [1.0, 2.0, None],
             "string": ["a", "a,bc", '"hello'],
             "int": [1, 2, 3],
             "bool": [True, False, None],
+            "date": [dt, None, dt],
+            "datetime": [None, dtm, dtm],
```
Comment (lBilali) [inline py-polars/tests/unit/io/test_csv.py:1472]: Maybe add a test case for Time datatype as well

File: crates/polars-io/src/csv/write_impl.rs (hunk 1 above)
Comment (stinodego) [reply crates/polars-io/src/csv/write_impl.rs:203]: I'll take a look. I don't like the code duplication introduced here.

Comment (alexander-beedie) [reply crates/polars-io/src/csv/write_impl.rs]: Ahhh... switching to `polars_bail` was staring me right in the face, hah... good call :)

File: py-polars/tests/unit/io/test_csv.py (hunk 2 above)
Comment (alexander-beedie) [reply py-polars/tests/unit/io/test_csv.py:1474]: Why not indeed... done  ;)

**Review by stinodego — APPROVED** [review]
Good to go if CI passes :+1:

**Comment by alexander-beedie** [comment]
> Good to go if CI passes 👍

Lint isn't happy - will take a look 🤔

**Review by stinodego — APPROVED** [review]
