### PR TITLE
fix: Allow broadcast in `group_by` for `ApplyExpr` and `BinaryExpr`

### LINKED ISSUE #25046: `group_by` expression fails on length check with broadcast
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3]})

out = df.select(pl.col.a == pl.lit(1))  # [true, false, false]
print(out)

out = df.select(pl.col.a == pl.lit(pl.Series([1])))  # [true, false, false]
print(out)

out = df.group_by(pl.lit(1)).agg(pl.col.a == pl.lit(1))  # [true, false, false] as list[bool]
print(out)

out = df.group_by(pl.lit(1)).agg(pl.col.a == pl.lit(pl.Series([1])))  # error
print(out)

```

### Log output

```shell
shape: (3, 1)
┌───────┐
│ a     │
│ ---   │
│ bool  │
╞═══════╡
│ true  │
│ false │
│ false │
└───────┘
shape: (3, 1)
┌───────┐
│ a     │
│ ---   │
│ bool  │
╞═══════╡
│ true  │
│ false │
│ false │
└───────┘
shape: (1, 2)
┌─────────┬──────────────────────┐
│ literal ┆ a                    │
│ ---     ┆ ---                  │
│ i32     ┆ list[bool]           │
╞═════════╪══════════════════════╡
│ 1       ┆ [true, false, false] │
└─────────┴──────────────────────┘
Traceback (most recent call last):
  File "/home/koen/my-polars/tmp/tt.py", line 14, in <module>
    out = df.group_by(pl.lit(1)).agg(pl.col.a == pl.lit(pl.Series([1])))  # error
  File "/home/koen/polars/py-polars/src/polars/dataframe/group_by.py", line 242, in agg
    .collect(optimizations=QueryOptFlags.none())
     ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koen/polars/py-polars/src/polars/_utils/deprecation.py", line 97, in wrapper
    return function(*args, **kwargs)
  File "/home/koen/polars/py-polars/src/polars/lazyframe/opt_flags.py", line 328, in wrapper
    return function(*args, **kwargs)
  File "/home/koen/polars/py-polars/src/polars/lazyframe/frame.py", line 2422, in collect
    return wrap_df(ldf.collect(engine, callback))
                   ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: expressions must have matching group lengths
```

### Issue description

Broadcast is not accounted for in the group length check.

### Expected behavior

Each example should return a successful result (to be confirmed..).

### Installed versions

Latest main (310a2fabd8, 2025-10-27).

### PR DESCRIPTION
**Pull request by kdn36**
fixes #25046

This PR introduces a broadcast check to ensure the dispatch in `ApplyExpr` and `BinaryExpr` on `group_by` falls back to the group_aware implementation.

ping @coastalwhite

### CODE REVIEW

File: crates/polars-expr/src/expressions/binary.rs [hunk 1]
```diff
@@ -318,6 +318,15 @@ impl PhysicalExpr for BinaryExpr {
             ac_l.get_values().dtype().is_decimal() || ac_r.get_values().dtype().is_decimal();
         let is_fallible = has_decimal_dtype && self.op.is_arithmetic();
 
+        // Broadcast in NotAgg or AggList requires group_aware
+        let check_broadcast = !ac_l.is_scalar() && !ac_r.is_scalar();
```
Comment (coastalwhite) [inline crates/polars-expr/src/expressions/binary.rs]: matches! instead of `is_scalar`

File: crates/polars-expr/src/expressions/apply.rs [hunk 2]
```diff
@@ -557,6 +563,28 @@ impl PhysicalExpr for ApplyExpr {
                     let elementwise_must_aggregate =
                         has_not_agg && (has_agg_list || not_agg_groups_may_diverge);
 
+                    // Broadcast in NotAgg or AggList requires group_aware
+                    let check_broadcast = num_non_scalar_acs > 1;
```
Comment (coastalwhite) [inline crates/polars-expr/src/expressions/apply.rs]: This is not needed if it was already going to go to group_aware

**Review by coastalwhite — APPROVED** [review]
