### PR TITLE
fix: Correctly handle null values when comparing structs

### LINKED ISSUE #23527: `fill_null` does not fill the null values.
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

print(
    pl.DataFrame(dict(a=[False, False, False, None, True, True]))
    .with_columns(pl.struct(["a"]).alias("a"))
    .with_columns((pl.col("a") == pl.col("a").shift(1)).fill_null(False))
)
```

### Log output

```shell

```

### Issue description

The output dataframe has a null even though `fill_nulls` is used.
```
shape: (6, 1)
┌───────┐
│ a     │
│ ---   │
│ bool  │
╞═══════╡
│ null  │
│ true  │
│ true  │
│ false │
│ false │
│ true  │
└───────┘
```

### Expected behavior

The reproducible example should return
```
shape: (6, 1)
┌───────┐
│ a     │
│ ---   │
│ bool  │
╞═══════╡
│ false │
│ true  │
│ true  │
│ false │
│ false │
│ true  │
└───────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.31.0
Index type:          UInt32
Platform:            Linux-6.8.0-60-generic-x86_64-with-glibc2.35
Python:              3.10.12 (main, May 27 2025, 17:12:29) [GCC 11.4.0]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                1.37.11
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.2.3
openpyxl             <not installed>
pandas               2.2.3
polars_cloud         <not installed>
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #23527

Kindly review.

### CODE REVIEW

File: crates/polars-core/src/chunked_array/comparison/mod.rs [hunk 1]
```diff
@@ -842,10 +842,13 @@ where
 
             let mut a = a.into_owned();
             a.zip_outer_validity(&b);
+            let mut new_null_count = 0;
```
Comment (orlp) [inline crates/polars-core/src/chunked_array/comparison/mod.rs]: Small style nitpick: this variable isn't accessed outside the `unsafe` scope, and its initial value is rather important for correctness, so I think this should go inside the `unsafe` block.

**Review by orlp — CHANGES_REQUESTED** [review]

File: crates/polars-core/src/chunked_array/comparison/mod.rs (hunk 1 above)
Comment (orlp) [reply crates/polars-core/src/chunked_array/comparison/mod.rs]: Rest looks good.
