### PR TITLE
fix: Fix enum scalar output

### LINKED ISSUE #19269: List min/max operations on List[Enum] are returning Strings
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
en = pl.Enum(['X', 'Z', 'Y'])
df = pl.DataFrame({'test': pl.Series(['X', 'Y', 'Z'], dtype=en), 'group': [1, 2, 2]})
print(df.group_by('group').agg(pl.col('test').mode()).select(pl.col('test').list.max()))

# It is returning the wrong dtype. Other list operations like `.first()` instead of `.max()`return the right dtype`
print(df.group_by('group').agg(pl.col('test').mode()).select(pl.col('test').list.first()))
# It is using the correct Enum ordering for the max() operation though, which you can verify by comparing the result against
df = pl.DataFrame({'test': pl.Series(['X', 'Y', 'Z'], dtype=str), 'group': [1, 2, 2]})

print(df.group_by('group').agg(pl.col('test').mode()).select(pl.col('test').list.max()))

```

### Log output

```shell
stderr:
keys/aggregates are not partitionable: running default HASH AGGREGATION
keys/aggregates are not partitionable: running default HASH AGGREGATION
keys/aggregates are not partitionable: running default HASH AGGREGATION

stdout:
# list[enum] .list.max() ; correct values, wrong dtype
shape: (2, 1)
┌──────┐
│ test │
│ ---  │
│ str  │
╞══════╡
│ Y    │
│ X    │
└──────┘
# list[enum] .list.first() ; correct dtype for reference
shape: (2, 1)
┌──────┐
│ test │
│ ---  │
│ enum │
╞══════╡
│ X    │
│ Y    │
└──────┘
# list[str] list.max() ; just for reference to check that it is actually different from list[enum]'s .max()
shape: (2, 1)
┌──────┐
│ test │
│ ---  │
│ str  │
╞══════╡
│ X    │
│ Z    │
└──────┘
```

### Issue description

In Lazy mode, `collect_schema()` also ends with up a result different from `collect().schema`, 
```pycon
>>> df.lazy().group_by('group').agg(pl.col('test').mode()).select(pl.col('test').list.max()).collect_schema()
Schema({'test': Enum(categories=['X', 'Z', 'Y'])})
>>> df.lazy().group_by('group').agg(pl.col('test').mode()).select(pl.col('test').list.max()).collect().schema
keys/aggregates are not partitionable: running default HASH AGGREGATION
Schema({'test': String})
```

**Might** be related to #18394

### Expected behavior

The `.list.max()` operation applied on a `list[Enum]` should return a series of dtype Enum rather than str

### Installed versions

<details>

```
--------Version info---------
Polars:              1.9.0
Index type:          UInt32
Platform:            Windows-11-10.0.22631-SP0
Python:              3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.9.0
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           3.8.2
nest_asyncio         <not installed>
numpy                1.26.4
openpyxl             3.1.2
pandas               2.2.2
pyarrow              15.0.0
pydantic             2.5.2
pyiceberg            <not installed>
sqlalchemy           2.0.29
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #19269

### CODE REVIEW

File: crates/polars-core/src/chunked_array/logical/enum_/mod.rs [hunk 1]
```diff
@@ -85,16 +85,12 @@ impl EnumChunkedBuilder {
         let length = arr.len() as IdxSize;
         let ca = unsafe {
             UInt32Chunked::new_with_dims(
-                Arc::new(Field::new(
-                    self.name,
-                    DataType::Enum(Some(self.rev.clone()), self.ordering),
```
Comment (ritchie46) [inline crates/polars-core/src/chunked_array/logical/enum_/mod.rs:90]: Invariant: Always the same physical type.
