### PR TITLE
fix: Various schema corrections

### LINKED ISSUE #18468: `.str` methods silenty cast input
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.select(pl.lit(1.5).str.replace("1", "2"))
# shape: (1, 1)
# ┌─────────┐
# │ literal │
# │ ---     │
# │ str     │
# ╞═════════╡
# │ 2.5     │
# └─────────┘
```

### Log output

_No response_

### Issue description

Originally `.replace` was mentioned in https://github.com/pola-rs/polars/issues/18465

It seems certain `.str` methods cast their input instead of throwing an error.

```python
pl.select(pl.date(2024, 1, 1).str.extract("(..)"))
# shape: (1, 1)
# ┌──────┐
# │ date │
# │ ---  │
# │ str  │
# ╞══════╡
# │ 19   │
# └──────┘
```

These all seem affected:

- `.str.concat`
- `.str.contains`
- `.str.ends_with`
- `.str.extract`
- `.str.find`
- `.str.join`
- `.str.replace`
- `.str.replace_all`
- `.str.starts_with`

### Expected behavior

Should raise an exception?

```python
pl.select(pl.lit(1.5).str.to_uppercase())
# SchemaError: invalid series dtype: expected `String`, got `f64`
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.6.0
Index type:           UInt32
Platform:             macOS-13.6.1-arm64-arm-64bit
Python:               3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         <not installed>
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
- fix: Window expressions now show proper schema
- fix: Raise when namespace is called in invalid dtypes
- chore: Split up code for maintainability
- perf: Ensure we don't hit the function resolving every time
- perf: Delay alloction

fixes #18468

### CODE REVIEW

File: crates/polars-plan/src/plans/conversion/type_coercion/binary.rs [hunk 1]
```diff
@@ -296,7 +296,13 @@ pub(super) fn process_binary(
         st = String
     }
 
-    // only cast if the type is not already the super type.
+    // TODO! raise here?
```
Comment (ritchie46) [inline crates/polars-plan/src/plans/conversion/type_coercion/binary.rs:299]: Will try this in a follow up.
