### PR TITLE
fix: IPC round-trip of list of empty view with non-empty bufferset

### LINKED ISSUE #21163: Serialization / ipc_stream roundtrip errors with ComputeError: out-of-spec: ExpectedBuffer
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import io
schema = {
        "s": pl.Utf8,
        "list": pl.List(pl.Utf8),
    }
empty = pl.DataFrame(
        {
            "s": [],
            "list": [],
        }
    ).cast(schema).lazy()

row1 = pl.DataFrame({"s" : ["A"] ,"list" : [[]] }).cast(schema).lazy()
row2 = pl.DataFrame({"s" : ["B"] ,"list" : [[]]}).cast(schema).lazy()
df = pl.concat([empty, row1, row2])

bytes = df.collect().serialize()
deserialized = pl.DataFrame.deserialize(io.BytesIO(bytes))
print(deserialized)
```

### Log output

```shell
if isinstance(source, StringIO):
            source = BytesIO(source.getvalue().encode())
        elif isinstance(source, (str, Path)):
            source = normalize_filepath(source)
    
        if format == "binary":
            deserializer = PyDataFrame.deserialize_binary
        elif format == "json":
            deserializer = PyDataFrame.deserialize_json
        else:
            msg = f"`format` must be one of {{'binary', 'json'}}, got {format!r}"
            raise ValueError(msg)
    
>       return cls._from_pydf(deserializer(source))
E       polars.exceptions.ComputeError: out-of-spec: ExpectedBuffer

cls        = <class 'polars.dataframe.frame.DataFrame'>
deserializer = <built-in method deserialize_binary of type object at 0x104711e70>
format     = 'binary'
source     = <_io.BytesIO object at 0x112698c70>
```

### Issue description

Deserialization of dataframe doesn't work sometimes in 1.22.0

### Expected behavior

Serialize -> deserialize should return original dataframe

### Installed versions

<details>
```
Polars:              1.22.0
Index type:          UInt32
Platform:            macOS-15.2-arm64-arm-64bit
Python:              3.10.12 (main, Oct 31 2023, 16:05:04) [Clang 15.0.0 (clang-1500.0.40.1)]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                1.35.5
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          2.32.0
great_tables         <not installed>
matplotlib           3.9.2
numpy                2.1.0
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             1.10.18
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by orlp**
Fixes #21163.

### CODE REVIEW

File: crates/polars-arrow/src/compute/concatenate.rs [hunk 1]
```diff
@@ -315,6 +318,7 @@ fn concatenate_view<V: ViewType + ?Sized, A: AsRef<dyn Array>>(
         Arc::new([Buffer::from(new_buffer)]) as Arc<[_]>
     };
 
+    dbg!(buffers.len());
```
Comment (ritchie46) [inline crates/polars-arrow/src/compute/concatenate.rs:321]: Stray dbg!

Comment (orlp) [reply crates/polars-arrow/src/compute/concatenate.rs:321]: I had already fixed it, forgot to push I think.

**Comment by ritchie46** [comment]
I think this one should be closed and just reopened. Github seems drunk.
