### PR TITLE
fix(rust, python): Ensure CsvReader always respects the n_rows parameter

### LINKED ISSUE #7490: pl.read_csv sometimes returns fewer rows than specified by the n_rows parameter
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When I call [polars.read_csv](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_csv.html) on my data with the `n_rows`  parameter set to an integer `n` and `n_threads` set to 1, I do not get back the number of rows I requested for all values of `n`.

I originally encountered this problem when working with a large csv file. After half a day of manually tweaking the large data file, I have managed to reproduce the issue in the fairly minimal snippet below. This example is bizarrely sensitive; removing a single character or row can prevent the erroneous behavior from manifesting.

### Reproducible example

```python
import polars as pl

pl.DataFrame(
    [[None, None, None, '?????????'] for i in range(1000)] +
    [['?????????????????????????????????????????????????', None, None, None]] +
    [[None, None, None, '?????????'] for i in range(1048)],
    orient='row',
    schema=[('0', pl.Utf8), ('1', pl.Utf8), ('2', pl.Utf8), ('3', pl.Utf8)]
).write_csv('data.csv')

# returns a frame with shape (2045, 4) instead of (2048, 4) as expected
pl.read_csv(
    'data.csv',
    infer_schema_length=0,
    n_rows=2048,
    n_threads=1
).shape
```

### Expected behavior

The `n_rows` parameter should function as documented.

### Installed versions

<details>

```
---Version info---
Polars: 0.16.12
Index type: UInt32
Platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.35
Python: 3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0]
---Optional dependencies---
pyarrow: 11.0.0
pandas: 1.5.3
numpy: 1.24.2
fsspec: <not installed>
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by foxcroftjn**
fixes #7490

### CODE REVIEW

File: polars/polars-io/src/csv/read_impl/mod.rs [hunk 1]
```diff
@@ -682,6 +702,67 @@ impl<'a> CoreReader<'a> {
                     })
                     .collect::<PolarsResult<Vec<_>>>()
             })?;
+            if let (Some(n_rows), Some(remaining_bytes)) = (self.n_rows, remaining_bytes) {
+                let rows_already_read = dfs.iter().map(|x| x.0.height()).sum::<usize>();
```
Comment (ritchie46) [inline polars/polars-io/src/csv/read_impl/mod.rs:706]: `x.1` is exactly that. See line 703. I think we should use that directly.

File: polars/polars-io/src/csv/read_impl/mod.rs [hunk 2]
```diff
@@ -682,6 +702,67 @@ impl<'a> CoreReader<'a> {
...
+
+                            DataFrame::new_no_checks(
+                                buffers
+                                    .into_iter()
+                                    .map(|buf| buf.into_series())
+                                    .collect::<PolarsResult<_>>()?,
+                            )
+                        };
+
+                        // update the running str bytes statistics
```
Comment (ritchie46) [inline polars/polars-io/src/csv/read_impl/mod.rs:752]: This would not be needed anymore on a last run. We can remove that branch.

File: polars/polars-io/src/csv/read_impl/mod.rs [hunk 3]
```diff
@@ -682,6 +702,67 @@ impl<'a> CoreReader<'a> {
...
+                            let remaining_rows = n_rows - rows_already_read;
+                            // estimate the buffer size required for the remaining rows from the
+                            // rows already read (adding a 10% margin of error)
+                            let estimated_chunk_size =
+                                (bytes.len() as f64 / rows_already_read as f64
+                                    * remaining_rows as f64
+                                    * 1.1) as usize;
+                            let mut buffers = init_buffers(
+                                &projection,
+                                estimated_chunk_size,
```
Comment (ritchie46) [inline polars/polars-io/src/csv/read_impl/mod.rs:719]: this should be `remaining_rows`

File: polars/polars-io/src/csv/read_impl/mod.rs [hunk 4]
```diff
@@ -682,6 +702,67 @@ impl<'a> CoreReader<'a> {
...
             })?;
+            if let (Some(n_rows), Some(remaining_bytes)) = (self.n_rows, remaining_bytes) {
+                let rows_already_read = dfs.iter().map(|x| x.0.height()).sum::<usize>();
+                if rows_already_read < n_rows {
+                    dfs.push({
+                        let mut df = {
+                            let remaining_rows = n_rows - rows_already_read;
+                            // estimate the buffer size required for the remaining rows from the
+                            // rows already read (adding a 10% margin of error)
+                            let estimated_chunk_size =
```
Comment (ritchie46) [inline polars/polars-io/src/csv/read_impl/mod.rs:713]: We don't need to estimate anymore as this last chunk will run single threaded. You can simply pass the `remaining_bytes` and ensure you pass `remaining_rows`, then the `parse_lines` should stop once that number of rows is read.

**Review by ritchie46 — COMMENTED** [review]
Thanks. I think this is a good fix. I have left some comments.

**Comment by foxcroftjn** [comment]
Thank you for the feedback! I believe I have modified my code as requested.

This is my first non-documentation contribution to any open source project, and I am pleased that it was to polars. I greatly enjoy using this library.

**Comment by ritchie46** [comment]
> This is my first non-documentation contribution to any open source project, and I am pleased that it is to polars. I greatly enjoy using this library.

Thanks for the contribution. :)
