### PR TITLE
fix(rust, python): prevent re-ordering of dict keys inside `.apply`

### LINKED ISSUE #10128: Polars `apply` changing key order in returned dict
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from polars import Struct, Field

## With this dtype defined (note reverse-alpha field order):
Similarity = Struct([
    Field('z', pl.Float64),
    Field('y', pl.Float64),
    Field('x', pl.List(pl.Int64))
])

## When I run this `apply` returning a fixed dict that matches `Similarity` in keys, type, and order:

df = pl.DataFrame({'a': [0, 1]})
df.with_columns(
    pl.col('a')
    .apply(lambda d: {'z':1.1, 'y': 0.1, 'x': [2]},
           return_dtype=Similarity))

## I get this SchemaError with key order mismatch (note key order): 
## **SchemaError: 
## expected output type ...**

Struct([
  Field { name: "z", dtype: Float64 }, 
  Field { name: "y", dtype: Float64 }, 
  Field { name: "x", dtype: List(Int64) }])

##**...got (note alphabetical key order)...**

Struct([
  Field { name: "x", dtype: List(Int64) }, 
  Field { name: "y", dtype: Float64 }, 
  Field { name: "z", dtype: Float64 }])
```

### Issue description

It appears that Polars is sorting the keys of returned dicts in alphabetical order, causing a difference from the order in the `return_dtype` struct. 

### Expected behavior

The code above should just run without any Schema error, as it does without the `return_dtype` spec:
```python
df.with_columns(
    pl.col('a')
    .apply(lambda d: {'z':1.1, 'y': 0.1, 'x': [2]},
           return_dtype=Similarity))

shape: (2, 1)
┌───────────────┐
│ a             │
│ ---           │
│ struct[3]     │
╞═══════════════╡
│ {[2],0.1,1.1} │
│ {[2],0.1,1.1} │
└───────────────┘

```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            macOS-11.7.8-x86_64-i386-64bit
Python:              3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.0
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            1.10.11
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

### PR DESCRIPTION
**Pull request by cmdlineluser**
Attempts to fix #10128

### CODE REVIEW

File: py-polars/src/apply/mod.rs [hunk 1]
```diff
@@ -54,6 +54,10 @@ fn iterator_to_struct<'a>(
     // ]
     let mut struct_fields: BTreeMap<&str, Vec<AnyValue>> = BTreeMap::new();
 
+    // as a BTreeMap sorts its keys, we also need to track the original
```
Comment (ritchie46) [inline py-polars/src/apply/mod.rs:57]: We can use `PlIndexMap` if insertion order needs to be maintained.

Comment (cmdlineluser) [reply py-polars/src/apply/mod.rs:57]: Ah, thanks @ritchie46 - my searching did find https://doc.rust-lang.org/stable/nightly-rustc/rustc_data_structures/sorted_map/struct.SortedIndexMultiMap.html but not `PlIndexMap`

Trying `PlIndexMap` gives me this back from the compiler, I'm not sure how to proceed.
```rust
error[E0599]: the method `par_iter` exists for struct `IndexMap<&str, Vec<AnyValue<'_>>, RandomState>`, but its trait bounds were not satisfied
   --> src/apply/mod.rs:114:14
    |
113 | /             struct_fields
114 | |             .par_iter()
    | |_____________-^^^^^^^^
    |
   ::: /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-2.0.0/src/map.rs:81:1
    |
81  |   pub struct IndexMap<K, V, S = RandomState> {
    |   ------------------------------------------ doesn't satisfy `_: IntoParallelRefIterator<'_>`
    |
    = note: the following trait bounds were not satisfied:
            `&indexmap::map::IndexMap<&str, Vec<polars_rs::prelude::AnyValue<'_>>, ahash::RandomState>: polars_rs::export::rayon::iter::IntoParallelIterator`
            which is required by `indexmap::map::IndexMap<&str, Vec<polars_rs::prelude::AnyValue<'_>>, ahash::RandomState>: polars_rs::export::rayon::iter::IntoParallelRefIterator<'_>`
```

Comment (ritchie46) [reply py-polars/src/apply/mod.rs:57]: Ah right. Then this solution is fine. Thank you! :+1:
