### PR TITLE
fix: Fix one edge case (out of many) of int128 literals not working

### LINKED ISSUE #20807: bug: series.index_of returns `None` for 2*66 with pl.Int128
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
s = pl.Series([2, 2**65], dtype=pl.Int128)
assert s.index_of(2**65) == 1
```

### Log output

```shell

```

### Issue description

The above raises an AssertionError, because `s.index_of(2**65)` returns `None` here

cc @itamarst in case it's not already on your radar

### Expected behavior

no assertion error

### Installed versions

<details>

```
--------Version info---------
Polars:              1.20.0
Index type:          UInt32
Platform:            Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.12.5 (main, Aug 14 2024, 05:08:31) [Clang 18.1.8 ]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               5.5.0
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
google.auth          <not installed>
great_tables         0.15.0
matplotlib           3.9.2
nest_asyncio         1.6.0
numpy                2.2.1
openpyxl             <not installed>
pandas               2.2.3
pyarrow              18.1.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #20807 

See also #20829 for related issues that also seem like they need fixing.

### CODE REVIEW

**Comment by itamarst** [comment]
The test failure doesn't seem to be related to this PR?

File: crates/polars-core/src/utils/supertype.rs [hunk 1]
```diff
@@ -537,17 +537,24 @@ fn super_type_structs(fields_a: &[Field], fields_b: &[Field]) -> Option<DataType
...
+    }
+    if let Ok(v) = i64::try_from(v) {
+        return AnyValue::Int64(v);
+    }
+    if let Ok(v) = u64::try_from(v) {
+        return AnyValue::UInt64(v);
     }
+    #[cfg(feature = "dtype-i128")]
+    {
+        AnyValue::Int128(v)
```
Comment (ritchie46) [inline crates/polars-core/src/utils/supertype.rs:551]: Can we still do a `i128::try_from`. Python has unbounded integers.

Comment (itamarst) [reply crates/polars-core/src/utils/supertype.rs:551]: I did that initially, and then the compiler pointed out that `v` is `i128` so the `try_from()` always succeeds and is redundant. So at the local scope the current code is the correct thing to do I think?
