### PR TITLE
fix: Block predicate pushdown when `group_by` key values are changed

### LINKED ISSUE #21439: Change in Datatype in `group_by` ignored in later filter for LazyFrames
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import datetime, timedelta

df = pl.DataFrame({"time": pl.datetime_range(datetime(2021, 1, 1), datetime(2021, 1, 2), timedelta(minutes=15), eager=True)})

# works on DataFrames
print(
	df
	.group_by(pl.col("time").dt.hour())
	.agg()
	.filter(pl.col("time").is_between(0, 10))
)

# Error on LazyFrames
print(
	df
	.lazy()
	.group_by(pl.col("time").dt.hour())
	.agg()
	.filter(pl.col("time").is_between(0, 10))
	.collect()
)
```

### Log output

```shell
shape: (11, 1)
┌──────┐
│ time │
│ ---  │
│ i8   │
╞══════╡
│ 9    │
│ 4    │
│ 5    │
│ 3    │
│ 8    │
│ …    │
│ 0    │
│ 10   │
│ 6    │
│ 2    │
│ 7    │
└──────┘
keys/aggregates are not partitionable: running default HASH AGGREGATION
dataframe filtered
keys/aggregates are not partitionable: running default HASH AGGREGATION
dataframe filtered

SchemaError: could not evaluate '>=' comparison between series 'time' of dtype: datetime[μs] and series 'literal' of dtype: i8
```

### Issue description

For LazyFrames the change of datatype is not represented in filter expressions down the line.

Seems like an issue with the pushdown of the filter expression.

### Expected behavior

Both operation should run without error and produce the same output

### Installed versions

<details>

--------Version info---------
Polars:              1.23.0
Index type:          UInt32
Platform:            Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]
LTS CPU:             False

----Optional dependencies----
Azure CLI            2.53.1
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.3.1
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.9.2
numpy                1.26.1
openpyxl             <not installed>
pandas               2.2.1
polars_cloud         <not installed>
pyarrow              15.0.2
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           2.0.37
torch                2.4.0+cu121
xlsx2csv             <not installed>
xlsxwriter           3.2.0

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #21439

This PR limits the use of predicate_pushdown on `group_by` keys to only those keys that are not modified.

The bug looks significant. This PR fixes correctness at the expense of some queries (that operate on key values) slowing down.

As usual, in-depth review appreciated.

### CODE REVIEW

File: crates/polars-plan/src/plans/optimizer/predicate_pushdown/group_by.rs [hunk 1]
```diff
@@ -36,11 +36,17 @@ pub(super) fn process_group_by(
...
     }
 
-    // If the predicate only resolves to the keys we can push it down.
+    // If the predicate only resolves to the keys we can push it down, on the condition
+    // that the keys are not modified from their original values.
     // When it filters the aggregations, the predicate should be done after aggregation.
     let mut local_predicates = Vec::with_capacity(acc_predicates.len());
+    let eligible_keys = keys
+        .iter()
+        .filter(|&key| matches!(expr_arena.get(key.node()), AExpr::Column(_)))
```
Comment (coastalwhite) [inline crates/polars-plan/src/plans/optimizer/predicate_pushdown/group_by.rs]: Does this also need to take into account aliases? Not sure? Does it break if the `c != key.output_name()` with `AExpr::Column(c)`?

Comment (kdn36) [reply crates/polars-plan/src/plans/optimizer/predicate_pushdown/group_by.rs]: Aliases to new key names were not optimized, and therefore not 'broken', just a missing optimization. However, aliases to existing key names (e.g. swapping ("a","b") to ("b","a") can cause problems. Let me iterate and close that scenario as well.

File: crates/polars-plan/src/plans/optimizer/predicate_pushdown/group_by.rs [hunk 2]
```diff
@@ -36,11 +36,19 @@ pub(super) fn process_group_by(
...
     // When it filters the aggregations, the predicate should be done after aggregation.
     let mut local_predicates = Vec::with_capacity(acc_predicates.len());
+    let eligible_keys = keys
+        .iter()
+        .filter(
+            |&key| matches!(expr_arena.get(key.node()), AExpr::Column(c) if c == key.output_name()),
+        )
+        .cloned()
+        .collect::<Vec<_>>();
     let key_schema = aexprs_to_schema(
```
Comment (ritchie46) [inline crates/polars-plan/src/plans/optimizer/predicate_pushdown/group_by.rs:46]: I belive this already accepts an iterator, so no need to collect into a vec.

File: crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs [hunk 3]
```diff
@@ -21,6 +21,7 @@ mod inner {
     use polars_utils::idx_vec::UnitVec;
     use polars_utils::unitvec;
 
+    #[derive(Debug)]
```
Comment (ritchie46) [inline crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs]: Can be removed (when not debugging).

File: crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs [hunk 4]
```diff
@@ -344,14 +344,14 @@ impl SlicePushDown {
...
-            (Sort {input, by_column, mut slice,
+            (Sort {input, by_column, slice: _,
                 sort_options}, Some(state)) => {
                 // first restart optimization in inputs and get the updated LP
                 let input_lp = lp_arena.take(input);
                 let input_lp = self.pushdown(input_lp, None, lp_arena, expr_arena)?;
                 let input= lp_arena.add(input_lp);
 
-                slice = Some((state.offset, state.len as usize));
+                let slice = Some((state.offset, state.len as usize));
```
Comment (ritchie46) [inline crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs]: I think this should be another PR. As there are more mutable changes here, I cannot tell if we rely on this and if we change it, we should do a full pass.
