### PR TITLE
fix(rust, python): Take input_schema to create physical expr for Selection

### LINKED ISSUE #10565: n_unique with Utf8 vs IntXX
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl

df_int = pl.DataFrame(data={"a": []}, schema={"a": pl.Int16})
df_int.filter(pl.col("a").n_unique().over("test") == 1)


df_str = pl.DataFrame(data={"a": []}, schema={"a": pl.Utf8})
df_str.filter(pl.col("a").n_unique().over("test") == 1)

```

### Issue description

For an empty dataframe, if the `dtype` is `Utf8`, the comparison == 1 throws an error.

### Expected behavior

For an empty dataframe, if the `dtype` is `Int16` (also `Int8`, `Int32`, and `Int64`) the comparison == 1 works perfectly fine and I would expect the behavior to be the same if `dtype = pl.Utf8`.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            macOS-13.5-arm64-arm-64bit
Python:              3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          0.3.0
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            1.10.12
sqlalchemy:          1.4.49
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
None
```

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This fixed #10565.

### CODE REVIEW

File: crates/polars-lazy/src/physical_plan/planner/lp.rs [hunk 1]
```diff
@@ -165,10 +165,11 @@ pub fn create_physical_plan(
             Ok(Box::new(executors::SliceExec { input, offset, len }))
         },
         Selection { input, predicate } => {
+            let input_schema = lp_arena.get(input).schema(lp_arena).into_owned();
             let input = create_physical_plan(input, lp_arena, expr_arena)?;
             let mut state = ExpressionConversionState::default();
             let predicate =
-                create_physical_expr(predicate, Context::Default, expr_arena, None, &mut state)?;
+                create_physical_expr(predicate, Context::Default, expr_arena, Some(&input_schema), &mut state)?;
```
Comment (reswqa) [inline crates/polars-lazy/src/physical_plan/planner/lp.rs:172]: I'm not sure if it's due to some reason I don't know that we didn't pass `input_schema` here. 🤔

**Review by orlp — APPROVED** [review]

File: crates/polars-lazy/src/physical_plan/planner/lp.rs [hunk 2]
```diff
@@ -165,10 +165,16 @@ pub fn create_physical_plan(
             Ok(Box::new(executors::SliceExec { input, offset, len }))
         },
         Selection { input, predicate } => {
+            let input_schema = lp_arena.get(input).schema(lp_arena).into_owned();
```
Comment (ritchie46) [inline crates/polars-lazy/src/physical_plan/planner/lp.rs:168]: Do we really need to clone here? As we pass by reference a few lines later.
