### PR TITLE
fix: Prevent deadlock when using `to_pandas()` in multithreaded context

### LINKED ISSUE #27396: Deadlock when calling to_pandas on the same df in multiple threads
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
from concurrent.futures import ThreadPoolExecutor

import polars as pl

df = pl.DataFrame({"a": [5234.523] * 100000})


def to_pandas() -> None:
    df.to_pandas()
    print("to_pandas")


with ThreadPoolExecutor(10) as e:
    fs = []
    for i in range(100):
        # This loop does not even finish
        print("submitting", i)
        fs.append(e.submit(to_pandas))
    [f.result() for f in fs]
```
```
$ python3 test.py
submitting 0
submitting 1
<hangs forever here>
```

### Log output

```shell
No additional output using POLARS_VERBOSE=1
```

### Issue description

It not only deadlocks the affected threads, but deadlocks the entire python interpreter.

If this happens inside a web server endpoint, it deadlocks the entire web server, and requires a process restart.

Cloning the df before calling `.to_pandas()` makes this work as expected:
```python
df.clone().to_pandas()
```

### Expected behavior

I expect that the code example runs to completion.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.40.1
Index type:          UInt32
Platform:            Linux-6.12.73+deb13-amd64-x86_64-with-glibc2.41
Python:              3.14.4 (main, Apr  7 2026, 20:47:53) [Clang 22.1.1 ]
Runtime:             rt32

----Optional dependencies----
Azure CLI            2.77.0
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.4.4
openpyxl             <not installed>
pandas               3.0.2
polars_cloud         <not installed>
pyarrow              24.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by Kevin-Patyk**
Resolves https://github.com/pola-rs/polars/issues/27396.

I did quite some tests with various fixes and this solution is the only one that worked. It also does not drastically reduce performance, as you can see with the benchmark results below.

In the original code, the problem was that one thread would acquire the write lock and then drop the Python GIL using `enter_polars_ok`. After doing the rechunk, the lock would get downgraded to read, but another thread could pick up the GIL and would then be trying to acquire the write lock, which is not possible due to the other thread having the read lock. This resulted in a deadlock since the thread with the read lock cannot proceed into `Python::attach` without the GIL and the other thread cannot release the GIL since it cannot acquire the write lock and execute the code that follows.

The fix was to always acquire a read lock initially. Then, if the `DataFrame` needed rechunking, the read lock would be dropped and a write lock would be acquired. The rechunking would then happen, followed by the write lock being downgraded to read. Thus, the first thread that encountered a `DataFrame` that needs to be rechunked would be the only one that would require a write lock, while the others would only ever need read locks and many could be held simultaneously. After the first thread is downgraded to read, all other threads can also read and then start competing for the GIL when encountering `Python::attach`.

🤖 Claude Sonnet 4.6 for a detailed refresher on multithreading/`RwLock` and rubber ducking. 

## Benchmark

Benchmark Code:

```python
import timeit
import polars as pl

df_single = pl.DataFrame({'a': [5234.523] * 100000})
n = 100

single_time = timeit.timeit(lambda: df_single.to_pandas(), number=n)
multi_time = timeit.timeit(lambda: pl.concat([pl.DataFrame({'a': [5234.523] * 50000}), pl.DataFrame({'a': [5234.523] * 50000})], rechunk=False).to_pandas(), number=n)

print(f'Single chunk: {single_time / n * 1000:.2f}ms per call')
print(f'Multi chunk:  {multi_time / n * 1000:.2f}ms per call')
```

Fix Branch:

Single chunk: `1.96ms` per call
Multi chunk: `5.79ms` per call

Main Branch:

Single chunk: `4.91ms` per call
Multi chunk: `5.87ms` per call

### CODE REVIEW

File: crates/polars-python/src/dataframe/export.rs [hunk 1]
```diff
@@ -107,11 +107,17 @@ impl PyDataFrame {
     /// since those can't be converted correctly via PyArrow. The calling Python
     /// code should make sure these are not included.
     #[allow(clippy::wrong_self_convention)]
-    pub fn to_pandas(&self, py: Python) -> PyResult<Vec<Py<PyAny>>> {
-        let mut df = self.df.write();
-        let dfr = &mut *df; // Lock guard isn't Send, but mut ref is.
-        py.enter_polars_ok(|| dfr.rechunk_mut_par())?;
-        let df = RwLockWriteGuard::downgrade(df);
+    pub fn to_pandas(&self) -> PyResult<Vec<Py<PyAny>>> {
```
Comment (orlp) [inline crates/polars-python/src/dataframe/export.rs]: Problem with this solution is that we don't release the GIL during the (potentially expensive) rechunk anymore.

Can you try this instead?

```rust
let mut df = self.df.read().clone();
py.enter_polars_ok(|| df.rechunk_mut_par())?;
*self.df.write() = df;
```

**Review by orlp — CHANGES_REQUESTED** [review]

**Comment by Kevin-Patyk** [comment]
Okay so I did some debugging and your solution does work, thanks for that. But I did make one change and it was removing the `python::attach` block. In [this pyo3 documentation](https://docs.rs/pyo3/latest/pyo3/marker/struct.Python.html), they say that:

"In a function or method annotated with `#[pyfunction]` or `#[pymethods]` you can declare it as a parameter, and PyO3 will pass in the token when Python code calls it."

Since the function already receives `py: Python` as a parameter, the GIL is already held and `Python::attach` is just a redundant reacquire because `enter_polars_ok` reacquires the GIL before returning, so `py` remains valid.

**Review by orlp — APPROVED** [review]
