### PR TITLE
fix(python): set null_count on categorical append

### LINKED ISSUE #11910: `Series.null_count()` for Categorical types only considers the first chunk
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

with pl.StringCache():
    s1 = pl.Series(["", ""], dtype=pl.Categorical)
    s2 = pl.Series([None, "", ""], dtype=pl.Categorical)

s = pl.concat([s1, s2], rechunk=False)

print(s.null_count())  # 0
```

### Log output

_No response_

### Issue description

Caught by parametric tests [here](https://github.com/pola-rs/polars/actions/runs/6592015533/job/17911807871).

Introduced by #11889

`null_count` is wrong for chunked Series of type Categorical.

### Expected behavior

Output for example should be `1`.

### Installed versions

main branch

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #11910

### CODE REVIEW

File: crates/polars-core/src/chunked_array/logical/categorical/from.rs [hunk 1]
```diff
@@ -7,7 +7,7 @@ use crate::using_string_cache;
 
 impl From<&CategoricalChunked> for DictionaryArray<u32> {
     fn from(ca: &CategoricalChunked) -> Self {
-        let keys = ca.logical().rechunk();
+        let keys = ca.physical().rechunk();
```
Comment (ritchie46) [inline crates/polars-core/src/chunked_array/logical/categorical/from.rs:10]: drive by, gives you access to the physical type, not the logical.
