### PR TITLE
fix: Fix `arr.{eval,agg}` in aggregation context

### LINKED ISSUE #25384: `arr.eval` fails in aggregation context
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series("a", [[0, 1, 2], [5, 3, 4]], pl.Array(pl.Int64, 3))
df = s.to_frame()

out = df.select(pl.col.a.arr.eval(pl.element().rank()).over([True]))
print(out)
```

### Log output

```shell
polars.exceptions.SchemaError: invalid series dtype: expected `Array`, got `list[array[i64, 3]]` for series with name `a`
```

### Issue description

Any `arr.eval` in aggregation context fails.

Same underlying problem as #25361 , possibly more.

### Expected behavior

Should work
```
shape: (2, 1)
┌─────────────────┐
│ a               │
│ ---             │
│ array[f64, 3]   │
╞═════════════════╡
│ [1.0, 2.0, 3.0] │
│ [3.0, 1.0, 2.0] │
└─────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.35.2
Index type:          UInt32
Platform:            Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
Python:              3.13.5 (main, Oct  5 2025, 19:39:24) [GCC 13.3.0]
Runtime:             rt32
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
Fixes #25384 

*Edit: Resolved (was: WIP note: fails on streaming unless `POLARS_MAX_THREADS=1`)

### CODE REVIEW

File: crates/polars-core/src/chunked_array/mod.rs [hunk 1]
```diff
@@ -739,14 +739,17 @@ impl ArrayChunked {
...
             .into_iter()
             .map(|chunk| {
                 debug_assert_eq!(chunk.len() % width, 0);
-                FixedSizeListArray::new(arrow_dtype.clone(), length, chunk, None).into_boxed()
+                let chunk_len = chunk.len() / width;
+                total_len += chunk_len;
+                FixedSizeListArray::new(arrow_dtype.clone(), chunk_len, chunk, None).into_boxed()
             })
             .collect();
+        debug_assert_eq!(total_len, length);
```
Comment (kdn36) [inline crates/polars-core/src/chunked_array/mod.rs:752]: Let me know if we prefer a hard `assert` or no check at all.
