### PR TITLE
fix: Properly account for nulls in the `is_not_nan` check made in `drop_nans`

### LINKED ISSUE #22706: `drop_nans` drops null values from DataFrames
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# Case 1
>>> pl.Series([1, 2, float('nan'), None], dtype=pl.Float64).drop_nulls()
shape: (3,)
Series: '' [f64]
[
        1.0
        2.0
        NaN
]

# Case 2
pl.Series([1, 2, float('nan'), None], dtype=pl.Float64).drop_nans()
shape: (3,)
Series: '' [f64]
[
        1.0
        2.0
        null
]

# Case 3
>>> pl.DataFrame({'a': [1, 2, float('nan'), None]}, schema={'a': pl.Float64}).drop_nulls()
shape: (3, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
│ 2.0 │
│ NaN │
└─────┘

# Case 4
>>> pl.DataFrame({'a': [1, 2, float('nan'), None]}, schema={'a': pl.Float64}).drop_nans()
shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
│ 2.0 │
└─────┘
```

### Log output

```shell

```

### Issue description

In the fourth case the missing value is dropped.

In the document [here](https://docs.pola.rs/api/python/dev/reference/dataframe/api/polars.DataFrame.drop_nans.html) another example is shown where missing values are not dropped. Therefore, the behaviour varies on a case-by-case basis.

### Expected behavior

As with the corresponding `pl.Series` example, the missing value should not be dropped.

### Installed versions

<details>

```
>>> pl.show_versions()
--------Version info---------
Polars:              1.29.0
Index type:          UInt32
Platform:            Windows-10-10.0.22631-SP0
Python:              3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
Azure CLI            'az' is not recognized as an internal or external command,
operable program or batch file.
<not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
polars_cloud         <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #22706.

_"Damn you, three-valued logic..."_ 🙄

* Fixes the check to properly account for null values; uses `remove` with `any_horizontal`, instead of `filter` with `all_horizontal`, for correctness and notably cleaner expression of the logic.
* Minor streamlining of `drop_nulls` (no performance gain/loss).

### CODE REVIEW

File: crates/polars-plan/src/dsl/builder_dsl.rs [hunk 1]
```diff
@@ -164,17 +164,15 @@ impl DslBuilder {
                 all_horizontal(
                     subset
                         .into_iter()
-                        .map(|v| v.is_not_nan())
+                        .map(|v| v.clone().is_not_nan().or(v.is_null()))
```
Comment (nikaltipar) [inline crates/polars-plan/src/dsl/builder_dsl.rs:167]: Nit: Can `.clone().is_not_nan().or(v.is_null())` be moved into a common utility so we can avoid repetition in lines below?

**Review by nikaltipar — COMMENTED** [review]
Thanks for the quick fix! That will be helpful for further releases.

I would recommend we also merge my change #22657 that changes the documentation to refer to `drop_nulls` and `drop_nans` from one another. If other users have hit similar issues, that will help clean up the confusion.

File: crates/polars-plan/src/dsl/builder_dsl.rs (hunk 1 above)
Comment (alexander-beedie) [reply crates/polars-plan/src/dsl/builder_dsl.rs]: Realised we could write this even more cleanly (by adding `remove` to the DsBuilder, as we have at the frame level), so no need for a utility function.

File: crates/polars-plan/src/dsl/builder_dsl.rs [hunk 2]
```diff
@@ -231,6 +208,16 @@ impl DslBuilder {
         .into()
     }
 
+    /// Remove rows matching a filter predicate (note that rows
+    /// where the predicate resolves to `null` are *not* removed).
+    pub fn remove(self, predicate: Expr) -> Self {
```
Comment (ritchie46) [inline crates/polars-plan/src/dsl/builder_dsl.rs:213]: We don't use this anywhere right? I think we should remove it in that case.

Comment (alexander-beedie) [reply crates/polars-plan/src/dsl/builder_dsl.rs:213]: It's used in `drop_nans` to make the check correct/clean, above ;)

File: crates/polars-plan/src/dsl/builder_dsl.rs [hunk 3]
```diff
@@ -156,45 +156,22 @@ impl DslBuilder {
...
-            self.filter(
-                // TODO: when Decimal supports NaN, include here
-                all_horizontal([dtype_cols([DataType::Float32, DataType::Float64]).is_not_nan()])
-                    .unwrap(),
-            )
-        }
+        let is_nan = match subset {
+            Some(subset) if subset.is_empty() => return self,
+            Some(subset) => subset.into_iter().map(Expr::is_nan).collect(),
+            // TODO: when Decimal supports NaN values, include that dtype here
```
Comment (orlp) [inline crates/polars-plan/src/dsl/builder_dsl.rs:162]: Can you remove this comment? I know it was part of the old code but we won't ever add NaNs to decimal.

**Review by orlp — CHANGES_REQUESTED** [review]
