### PR TITLE
fix: Fix concat_arr panic when using categoricals/enums

### LINKED ISSUE #20917: Panic on concat_arr method when using Enums
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
ENUM = pl.Enum(["A", "B"])
df = pl.DataFrame([pl.Series("left", ["A", "B"], dtype=ENUM), pl.Series("right", ["A", "B"], dtype=ENUM)])
df.select(pl.concat_arr(pl.all()))
```

### Log output

```shell
thread '<unnamed>' panicked at crates/polars-ops/src/series/ops/concat_arr.rs:135:19:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("FixedSizeListArray's child's DataType must match. However, the expected DataType is Dictionary(UInt32, Utf8View, false) while it got UInt32."))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/etrotta/redacted/.venv/lib/python3.12/site-packages/polars/dataframe/frame.py", line 9413, in select
    return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/etrotta/redacted/.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2056, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("FixedSizeListArray's child's DataType must match. However, the expected DataType is Dictionary(UInt32, Utf8View, false) while it got UInt32."))
```

### Issue description

The example code errors with a Panic exception

### Expected behavior

For it to work the same as
```python
df.select(pl.concat_list(pl.all()).list.to_array(2))
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.21.0
Index type:          UInt32
Platform:            Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
Python:              3.12.3 (main, Jan 17 2025, 18:03:48) [GCC 13.3.0]
LTS CPU:             False

----Optional dependencies----
Azure CLI            2.67.0
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.2.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by alex-gregory-ds**
Closes #20917.

This fixes `concat_arr` panicing when concatenating columns of enums. The panic happened because concat array tries to create a new series of arrays that contain enums. But, enums are stored as integers under the hood so there was a mismatch between the enum and underlying integer data type.

This fixes the problem by first performing `concat_arr` on the underlying integers then casting the result the correct array enum data type.

## Notes for reviews

This solution adds support for enums but I suspect does not fix the underlying problem so it feels like a bolt-on solution. If there are better ways to do this please let me know.

### CODE REVIEW

**Comment by nameexhaustion** [comment]
Thanks for the PR, there's some non-trivial details surrounding this issue - I'll take it from here, but will leave some notes on the initial diff

File: crates/polars-ops/src/series/ops/concat_arr.rs [hunk 1]
```diff
@@ -130,73 +130,18 @@ pub fn concat_arr(args: &[Column], dtype: &DataType) -> PolarsResult<Column> {
             unsafe { horizontal_flatten_unchecked(&arrays, &widths, output_height) }
         };
 
-        let arrow_dtype = match dtype.inner_dtype() {
-            Some(DataType::Enum(_, _)) => ArrowDataType::FixedSizeList(
```
Comment (nameexhaustion) [inline crates/polars-ops/src/series/ops/concat_arr.rs]: Note, this didn't match against all logical types (e.g. categorical, datetime), and didn't work for nested types (e.g. `List(Enum(..))`)

File: crates/polars-ops/src/series/ops/concat_arr.rs [hunk 2]
```diff
@@ -130,73 +130,18 @@ pub fn concat_arr(args: &[Column], dtype: &DataType) -> PolarsResult<Column> {
...
 
-        chunked_array.into_column()
+        out.into_column()
     };
 
     Ok(out)
 }
-
-#[cfg(test)]
-mod tests {
```
Comment (nameexhaustion) [inline crates/polars-ops/src/series/ops/concat_arr.rs]: We'd prefer to avoid adding Rust tests if the issue can be tested in Python
