### PR TITLE
fix(rust!, python): Error on `value_counts` on column named `"counts"`

### LINKED ISSUE #10732: `Series.value_counts` produces a data frame with duplicate column names
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
print(to_markdown(pl.Series("counts", [1]).value_counts()))
```
gives a data frame with two identically named columns
```markdown
+----------+----------+
|   counts |   counts |
+==========+==========+
|        1 |        1 |
+----------+----------+
```

### Issue description

If the series' name is the same as the one created internally by `value_counts` the resulting data frame has duplicate names.

### Expected behavior

The expected behaviour is up the the devs to define.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-5.4.0-1109-azure-x86_64-with-glibc2.27
Python:              3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.25.2
pandas:              2.0.3
pyarrow:             10.0.1
pydantic:            2.3.0
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by stinodego**
Fixes #10732

Also did a bunch of code cleanup.

#### Changes

* Add a check when constructing the value counts struct.
* Dispatch `Series.value_counts` to the expression.
* Rename `multithreaded` param to `parallel` - this is more in line with other functions like `concat`.
* Clean up docstrings etc.

### CODE REVIEW

File: crates/polars-ops/src/series/ops/various.rs [hunk 1]
```diff
@@ -10,15 +10,15 @@ use crate::series::ops::SeriesSealed;
...
-    fn value_counts(&self, multithreaded: bool, sorted: bool) -> PolarsResult<DataFrame> {
+    fn value_counts(&self, sort: bool, parallel: bool) -> PolarsResult<DataFrame> {
         let s = self.as_series();
         // we need to sort here as well in case of `maintain_order` because duplicates behavior is undefined
-        let groups = s.group_tuples(multithreaded, sorted)?;
+        let groups = s.group_tuples(parallel, sort)?;
         let values = unsafe { s.agg_first(&groups) };
         let counts = groups.group_lengths("counts");
         let cols = vec![values, counts.into_series()];
-        let df = DataFrame::new_no_checks(cols);
```
Comment (stinodego) [inline crates/polars-ops/src/series/ops/various.rs:20]: This was the issue - a check is needed on the column name as it CAN contain a duplicate.

File: py-polars/polars/expr/expr.py [hunk 2]
```diff
@@ -8269,48 +8269,62 @@ def extend_constant(self, value: PythonLiteral | None, n: int) -> Self:
 
         return self._from_pyexpr(self._pyexpr.extend_constant(value, n))
 
-    def value_counts(self, *, multithreaded: bool = False, sort: bool = False) -> Self:
+    @deprecate_renamed_parameter("multithreaded", "parallel", version="0.19.0")
+    def value_counts(self, *, sort: bool = False, parallel: bool = False) -> Self:
```
Comment (stinodego) [inline py-polars/polars/expr/expr.py:8273]: I switched the parameters here. I believe the "what" should come before the "how". i.e. `parallel` won't impact the result, only how it's computed. So these params should come last if possible.

File: crates/polars-ops/src/series/ops/various.rs (hunk 1 above)
Comment (reswqa) [reply crates/polars-ops/src/series/ops/various.rs:20]: How about directly check self.name() and ＂counts" to avoid other overhead introduced by DataFrame::new. But it shouldn't cost mush as we only have two columns here，it's up tp you :）

Comment (stinodego) [reply crates/polars-ops/src/series/ops/various.rs:20]: That would be more efficient! Can do that.

**Review by ritchie46 — APPROVED** [review]

**Review by ritchie46 — APPROVED** [review]
