### PR TITLE
fix: Add `Expr.sign` for `Decimal` datatype

### LINKED ISSUE #24715: `Expr.sign()` unsupported error on `polars.Decimal` datatype
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({'dec_col' : pl.Series(['1.0','-1.0','0'], dtype=pl.Decimal(None,2))})

df.with_columns(pl.col('dec_col').sign())
```

### Log output

```shell
---------------------------------------------------------------------------
InvalidOperationError                     Traceback (most recent call last)
Cell In[69], line 4
      1 import polars as pl
      2 df = pl.DataFrame({'dec_col' : pl.Series(['1.0','-1.0','0'], dtype=pl.Decimal(None,2))})
----> 4 df.with_columns(pl.col('dec_col').sign())

File ~\python\Lib\site-packages\polars\dataframe\frame.py:10022, in DataFrame.with_columns(self, *exprs, **named_exprs)
   9895 """
   9896 Add columns to this DataFrame.
   9897 
   (...)
  10015 └─────┴──────┴───────┴──────┴───────┘
  10016 """
  10017 from polars.lazyframe.opt_flags import QueryOptFlags
  10019 return (
  10020     self.lazy()
  10021     .with_columns(*exprs, **named_exprs)
> 10022     .collect(optimizations=QueryOptFlags._eager())
  10023 )

File ~\python\Lib\site-packages\polars\_utils\deprecation.py:97, in deprecate_streaming_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
     93         kwargs["engine"] = "in-memory"
     95     del kwargs["streaming"]
---> 97 return function(*args, **kwargs)

File ~\python\Lib\site-packages\polars\lazyframe\opt_flags.py:330, in forward_old_opt_flags.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    327         optflags = cb(optflags, kwargs.pop(key))  # type: ignore[no-untyped-call,unused-ignore]
    329 kwargs["optimizations"] = optflags
--> 330 return function(*args, **kwargs)

File ~\python\Lib\site-packages\polars\lazyframe\frame.py:2335, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, collapse_joins, no_optimization, engine, background, optimizations, **_kwargs)
   2333 # Only for testing purposes
   2334 callback = _kwargs.get("post_opt_callback", callback)
-> 2335 return wrap_df(ldf.collect(engine, callback))

InvalidOperationError: `sign` operation not supported for dtype `decimal[*,2]` as argument 0
```

### Issue description

The ability to apply the sign() method on a signed numeric data type does not appear to be implemented.

### Expected behavior

Like other signed numeric data types (Int16, Int32, Float32, Float64 etc.), the `Expr.sign()` operator should return -1, 1 , or 0/NaN depending on the sign of the value in the column for polars `Decimal` types.

### Installed versions

<details>

--------Version info---------
Polars:              1.33.1
Index type:          UInt32
Platform:            Windows-11-10.0.26100-SP0
Python:              3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               5.5.0
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          3.1.1
connectorx           <not installed>
deltalake            <not installed>
fastexcel            0.12.0
fsspec               2025.3.2
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.10.0
numpy                2.2.6
openpyxl             3.1.5
pandas               2.3.0
polars_cloud         <not installed>
pyarrow              18.1.0
pydantic             2.11.7
pyiceberg            <not installed>
sqlalchemy           2.0.41
torch                2.6.0+cpu
xlsx2csv             0.8.4
xlsxwriter           3.2.9

</details>

### PR DESCRIPTION
**Pull request by coastalwhite**
Fixes #24715.

### CODE REVIEW

File: crates/polars-plan/src/plans/aexpr/function_expr/sign.rs [hunk 1]
```diff
@@ -5,12 +5,34 @@ use super::*;
...
-    })
+    let dtype = s.dtype();
+    match dtype {
+        _ if dtype.is_primitive_numeric() => with_match_physical_numeric_polars_type!(dtype, |$T| {
+            let ca: &ChunkedArray<$T> = s.as_ref().as_ref();
+            Ok(sign_impl(ca))
+        }),
+        DataType::Decimal(_, scale) => {
+            let ca = s.decimal()?;
+
```
Comment (orlp) [inline crates/polars-plan/src/plans/aexpr/function_expr/sign.rs]: Can you add this implementation to `polars-compute/src/decimal.rs` and call that instead of doing it here?

```rust
#[inline(always)]
pub fn dec128_sign(x: i128, s: usize) -> i128 {
    if x < 0 {
        -POW10_I128[s]
    } else if x > 0 {
        POW10_I128[s]
    } else {
        0
    }
}
```

I prefer it if we keep all arithmetic implementations centralized there.

**Review by orlp — APPROVED** [review]
