### PR TITLE
fix: Fix handling of UTF-8 in `write_csv` to `IO[str]`

### LINKED ISSUE #23629: polars.DataFrame.write_csv corrupts or fails with Unicode strings after upgrade from 1.30
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import os

os.environ['POLARS_VERBOSE'] = '1'  # Enable verbose logging for Polars


import polars as pl
from io import StringIO
import random

# Helper functions
def random_unicode_string(length=10):
    valid_ranges = [
        (0x0020, 0x007E),   # Basic Latin (printable ASCII)
        (0x00A0, 0x00FF),   # Latin-1 Supplement (mostly printable)
        (0x0400, 0x04FF),   # Cyrillic
    ]
    
    return ''.join(chr(random.randint(r[0], r[1])) for _ in range(length) for r in [random.choice(valid_ranges)])


def generate_data(num_cols=10, num_rows=10):
    data = {
        f'col{i+1}': [random_unicode_string(10) for _ in range(num_rows)]
        for i in range(num_cols)
    }
    return data

def main():
    data = generate_data(num_rows=15, num_cols=10)
    df = pl.DataFrame(data)

    buffer = StringIO()
    df.write_csv(buffer, include_header=False)
    buffer.seek(0)
    
    df_from_csv = pl.read_csv(buffer, has_header=False, schema=df.schema)

    if not df_from_csv.equals(df):
        ValueError("DataFrame from CSV does not match original DataFrame")
    print("DataFrame from CSV matches original DataFrame")
    

if __name__ == "__main__":
    main()

```

### Log output

```shell
Either

_init_credential_provider_builder(): credential_provider_init = None
Traceback (most recent call last):
  File ".../main.py", line 73, in <module>
    main()
    ~~~~^^
  File ".../main.py", line 68, in main
    batch.write_csv(buffer, include_header=False)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/polars/dataframe/frame.py", line 3073, in write_csv
    self.lazy().sink_csv(
    ~~~~~~~~~~~~~~~~~~~~^
        target,
        ^^^^^^^
    ...<17 lines>...
        engine=engine,
        ^^^^^^^^^^^^^^
    )
    ^
  File ".../.venv/lib/python3.13/site-packages/polars/lazyframe/frame.py", line 3300, in sink_csv
    ldf.collect(engine=engine)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/polars/_utils/deprecation.py", line 97, in wrapper
    return function(*args, **kwargs)
  File ".../.venv/lib/python3.13/site-packages/polars/lazyframe/opt_flags.py", line 330, in wrapper
    return function(*args, **kwargs)
  File ".../.venv/lib/python3.13/site-packages/polars/lazyframe/frame.py", line 2332, in collect
    return wrap_df(ldf.collect(engine, callback))


----
or the csv with the last lines broken resulting in:
----


_init_credential_provider_builder(): credential_provider_init = None
Traceback (most recent call last):
  File "/home/pkludig/Documents/Senger/SoftwareProjects/TestPolarsBug/main.py", line 86, in <module>
    main()
    ~~~~^^
  File "/home/pkludig/Documents/Senger/SoftwareProjects/TestPolarsBug/main.py", line 77, in main
    batch_from_csv = pl.read_csv(buffer, has_header=False, schema=batch.schema)
  File "/home/pkludig/Documents/Senger/SoftwareProjects/TestPolarsBug/.venv/lib/python3.13/site-packages/polars/_utils/deprecation.py", line 128, in wrapper
    return function(*args, **kwargs)
  File "/home/pkludig/Documents/Senger/SoftwareProjects/TestPolarsBug/.venv/lib/python3.13/site-packages/polars/_utils/deprecation.py", line 128, in wrapper
    return function(*args, **kwargs)
  File "/home/pkludig/Documents/Senger/SoftwareProjects/TestPolarsBug/.venv/lib/python3.13/site-packages/polars/_utils/deprecation.py", line 128, in wrapper
    return function(*args, **kwargs)
  File "/home/pkludig/Documents/Senger/SoftwareProjects/TestPolarsBug/.venv/lib/python3.13/site-packages/polars/io/csv/functions.py", line 549, in read_csv
    df = _read_csv_impl(
        data,
    ...<27 lines>...
        glob=glob,
    )
  File "/home/pkludig/Documents/Senger/SoftwareProjects/TestPolarsBug/.venv/lib/python3.13/site-packages/polars/io/csv/functions.py", line 697, in _read_csv_impl
    pydf = PyDataFrame.read_csv(
        source,
    ...<28 lines>...
        schema=schema,
    )
polars.exceptions.ComputeError: could not parse `ё҃É§` as dtype `i64` at column 'col1' (column number 1)

The current offset in the file is 4665 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `ё҃É§` to the `null_values` list.

Original error:  bytes non-empty
```

### Issue description

My example code does two things, depending on which charackters are generated:

- completely break the writing process. This was unintentional and could be due to the way the strings are generated. I'm not sure if this is a bug or I unintentionally hit some weird characters that should not appear.

- Produce a corrupted csv, where the last line(s) are missing columns. This happened to me with a dataframe I can't share and this is as close to reproducing it as I could manage in a reasonable time. This worked fine until polars ~1.30~ 1.29 and seems to be broken now.

Note that the slicing is not necessary, but the nature of the random function makes the first event more probable so it helps with increasing the probability to also see the second one. Also, I'm sorry for having random data in an example ...

### Expected behavior

Correct csv output with all the data

### Installed versions

<details>

```
>>> import polars as pl
>>> pl.show_versions()
--------Version info---------
Polars:              1.31.0
Index type:          UInt32
Platform:            Linux-6.8.0-60-generic-x86_64-with-glibc2.35
Python:              3.13.3 (main, Apr  9 2025, 04:03:52) [Clang 20.1.0 ]
LTS CPU:             False

----Optional dependencies----
Azure CLI            2.58.0
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.3.1
openpyxl             <not installed>
pandas               <not installed>
polars_cloud         <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #23629 

ping @coastalwhite

### CODE REVIEW

File: crates/polars-python/src/file.rs [hunk 1]
```diff
@@ -184,14 +202,25 @@ impl Write for PyFileLikeObject {
                     None,
                 )
```
Comment (coastalwhite) [inline crates/polars-python/src/file.rs]: The code below can be put here, and it would be easier to follow the flow.

File: crates/polars-python/src/file.rs [hunk 2]
```diff
@@ -184,14 +202,25 @@ impl Write for PyFileLikeObject {
...
-
-            Ok(n)
+            let n = char_or_bytes_written.extract(py).map_err(pyerr_to_io_err)?;
+            let n_bytes = if expects_str && !expects_str_and_is_ascii {
+                // substitute char count with buf len
+                let expected_chars = std::str::from_utf8(buf)
+                    .map_err(io::Error::other)?
+                    .chars()
+                    .count();
+                assert!(n == expected_chars);
```
Comment (coastalwhite) [inline crates/polars-python/src/file.rs]: I think this is not what you want. You want to do is find the offset of the nth char. This would go wrong if you have a rate limited network interface for instance. You can use `.char_indices().nth(n).map(|(i, _)| i).expect("...")` for this.

```

**Review by coastalwhite — CHANGES_REQUESTED** [review]

**Review by coastalwhite — APPROVED** [review]
