### PR TITLE
perf: Fix pathological perf issue in window-order-by

### LINKED ISSUE #17637: Performance: Calculation 200x+ slower without rechunking or sorting first
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df_sales = pl.read_parquet(PATH_SALES)
# simple df (10_000_000, 5)

df_sales.with_columns(
    time_between_sales=pl.col("created_on")
    .diff()
    .over(
        partition_by="customer_id",
        order_by="created_on",
    ),
)
```

### Log output

_No response_

### Issue description

I created a simple sales_df with polars that I saved as parquet.
When I read the data back in and do a simple window calculation the performance is super slow (~70 sec).

However if I
- `rechunk()` or
- `.sort("created_on", "customer_id")`

first the performance is ~200x++ faster (~0.3 sec)

possibly related: #17562

### Expected behavior

Great Performance as usual 😄 

When I read a df that I just saved using polars I expect good performance without need to explicitly rechunk myself.

### Installed versions

<details>

```
1.1.0
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #17637

### CODE REVIEW

File: crates/polars-expr/src/expressions/sortby.rs [hunk 1]
```diff
@@ -58,10 +58,14 @@ pub(super) fn update_groups_sort_by(
     sort_by_s: &Series,
     options: &SortOptions,
 ) -> PolarsResult<GroupsProxy> {
-    let groups = groups
-        .par_iter()
-        .map(|indicator| sort_by_groups_single_by(indicator, sort_by_s, options))
-        .collect::<PolarsResult<_>>()?;
+    // Will trigger a gather for every group, so rechunk before.
+    let sort_by_s = sort_by_s.rechunk();
+    let groups = POOL.install(|| {
```
Comment (ritchie46) [inline crates/polars-expr/src/expressions/sortby.rs:63]: We forgot to launch on our thread pool, so for every group our thread pool was contending with rayon's default. This improved the single chunk query 7 times on a debug build for me.

File: crates/polars-expr/src/expressions/sortby.rs [hunk 2]
```diff
@@ -58,10 +58,14 @@ pub(super) fn update_groups_sort_by(
     sort_by_s: &Series,
     options: &SortOptions,
 ) -> PolarsResult<GroupsProxy> {
-    let groups = groups
-        .par_iter()
-        .map(|indicator| sort_by_groups_single_by(indicator, sort_by_s, options))
-        .collect::<PolarsResult<_>>()?;
+    // Will trigger a gather for every group, so rechunk before.
```
Comment (ritchie46) [inline crates/polars-expr/src/expressions/sortby.rs:61]: This was the culprit.
