### PR TITLE
fix(rust, python): fix date/datetime parsing for short inputs with exact=False

### LINKED ISSUE #10223: `PanicException` for `str.to_date` & `str.to_datetime` with `strict=False`
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.Series(
    name='date',
    values=['2019-01-01', 'ab'], # <<< PanicException
    # values=['2019-01-01', 'a'], # <<< This does NOT Panic
).str.to_date(exact=False)

pl.Series(
    name='datetime',
    values=['2019-01-01 00:00:00', 'ab'], # <<< PanicException
    # values=['2019-01-01 00:00:00', 'a'], # <<< This does NOT Panic
).str.to_datetime(exact=False)
```

### Issue description

`str.to_date` & `str.to_datetime` panic when `strict=False` and text cannot be parsed and has length of >1 it seems

### Expected behavior

normal `ComputeError` with conversion/parsing failed message

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            macOS-12.6.1-x86_64-i386-64bit
Python:              3.11.4 (main, Jul 25 2023, 17:08:27) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #10223

### CODE REVIEW

File: crates/polars-time/src/chunkedarray/utf8/mod.rs [hunk 1]
```diff
@@ -29,54 +29,33 @@ fn datetime_pattern<F, K>(val: &str, convert: F) -> Option<&'static str>
...
-        // microseconds
-        "%Y-%m-%d %H:%M:%S.%6f",
-        "%Y-%m-%dT%H:%M:%S.%6f",
-        // nanoseconds
-        "%Y-%m-%d %H:%M:%S.%9f",
-        "%Y-%m-%dT%H:%M:%S.%9f",
-    ]
-    .into_iter()
-    .find(|&fmt| convert(val, fmt).is_ok())
+    let result = patterns::DATETIME_Y_M_D
```
Comment (ritchie46) [inline crates/polars-time/src/chunkedarray/utf8/mod.rs:32]: Is this the gist of the change? That we search in another set?

Comment (MarcoGorelli) [reply crates/polars-time/src/chunkedarray/utf8/mod.rs:32]: hey - sorry, I wanted to leave some commentary but it was getting late, I should've left it in 'draft'

The gist of the change is
```diff
-                    for i in 1..(s.len() - fmt_len) {
+                    for i in 1..(s.len().saturating_sub(fmt_len)) {
```
which avoid the panic error

The change in this file is a drive-by cleanup - the formats are duplicated between here and `patterns.rs`, so this reduces the difference between `exact=True` and `exact=False`

Comment (ritchie46) [reply crates/polars-time/src/chunkedarray/utf8/mod.rs:32]: Great, thanks!
