### PR TITLE
fix(rust): correct assertion

### LINKED ISSUE #9128: Groupby.agg from within apply_multiple works in 0.28 but 0.30 "panicked at 'assertion failed: !arr.has_validity()" when a column has NULLs
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

The code below (presumably valid) worked in `0.28` but fails with `0.30`:
```
thread '<unnamed>' panicked at 'assertion failed: !arr.has_validity()', C:\Users\Anato\.cargo\registry\src\github.com-1ecc6299db9ec823\polars-arrow-0.30.0\src\kernels\take_agg\mod.rs:29:
```

### Reproducible example - Updated Simplified

**Note: in the below example what causes panic is None vaues in s0**

```rust
use polars::prelude::*;

pub fn lists(){
    // let s0 = Series::new("B", [Some(1), Some(2), Some(4), Some(4)]);   <--- this would work
    let s0 = Series::new("B", [Some(1), Some(2), None, None]);
    let s1 = Series::new("C", [1, 1, 2, 4]);
    let s2 = Series::new("F", ["1", "1", "1", "1"]);
    let df = DataFrame::new(vec![s0, s1, s2]).unwrap();

    let res = df.lazy()
        .groupby([col("C")])
        .agg([
            inner()
        ])
        .collect().unwrap();
    dbg!(res);
}

fn inner() -> Expr {
    apply_multiple(
        move |columns| {
            let df = df![
                "F" => &columns[0],
                "B" => &columns[1],
            ].unwrap();
            let df = df.lazy()
                .groupby([col("F")])
                .agg([
                    col("B").sum().alias("s")
                ])
                .collect().unwrap();
            
            return Ok(Some(Series::new("res", [0.]))); // dummy return
        },
        &[
            col("F"),
            col("B")
        ],
        GetOutput::from_type(DataType::Float64),
        true
    )
}
```

### Expected behavior

This code should work

### Installed versions

0.30

### PR DESCRIPTION
**Pull request by AnatolyBuga**
bug fix + a useful unit test for complex aggregation

### CODE REVIEW

File: polars/tests/it/lazy/aggregation.rs [hunk 1]
```diff
@@ -95,3 +95,55 @@ fn test_apply_multiple_error() {
         .collect()
         .unwrap();
 }
+
+#[test]
```
Comment (ritchie46) [inline polars/tests/it/lazy/aggregation.rs:99]: I am not really sure about this test. I think just changing the assert is fine

Comment (AnatolyBuga) [reply polars/tests/it/lazy/aggregation.rs]: Thanks @ritchie46 , I've removed the integration unittest. Although personally I think it could be a good one as it touches on multiple important parts. If you change your mind lmk I will plug it back in.

File: polars/polars-arrow/src/kernels/take_agg/mod.rs [hunk 2]
```diff
@@ -26,7 +25,7 @@ pub unsafe fn take_agg_no_null_primitive_iter_unchecked<
     f: F,
     init: TOut,
 ) -> TOut {
-    debug_assert!(!arr.has_validity());
+    assert!(arr.null_count() == 0);
```
Comment (ritchie46) [inline polars/polars-arrow/src/kernels/take_agg/mod.rs:28]: This should only be a debug assert.

Comment (AnatolyBuga) [reply polars/polars-arrow/src/kernels/take_agg/mod.rs]: @ritchie46 , pls approve
