### PR TITLE
fix: correct `truncate` when truncating by multiple weeks

### LINKED ISSUE #12937: pl.Series.dt.truncate("2w") truncates to 1 week instead
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
import polars as pl 
import datetime as dt 
print(pl.Series([dt.datetime(2022, 1, i) for i in range(1, 30, 3)]).dt.truncate("2w"))
```
outputs the following: 
```
output: 
shape: (10,)
Series: '' [datetime[μs]]
[
        2021-12-20 00:00:00
        2021-12-27 00:00:00
        2021-12-27 00:00:00
        2022-01-03 00:00:00
        2022-01-03 00:00:00
        2022-01-03 00:00:00
        2022-01-10 00:00:00
        2022-01-10 00:00:00
        2022-01-17 00:00:00
        2022-01-17 00:00:00
]
```

### Log output

_No response_

### Issue description

When truncating datetime column to N weeks, the output is still different by only 1 week. 

It is not the case for days or months. E.g. dt.truncate("14d") is what I expect it to be - outputs will be e.g Dec 23, Jan 6, Jan 20

Increasing the # of weeks seems to push the start of the period back, but the outputs are still spaced by 1 week.

### Expected behavior

I expect weeks to behave the same way as days and months. 

### Installed versions

<details>

```
--------Version info---------
Polars:               0.19.19
Index type:           UInt32
Platform:             Linux-6.2.0-37-generic-x86_64-with-glibc2.35
Python:               3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               2023.10.0
gevent:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.2
openpyxl:             3.1.2
pandas:               2.1.3
pyarrow:              14.0.1
pydantic:             2.5.1
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           1.4.50
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #12937

haven't timed this yet, but it should come with a nice perf improvement, as for the naive case the arithmetic can all be done on the underlying integers

UPDATE
------

Timing result from truncating 50 million rows by 3 weeks: https://www.kaggle.com/code/marcogorelli/polars-timing?scriptVersionId=154070136

- main: 2.8141296769999826
- here: 2.207328452333362

That's > 20% improvement!

### CODE REVIEW

File: crates/polars-time/src/windows/duration.rs [hunk 1]
```diff
@@ -487,40 +487,52 @@ impl Duration {
...
+        // If we did
+        //   t - (t % (7 * self.weeks * daily_duration))
+        // then the timestamp would get truncated to the previous Thursday,
+        // because 1970-01-01 (timestamp 0) is a Thursday.
+        // So, we adjust by 4 days to get to Monday.
+        let mut remainder = (t - 4 * daily_duration) % (7 * self.weeks * daily_duration);
+        if remainder < 0 {
+            remainder += 7 * self.weeks * daily_duration
+        }
+        let result_t_local = t - remainder;
```
Comment (MarcoGorelli) [inline crates/polars-time/src/windows/duration.rs:522]: This is the gist of the change

Instead of using Chrono to go to the previous monday, just do the arithmetic on the underlying integers - this matches the pattern used in `truncate_subweekly`

File: crates/polars-time/src/windows/duration.rs [hunk 2]
```diff
@@ -412,32 +412,32 @@ impl Duration {
...
     ///   original datetime was 2022-11-06 01:30:00 CST, then this would
     ///   be 2022-11-06 07:30:00.
-    /// * `result_dt_naive` - result, without time zone.
+    /// * `result_dt_local` - result, without time zone.
     #[cfg(feature = "timezones")]
     fn localize_result(
         &self,
-        original_dt_naive: NaiveDateTime,
+        original_dt_local: NaiveDateTime,
         original_dt_utc: NaiveDateTime,
```
Comment (MarcoGorelli) [inline crates/polars-time/src/windows/duration.rs:426]: drive-by: improve naming (both `original_dt_naive` and `original_dt_utc` are `NaiveDateTime`, so this should reduce confusion. The docstring above the function definition explains the difference)

File: py-polars/tests/unit/datatypes/test_temporal.py [hunk 3]
```diff
@@ -2312,14 +2312,35 @@ def test_truncate_by_multiple_weeks() -> None:
...
-        "3w": [date(2022, 4, 4), date(2022, 11, 14)],
-        "4w": [date(2022, 3, 28), date(2022, 11, 7)],
-        "5w": [date(2022, 3, 21), date(2022, 10, 31)],
-        "17w": [date(2021, 12, 27), date(2022, 8, 8)],
+        "2w": [date(2022, 4, 18), date(2022, 11, 28)],
+        "3w": [date(2022, 4, 11), date(2022, 11, 28)],
+        "4w": [date(2022, 4, 18), date(2022, 11, 28)],
+        "5w": [date(2022, 3, 28), date(2022, 11, 28)],
+        "17w": [date(2022, 2, 21), date(2022, 10, 17)],
     }
```
Comment (MarcoGorelli) [inline py-polars/tests/unit/datatypes/test_temporal.py:2320]: this one wasn't quite correct to begin with

**Review by ritchie46 — APPROVED** [review]
