### PR TITLE
fix: Honor `n=0` in all cases of `str.replace`

### LINKED ISSUE #23570: `.str.replace(…, value=Expr, n={0, 1})` produces identical output
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl # 1.31.0

df = pl.DataFrame({'a': ['abc abc abc', 'abc ghi'], 'b': ['jkl', 'xyz']})
out = df.select(
    pl.col('a').str.replace('abc', 'XYZ', n=0).alias('.str.replace(…, str, n=0)'),
    pl.col('a').str.replace('abc', pl.col('b'), n=0).alias('.str.replace(…, Expr, n=0)'),

)
print(out)
```

Produces

```
shape: (2, 2)
┌───────────────────────────┬────────────────────────────┐
│ .str.replace(…, str, n=0) ┆ .str.replace(…, Expr, n=0) │
│ ---                       ┆ ---                        │
│ str                       ┆ str                        │
╞═══════════════════════════╪════════════════════════════╡
│ abc abc abc               ┆ jkl abc abc                │
│ abc ghi                   ┆ xyz ghi                    │
└───────────────────────────┴────────────────────────────┘
```

### Log output

```shell

```

### Issue description

`Expr.str.replace` allows one to specify an expression as its value and is currently limits users to also pass `n <= 1`. However, I noticed that `n=0` produces a replacement. This is in contrast to `.str.replace(…, value=str, n=0)` which performs no replacements.

### Expected behavior

I would expect that `n=0` to make no replacements regardless of the type passed to `value` in `.str.replace(…, value=…)`.
```
shape: (2, 2)
┌───────────────────────────┬────────────────────────────┐
│ .str.replace(…, str, n=0) ┆ .str.replace(…, Expr, n=0) │
│ ---                       ┆ ---                        │
│ str                       ┆ str                        │
╞═══════════════════════════╪════════════════════════════╡
│ abc abc abc               ┆ abc abc abc                │
│ abc ghi                   ┆ abc ghi                    │
└───────────────────────────┴────────────────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              1.31.0
Index type:          UInt32
Platform:            Linux-6.12.33-1-lts-x86_64-with-glibc2.41
Python:              3.11.0rc1 (main, Oct 26 2022, 10:50:14) [GCC 12.2.0]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  1.7.0
altair               5.5.0
azure.identity       <not installed>
boto3                1.38.27
cloudpickle          3.1.1
connectorx           0.4.3
deltalake            1.0.2
fastexcel            0.14.0
fsspec               2025.5.1
gevent               25.5.1
google.auth          2.40.3
great_tables         0.18.0
matplotlib           3.10.3
numpy                2.2.6
openpyxl             3.1.5
pandas               2.3.1
polars_cloud         0.0.10
pyarrow              20.0.0
pydantic             2.11.7
pyiceberg            <not installed>
sqlalchemy           2.0.41
torch                <not installed>
xlsx2csv             0.8.4
xlsxwriter           3.2.5```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #23570

In addition, this PR has proposed code simplification similar to https://github.com/pola-rs/polars/pull/6777

Code is pending selection of preferred implementation option and review. 
*Edit: ready for review.

### CODE REVIEW

File: crates/polars-plan/src/plans/aexpr/function_expr/strings.rs [hunk 1]
```diff
@@ -1006,18 +1006,19 @@ fn replace_n<'a>(
...
-                } else {
-                    // According to the docs for replace
-                    // when literal = True then capture groups are ignored.
-                    if literal {
-                        reg.replace(s, NoExpand(val))
-                    } else {
-                        reg.replace(s, val)
-                    }
+                match n {
+                    0 => Cow::Borrowed(s),
```
Comment (orlp) [inline crates/polars-plan/src/plans/aexpr/function_expr/strings.rs]: If `n == 0` why are we still looping over the entire input? Can't we just return `ca` directly?

Comment (kdn36) [reply crates/polars-plan/src/plans/aexpr/function_expr/strings.rs]: Good point. Done.
