### PR TITLE
fix(rust,python): Fix predicate pushdown into inequality joins

### LINKED ISSUE #19580: join_where returns different results depending on order of equality expressions
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

from polars.testing import assert_frame_equal

left = pl.LazyFrame(
    {
        "a": [1, 2, 3, 1, None],
        "b": [1, 2, 3, 4, 5],
        "c": [2, 3, 4, 5, 6],
    }
)

right = pl.LazyFrame(
    {
        "a": [1, 4, 3, 8, None, None, 1],
        "c": [2, 3, 4, 5, 6, 7, 8],
        "d": [6, None, 3, 8, -1, 2, 4],
    }
)


q_good = left.join_where(
    right,
    pl.col("a") < pl.col("d"),
    pl.col("b") < pl.col("c_right"),
    pl.col("a") < pl.col("a_right"),
)

q_bad = left.join_where(
    right,
    pl.col("b") < pl.col("c_right"),
    pl.col("a") < pl.col("a_right"),
    pl.col("a") < pl.col("d"),
)

q_expect = (
    left.join(right, how="cross")
    .collect()
    .filter(
        (pl.col("a") < pl.col("d"))
        & (pl.col("b") < pl.col("c_right"))
        & (pl.col("a") < pl.col("a_right"))
    )
)

assert_frame_equal(q_expect, q_good.collect(), check_row_order=False)
assert_frame_equal(q_expect, q_bad.collect(), check_row_order=False)
```

### Log output

```shell
join parallel: true
IEJOIN join dataframes finished
dataframe filtered
join parallel: true
IEJOIN join dataframes finished
join parallel: true
CROSS join dataframes finished
dataframe filtered
dataframe filtered
dataframe filtered
```

### Issue description

My understanding of `join_where` is that the conditions are ANDed together to produce the filter on the output table. 

When more than two conditions are applied the third and subsequent conditions are not applied in the `ie_join` implementation itself, but are instead done as postfilters on the result.

However, it looks like the normalisation rule for these filters does different things depending on the exact schemas of the left and right tables.

```
print(q_good.explain())
FILTER [(col("a")) < (col("a_right"))] FROM
  IEJOIN JOIN:
  LEFT PLAN ON: [col("a"), col("b")]
    DF ["a", "b", "c"]; PROJECT */3 COLUMNS; SELECTION: None
  RIGHT PLAN ON: [col("d"), col("c")]
    DF ["a", "c", "d"]; PROJECT */3 COLUMNS; SELECTION: None
  END IEJOIN JOIN
```

```
print(q_bad.explain())
IEJOIN JOIN:
LEFT PLAN ON: [col("b"), col("a")]
  DF ["a", "b", "c"]; PROJECT */3 COLUMNS; SELECTION: None
RIGHT PLAN ON: [col("c"), col("a")]
  DF ["a", "c", "d"]; PROJECT */3 COLUMNS; SELECTION: [(col("a")) < (col("d"))]
END IEJOIN JOIN
```

Notice how in the bad case, the condition `col("a") < col("d")` has been pushed into a selection on the right dataframe. However, this is not right, by the semantics of `join_where`, `col("a")` refers to the column in the left table, whereas `col("d")` refers to the column in the right table.

### Expected behavior

I expect `q_good` and `q_bad` to produce the same result, matching `q_expect`.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.12.0
Index type:          UInt32
Platform:            Linux-6.8.0-48-generic-x86_64-with-glibc2.35
Python:              3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          3.1.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         1.6.0
numpy                2.0.2
openpyxl             3.1.5
pandas               2.2.3
pyarrow              17.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           2.0.36
torch                2.4.1.post302
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by wence-**
Inequality joins are, from the optimizer's point of view, the same as cross joins: they logically produce a cartesian product that is then filtered. Consequently, if a predicate combines columns from both tables, we cannot push the filter into the join.

- Fixes #19580

### CODE REVIEW

File: crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs [hunk 1]
```diff
@@ -149,7 +149,8 @@ pub(super) fn process_join(
 
     for (_, predicate) in acc_predicates {
         // Cross joins produce a cartesian product, so if a predicate combines columns from both tables, we should not push down.
-        if matches!(options.args.how, JoinType::Cross)
+        // Inequality joins logically produce a cartesian product, so the same logic applies.
+        if (matches!(options.args.how, JoinType::Cross) || options.args.how.is_ie())
```
Comment (ritchie46) [inline crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs:153]: Let's add an `is_cross` as well. Looks a bit cleaner. :)

**Comment by ritchie46** [comment]
Thanks Lawrence!

File: crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs (hunk 1 above)
Comment (wence-) [reply crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs]: Done. I used it in the other places we previously did the `matches!` dance as well.
