### PR TITLE
refactor: Fix rolling kernel dispatch with `monotonic` group attribute

### LINKED ISSUE #25434: Panic in rolling sum with varying window size
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"Value": [1, 2, 3, 4], "Window_size": [3, 1, 1, 2]})

df.with_row_index().select(
    pl.col("Value").slice(1, pl.col("Window_size").first()).sum()
    .rolling("index", period=f"{df.height}i", offset="0i", closed="left")
)
```

### Log output

```shell
thread 'polars-6' (4736065) panicked at /Users/runner/work/polars/polars/crates/polars-compute/src/rolling/sum.rs:141:31:
slice index starts at 4 but ends at 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "pl_rolling_panic.py", line 5, in <module>
    df.with_row_index().select(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        pl.col("Value").slice(1, pl.col("Window_size").first()).sum()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        .rolling("index", period=f"{df.height}i", offset="0i", closed="left")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/polars/dataframe/frame.py", line 10144, in select
    .collect(optimizations=QueryOptFlags._eager())
     ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/polars/_utils/deprecation.py", line 97, in wrapper
    return function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/polars/lazyframe/opt_flags.py", line 328, in wrapper
    return function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/polars/lazyframe/frame.py", line 2422, in collect
    return wrap_df(ldf.collect(engine, callback))
                   ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: slice index starts at 4 but ends at 3
```

### Issue description

I encountered a very weird bug. My goal is to calculate the sum of the next `Window_size` values. My strategy is to select the rest of the data frame for each row with `rolling()` and then slice appropriately using the `Window_size` of the row as the slice length. Changing either the first or the second `Window_size` to 2 prevents the panic. So the individual window sizes are not at fault, but their specific combination. It doesn't seem to happen with functions other than sum, so now I use `cum_sum().last()` as a workaround.

### Expected behavior

No error.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.35.2
Index type:          UInt32
Platform:            macOS-26.1-arm64-arm-64bit-Mach-O
Python:              3.14.0 (v3.14.0:ebf955df7a8, Oct  7 2025, 08:20:14) [Clang 16.0.0 (clang-1600.0.26.6)]
Runtime:             rt32
----Optional dependencies----
Azure CLI            2.67.0
adbc_driver_manager  1.8.0
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          3.1.1
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2025.9.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.10.7
numpy                2.3.5
openpyxl             3.1.5
pandas               2.3.3
polars_cloud         <not installed>
pyarrow              22.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                2.9.0
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #25434 

This also fixes an undocumented issue whereby the rolling group sum kernel returns `None` on empty groups instead of `0`.

This PR introduces the `monotonic` attribute for `groups`. It is used now -- in combination with `overlapping` -- for dispatch to the rolling kernel, but it can be leveraged for other use cases in the future.

The dispatch logic has been tested one-off for correct dispatch on `rolling` and `group_by_dynamic`, and against false misclassifications on the CI suite. Still, it is possible that it gets misclassified now or later, but the impact is limited.

Confirmed following the rolling agg kernel for sum:
- `group_by_dynamic`
- `rolling`
- `rolling` in `group_by`
- `group_by_dynamic` with `by` argument

This PR replaces https://github.com/pola-rs/polars/pull/25470

### CODE REVIEW

**Comment by kdn36** [comment]
> Now that we have these `overlapping` and `monotonic` attributes, setting them wrong somewhere can be disastrous. Can you replace all instances where we create a `GroupsType` with some sort of constructor (for example `GroupStype::new_slice(groups, overlapping, monotonic)`) which when `#[cfg(debug_assertions)]` is true actually checks those properties? That should allow us to catch bugs early in the CI.

Yes, for sure. That said, I’m just as concerned about the scenario where we set it correctly initially, but the groups later change and the attribute isn’t updated. We could put the attribute behind a getter and add run-time verification in debug builds, to be exercsied in CI and when debugging issues. These attributes aren’t accessed often and are typically used only for dispatch between different implementation paths.

File: crates/polars-core/src/frame/group_by/position.rs [hunk 1]
```diff
@@ -271,6 +273,64 @@ impl Default for GroupsType {
...
+                        return true;
+                    }
+                    if end > prev_end {
+                        prev_end = end;
+                    }
+                }
+                false
+            }
+
+            assert!(!groups_overlap(&groups) || overlapping);
```
Comment (orlp) [inline crates/polars-core/src/frame/group_by/position.rs]: Swap the order, only do the test if it's claimed the groups aren't overlapping:

```rust
assert!(overlapping || !groups_overlap(&groups));
```

You always want to put cheap conditions before expensive conditions if possible.

File: crates/polars-core/src/frame/group_by/position.rs [hunk 2]
```diff
@@ -271,6 +273,64 @@ impl Default for GroupsType {
...
+                    if start < prev_start || end < prev_end {
+                        return false;
+                    }
+
+                    prev_start = start;
+                    prev_end = end;
+                }
+                true
+            }
+            assert!(groups_are_monotonic(&groups) || !monotonic);
```
Comment (orlp) [inline crates/polars-core/src/frame/group_by/position.rs]: Same here.

File: crates/polars-core/src/frame/group_by/position.rs (hunk 1 above)
Comment (kdn36) [reply crates/polars-core/src/frame/group_by/position.rs]: Excellent point.
