### PR TITLE
fix(rust,python): handle edge-case with string-literal replacement when the replace value looks like a capture group

### LINKED ISSUE #6755: `str.replace` and `str.replace_all` cannot replace with the literal string "$0" when `literal=True`. (but only in some cases)
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Replacing some strings with `$0` will replace it with itself, even when `literal=True`. When replacing with `$1` it will replace with empty string.

It's obviously taking the match groups.

### Reproducible example

```python
import polars as pl

# . is replaced with itself
print(pl.Series(["."]).str.replace(".", "$0", literal=True)[0])  # -> "."

# . is replaced with literal $0
print(pl.Series(["1"]).str.replace("1", "$0", literal=True)[0])  # -> "$0"

# replace_all always replaces with itself
print(pl.Series(["."]).str.replace_all(".", "$0", literal=True)[0])  # -> "."
print(pl.Series([".."]).str.replace_all(".", "$0", literal=True)[0])  # -> ".."
print(pl.Series(["a"]).str.replace_all("a", "$0", literal=True)[0])  # -> "a"
print(pl.Series(["aa"]).str.replace_all("a", "$0", literal=True)[0])  # -> "aa"
print(pl.Series(["aa"]).str.replace_all("a", "$1", literal=True)[0])  # -> ""


def replace(pattern, replace):
    return pl.Series([pattern]).str.replace(pattern, replace, literal=True)[0]


# Happens with single chars that are symbols
replace(".", "$0")  # "."
replace(";", "$0")  # ";"
replace("[", "$0")  # "["
replace("]", "$0")  # "]"
replace("(", "$0")  # "("
replace(")", "$0")  # ")"
replace("^", "$0")  # "^"
replace("$", "$0")  # "$"

# Happens when just a single symbol is present in string
replace("a#b", "$0")  # "a#b"

# Empty string when using $1
replace(".", "$1")  # ""
replace(";", "$1")  # ""

# Other chars works fine
replace("1", "$0")  # "$0"
replace("ab", "$0")  # "$0"
replace("aa", "$0")  # "$0"
replace("1", "$1")  # "$1"
replace("a", "$1")  # "$1"
replace(" ", "$0")  # "$0"
```

### Expected behavior

When `literal=True` I would expect it to also replace with the literal string `$0`. I guess the documentation does actually say that the _pattern_ is taken as literal, but if the pattern is literal you have no reason to use match groups in `replace` (Since you know that `$0 == pattern` and `$n == ""`)

### Installed versions

<details>

```
---Version info---
Polars: 0.16.2
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.9.14 (main, Sep  7 2022, 23:43:48) 
[GCC 11.2.0]
---Optional dependencies---
pyarrow: 10.0.0
pandas: 1.3.5
numpy: 1.23.5
fsspec: 2022.11.0
connectorx: <not installed>
xlsx2csv: <not installed>
deltalake: <not installed>
matplotlib: 3.4.0
```

</details>

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #6755.

Addresses edge-case with literal string replacement when using the regex engine. If the replacement pattern looks like (or contains) a capture group string you could get some unexpected/failed substitutions...

## Example
```python
import polars as pl
s = pl.Series( "srs", ["."] )
s.str.replace_all( ".", "$0", literal=True )[0]
```
**Before**: `'.'` _(applied capture group, despite "literal=True")_
**After**: `'$0'` _(capture group syntax ignored, literal properly replaced)_

## Also

* Added test coverage for replacement patterns of this type.
* Making explicit use of `NoExpand` for literal replacement should also be marginally faster in general, as no capture groups have to be searched for at all:
  * https://docs.rs/regex/latest/regex/struct.NoExpand.html

### CODE REVIEW

File: polars/polars-ops/src/chunked_array/strings/namespace.rs [hunk 1]
```diff
@@ -217,25 +217,36 @@ pub trait Utf8NameSpaceImpl: AsUtf8 {
...
+        let ca = self.as_utf8();
         Ok(ca.apply(f))
     }
 
     /// Replace the leftmost literal (sub)string with another string
-    fn replace_literal(&self, pat: &str, val: &str) -> PolarsResult<Utf8Chunked> {
-        self.replace(escape(pat).as_str(), val)
+    fn replace_literal<'a>(&'a self, pat: &str, val: &str) -> PolarsResult<Utf8Chunked> {
+        let reg = Regex::new(escape(pat).as_str())?;
+        let f = |s: &'a str| {
```
Comment (ritchie46) [inline polars/polars-ops/src/chunked_array/strings/namespace.rs:227]: Why do we actually use regex when we replace literal? :thinking:

Comment (alexander-beedie) [reply polars/polars-ops/src/chunked_array/strings/namespace.rs:227]: Speed; it's actually faster on longer strings - we use standard string replace on strings < 32 chars. See https://github.com/pola-rs/polars/pull/4057 for all the relevant graphs :)

Comment (ritchie46) [reply polars/polars-ops/src/chunked_array/strings/namespace.rs:227]: Ah, check! 

I think we should do a new benchmark in a year. Rust std might catch up with burntsushi on this.

Comment (alexander-beedie) [reply polars/polars-ops/src/chunked_array/strings/namespace.rs:227]: > I think we should do a new benchmark in a year. Rust std might catch up with burntsushi on this.

Lol... I found the script (I'll gist it for you if you like) and am running it now to se if we can simplify on one or the other ;)
