### PR TITLE
fix(rust, python): Reused input series in rolling_apply should not be orderly

### LINKED ISSUE #10681: Wrong results for rolling_apply, when using min() as apply function.
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame({"a": [1, 1, 1, 1, 2, 2, 2, 2], "b": [0, 1, 11.0, 7, 4, 2, 3, 8]})
df.with_columns(
    pl.col('b').cast(pl.Float64)
    .rolling_apply(lambda s: s.min(), window_size=3, min_periods=2)
    .over('a').alias('min')
    )
```

### Issue description

The output of above syntax is below, which is obviously wrong. 
<html>
<body>
<small style="color: rgb(248, 248, 242); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">shape: (8, 3)</small>

a | b | min
-- | -- | --
i64 | f64 | f64
1 | 0.0 | null
1 | 1.0 | 0.0
1 | 11.0 | 0.0
1 | 7.0 | 1.0
2 | 4.0 | null
2 | 2.0 | 4.0
2 | 3.0 | 4.0
2 | 8.0 | 2.0

</body>
</html>

### Expected behavior

While using this rolling_min, the result is right.
```python
df.with_columns([pl.col('b').rolling_min(window_size=3, min_periods=2).over('a').alias('min')])
```
<html>
<body>
<small style="color: rgb(248, 248, 242); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">shape: (8, 3)</small>

a | b | min
-- | -- | --
i64 | f64 | f64
1 | 0.0 | null
1 | 1.0 | 0.0
1 | 11.0 | 0.0
1 | 7.0 | 1.0
2 | 4.0 | null
2 | 2.0 | 2.0
2 | 3.0 | 2.0
2 | 8.0 | 2.0

</body>
</html>

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-5.3.0-28-generic-x86_64-with-glibc2.27
Python:              3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.24.4
pandas:              2.0.3
pyarrow:             12.0.1
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This fixes #10681.

### CODE REVIEW

File: crates/polars-core/src/chunked_array/ops/rolling_window.rs [hunk 1]
```diff
@@ -168,7 +168,8 @@ mod inner_mod {
                         }
                         // ensure the length is correct
                         series_container._get_inner_mut().compute_len();
-
+                        // reset flags as we reuse this container
+                        series_container.clear_settings();
```
Comment (reswqa) [inline crates/polars-core/src/chunked_array/ops/rolling_window.rs:172]: We reuse the following series to avoid re-allocation.

https://github.com/pola-rs/polars/blob/9bfa5b6db9b112328c657651c2def6543ae46473/crates/polars-core/src/chunked_array/ops/rolling_window.rs#L93-L94

But it is `Ascending` because when we first computed its size, we went to the following branch:

https://github.com/pola-rs/polars/blob/9bfa5b6db9b112328c657651c2def6543ae46473/crates/polars-core/src/chunked_array/ops/chunkops.rs#L77-L79

This will affect subsequent function call. Maybe simply unset the sorting mark when creating it can solve this problem. But for safety reasons, I chose to reset all states before each function call. WDYT?

Comment (ritchie46) [reply crates/polars-core/src/chunked_array/ops/rolling_window.rs:173]: This is indeed the way to go. Only the `clear_settings` should be before the `compute_len()`. As `compute_len` sets sorted info.

Comment (reswqa) [reply crates/polars-core/src/chunked_array/ops/rolling_window.rs:173]: Ah, that's a foolish mistake, I messed up their order. :)

Comment (reswqa) [reply crates/polars-core/src/chunked_array/ops/rolling_window.rs:171]: Order exchanged.

**Review by ritchie46 — APPROVED** [review]
