### PR TITLE
fix(rust, python): respect time_zone in lazy date_range

### LINKED ISSUE #8512: lazy date_range doesn't respect time zone
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The following outputs
```python
shape: (3, 4)
┌──────┬─────────────────────┬─────────────────────┬───────────────────────────────────┐
│ name ┆ from                ┆ to                  ┆ date_range                        │
│ ---  ┆ ---                 ┆ ---                 ┆ ---                               │
│ str  ┆ datetime[μs]        ┆ datetime[μs]        ┆ list[datetime[μs]]                │
╞══════╪═════════════════════╪═════════════════════╪═══════════════════════════════════╡
│ A    ┆ 2020-01-01 00:00:00 ┆ 2020-01-02 00:00:00 ┆ [2020-01-01 00:00:00, 2020-01-02… │
│ B    ┆ 2020-01-02 00:00:00 ┆ 2020-01-03 00:00:00 ┆ [2020-01-02 00:00:00, 2020-01-03… │
│ C    ┆ 2020-01-03 00:00:00 ┆ 2020-01-04 00:00:00 ┆ [2020-01-03 00:00:00, 2020-01-04… │
└──────┴─────────────────────┴─────────────────────┴───────────────────────────────────┘

```

### Reproducible example

```python
df = pl.DataFrame(
    {
        "name": ["A", "B", "C"],
        "from": [datetime(2020, 1, 1), datetime(2020, 1, 2), datetime(2020, 1, 3)],
        "to": [datetime(2020, 1, 2), datetime(2020, 1, 3), datetime(2020, 1, 4)],
    }
)
print(
    df.with_columns(
        pl.date_range(
            start=pl.col("from"),
            end=pl.col("to"),
            interval="1d",
            lazy=True,
            time_zone="Asia/Kathmandu",
        ).alias("date_range")
    )
)
```

### Expected behavior

```
shape: (3, 4)
┌──────┬─────────────────────┬─────────────────────┬────────────────────────────────────┐
│ name ┆ from                ┆ to                  ┆ date_range                         │
│ ---  ┆ ---                 ┆ ---                 ┆ ---                                │
│ str  ┆ datetime[μs]        ┆ datetime[μs]        ┆ list[datetime[μs, Asia/Kathmandu]] │
╞══════╪═════════════════════╪═════════════════════╪════════════════════════════════════╡
│ A    ┆ 2020-01-01 00:00:00 ┆ 2020-01-02 00:00:00 ┆ [2020-01-01 00:00:00 +0545, 2020…  │
│ B    ┆ 2020-01-02 00:00:00 ┆ 2020-01-03 00:00:00 ┆ [2020-01-02 000:00:00 +0545, 2020…  │
│ C    ┆ 2020-01-03 00:00:00 ┆ 2020-01-04 00:00:00 ┆ [2020-01-03 00:00:00 +0545, 2020…  │
└──────┴─────────
```

### Installed versions

<details>

```
---Version info---
Polars: 0.17.8
Index type: UInt32
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python: 3.8.16 (default, Dec  7 2022, 01:12:06)
[GCC 11.3.0]
---Optional dependencies---
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.6.2
xlsx2csv: <not installed>
xlsxwriter: <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #8512 

marking as draft while I split part of it out into a separate pr

### CODE REVIEW

File: polars/polars-lazy/polars-plan/src/dsl/function_expr/temporal.rs [hunk 1]
```diff
@@ -135,7 +167,25 @@ pub(super) fn temporal_range_dispatch(
             }
             builder.finish().into_series()
         }
-        DataType::Datetime(_, _) | DataType::Time => {
+        DataType::Datetime(tu, ref tz) => {
```
Comment (MarcoGorelli) [inline polars/polars-lazy/polars-plan/src/dsl/function_expr/temporal.rs:170]: separating the `Datetime` and `Time` arms to make use of `tu` and `tz` from `Datetime`

File: polars/polars-lazy/polars-plan/src/dsl/function_expr/temporal.rs [hunk 2]
```diff
@@ -93,21 +93,45 @@ pub(super) fn temporal_range_dispatch(
...
+                .to_physical_repr()
+                .cast(&DataType::Int64)?,
+        ),
+        _ => (
+            start.to_physical_repr().cast(&DataType::Int64)?,
+            stop.to_physical_repr().cast(&DataType::Int64)?,
+        ),
+    };
 
-    let (tu, tz) = match dtype {
```
Comment (MarcoGorelli) [inline polars/polars-lazy/polars-plan/src/dsl/function_expr/temporal.rs:103]: the output dtype isn't necessarily `start.dtype()` (if `tz` is not None). so instead of just recording `tu` and `tz`, I'm assigning to `dtype`, which contains `tu` and `tz`.

Then,
- for `Date`, I just use `Milliseconds` as `tu` and `None` for `tz`
- for `Time`, same, but with `Nanoseconds` as `tu`
- for `Datetime`, use its `tu` and `tz`

File: polars/polars-lazy/polars-plan/src/dsl/function_expr/temporal.rs [hunk 3]
```diff
@@ -93,21 +93,45 @@ pub(super) fn temporal_range_dispatch(
...
-    let mut stop = rng_stop.cast(&DataType::Int64)?;
+    // Note: `start` and `stop` have already been cast to their supertype,
+    // so only `start`'s dtype needs to be matched against.
+    let (mut start, mut stop) = match start_dtype {
+        #[cfg(feature = "timezones")]
+        DataType::Datetime(_, Some(_)) => (
+            start
+                .datetime()
+                .unwrap()
+                .replace_time_zone(None, None)?
```
Comment (MarcoGorelli) [inline polars/polars-lazy/polars-plan/src/dsl/function_expr/temporal.rs:106]: if `start` and `stop` have a time zone, I'm removing it, as `date_range_impl` deals with that

File: polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs [hunk 4]
```diff
@@ -59,7 +59,38 @@ impl FunctionExpr {
                     }
                     #[cfg(feature = "timezones")]
                     TzLocalize(tz) => return mapper.map_datetime_dtype_timezone(Some(tz)),
-                    DateRange { .. } => return mapper.map_to_supertype(),
+                    DateRange {
+                        every: _,
+                        closed: _,
+                        tz,
+                    } => {
+                        let mut ret = mapper.map_to_supertype()?;
```
Comment (ritchie46) [inline polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs:67]: Can we hoist this into a function. That keeps the `schema` branch a bit more lean.

File: polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs [hunk 5]
```diff
@@ -59,7 +59,38 @@ impl FunctionExpr {
                     }
                     #[cfg(feature = "timezones")]
                     TzLocalize(tz) => return mapper.map_datetime_dtype_timezone(Some(tz)),
-                    DateRange { .. } => return mapper.map_to_supertype(),
+                    DateRange {
```
[the remark this answers is not in the document]
Comment (ritchie46) [reply polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs:62]: Right, can you add that as comment?

**Review by ritchie46 — APPROVED** [review]

**Comment by ritchie46** [comment]
Thanks for the reminder. Forgot about this one.
