### PR TITLE
Fix invalid csv scanning

### LINKED ISSUE #1808: `filter().collect()` returns empty when `scan_csv()` reads large file
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

v0.10.21

#### What operating system are you using polars on?

Windows 11

#### Describe your bug.

Lazy API. `filter().collect()` returns empty when `scan_csv()` reads large file

The polars works well with small lazy dataframe

image

When I read a local csv file that's ~18G, a similar operation returns empty. 

To make sure that the record exists, I perform a unique operation that returns the result.

image

I also tried `dask` to perform the task

image

Sorry about posting pictures here, I don't know how to share a large file.

### PR DESCRIPTION
**Pull request by ritchie46**
Fixes #1808.

Also adds a test in CI where we compare eager vs lazy outputs. We can extend this and run agains the db-benchmark csv, which is quite large.

### CODE REVIEW

File: polars/polars-io/src/csv_core/buffer.rs [hunk 1]
```diff
@@ -236,8 +232,7 @@ impl ParsedBuffer<BooleanType> for BooleanChunkedBuilder {
         } else {
             return Err(PolarsError::ComputeError(
                 format!(
-                    "Error while parsing value {} at byte position {} as boolean",
-                    start_pos,
+                    "Error while parsing value {} at  as boolean",
```
Comment (ghuls) [inline polars/polars-io/src/csv_core/buffer.rs:235]: something is missing / or too much.

Comment (ritchie46) [reply polars/polars-io/src/csv_core/buffer.rs:235]: Yeap, good one.
