### PR TITLE
fix: Fix `sort_by` for `group_by_dynamic` context

### LINKED ISSUE #24057: `sort_by` in `group_by_dynamic` broken
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import datetime as dt

pl.DataFrame(
    {
        'time': [base_time, base_time + dt.timedelta(minutes=6)],
        'foo': [0, 1],
    },
).group_by_dynamic(
    index_column='time',
    every='5m',
    period='10m',
).agg(
    pl.arange(pl.len()),
    pl.col('foo'),
    #pl.arange(pl.len()).sort_by(pl.col('foo')).alias('throws'),
)
```

time | literal | foo
-- | -- | --
datetime[μs] | list[i64] | list[i64]
2020-01-01 10:00:00 | [0, 1] | [0, 1]
2020-01-01 10:05:00 | [0] | [1]

but uncommenting the last line throws

### Log output

```shell
.
```

### Issue description

`pl.arange(pl.len()).sort_by(pl.col('foo'))`  throws

```
ComputeError: the expression in `sort_by` argument must result in the same length

Error originated in expression: 'dyn int: 0.int_range([len()]).sort_by(by=[col("foo")], sort_option=SortMultipleOptions { descending: [false], nulls_last: [false], multithreaded: true, maintain_order: false, limit: None })'
```

### Expected behavior

`pl.arange(pl.len()).sort_by(pl.col('foo'))` should return the same as ` pl.arange(pl.len())` in this example

### Installed versions

<details>

```
--------Version info---------
Polars:              1.32.2
Index type:          UInt32
Platform:            Linux-5.15.0-91-generic-x86_64-with-glibc2.35
Python:              3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  1.1.0
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          3.0.0
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          2.33.0
great_tables         <not installed>
matplotlib           3.9.2
numpy                1.26.4
openpyxl             3.1.2
pandas               2.3.1
polars_cloud         <not installed>
pyarrow              15.0.0
pydantic             2.7.1
pyiceberg            <not installed>
sqlalchemy           2.0.32
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #24057

Summary of changes:
- removed false positive check which was incorrect for overlapping groups
- added regression test
- added code fix for `literal`
- improved error message feedback

### CODE REVIEW

File: crates/polars-expr/src/expressions/sortby.rs [hunk 1]
```diff
@@ -305,6 +305,19 @@ impl PhysicalExpr for SortByExpr {
             .iter()
             .map(|e| e.evaluate_on_groups(df, groups, state))
             .collect::<PolarsResult<Vec<_>>>()?;
+
+        assert!(
```
Comment (ritchie46) [inline crates/polars-expr/src/expressions/sortby.rs:309]: Can this be a debug_assert? This is not a simple cheap check.

Comment (orlp) [reply crates/polars-expr/src/expressions/sortby.rs:309]: I don't think this is expensive? `ac_sort_by` should be very small and constant and the `len` functions are basically free?

Comment (ritchie46) [reply crates/polars-expr/src/expressions/sortby.rs:309]: Isn't this sorting over the groups? I haven't looked thoroughly?

Does this iter over the the sort by columns?

Comment (ritchie46) [reply crates/polars-expr/src/expressions/sortby.rs:309]: Another question, does this check our invariants or user input? If the latter, it should raise instead of panic.

Comment (kdn36) [reply crates/polars-expr/src/expressions/sortby.rs:309]: > Isn't this sorting over the groups? I haven't looked thoroughly?
> 
> Does this iter over the the sort by columns?

Correct, it only iters over the columns, of which there are few. Any proper check (each group to have a matching len) would inevitably be expensive, and that happens later. Fwiw, I was unable to find a cheap reliable way to calculate the effective total number of elements across all groups as the original check intended.

Comment (kdn36) [reply crates/polars-expr/src/expressions/sortby.rs:309]: > Another question, does this check our invariants or user input? If the latter, it should raise instead of panic.

Originally we had a user-facing error message. As I understand, the consistency of the number of groups is an invariant the user has no influence over, hence the change to `assert`... Unless I am missing something. We can revert or switch to `debug_assert` if prefered.

Comment (ritchie46) [reply crates/polars-expr/src/expressions/sortby.rs:309]: Alright, given that it's only columns and an invariant. 👍
