### PR TITLE
fix(rust,python): escape csv header names if they contain special chars

### LINKED ISSUE #8315: polars write_csv does not escape column names
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Separator characters inside column names of a dataframe do not get escaped when using write_csv.

### Reproducible example

```python
import polars as pl

a = {'column,1': ['data,1']}
df = pl.DataFrame(a)
print(df.write_csv())
```

This code prints:
```
column,1
"data,1"
```

### Expected behavior

should print:
```
"column,1"
"data,1"
```

### Installed versions

Hmm, looks like my xlsxwriter install is borked, but I don't think that's related.

<details>

```
---Version info---
Polars: 0.16.18
Index type: UInt32
Platform: Linux-5.4.0-126-generic-x86_64-with-glibc2.31
Python: 3.11.3 (main, Apr  5 2023, 14:15:06) [GCC 9.4.0]
---Optional dependencies---
/usr/lib/python3/dist-packages/xlsxwriter/worksheet.py:358: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if token is '':
/usr/lib/python3/dist-packages/xlsxwriter/worksheet.py:2437: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if options['min_type'] is 'min' and options['min_value'] == 0:
/usr/lib/python3/dist-packages/xlsxwriter/worksheet.py:2440: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if options['max_type'] is 'max' and options['max_value'] == 0:
/usr/lib/python3/dist-packages/xlsxwriter/worksheet.py:4999: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if props[i]['type'] is 'number':
/usr/lib/python3/dist-packages/xlsxwriter/worksheet.py:6827: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if data_bar['bar_axis_position'] is not 'none':
/usr/lib/python3/dist-packages/xlsxwriter/worksheet.py:6862: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if data_bar['bar_direction'] is 'left':
/usr/lib/python3/dist-packages/xlsxwriter/worksheet.py:6865: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if data_bar['bar_direction'] is 'right':
/usr/lib/python3/dist-packages/xlsxwriter/worksheet.py:6875: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if data_bar['bar_axis_position'] is 'middle':
/usr/lib/python3/dist-packages/xlsxwriter/worksheet.py:6878: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if data_bar['bar_axis_position'] is 'none':
/usr/lib/python3/dist-packages/xlsxwriter/chart.py:2497: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if val is 'right':
/usr/lib/python3/dist-packages/xlsxwriter/chart.py:2500: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if val is 'left':
numpy: 1.24.2
pandas: 1.5.3
pyarrow: 11.0.0
connectorx: <not installed>
deltalake: <not installed>
fsspec: <not installed>
matplotlib: 3.7.0
xlsx2csv: <not installed>
xlsxwriter: 1.1.2```

</details>

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #8315. 

Header names should also be escaped when writing CSV data (eg: if they contain `,` or `"` chars). No new logic, just passes the names through the existing `fmt_and_escape_str`.

## Example

**Setup:**
```python
from io import BytesIO
df = pl.DataFrame( {"c,o,l,u,m,n": [123]} )

buf = BytesIO()
df.write_csv( buf )
```
**Before:**
```python
pl.read_csv( buf )
# shape: (1, 6)
# ┌─────┬──────┬──────┬──────┬──────┬──────┐
# │ c   ┆ o    ┆ l    ┆ u    ┆ m    ┆ n    │
# │ --- ┆ ---  ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
# │ i64 ┆ str  ┆ str  ┆ str  ┆ str  ┆ str  │
# ╞═════╪══════╪══════╪══════╪══════╪══════╡
# │ 123 ┆ null ┆ null ┆ null ┆ null ┆ null │
# └─────┴──────┴──────┴──────┴──────┴──────┘
```
**After:**
```python
pl.read_csv( buf )
# shape: (1, 1)
# ┌─────────────┐
# │ c,o,l,u,m,n │
# │ ---         │
# │ i64         │
# ╞═════════════╡
# │ 123         │
# └─────────────┘
```

### CODE REVIEW

File: polars/polars-io/src/csv/write_impl.rs [hunk 1]
```diff
@@ -332,14 +332,21 @@ pub(crate) fn write<W: Write>(
...
     Ok(())
 }
+
 /// Writes a CSV header to `writer`
 pub(crate) fn write_header<W: Write>(
     writer: &mut W,
     names: &[&str],
     options: &SerializeOptions,
 ) -> PolarsResult<()> {
+    let mut escaped_names: Vec<String> = Vec::new();
```
Comment (ritchie46) [inline polars/polars-io/src/csv/write_impl.rs:342]: We can allocate `with_capacity(names.len())` and save a few reallocs.

**Review by ritchie46 — COMMENTED** [review]
Thanks, left some comments.

File: polars/polars-io/src/csv/write_impl.rs [hunk 2]
```diff
@@ -329,17 +329,24 @@ pub(crate) fn write<W: Write>(
...
+    let mut nm: Vec<u8> = Vec::with_capacity(1);
+    for name in names {
+        fmt_and_escape_str(&mut nm, name, options)?;
+        escaped_names.push(std::str::from_utf8(&nm).unwrap().to_string());
+        nm.clear();
+    }
     writer.write_all(
-        names
+        escaped_names
             .join(std::str::from_utf8(&[options.delimiter]).unwrap())
```
Comment (ritchie46) [inline polars/polars-io/src/csv/write_impl.rs:350]: we could use `from_utf8_unchecked` as we know we are dealing with utf8 data here. This might be worth it for the genomics people who deal with millions of columns.

Comment (alexander-beedie) [reply polars/polars-io/src/csv/write_impl.rs:354]: Done 👍

**Comment by ritchie46** [comment]
Perf! 🙏
