### PR TITLE
fix: dont overflow when calculating date range over very long periods

### LINKED ISSUE #12461: Unable to create date ranges for very large time periods(>=0.19.13)
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.date_range(pl.date(1900, 1, 1), pl.date(2300, 1, 1), eager=True)
```

### Log output

```shell
no output
```

### Issue description

When executed, it does nothing and the program stops working.
In (<=0.19.12), it worked fine.

### Expected behavior

```log
shape: (146_098,)
Series: 'date' [date]
[
	1900-01-01
	1900-01-02
	1900-01-03
	1900-01-04
	1900-01-05
	1900-01-06
	1900-01-07
	1900-01-08
	1900-01-09
	1900-01-10
	1900-01-11
	1900-01-12
	…
	2299-12-20
	2299-12-21
	2299-12-22
	2299-12-23
	2299-12-24
	2299-12-25
	2299-12-26
	2299-12-27
	2299-12-28
	2299-12-29
	2299-12-30
	2299-12-31
	2300-01-01
]
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            macOS-13.5.1-arm64-arm-64bit
Python:              3.11.3 (main, May 31 2023, 14:12:50) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.2
openpyxl:            <not installed>
pandas:              2.1.3
pyarrow:             14.0.1
pydantic:            2.5.0
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.23
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

&&

```
--------Version info---------
Polars:              0.19.13
Index type:          UInt32
Platform:            Linux-6.2.0-1014-azure-x86_64-with-glibc2.31
Python:              3.11.5 (main, Aug 26 2023, 00:14:19) [GCC 10.2.1 20210110]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          <not installed>
numpy:               1.26.2
openpyxl:            <not installed>
pandas:              2.1.3
pyarrow:             14.0.1
pydantic:            2.5.0
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          2.0.23
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #12461

### CODE REVIEW

File: crates/polars-time/src/windows/duration.rs [hunk 1]
```diff
@@ -689,7 +691,7 @@ impl Duration {
         }
 
         if d.weeks > 0 {
-            let t_weeks = nsecs_to_unit(self.weeks * NS_WEEK);
+            let t_weeks = nsecs_to_unit(NS_WEEK) * self.weeks;
```
Comment (MarcoGorelli) [inline crates/polars-time/src/windows/duration.rs:694]: this could be cleaner with, say, `MS_WEEK` and `US_WEEK`...but this simple change at least fixes the issue

**Review by ritchie46 — APPROVED** [review]
