### PR TITLE
fix: Fix lifetime for `AmortSeries` lazy group iterator

### LINKED ISSUE #25567: `InvalidOperation` on `group_by_dynamic` with `gather_every` agg
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = (
    pl.from_dict({
        "idx": [
            27578,
            27579,
            27580,
            27581,
            27582,
            27987,
            27988,
            27989,
            27990,
            27991,
            27992,
            27993,
            27994,
            27995,
            27996,
            27997,
            27998,
            27999,
            28000,
            28001,
            28002,
            28003,
            28004,
            28005,
            28006,
            28007,
            28008,
            28009,
            28010,
            28011,
            28012,
            28013,
            28014,
            28015,
            28016,
            28017,
            28018,
            28019,
            28020,
            28021,
            28022,
            28023,
            28024,
            28025,
            28026,
            28027,
            28028,
            28029,
            28030,
            28031,
        ],
        "value": [
            [
                [-5.942775535525309, -8.840878476642313],
                [-6.384293289185543, 1.1631090120257594],
                [-7.293629554435345, 11.13356969412503],
                [-8.174242205046818, 21.035170178899328],
                [-9.083615398713688, 31.00563663330112],
                [-9.993007118668555, 40.97610596831943],
                [-10.873674839666872, 50.87771514468633],
                [-11.783103489747019, 60.848190251264555],
                [-12.692550666899653, 70.81866823792785],
                [-13.499437918572045, 80.83196460737813],
            ],
            [
                [-5.942775535525309, -8.840878476642313],
                [-6.384293289185543, 1.1631090120257594],
                [-7.293629554435345, 11.13356969412503],
                [-8.174242205046818, 21.035170178899328],
                [-9.083615398713688, 31.00563663330112],
                [-9.993007118668555, 40.97610596831943],
                [-10.873674839666872, 50.87771514468633],
                [-11.783103489747019, 60.848190251264555],
                [-12.692550666899653, 70.81866823792785],
                [-13.499437918572045, 80.83196460737813],
            ],
            [
                [-5.942775535525309, -8.840878476642313],
                [-6.384293289185543, 1.1631090120257594],
                [-7.293629554435345, 11.13356969412503],
                [-8.174242205046818, 21.035170178899328],
                [-9.083615398713688, 31.00563663330112],
                [-9.993007118668555, 40.97610596831943],
                [-10.873674839666872, 50.87771514468633],
                [-11.783103489747019, 60.848190251264555],
                [-12.692550666899653, 70.81866823792785],
                [-13.499437918572045, 80.83196460737813],
            ],
            [
                [-5.942775535525309, -8.840878476642313],
                [-6.384293289185543, 1.1631090120257594],
                [-7.293629554435345, 11.13356969412503],
                [-8.174242205046818, 21.035170178899328],
                [-9.083615398713688, 31.00563663330112],
                [-9.993007118668555, 40.97610596831943],
                [-10.873674839666872, 50.87771514468633],
                [-11.783103489747019, 60.848190251264555],
                [-12.692550666899653, 70.81866823792785],
                [-13.499437918572045, 80.83196460737813],
            ],
            [
                [-5.942775535525309, -8.840878476642313],
                [-6.384293289185543, 1.1631090120257594],
                [-7.293629554435345, 11.13356969412503],
                [-8.174242205046818, 21.035170178899328],
                [-9.083615398713688, 31.00563663330112],
                [-9.993007118668555, 40.97610596831943],
                [-10.873674839666872, 50.87771514468633],
                [-11.783103489747019, 60.848190251264555],
                [-12.692550666899653, 70.81866823792785],
                [-13.499437918572045, 80.83196460737813],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [34.45007964993059, -57.29307185382987],
                [34.07655448576116, -50.02005567688363],
                [33.48842434884209, -40.01213350153069],
                [32.90027611459735, -30.004208904491623],
                [32.22614320578208, -20.098916191817555],
                [31.637958962854896, -10.090986923142264],
                [31.049756622619064, -0.08305523283649308],
                [30.48232492075559, 9.853210059415632],
                [29.894086515535317, 19.86114660220629],
                [29.326619007113603, 29.79741676495173],
            ],
            [
                [-4.9943891937162945, 1.066998320813858],
                [-5.3679143578857245, 8.340014497760096],
                [-5.956044494804793, 18.34793667311303],
                [-6.544192729049534, 28.3558612701521],
                [-7.218325637864802, 38.26115398282617],
                [-7.80650988079199, 48.26908325150146],
                [-8.394712221027822, 58.27701494180723],
                [-8.962143922891293, 68.21328023405935],
                [-9.55038232811157, 78.22121677685001],
                [-10.117849836533283, 88.15748693959546],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
            [
                [-4.737280819379784, 8.713697080733338],
                [-4.584644433941981, 18.7377234903012],
                [-4.432025917542803, 28.761753651564533],
                [-4.372737370287231, 38.689782850286],
                [-4.220154419188316, 48.713820329938066],
                [-4.067589337115155, 58.73786156122884],
                [-3.8996034471424945, 68.68889806176806],
                [-3.7470739731607914, 78.71294679596063],
                [-3.579123432229144, 88.66399079827418],
                [-3.426629565404884, 98.68804703546095],
            ],
        ],
    })
    .group_by_dynamic(
        "idx",
        every="10i",
        period="60i",
        closed="left",
        label="datapoint",
        start_by="datapoint",
    )
    .agg(pl.all().gather_every(10))
)

```

### Log output

```python-traceback
thread 'polars-0' (2397349) panicked at crates/polars-core/src/chunked_array/builder/list/anonymous.rs:157:69:
called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("It is not possible to concatenate arrays of different data types."))
stack backtrace:
   0:     0x76b93df54396 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h9cc4873ee28b174b
   1:     0x76b93848402f - core::fmt::write::h98addc6f16b029c7
   2:     0x76b93df5378f - std::io::Write::write_fmt::h0c1167b64e42f3ed
   3:     0x76b93df541d3 - std::sys::backtrace::BacktraceLock::print::ha14c16ec61850d40
   4:     0x76b93df53e16 - std::panicking::default_hook::h279ceada925c78c1
   5:     0x76b939a328a4 - polars_error::signals::register_polars_keyboard_interrupt_hook::{{closure}}::hc586fb66b52fde7e
   6:     0x76b93df533a3 - std::panicking::panic_with_hook::hae2a27acfb2df435
   7:     0x76b93df7cd18 - std::panicking::panic_handler::{{closure}}::hc339ae507b9da894
   8:     0x76b93df7cc79 - std::sys::backtrace::__rust_end_short_backtrace::ha26661647ee40c8b
   9:     0x76b93df7cc6e - __rustc[4683036c762297f9]::rust_begin_unwind
  10:     0x76b9384851cf - core::panicking::panic_fmt::h7a39be529a1dbf2a
  11:     0x76b938492065 - core::result::unwrap_failed::h37fc1a30088fc974
  12:     0x76b938b7b04d - <polars_core::chunked_array::builder::list::anonymous::AnonymousOwnedListBuilder as polars_core::chunked_array::builder::list::ListBuilderTrait>::finish::h68d8be2c36bd09e1
  13:     0x76b939a3b45a - <polars_expr::expressions::apply::ApplyExpr as polars_expr::expressions::PhysicalExpr>::evaluate_on_groups::h21c0c1ae2a6ca0cd
  14:     0x76b939a375b9 - <polars_expr::expressions::alias::AliasExpr as polars_expr::expressions::PhysicalExpr>::evaluate_on_groups::hd38100950e7a4a30
  15:     0x76b93a674b1e - rayon::iter::plumbing::bridge_producer_consumer::helper::h67f10be7d7d263d2
  16:     0x76b93a674219 - rayon_core::thread_pool::ThreadPool::install::{{closure}}::h677f9ad161117f64
  17:     0x76b93a676476 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h0978fafcf4f9305d
  18:     0x76b93dcace95 - rayon_core::registry::WorkerThread::wait_until_cold::h3916b146346b5389
  19:     0x76b93dcacba0 - std::sys::backtrace::__rust_begin_short_backtrace::hbee8b8f9e10803b4
  20:     0x76b93dcac724 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8383b6a238f0d506
  21:     0x76b93df84ebb - std::sys::thread::unix::Thread::new::thread_start::h27baf5f3ef7ea848
  22:     0x76b93f094ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  23:     0x76b93f1268c0 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81:0
  24:                0x0 - <unknown>
Traceback (most recent call last):
  File "/home/evgenii/dev/repro.py", line 668, in <module>
    .agg(pl.all().gather_every(10))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evgenii/.cache/uv/archive-v0/2g8FJlSLVzja-gt72QMuU/lib/python3.12/site-packages/polars/dataframe/group_by.py", line 1172, in agg
    return group_by.agg(*aggs, **named_aggs).collect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evgenii/.cache/uv/archive-v0/2g8FJlSLVzja-gt72QMuU/lib/python3.12/site-packages/polars/_utils/deprecation.py", line 97, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evgenii/.cache/uv/archive-v0/2g8FJlSLVzja-gt72QMuU/lib/python3.12/site-packages/polars/lazyframe/opt_flags.py", line 328, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evgenii/.cache/uv/archive-v0/2g8FJlSLVzja-gt72QMuU/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2427, in collect
    return wrap_df(ldf.collect(engine, callback))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("It is not possible to concatenate arrays of different data types."))
```

### Issue description

Apologies for the verbose repro -- this is as far as I was able to narrow it down from the actual use case while keeping the params identical.

The issue seems to only occur for `polars>1.34.0`.

### Expected behavior

The operation succeeds.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.36.0-beta.1
Index type:          UInt32
Platform:            Linux-6.8.0-85-generic-x86_64-with-glibc2.35
Python:              3.12.11 (main, Sep 18 2025, 19:47:19) [Clang 20.1.4 ]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
polars_cloud         <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #25567 

Preliminary fix (or workaround) using `deep_clone()`.

Micro-benchmark:
```python
n_rows = 100_000
col = [1, 2, 3]
n_rows = n_rows // len(col) * len(col)
period = 1000

df = pl.DataFrame({"d": range(n_rows), "n": col * (n_rows // len(col))})
q = df.lazy().rolling("d", period=str(period) + "i").agg(pl.col.n.rank().last())
```
Gives:
- On 1.35.2 public release: 3742.435320 milliseconds
- On 1.36.0b2: 2761.884359 milliseconds
- Prior main (build-release): 2358.850281 milliseconds
- With this PR (build-release): 2514.513819 milliseconds

### CODE REVIEW

File: crates/polars-expr/src/expressions/group_iter.rs [hunk 1]
```diff
@@ -75,7 +75,9 @@ impl AggregationContext<'_> {
 
 impl AggregationContext<'_> {
     /// Iterate over groups lazily, i.e., without greedy aggregation into an AggList.
-    pub(super) fn iter_groups_lazy(
+    ///
+    /// # Safety: AmortSeries does not live longer than the next call to `next`.
+    pub(super) unsafe fn iter_groups_lazy(
```
Comment (orlp) [inline crates/polars-expr/src/expressions/group_iter.rs]: Since you made this unsafe and you only had to change the `ApplyExpr` usage I think we can conclude this is only used there. Can we rewrite this so it doesn't involve an unsafe function returning an `AmortSeries` which is then immediately deep cloned, and instead it just uses some safe form of iteration which does any clones ahead of time if necessary?

**Review by orlp — CHANGES_REQUESTED** [review]

**Comment by kdn36** [comment]
Final ad hoc micro-benchmark results (directionally correct at best, with build-release being slower than dist-release):

[1.36.0-beta.2, single-threaded] Execution time: 1302.223 milliseconds
[1.36.0-beta.2, multi-threaded] Execution time: 2705.488 milliseconds

[Latest commit, build-release build, 1-threaded] Execution time: 991.346 milliseconds
[Latest commit, build-release build, multi-threaded] Execution time: 390.614 milliseconds

Rust ASAN all-clean on the latest PR.
