### PR TITLE
fix(rust, python): re-sort buffer when update window swap the whole buffer

### LINKED ISSUE #10695: Panic when performing groupby_dynamic
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
from datetime import datetime

df = pl.DataFrame(
    {
        "timestamp": pl.date_range(
            datetime(2023, 8, 22, 15, 44, 30),
            datetime(2023, 8, 22, 15, 48, 50),
            "20s",
            eager=True,
        ),
        "foo": [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    }
)

gb = df.groupby_dynamic(
    index_column="timestamp",
    every="60s",
    period="3m",
)

print(gb.agg(pl.col("foo").median()))

```

### Issue description

Polars crashes with a PanicException on the script above, but I don't see a particular reason why it should.

```shell
thread '<unnamed>' panicked at 'removal index (is 8) should be < len (is 8)', /home/runner/work/polars/polars/crates/polars-arrow/src/kernels/rolling/window.rs:47:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/app/donut_counting/panic.py", line 23, in <module>
    print(gb.agg(pl.col("foo").median()))
  File "/usr/local/lib/python3.8/dist-packages/polars/dataframe/groupby.py", line 1070, in agg
    self.df.lazy()
  File "/usr/local/lib/python3.8/dist-packages/polars/utils/deprecation.py", line 93, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polars/lazyframe/frame.py", line 1695, in collect
    return wrap_df(ldf.collect())
pyo3_runtime.PanicException: removal index (is 8) should be < len (is 8)
```

Modifying the `counts` Series to be all `1`s does not fail.

```python
df = pl.DataFrame(
    {
        "timestamp": pl.date_range(
            datetime(2023, 8, 22, 15, 44, 30),
            datetime(2023, 8, 22, 15, 48, 50),
            "20s",
            eager=True,
        ),
        "foo": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    }
)
```

I've done my best looking at open issues but I couldn't find anything exactly like this, but I might have missed something.

### Expected behavior

I expect polars to print

```shell
shape: (5, 2)
┌─────────────────────┬─────┐
│ timestamp           ┆ foo │
│ ---                 ┆ --- │
│ datetime[μs]        ┆ f64 │
╞═════════════════════╪═════╡
│ 2023-08-22 15:44:00 ┆ 1.0 │
│ 2023-08-22 15:45:00 ┆ 1.0 │
│ 2023-08-22 15:46:00 ┆ 1.0 │
│ 2023-08-22 15:47:00 ┆ 1.0 │
│ 2023-08-22 15:48:00 ┆ 1.0 │
└─────────────────────┴─────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.15
Index type:          UInt32
Platform:            Linux-5.10.104-tegra-aarch64-with-glibc2.29
Python:              3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          3.7.2
numpy:               1.21.1
pandas:              1.5.1
pyarrow:             12.0.1
pydantic:            2.2.0
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          3.1.2
```

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This fixes #10695.

### CODE REVIEW

File: crates/polars-arrow/src/kernels/rolling/window.rs [hunk 1]
```diff
@@ -30,7 +30,8 @@ impl<'a, T: NativeType + IsFloat + PartialOrd> SortedBuf<'a, T> {
         if start >= self.last_end {
             self.buf.clear();
             let new_window = self.slice.get_unchecked(start..end);
-            self.buf.extend_from_slice(new_window)
+            self.buf.extend_from_slice(new_window);
+            sort_buf(&mut self.buf);
```
Comment (ritchie46) [inline crates/polars-arrow/src/kernels/rolling/window.rs:34]: That is quite an essential part of the `SortedWindow` yes. Good fix. :+1:

**Review by ritchie46 — APPROVED** [review]
