### PR TITLE
fix(rust, python): `group_by` partitioned with literal `Series` panic

### LINKED ISSUE #15354: `.group_by(series).agg(...)` fails when using `is_not_null` in aggregation
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import numpy as np
import polars as pl

df = pl.DataFrame(np.random.randn(1000,1))
groups = pl.Series([0]*1000)
df.group_by(groups).agg(pl.all().is_not_null().sum()) # This crashes
```

### Log output

```shell
estimated unique values: 1
run PARTITIONED HASH AGGREGATION
```

### Issue description

When reducing the length of the dataframe, the code works. This runs without failing on my computer :

```python
import numpy as np
import polars as pl

df = pl.DataFrame(np.random.randn(100,1))
groups = pl.Series([0]*100)
df.group_by(groups).agg(pl.all().is_not_null().sum()) # This is OK !
```

Another work around is to include the Series into the dataframe before aggregating :

```python
df = pl.DataFrame(np.random.randn(1000,1))
groups = pl.Series([0]*1000)
df.with_columns(groups).group_by(groups.name).agg(pl.all().is_not_null().sum()) # This is OK !
```

Another work around is to remove the `is_not_null` step from the aggregation

```python
df = pl.DataFrame(np.random.randn(100,1))
groups = pl.Series([0]*100)
df.with_columns(groups).group_by(groups.name).agg(pl.all().sum()) # This is OK !
```

### Expected behavior

This should work without failing, instead I get a PanicException :

> File C:\...\polars\lazyframe\frame.py:1943, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, background, _eager)
>    1940 if background:
>    1941     return InProcessQuery(ldf.collect_concurrently())
> -> 1943 return wrap_df(ldf.collect())
> 
> ShapeError: series used as keys should have the same length as the DataFrame

I did not find the same error message being reported, but this issue may be linked to other current issues dealing with nulls (ex : https://github.com/pola-rs/polars/issues/15150).

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.16
Index type:           UInt32
Platform:             Windows-10-10.0.22000-SP0
Python:               3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:40:50) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.3
numpy:                1.24.4
openpyxl:             <not installed>
pandas:               2.2.1
pyarrow:              15.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>


```

</details>

### PR DESCRIPTION
**Pull request by CanglongCl**
Closes #15354.

### CODE REVIEW

File: crates/polars-lazy/src/physical_plan/executors/group_by_partitioned.rs [hunk 1]
```diff
@@ -339,12 +344,22 @@ impl PartitionGroupByExec {
...
+                    let _ = acc.append(&e);
+                });
+                acc
+            })
+            .unwrap();
+
+        // the partitioned group_by has added columns so we must update the schema.
         state.set_schema(self.output_schema.clone());
+
         // MERGE phase
```
Comment (ritchie46) [inline crates/polars-lazy/src/physical_plan/executors/group_by_partitioned.rs:361]: This comment should be above L347

File: py-polars/tests/unit/operations/test_group_by.py [hunk 2]
```diff
@@ -768,6 +768,13 @@ def test_group_by_partitioned_ending_cast(monkeypatch: Any) -> None:
     assert_frame_equal(out, expected)
 
 
+def test_group_by_series_partitioned() -> None:
+    # test 15354
+    df = pl.DataFrame([0] * 1000)
```
Comment (ritchie46) [inline py-polars/tests/unit/operations/test_group_by.py:773]: Instead of `1000` we should use `PARTITION_LIMIT` here which is available under `py-polars/polars/testing/_constants.py`

On `debug` builds the threshold is not 1000.

**Review by ritchie46 — CHANGES_REQUESTED** [review]

**Review by ritchie46 — APPROVED** [review]
Thank you @CanglongCl. Good to go. :ok_hand:
