### PR TITLE
fix: Properly broadcast in sort_by

### LINKED ISSUE #7207: Panic when using `arg_sort_by` on literal
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

See example. Even though literal input doesn't make much sense, there is no reason it should panic.

### Reproducible example

```python
import polars as pl
from polars.testing import assert_frame_equal

df = pl.DataFrame({"a": [0, 1, 1, 0], "b": [3, 2, 3, 2]})
result = df.select(pl.arg_sort_by(["a", 1]))

expected = pl.DataFrame({"a": [0, 3, 1, 2]})
assert_frame_equal(result, expected)
# pyo3_runtime.PanicException: assertion failed: `(left == right)`
#  left: `4`,
# right: `1`
```

It looks like literals are not treated properly, see:

```python
result = df.select(pl.arg_sort_by(pl.lit(1)))
expected = pl.DataFrame({"literal": [0, 1, 2, 3]})
assert_frame_equal(result, expected)
# AssertionError: DataFrames are different.
```

Which results in:
```
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ u32     │
╞═════════╡
│ 0       │
└─────────┘
```

I would expect a column with `[0,1,2,3]`.

### Expected behavior

I expect the code to run normally.

### Installed versions

master

### PR DESCRIPTION
**Pull request by coastalwhite**
Fixes #7207.

### CODE REVIEW

File: crates/polars-expr/src/expressions/sortby.rs [hunk 1]
```diff
@@ -219,33 +219,54 @@ impl PhysicalExpr for SortByExpr {
...
+                            DataType::Categorical(_, _) | DataType::Enum(_, _) => c,
+                            _ => c.to_physical_repr(),
+                        })?;
+
+                        if column.len() == 1 && broadcast_length != 1 {
+                            return Ok(column.new_from_index(0, broadcast_length));
+                        }
+
+                        if broadcast_length != column.len() {
+                            polars_ensure!(
```
Comment (ritchie46) [inline crates/polars-expr/src/expressions/sortby.rs:241]: Can we also check the expression is a proper `scalar`. There should be a `e.is_scalar()`

**Review by ritchie46 — APPROVED** [review]
