### PR TITLE
fix: Properly fetch type of full None List Series

### LINKED ISSUE #18910: Casting an all null column created with pl.lit(None) with length greater than 1 to another type in the same with_columns or select context fails
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
assert (
    pl.DataFrame({"a": [1, 2]})
    .with_columns(pl.lit(None).cast(pl.List(pl.Int32)).alias("b"))
    .collect_schema()
    .dtypes()
) == [pl.Int64, pl.List(pl.Int32)]
```

### Log output

```shell
AssertionError
```

### Issue description

This creates a dtype of `pl.List(pl.Null)` for column `b` instead of the expected `pl.List(pl.Int32)`.

### Expected behavior

Expected the dtype of column `b` to be `pl.List(pl.Int32)`

### Installed versions

<details>

```
--------Version info---------
Polars:              1.8.1
Index type:          UInt32
Platform:            Linux-6.8.0-40-generic-x86_64-with-glibc2.35
Python:              3.12.2 (main, May  7 2024, 12:21:38) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            0.20.0
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                2.1.1
openpyxl             <not installed>
pandas               <not installed>
pyarrow              17.0.0
pydantic             2.9.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>

```

</details>

### PR DESCRIPTION
**Pull request by coastalwhite**
Fixes #18910, #18911.

### CODE REVIEW

**Comment by coastalwhite** [comment]
Windows CI issue again

File: crates/polars-core/src/datatypes/any_value.rs [hunk 1]
```diff
@@ -80,6 +80,7 @@ pub enum AnyValue<'a> {
     Enum(u32, &'a RevMapping, SyncPtr<Utf8ViewArray>),
     #[cfg(feature = "dtype-categorical")]
     EnumOwned(u32, Arc<RevMapping>, SyncPtr<Utf8ViewArray>),
+    // @TODO: This should be a ListArray<i64>, DataType instead of a Series
```
Comment (ritchie46) [inline crates/polars-core/src/datatypes/any_value.rs:83]: I don't thinks so. It is a single value of the list. Which is a `Series` or better, zero or more elements of the inner dtype of the list. Since the inner dtype is not known statically, this is a `Series`.

File: crates/polars-core/src/series/any_value.rs [hunk 2]
```diff
@@ -603,76 +604,92 @@ fn any_values_to_list(
...
-        // Structs don't support empty fields yet.
-        // We must ensure the data-types match what we do physical
-        #[cfg(feature = "dtype-struct")]
-        DataType::Struct(fields) if fields.is_empty() => {
-            DataType::Struct(vec![Field::new(PlSmallStr::EMPTY, DataType::Null)])
-        },
-        _ => inner_type.clone(),
-    };
-    let target_dtype = DataType::List(Box::new(it));
+    // GB:
```
Comment (ritchie46) [inline crates/polars-core/src/series/any_value.rs:607]: Maybe add a more informative comment? ;)
