### PR TITLE
fix(rust,python): Fix as-of join when `by` groups are interleaved

### LINKED ISSUE #9930: Weird behavior of `join_asof` with `strategy='nearest'` and `by`
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
In [1]: import pandas as pd
   ...: import polars as pl
   ...: a = pl.DataFrame(
   ...:     {
   ...:         "code": [676,    35,     676,    676,    676],
   ...:         "time": [364360, 364370, 364380, 365400, 367440],
   ...:     }
   ...: )
   ...: b = pl.DataFrame(
   ...:     {
   ...:         "code": [676,    676,     35,    676,    676],
   ...:         "time": [364000, 365000, 365000, 366000, 367000],
   ...:         "price": [1.0,   2.0,    50,    3.0,    None]
   ...:     }
   ...: )
   ...: c = a.join_asof(b, by='code', on='time', strategy='nearest')
   ...: print(c.with_row_count())
shape: (5, 4)
┌────────┬──────┬────────┬───────┐
│ row_nr ┆ code ┆ time   ┆ price │
│ ---    ┆ ---  ┆ ---    ┆ ---   │
│ u32    ┆ i64  ┆ i64    ┆ f64   │
╞════════╪══════╪════════╪═══════╡
│ 0      ┆ 676  ┆ 364360 ┆ 50.0  │
│ 1      ┆ 35   ┆ 364370 ┆ 50.0  │
│ 2      ┆ 676  ┆ 364380 ┆ 50.0  │
│ 3      ┆ 676  ┆ 365400 ┆ 3.0   │
│ 4      ┆ 676  ┆ 367440 ┆ null  │
└────────┴──────┴────────┴───────┘

# Expected behavior
In [2]: d = pd.merge_asof(a.to_pandas(), b.to_pandas(), by='code', on='time', direction='nearest')
   ...: print(d)
   code    time  price
0   676  364360    1.0
1    35  364370   50.0
2   676  364380    1.0
3   676  365400    2.0
4   676  367440    NaN
```

### Issue description

1. **row0 and row2 of DataFrame `c`**: It seems the keyword argument `by` doesn't work properly in this case (see row0 and row2 of DataFrame `c`).
2. **row3 of DataFrame `c`**: `join_asof` doesn't find the row2 in the DataFrame `b` whose value (time=365000) is nearest to the left’s key (time=365400). 

### Expected behavior

Pandas' behavior is expected.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.7
Index type:          UInt32
Platform:            Windows-10-10.0.22621-SP0
Python:              3.10.11 | packaged by Anaconda, Inc. | (main, Apr 20 2023, 18:56:50) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.1
numpy:               1.24.3
pandas:              1.5.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Resolves #9930.

### CODE REVIEW

File: polars/polars-core/src/frame/asof_join/groups.rs [hunk 1]
```diff
@@ -152,26 +152,26 @@ pub(super) unsafe fn join_asof_nearest_with_indirection<
...
-            } else {
-                val_l - val_r
-            };
-            if dist_curr <= dist {
-                // candidate for match
-                dist = dist_curr;
-            } else {
-                // note for a nearest-match, we can re-match on the same val_r next time,
-                // so we need to rewind the idx by 1
-                return (Some(offset - 1), idx - 1);
```
Comment (mcrumiller) [inline polars/polars-core/src/frame/asof_join/groups.rs:172]: When the `by` groups are interleaved, the previous value may not be at location `offset - 1`, so we need to store the prior offset's location.

**Review by ritchie46 — APPROVED** [review]
Thanks for the quick fix!
