### PR TITLE
fix: Fix handling of `AggregatedScalar` in `ApplyExpr` single input

### LINKED ISSUE #24616: `implode` + `explode` + `over` PanicException
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

df = pl.DataFrame({"x": [[1, 2]]})

df.select(pl.col.x.implode().explode().over(1))
# pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("dtypes don't match, got list[i64], expected: list[list[i64]]"))
```

### Log output

```shell
thread 'polars-2' (149360) panicked at polars/crates/polars-core/src/chunked_array/from_iterator_par.rs:261:85:
called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("dtypes don't match, got i64, expected: list[i64]"))
```

### Issue description

This did not panic on 1.31.0

```
shape: (1, 1)
┌───────────┐
│ x         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [1, 2]    │
└───────────┘
```

### Expected behavior

No panic.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.34.0-beta.1
Index type:          UInt32
Platform:            macOS-13.6.1-arm64-arm-64bit-Mach-O
Python:              3.13.3 (main, Apr  8 2025, 13:54:08) [Clang 15.0.0 (clang-1500.1.0.2.5)]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            1.1.4
fastexcel            0.14.0
fsspec               2025.3.2
gevent               <not installed>
google.auth          <not installed>
great_tables         0.17.0
matplotlib           3.10.0
numpy                2.3.2
openpyxl             3.1.5
pandas               2.2.3
polars_cloud         <not installed>
pyarrow              21.0.0
pydantic             2.11.4
pyiceberg            0.9.1
sqlalchemy           2.0.40
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.0```

</details>

### PR DESCRIPTION
**Pull request by kdn36**
fixes #24616

This PR fixes how `AggregatedScalar` is handled in `ApplyExpr` with single input on group_aware. 

Kindly review, especially around low-level performance implications.

### CODE REVIEW

File: crates/polars-expr/src/expressions/apply.rs [hunk 1]
```diff
@@ -117,7 +117,11 @@ impl ApplyExpr {
         }
 
         let name = s.name().clone();
-        let agg = ac.aggregated();
```
Comment (coastalwhite) [inline crates/polars-expr/src/expressions/apply.rs:120]: The fact that we have to do `as_list` hurts me, but there is no way around it at the moment.
