### PR TITLE
fix: uint64 should be correctly extracted from python object

### LINKED ISSUE #12329: `from_records` schema not respected
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
pl.Series([np.uint64("9908227375760408577")], dtype=pl.UInt64)
# element is 9908227375760408577

pl.from_records([{"a": np.uint64("9908227375760408577")}], schema={"a": pl.UInt64})
# element is 990822737576040856

```

### Log output

_No response_

### Issue description

UInt64 not properly handled in `from_records`

### Expected behavior

expect elements to have same value with the two constructions

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.12
Index type:          UInt32
Platform:            Linux-5.15.0-1031-aws-x86_64-with-glibc2.35
Python:              3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         2.2.1
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.10.0
gevent:              22.10.2
matplotlib:          3.8.1
numpy:               1.26.1
openpyxl:            3.0.9
pandas:              2.1.2
pyarrow:             14.0.0
pydantic:            1.10.13
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          1.4.50
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>```

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This fixes #12329.

I'm not sure if this is the best fix, but it seems that we extract a integer large than `i64` to `f64` instead of `u64`.

### CODE REVIEW

File: py-polars/src/conversion.rs [hunk 1]
```diff
@@ -839,7 +839,9 @@ impl<'s> FromPyObject<'s> for Wrap<AnyValue<'s>> {
                             get_bool
                             // TODO: this heap allocs on failure
                         } else if ob.extract::<i64>().is_ok() {
-                            get_int
+                            get_i64
+                        } else if ob.extract::<u64>().is_ok() {
+                            get_u64
```
Comment (ritchie46) [inline py-polars/src/conversion.rs:844]: I think this should remain `get_int` and `get_int` should remain unchanged as it will correct for overflow.

The extra branch is correct. That was the reason we skipped `i64` and got into the float branch.

However, we do need the generic `get_int` function as both small integers and large integers will have the same place in the lookup table.

**Review by ritchie46 — CHANGES_REQUESTED** [review]

File: py-polars/src/conversion.rs [hunk 2]
```diff
@@ -838,7 +838,7 @@ impl<'s> FromPyObject<'s> for Wrap<AnyValue<'s>> {
                         if ob.is_instance_of::<PyBool>() {
                             get_bool
                             // TODO: this heap allocs on failure
-                        } else if ob.extract::<i64>().is_ok() {
+                        } else if ob.extract::<i64>().is_ok() || ob.extract::<u64>().is_ok() {
```
Comment (ritchie46) [inline py-polars/src/conversion.rs:841]: Yeap, like this! :+1:

**Review by ritchie46 — APPROVED** [review]
