### PR TITLE
fix: Informative error for multi-quantile in `group_by`

### LINKED ISSUE #26956: `group_by` quantile with multiple quantiles crashes with internal error instead of unsupported-operation message
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python

import polars as pl
df = pl.DataFrame({"g": ["a", "a", "b", "b"], "v": [1, 2, 3, 4]})
df.group_by("g").agg(pl.col("v").quantile([0.25, 0.75]))

```

### Log output

```shell
Traceback (most recent call last):
  File "/home/gauta/polars/repro_multi_quantile_groupby.py", line 4, in <module>
    df.group_by("g").agg(pl.col("v").quantile([0.25, 0.75]))
  File "/home/gauta/polars/py-polars/src/polars/dataframe/group_by.py", line 298, in agg
    .collect(optimizations=QueryOptFlags.none())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gauta/polars/py-polars/src/polars/_utils/deprecation.py", line 97, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gauta/polars/py-polars/src/polars/lazyframe/opt_flags.py", line 326, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gauta/polars/py-polars/src/polars/lazyframe/frame.py", line 2464, in collect
    return wrap_df(ldf.collect(engine, callback))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ComputeError: could not extract number from any-value of dtype: 'List(Float64)'

This error occurred in the following expression:
        col("v").quantile()
```

### Issue description

Multi-quantile support was added in #25516, and `group_by` support was intentionally left out. The guard that is supposed to reject this case checks row count rather than dtype, so a list literal like `[0.25, 0.75]` passes the check and later crashes internally instead of raising the intended clean unsupported-operation error.

### Expected behavior

A clean error indicating that multiple quantiles are not yet supported in `group_by` aggregations, instead of an internal extraction error.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.39.0
Index type:          UInt32
Platform:            Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
Python:              3.12.12 | packaged by conda-forge | (main, Oct 22 2025, 23:25:55) [GCC 14.3.0]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  1.10.0
altair               6.0.0
azure.identity       1.25.2
boto3                1.42.49
cloudpickle          3.1.2
connectorx           0.4.5
deltalake            1.4.2
fastexcel            0.19.0
fsspec               2026.2.0
gevent               25.9.1
google.auth          2.48.0
great_tables         0.20.0
matplotlib           3.10.8
numpy                2.4.2
openpyxl             3.1.5
pandas               3.0.1
polars_cloud         0.5.0
pyarrow              23.0.1
pydantic             2.12.5
pyiceberg            0.11.0
sqlalchemy           2.0.46
torch                <not installed>
xlsx2csv             0.8.6
xlsxwriter           3.2.9

```

</details>

### PR DESCRIPTION
**Pull request by gautamvarmadatla**
The guard blocking multi-quantile in `group_by` checked row count instead of dtype, allowing list-valued quantiles like `[0.25, 0.75]` to slip through. Fixed by adding a dtype check alongside the existing length check.

Fixes #26956

### CODE REVIEW

**Comment by gautamvarmadatla** [comment]
> We should ensure that quantile_column matches supported dtypes rather than specifically excluding list

makes sense, updated it! :)

File: crates/polars-expr/src/expressions/aggregation.rs [hunk 1]
```diff
@@ -578,8 +578,10 @@ impl PhysicalExpr for AggQuantileExpr {
         let keep_name = ac.get_values().name().clone();
 
         let quantile_column = self.quantile.evaluate(df, state)?;
-        polars_ensure!(quantile_column.len() <= 1, ComputeError:
-            "polars only supports computing a single quantile in a groupby aggregation context"
+        polars_ensure!(
+            quantile_column.len() <= 1 && quantile_column.dtype().is_numeric(),
```
Comment (nameexhaustion) [inline crates/polars-expr/src/expressions/aggregation.rs]: Dtype check needs to be a separate polars_ensure, then we should print the got vs expected styles when they don't match

Comment (gautamvarmadatla) [reply crates/polars-expr/src/expressions/aggregation.rs]: done, moved to a seperate check

File: py-polars/tests/unit/operations/aggregation/test_aggregations.py [hunk 2]
```diff
@@ -138,6 +138,14 @@ def test_quantile_error_checking() -> None:
         s.quantile([0.0, 1.2])
 
 
+def test_multi_quantile_group_by_unsupported() -> None:
```
Comment (nameexhaustion) [inline py-polars/tests/unit/operations/aggregation/test_aggregations.py]:
```suggestion
def test_multi_quantile_group_by_unsupported_26956() -> None:
```
