### PR TITLE
fix(rust): Add broadcasting for list comparisons

### LINKED ISSUE #10138: Add a way to test for list equality
### Problem description

I'm currently working with a dataset that contains list columns, and I was surprised not to find an easy way to test for list equality:

```python
>>> import polars as pl
>>> data = pl.DataFrame({"x": [[1], [1, 2], [2, 3]]}, schema={"x": pl.List(int)})
... data
shape: (3, 1)
┌───────────┐
│ x         │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [1]       │
│ [1, 2]    │
│ [2, 3]    │
└───────────┘
>>> data.filter(pl.col("x") == pl.lit([1]))
ArrowErrorException: NotYetImplemented("Casting from Int64 to 
    LargeList(Field { name: \"item\", data_type: Int64, is_nullable: true, metadata: {} }) 
    not supported")
```

Maybe I missed the right incantation from the `Expr.list` namespace?
In the meantime I went with the following utility function:

```python
def filter_list_equal(df: pl.DataFrame, colname: str, values: list) -> pl.DataFrame:
    col = pl.col(colname)
    lf = df.lazy()
    lf = lf.filter(col.list.lengths() == pl.lit(len(values)))
    for i, v in enumerate(values):
        lf = lf.filter(col.list[i] == pl.lit(v))
    return lf.collect()
```

### LINKED ISSUE #10698: `Series.eq` does not work correctly for `List` types
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

s = pl.Series([[1], [1,2]])
s == [1]
```
```
shape: (1,)
Series: '' [bool]
[
        true
]
```

### Issue description

I tried various variations for comparison, but it seems like broadcasting does not work correctly here. The result is always of length 1.

### Expected behavior

```
shape: (2,)
Series: '' [bool]
[
        true
        false
]
```

### Installed versions

main

### PR DESCRIPTION
**Pull request by c-peters**
fix #10698, fix #10138

### CODE REVIEW

**Comment by c-peters** [comment]
Note that with `get` and `get_unchecked` the series that get returned have the same name as the list itself.

With the `amortized_iter` they did not and got an empty string as name, I changed it to follow the behavior of `get`, but we could also do it the other way around

File: crates/polars-core/src/chunked_array/ops/take/take_single.rs [hunk 1]
```diff
@@ -254,7 +254,7 @@ impl TakeRandom for ListChunked {
         let opt_arr = unsafe { impl_take_random_get!(self, index, LargeListArray) };
         opt_arr.map(|arr| unsafe {
             Series::from_chunks_and_dtype_unchecked(
-                self.name(),
+                "",
```
Comment (ritchie46) [inline crates/polars-core/src/chunked_array/ops/take/take_single.rs:257]: These drive-by changes can have large performance impact on other places.

In this case it gets cheaper, so let's leave it.  But I think we should make these very clear. Maybe even in their own PR.

Comment (c-peters) [reply crates/polars-core/src/chunked_array/ops/take/take_single.rs:257]: This was necessary as `.get` returns a series with the name of the origin list series while `amortized_iter` returns a series with an empty name so the comparison would fail.

Hoping to get rid of this once I have the loop without `get`

Comment (ritchie46) [reply crates/polars-core/src/chunked_array/ops/take/take_single.rs]: We can alway rename temporary for the comparison.

File: crates/polars-core/src/chunked_array/comparison/mod.rs [hunk 2]
```diff
@@ -680,59 +680,90 @@ impl ChunkCompare<&str> for Utf8Chunked {
...
+            let right = right_us.as_ref().map(|s| s.as_ref());
+            // Safety: values within iterator do not outlive the iterator itself
+            unsafe {
+                lhs.amortized_iter()
+                    .map(|left| op(left.as_ref().map(|us| us.as_ref()), right))
+                    .collect_trusted()
+            }
+        },
+        (1, _) => {
+            // Safety: values within iterator do not outlive the iterator itself
```
Comment (ritchie46) [inline crates/polars-core/src/chunked_array/comparison/mod.rs:702]: Request from Orson to write safety all caps. That's the rustlib style guide. ^^

File: crates/polars-core/src/chunked_array/comparison/mod.rs [hunk 3]
```diff
@@ -680,59 +680,90 @@ impl ChunkCompare<&str> for Utf8Chunked {
...
-            self.amortized_iter()
+#[doc(hidden)]
+fn _list_comparison_helper<F>(lhs: &ListChunked, rhs: &ListChunked, op: F) -> BooleanChunked
+where
+    F: Fn(Option<&Series>, Option<&Series>) -> Option<bool>,
+{
+    match (lhs.len(), rhs.len()) {
+        (_, 1) => {
+            // Safety: values within iterator do not outlive the iterator itself
+            let mut iter = unsafe { rhs.amortized_iter() };
```
Comment (ritchie46) [inline crates/polars-core/src/chunked_array/comparison/mod.rs:691]: This could be handled with `.get(0).with_name("")`. It saves us an `unsafe` tag.

No strong opinion here, but I favor keeping the tag count lower.

File: crates/polars-core/src/chunked_array/comparison/mod.rs [hunk 4]
```diff
@@ -680,59 +680,90 @@ impl ChunkCompare<&str> for Utf8Chunked {
...
-        unsafe {
-            self.amortized_iter()
-                .zip(rhs.amortized_iter())
-                .map(|(left, right)| match (left, right) {
-                    (Some(l), Some(r)) => Some(!l.as_ref().series_equal_missing(r.as_ref())),
-                    _ => None,
-                })
-                .collect_trusted()
-        }
+        let _series_not_equal = |lhs: Option<&Series>, rhs: Option<&Series>| match (lhs, rhs) {
```
Comment (ritchie46) [inline crates/polars-core/src/chunked_array/comparison/mod.rs:750]: Nice cleanup.

**Review by ritchie46 — APPROVED** [review]

**Comment by ritchie46** [comment]
Nicw functionality! 👍
