### PR TITLE
fix: Add `.rolling_rank()` support for temporal types and `pl.Boolean`

### LINKED ISSUE #25507: `rolling_rank` panics for temporals and `Boolean`
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

`rolling_rank` and `rolling_rank_by` panic for temporal dtype columns.

```python
from datetime import date, datetime, time, timedelta

import polars as pl
from polars import col

df = pl.DataFrame(
    {
        "index": [1, 2, 3, 4, 5],
        "date": [date(2025, 1, x) for x in range(1, 6)],
        "datetime": [datetime(2025, 1, x) for x in range(1, 6)],
        "duration": [timedelta(hours=x) for x in range(1, 6)],
        "time": [time(hour=x) for x in range(1, 6)],
    }
)

# Expr.rolling_rank
df.select(
    date=col("date").rolling_rank(4),
    datetime=col("datetime").rolling_rank(4),
    duration=col("duration").rolling_rank(4),
    time=col("time").rolling_rank(4),
)
# pyo3_runtime.PanicException: not implemented for dtype Date

# Expr.rolling_rank_by
df.select(
    date=col("date").rolling_rank_by("index", "4i"),
    datetime=col("datetime").rolling_rank_by("index", "4i"),
    duration=col("duration").rolling_rank_by("index", "4i"),
    time=col("time").rolling_rank_by("index", "4i"),
)
# pyo3_runtime.PanicException: not implemented for dtype Date
```

### Installed versions

main

### PR DESCRIPTION
**Pull request by dsprenkels**
Fixes #25507

### CODE REVIEW

File: crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs [hunk 1]
```diff
@@ -574,6 +586,18 @@ pub trait SeriesOpsTime: AsSeries {
     fn rolling_rank(&self, options: RollingOptionsFixedWindow) -> PolarsResult<Series> {
         let s = self.as_series();
 
+        match s.dtype() {
+            DataType::Boolean => return s.cast(&DataType::UInt8)?.rolling_rank(options),
```
Comment (orlp) [inline crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs:590]: This hurts my soul 😭. Probably not worth the time to make a dedicated kernel though.

Comment (dsprenkels) [reply crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs:590]: Yup, me too. Although I just copied it from [some](https://github.com/pola-rs/polars/blob/d527a8a64fa39e3512ac332b70f1ec1368aee998/crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs#L306) [other](https://github.com/pola-rs/polars/blob/d527a8a64fa39e3512ac332b70f1ec1368aee998/crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs#L346) [rank](https://github.com/pola-rs/polars/blob/d527a8a64fa39e3512ac332b70f1ec1368aee998/crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs#L387) [operations](https://github.com/pola-rs/polars/blob/d527a8a64fa39e3512ac332b70f1ec1368aee998/crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs#L427).

**Comment by mcrumiller** [comment]
Ahh I have a PR almost ready for this one too, sorry I should have indicated.

**Comment by mcrumiller** [comment]
That's fine I can merge this into my update, which also covers #25480.
