### PR TITLE
feat!: Change behavior of `all` - fix Kleene logic implementation for `all`/`any`

### LINKED ISSUE #10550: `drop_nulls` parameter for `any`/`all` is misimplemented
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

# `any`
pl.Series([], dtype=pl.Boolean).any(drop_nulls=False)  # None - should be False
pl.Series([False], dtype=pl.Boolean).any(drop_nulls=False)  # None - should be False

# `all`
pl.Series([False, None], dtype=pl.Boolean).all(drop_nulls=False)  # None - should be False
```

### Issue description

Full overview of current behaviors is below.

```python
import polars as pl

# ANY

# with drop_nulls=True (default)
# everything is correct
pl.Series([], dtype=pl.Boolean).any()  # False
pl.Series([None], dtype=pl.Boolean).any()  # False
pl.Series([False], dtype=pl.Boolean).any()  # False
pl.Series([False, None], dtype=pl.Boolean).any()  # False
pl.Series([True], dtype=pl.Boolean).any()  # True
pl.Series([True, None], dtype=pl.Boolean).any()  # True

# with drop_nulls=False
pl.Series([], dtype=pl.Boolean).any(drop_nulls=False)  # None - should be False
pl.Series([None], dtype=pl.Boolean).any(drop_nulls=False)  # None
pl.Series([False], dtype=pl.Boolean).any(drop_nulls=False)  # None - should be False
pl.Series([False, None], dtype=pl.Boolean).any(drop_nulls=False)  # None
pl.Series([True], dtype=pl.Boolean).any(drop_nulls=False)  # True
pl.Series([True, None], dtype=pl.Boolean).any(drop_nulls=False)  # True

# ALL

# with drop_nulls=True (default)
pl.Series([], dtype=pl.Boolean).all()  # True
pl.Series([None], dtype=pl.Boolean).all()  # False
pl.Series([False], dtype=pl.Boolean).all()  # False
pl.Series([False, None], dtype=pl.Boolean).all()  # False
pl.Series([True], dtype=pl.Boolean).all()  # True
pl.Series([True, None], dtype=pl.Boolean).all()  # False

# with drop_nulls=False
# everything is correct
pl.Series([], dtype=pl.Boolean).all(drop_nulls=False)  # True
pl.Series([None], dtype=pl.Boolean).all(drop_nulls=False)  # None
pl.Series([False], dtype=pl.Boolean).all(drop_nulls=False)  # False
pl.Series([False, None], dtype=pl.Boolean).all(drop_nulls=False)  # None - should be False
pl.Series([True], dtype=pl.Boolean).all(drop_nulls=False)  # True
pl.Series([True, None], dtype=pl.Boolean).all(drop_nulls=False)  # True

```

Additionally, the parameter name `drop_nulls` is extremely misleading. Null values are not dropped, they are treated as `False`. That is completely different behavior.

Renaming to `null_as_false` would be more appropriate. However, I don't like that we have to set `null_as_false` to get different behavior, yet it's not clear that that behavior would be.

Better would be something like `three_value_logic`, defaulting to `False`. Then you can opt-in to the behavior by setting `three_value_logic=True`. Then you know what you're signing up for. However, I'm still looking for a better parameter name.

### Expected behavior

See description.

Also, parameter should be named `ignore_nulls`.

### Installed versions

main

### PR DESCRIPTION
**Pull request by stinodego**
Closes #10550 

#### Changes

* `all` will now ignore null values by default, rather than treat them as `False`.
  * This change is introduced by updating `arrow2` to a version that includes [this breaking change](https://github.com/jorgecarleitao/arrow2/pull/1545).

Before:
```python
>>> pl.Series([True, None]).all()
False
```

After:
```python
>>> pl.Series([True, None]).all()
True
```

#### Other changes
* Fix the implementation of Kleene logic. The output was incorrect in some cases, this has been corrected.
* Rename parameter `drop_nulls` to `ignore_nulls`, to better align with the rest of our API.
* Make the parameter `drop_nulls` keyword-only. _(all boolean flags must be keyword only)_

### CODE REVIEW

**Comment by avimallu** [comment]
Does `propagate_nulls` work? You can eschew the use of a loaded complex term like `three_value_logic`, and still avoid any layered implicit meaning from `drop_nulls`? In the description, then, you can explain that it uses three valued logic (with a Wikipedia link to what that means), and also specify what setting the parameter to `False` does (sets all `null` to `False`).

**Comment by mcrumiller** [comment]
I think `include_nulls` is fairly obvious and works with your ideal that it defaults to false.

I don't really like the word "propagate" in this context. From a user perspective, when I call functions like `all` I don't think about the results *propagating*. For bitwise comparisons it makes a little bit of sense, because those are one-to-one functions in which the null values propagate from one series to the next, but `all` is a many-to-one operation involving an aggregation. When I say that 1 + 2 = 3, I don't think of 1 and 2 as "propagating into the sum."

**Comment by stinodego** [comment]
Thanks for chiming in, guys!

`include_nulls` would not work, because we are including null values in both implementations, it's just that one implementation treats them as False, while the other treats them as 'unknowns'.

I guess `propagate_nulls` could work, though I agree with @mcrumiller that it's not immediately obvious what that would do. Explanation in the parameter description with a Wikipedia link is a great idea regardless!

**Comment by mcrumiller** [comment]
@stinodego you could maybe use `null_sensitive=False`. If the function is sensitive to nulls, that means that the mere presence of a single null value makes `all()` return the null value (presumably), whereas the `any` will still depend on the presence of True being somewhere in the deck.

**Comment by stinodego** [comment]
After reading the Wikipedia article on three-valued logic, I'm leaning to either `allow_unknown` or `ternary` as parameter names.

I don't see how we could succinctly describe exactly how null values are handled in three-valued logic in a single parameter name, but we CAN describe what type of output to expect.

**Comment by mcrumiller** [comment]
If you used one of those I would vote for `use_ternary` or `use_ternary_logic`.

**Comment by magarick** [comment]
If you want to go with something "classic" R uses `na.rm` and I've seen `skipna` in pandas. `na` might be weird since Polars doesn't use it anywhere, but it does have the advantage of making it crystal clear you're talking about missing values as opposed to `null` in some other sense, which is also overloaded.

For the purposes of calculating, the nulls actually are dropped. Not in the sense of physically removing them but `drop` is kind of an overloaded term I guess. Skip and ignore are also good because they make it clear what action you're taking.
@stinodego It _usually_ looks like false but consider `all([true, null])`. That'll be `true` if you don't use the null.

`skip`, `drop`, and `ignore` are short, simple verbs that make it clear what's being done. Something like `ternary` might be obscure for some people, and it feels like twisting yourself in knots just to make a default flag value false without changing the current default behavior. Maybe `use_{null,na}` could work, but `use` is ambiguous and doesn't describe what's happening. `keep`? `dont_skip`?

**Comment by stinodego** [comment]
> It usually looks like false but consider all([true, null]). That'll be either true or null depending on the setting.

No, that's the mistake that was made in the earlier implementation. This evaluates to False in binary logic as not all the values are true.

That's why all the skip, drop, ignore etc. do not work as parameter names. The nulls are not skipped, they are an integral part of the calculation.

**Comment by mcrumiller** [comment]
> The nulls are not skipped, they are an integral part of the calculation.

Yeah, I get it. `None` is treated as a distinct value from true/false. So with binary logic:

* `all([True, True, None])` --> `False`. There is a non-true value in there (`None`).
* `any([False, None])` --> `False`. There is no `True` value present.
* `any([True, None])` --> `True`. There is a `True` value present.

With ternary logic, `None` instead of being a 3rd value is an "unknown" value:

* `all([True, True, None])` --> `None`. We don't know if the 3rd value is true or false.
* `any([False, None])` --> `None`. We don't know if the second value is true or false.
* `any([True, None])` --> `True`. There is a `True` value present.

With this in mind, we can define the parameter as "Null values are unknown". What's a good way to say that?

**Comment by avimallu** [comment]
Perhaps a much simpler and verbose `treat_null_as_false`?

**Comment by mcrumiller** [comment]
@avimallu I don't think that's accurate though: in binary logic !null is still null. So if you have for e.g. `any(NONE)` and `any(!NONE)` is false.

**Comment by avimallu** [comment]
Ah, I see. I guess propagation is still key here, although I agree with your sentiment that the results in *general* don't propagate, so it may be a *learned* but clear parameter for the average user. My 2c, at least.

**Comment by mcrumiller** [comment]
I would maybe vote for `null_as_unknown` but that also seems a bit like something nobody would have encountered before. Let's wait for @stinodego to get his rest before we make this conversation too long for him to read.

**Comment by magarick** [comment]
> > It usually looks like false but consider all([true, null]). That'll be either true or null depending on the setting.
> 
> No, that's the mistake that was made in the earlier implementation. This evaluates to False in binary logic as not all the values are true.

It depends on what people expect. In both R and Julia it will return NA/missing by default. The equivalent in Pandas is calling with `skipna=False` will return `False` but that actually isn't correct. And, it doesn't always do this. Pandas is, uh, weird.
```
>>> pd.Series([True, None]).all(skipna=True)
True
>>> pd.Series([True, None]).all(skipna=False)
False

>>> pd.Series([True, np.nan]).all(skipna=False)
True
>>> pd.Series([True, np.nan]).all(skipna=True)
True
```
And the pandas documentation for `skipna` says "If skipna is False, then NA are treated as True, because these are not equal to zero." so 🤷 . I'm guessing this has to do with the shaky support for missing values.

Perhaps a clearer example: If I flip two coins, show you one, and it's heads, then ask "are they both heads?" the answer isn't "no" it's "I don't know". In many, if not most cases (at least that I'm aware of) a missing value isn't a value in and of itself, but it's a flag telling you "there's something here but I don't know what it is".

You're right though, that there is a bug in `any_3val`. Too clever by half. Easy fix though to have it be consistent.

**Comment by magarick** [comment]
I think the point of confusion might be that this isn't really three-value-logic and that isn't what most people want. The request I was replying to was very specifically to replicate the behavior of R and other tools where it will return a missing value if the result can't be known. This is different than propagating since null values in your input sometimes don't matter.

**Comment by stinodego** [comment]
Really appreciate everyone thinking along here 👍 

Perhaps the binary (default) implementation for `all([True, None])` should actually ignore nulls and return True? Then the parameter name becomes easy and can be `ignore_nulls` or `skip_nulls` or something.

This part is implemented in arrow2 and it actually took me a moment to figure out the None was treated as False rather than skipped.

I'll be home later today and check out how our colleagues at pandas/arrow/etc do things and finish things up.

**Comment by ritchie46** [comment]
I want to hook myself in before merging. :)

File: crates/polars-core/src/chunked_array/comparison/mod.rs [hunk 1]
```diff
@@ -978,18 +978,22 @@ impl BooleanChunked {
         self.downcast_iter().any(compute::boolean::any)
     }
 
-    // Three-valued versions which can return None
-    pub fn all_3val(&self, drop_nulls: bool) -> Option<bool> {
-        if drop_nulls || self.null_count() == 0 {
+    // Three-valued versions which can return None.
+    pub fn all_3val(&self, ignore_nulls: bool) -> Option<bool> {
+        // self.downcast_iter().map(|v|)all(compute::boolean::all)
```
Comment (ritchie46) [inline crates/polars-core/src/chunked_array/comparison/mod.rs:983]: Commented out code

File: crates/polars-core/src/chunked_array/comparison/mod.rs [hunk 2]
```diff
@@ -978,18 +978,22 @@ impl BooleanChunked {
...
+        if ignore_nulls || self.null_count() == 0 {
             Some(self.all())
+        } else if self.not().any() {
```
Comment (ritchie46) [inline crates/polars-core/src/chunked_array/comparison/mod.rs:986]: `not` does an allocation. We should then implement it manually, I don't want this code to allocate. 

Could you help me with the rationale of this change?

**Comment by ritchie46** [comment]
> Perhaps the binary (default) implementation for all([True, None]) should actually ignore nulls and return True? Then the parameter name becomes easy and can be ignore_nulls or skip_nulls or something.

I really don't think we should change defaults to make the parameter name easier. 

As a proposal for the kwarg. What about `negate_nulls`?

**Comment by mcrumiller** [comment]
> Perhaps the binary (default) implementation for all([True, None]) should actually ignore nulls and return True?

I don't like this, this would be pretty unexpected behavior. If I said:

```python
if all(have_space_suits_on):
   open_airlock()
```

and we had some `None`s in there, someone may die :)

I'm leaning towards something like `use_3vl` or `use_three_value_logic`. It's specific, people who want to use 3-value logic will know what it means, and we don't have to agonize over how to encapsulate its meaning in a single parameter name.

File: crates/polars-core/src/chunked_array/comparison/mod.rs [hunk 3]
```diff
@@ -968,28 +968,52 @@ impl Not for BooleanChunked {
...
+    /// contains any null values and no `false` values.
+    pub fn all_ternary(&self, ignore_nulls: bool) -> Option<bool> {
+        if ignore_nulls || self.null_count() == 0 {
+            return Some(self.all());
+        }
+
+        // Inverse version of `any` - check if any values are False
+        let contains_false = self.downcast_iter().any(|array| {
+            if array.is_empty() {
+                false
```
Comment (magarick) [inline crates/polars-core/src/chunked_array/comparison/mod.rs:993]: If it's empty the null count will be 0, so this is handled by the case above.

File: crates/polars-core/src/chunked_array/comparison/mod.rs (hunk 2 above)
Comment (stinodego) [reply crates/polars-core/src/chunked_array/comparison/mod.rs]: The old version went wrong when there were both null values and `False` values in the data. It just said "if there's a null, I'll return null". However, if there is at least one `False` value in the data, we know that `all` can never be true.

So we have to check "does the Series contain a False value"? Which is the same as calling `any` on an inverted Series. That's what I initially implemented here. But it's inefficient, as you've pointed out, so I implemented it now as a closure based on the implementation of `any` in the `arrow2` crate.

File: crates/polars-core/src/chunked_array/comparison/mod.rs (hunk 3 above)
Comment (stinodego) [reply crates/polars-core/src/chunked_array/comparison/mod.rs:993]: This closure operates on array chunks, which may be empty / have no validity mask.

File: crates/polars-core/src/chunked_array/comparison/mod.rs (hunk 1 above)
Comment (stinodego) [reply crates/polars-core/src/chunked_array/comparison/mod.rs]: Yeah I had some cleanup to do still! (PR was still in draft 😸 )

**Comment by magarick** [comment]
> > Perhaps the binary (default) implementation for all([True, None]) should actually ignore nulls and return True? Then the parameter name becomes easy and can be ignore_nulls or skip_nulls or something.
> 
> I really don't think we should change defaults to make the parameter name easier.

Some background that might help. The original implementation wrapped what arrow2 provides, which skips missing values. So it would always either give you true or false because it was ignoring them, not treating them as one of the two values. This behavior exists in other systems, but often you have to ask for it explicitly because it can hide data issues.

> As a proposal for the kwarg. What about `negate_nulls`?

If nulls are "I don't know" then negating it is still "I don't know" (or maybe I know but I'm not telling you :-))

> More info on the defaults we want to follow: #9472

@ritchie46 Thank you for linking this. To follow those rules, it's just a one line fix here so calling any on a series that contains only false and null does the right thing. If someone wants to implement different logic, that's a separate function.

Perhaps the right thing to do is to have the user make it absolutely explicit what they want and not have a kwarg at all, but two functions. This deviates from R and pandas but is similar to Julia (I think you have to call skipmissing on your vector first).

Another reason to not try and get too fancy with naming it is that you have to consider how other functions act in the presence of missing data. Means, etc. If there's a missing value the choice you have is to either skip over it or declare the whole answer "I don't know". In these cases, imputing is not part of the function since there's more choice involved. The difference between say, a mean and any/all is that the latter can sometimes give you an answer even in the presence of missing values but a mean can't. Fundamentally, you're taking the same action, though.

**Comment by mcrumiller** [comment]
@stinodego if you leave it as `null_as_false`, does that mean that in binary logic, `any(![True, None]) == True`, meaning null values negate to True?

**Comment by stinodego** [comment]
> @stinodego if you leave it as `null_as_false`, does that mean that in binary logic, `any(![True, None]) == True`, meaning null values negate to True?

Please elaborate, I don't understand what you mean! Can you give a working code example?

**Comment by mcrumiller** [comment]
> > @stinodego if you leave it as `null_as_false`, does that mean that in binary logic, `any(![True, None]) == True`, meaning null values negate to True?
> 
> Please elaborate, I don't understand what you mean! Can you give a working code example?

What should we expect from the following?
```python
pl.Series([None, None, None], dtype=pl.Boolean).is_not(null_as_false=True)
```
Does this return a series with 3 `True` values in it?

**Comment by stinodego** [comment]
> What should we expect from the following?

I think you made a mistake in your code example, it doesn't work and doesn't include `all` or `any`.

**Comment by mcrumiller** [comment]
Maybe that's tangential to implementing 3-valued logic in `is_not()`. My concern is on `(~x).all()` being confusing with `None` values.

**Comment by stinodego** [comment]
> Maybe that's tangential to implementing 3-valued logic in `is_not()`. My concern is on `(~x).all()` being confusing with `None` values.

I don't think it's confusing at all. After calling `is_not` on a null value, the result is still a null value. And if you call subsequently call `all` on it, the values are treated as `False`.

**Comment by magarick** [comment]
@stinodego I'm still confused. Where are you getting the idea that nulls are/should be treated as false? I don't see that done anywhere nor is it implied in the description of three-valued logic. `all` is equivalent to `fold`ing with `and`. The truth tables in the wikipedia article have `F & U = F` but `U & U = U`, `T & U = U`.

**Comment by stinodego** [comment]
> Where are you getting the idea that nulls are/should be treated as false?

This is the way it's implement in arrow2. See the linked issue for the truth values with `drop_nulls=True`, and you'll see that nulls are treated as False. I did not touch these in this PR, I only fixed some of the return values when `drop_nulls=False` (i.e. ternary logic).

**Comment by stinodego** [comment]
I think this PR is ready to go, and offers a working fix to the linked issue.

_HOWEVER..._

I believe that we should ideally change the way `all` works conceptually (`any` is simpler and already works fine).

I think `pyarrow` is doing it right ([see docs](https://arrow.apache.org/docs/python/generated/pyarrow.compute.all.html)). What they're doing conceptually:
* `all` performs ternary logic
* It has a flag argument (they call it `skip_nulls`) that makes the computation ignore all null values. This essentially makes it behave like **binary** logic. This will make `all([True, None])` return `True`. This flag is enabled by default.

This is very unfortunate for @mcrumiller 's astronauts (that was a great analogy), but I think this will make the whole thing make more sense conceptually.

But we don't have to solve or agree on this today. This fix can already go in, and I can make a separate issue for this discussion.

**Comment by magarick** [comment]
> > Where are you getting the idea that nulls are/should be treated as false?
> 
> This is the way it's implement in arrow2. See the linked issue for the truth values with `drop_nulls=True`, and you'll see that nulls are treated as False. I did not touch these in this PR, I only fixed some of the return values when `drop_nulls=False` (i.e. ternary logic).

I just checked arrow2 and "yikes" on two fronts

Take a look here:
https://docs.rs/arrow2/latest/src/arrow2/compute/boolean.rs.html#234-243

It completely ignores the presence or absence of nulls. They're not treated as false, they're treated as whatever happens to be there. From the documentation for `values`
https://docs.rs/arrow2/latest/arrow2/array/struct.BooleanArray.html#method.values
`The values [Bitmap](https://docs.rs/arrow2/latest/arrow2/bitmap/struct.Bitmap.html). Values on null slots are undetermined (they can be anything).`

Now _that's_ the bug. If you call this on an array that might have null values without checking you can get an indeterminate result.

It also has `boolean_kleene` (I guess a good name if you know it's called Kleene logic) which does the correct three value thing.
https://docs.rs/arrow2/latest/src/arrow2/compute/boolean_kleene.rs.html#238-247

**Comment by stinodego** [comment]
I'm sorry to say, but you're simply wrong here. Please study the code and you'll see.

I did miss the `boolean_kleene` module, but the implementation for `all` and `any` are identical to the non-Kleene version. So these are not properly implemented in arrow2 and not usable.

**Comment by magarick** [comment]
Sorry, I read it a bit too quickly. But that's a bug in arrow2's implementation of `all`. My best guess is it's a consequence of forcing the function to return a bool, so you end up interpreting null as "not true" rather than "I don't know" which is a subtle but important distinction. Or maybe with "simple" things like this there's the temptation to try and be quick, which is the same as the issue with the original polars functions. Are other libraries that have this behavior?

I obviously can't stop this, but unless there's another common library that does it this way and some community I'm not aware of expects and wants this behavior, I think it will cause an issue.

**Comment by magarick** [comment]
Actually, there's an easy way to resolve this, lol.
@ritchie46 wrote the arrow2 functions. Ritchie, did you mean for nulls to be treated as false in `all`? If that was intentional, then go for it. I've just never seen it done that way before 🤷

File: crates/polars-core/src/chunked_array/comparison/mod.rs (hunk 2 above)
Comment (stinodego) [reply crates/polars-core/src/chunked_array/comparison/mod.rs]: Actually, it was pointed out there is a `boolean_kleene` module in `arrow2` that is supposed to contain this logic, but is currently broken. I went ahead and properly implemented it:
https://github.com/jorgecarleitao/arrow2/pull/1545

If that's merged, the implementation here can be simplified.

File: crates/polars-core/src/chunked_array/comparison/mod.rs [hunk 4]
```diff
@@ -884,31 +884,50 @@ impl Not for BooleanChunked {
...
+    /// Returns whether all values in the column are `true`.
+    ///
+    /// The output is unknown (`None`) if the array contains any null values and
+    /// no `false` values.
+    pub fn all_kleene(&self) -> Option<bool> {
+        let mut result = Some(true);
+        for arr in self.downcast_iter() {
+            match compute::boolean_kleene::all(arr) {
+                Some(false) => return Some(false),
+                None => result = None,
```
Comment (ritchie46) [inline crates/polars-core/src/chunked_array/comparison/mod.rs:926]: This should directly return `None` right? If there is a single null we should return. A later `Some(true)` result should not overwrite the `None` of previous array.

Comment (stinodego) [reply crates/polars-core/src/chunked_array/comparison/mod.rs:926]: We might encounter a `Some(false)` in a later chunk, in which case the final output should be `Some(false)` (this will be returned directly.

Once `result` is `None`, it will stay `None`. Encountering a `Some(true)` does nothing either way (it's the empty match arm).

Comment (ritchie46) [reply crates/polars-core/src/chunked_array/comparison/mod.rs:926]: Oh.. My bad. I misread the description. Specifically line 920. Then this one is good to go!

**Review by ritchie46 — APPROVED** [review]
