### PR TITLE
fix(rust,python): fix row-wise init of `UInt64` values that exceed `UInt64` upper bound

### LINKED ISSUE #8144: Initialising DataFrame row-wise with large UInt64 value fails, but succeeds column-wise
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

Valid unsigned int values that exceed their equivalent signed-int upper bound cause a `BindingError` if used to initialise a DataFrame in row orientation - the same data succeeds when initialised column-wise.

### Reproducible example

* **Succeeds** _(column-wise)_

  ```python
  df = pl.DataFrame(
      data = {'x':[0,14082482264987928070]},
      schema = {'x':pl.UInt64},
  )

  # shape: (2, 1)
  # ┌──────────────────────┐
  # │ x                    │
  # │ ---                  │
  # │ u64                  │
  # ╞══════════════════════╡
  # │ 0                    │
  # │ 14082482264987928070 │
  # └──────────────────────┘
  ```

* **Fails** _(row-wise)_
  
  ```python
  df = pl.DataFrame(
      data = [[0],[14082482264987928070]],
      schema = {'x':pl.UInt64},
  )

  #   File "_construction.py", line 859, in _sequence_of_sequence_to_pydf
  #     pydf = PyDataFrame.read_rows(
  #            ^^^^^^^^^^^^^^^^^^^^^^
  # BindingsError: "object type not supported 14082482264987928070"
  ```

### Expected behavior

Should be able to initialise the same data in either orientation.

### Installed versions

Latest build compiled from `main` (including just-merged #8140).

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #8144.

### CODE REVIEW

File: py-polars/src/conversion.rs [hunk 1]
```diff
@@ -692,6 +692,8 @@ impl<'s> FromPyObject<'s> for Wrap<AnyValue<'s>> {
             Ok(AnyValue::Boolean(ob.extract::<bool>().unwrap()).into())
         } else if let Ok(value) = ob.extract::<i64>() {
             Ok(AnyValue::Int64(value).into())
+        } else if let Ok(value) = ob.extract::<u64>() {
```
Comment (ritchie46) [inline py-polars/src/conversion.rs:695]: Can we put this one between `null` and `struct`? This seems a bit rare and will slow down the hotter paths, like float and string.

Comment (alexander-beedie) [reply py-polars/src/conversion.rs:695]: No problem 👍
