### PR TITLE
fix(rust): Retain original dtype when deserializing an empty list

### LINKED ISSUE #10781: Pickling struct with null list unpickles with incorrect dtype
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
import pickle
df = pl.Series([{'a':None}],dtype=pl.Struct([pl.Field('a',pl.List(pl.Utf8))]))
print(df.dtype)
print(pickle.loads(pickle.dumps(df)).dtype)
```
Output:
```
Struct([Field('a', List(Utf8))])
Struct([Field('', List(Null))])
```

### Issue description

The dtype is not being reproduced after an unpickle - both the field name and the list type are lost.

### Expected behavior

Both print statements should show the same thing.

### Installed versions

<details>

```
--------Version info---------
Polars:       0.18.15
Index type:     UInt32
Platform:      macOS-13.5.1-arm64-arm-64bit
Python:       3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite: <not installed>
cloudpickle:     <not installed>
connectorx:     <not installed>
deltalake:      <not installed>
fsspec:       2022.11.0
matplotlib:     3.6.3
numpy:        1.24.2
pandas:       1.5.2
pyarrow:       12.0.0
pydantic:      <not installed>
sqlalchemy:     <not installed>
xlsx2csv:      0.8.1
xlsxwriter:     <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by c-peters**
fix #10781

### CODE REVIEW

File: crates/polars-core/src/serde/series.rs [hunk 1]
```diff
@@ -204,8 +204,11 @@ impl<'de> Deserialize<'de> for Series {
                     },
                     DataType::List(_) => {
                         let values: Vec<Option<Series>> = map.next_value()?;
+                        // retain dtype information in case of no actual values
                         if values.is_empty() {
                             Ok(Series::new_empty(&name, &dtype))
+                        } else if values.iter().all(|s| s.is_none()) {
```
Comment (ritchie46) [inline crates/polars-core/src/serde/series.rs:210]: We should use the `AnonymousListBuilder here`. It accepts the `inner_dtype` of the `List` as argument upon construction and will ensure we don't do a double pass on the data.

**Review by ritchie46 — APPROVED** [review]
Yeap, Looks great. :+1:
