### PR TITLE
fix(rust): check dtypes of single-column 'by' parameter in asof-join

### LINKED ISSUE #10278: join_asof panics with different types of "by" column depending on their order
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```python
import polars as pl
df = pl.DataFrame({
    "time": pl.date_range(date(2018,1,1), date(2018,1,8), eager=True),
    "group": [1,1,1,1,2,2,2,2],
    "value": [0,0,None,None,2,None,1,None]
})

dfa = df.with_columns(group=col("group").cast(pl.Int32))
dfb = df.with_columns(group=col("group").cast(pl.Int64))

dfa.join_asof(dfb, on="time", by="group"); # OK

dfb.join_asof(dfa, on="time", by="group") # panics

```

### Issue description

join_asof shows different behaviors, depending on the order of the types on the "by" argument

* OK: left -> i32, right-> i64 
* Panic: left -> i64, right -> i32

Panic stack trace:

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /Users/runner/work/polars/polars/crates/polars-core/src/chunked_array/ops/bit_repr.rs:105:13

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[39], line 13
      9 dfb = df.with_columns(group=col("group").cast(pl.Int64))
     11 dfa.join_asof(dfb, on="time", by="group"); # OK
---> 13 dfb.join_asof(dfa, on="time", by="group")

File ~/miniconda3/envs/polars/lib/python3.10/site-packages/polars/dataframe/frame.py:5570, in DataFrame.join_asof(self, other, left_on, right_on, on, by_left, by_right, by, strategy, suffix, tolerance, allow_parallel, force_parallel)
   5564 if not isinstance(other, DataFrame):
   5565     raise TypeError(
   5566         f"Expected 'other' join table to be a DataFrame, not a {type(other).__name__}"
   5567     )
   5569 return (
-> 5570     self.lazy()
   5571     .join_asof(
   5572         other.lazy(),
   5573         left_on=left_on,
   5574         right_on=right_on,
   5575         on=on,
   5576         by_left=by_left,
   5577         by_right=by_right,
   5578         by=by,
   5579         strategy=strategy,
   5580         suffix=suffix,
   5581         tolerance=tolerance,
   5582         allow_parallel=allow_parallel,
   5583         force_parallel=force_parallel,
   5584     )
   5585     .collect(no_optimization=True)
   5586 )

File ~/miniconda3/envs/polars/lib/python3.10/site-packages/polars/utils/deprecation.py:93, in deprecate_renamed_parameter.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
     88 @wraps(function)
     89 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     90     _rename_keyword_argument(
     91         old_name, new_name, kwargs, function.__name__, version
     92     )
---> 93     return function(*args, **kwargs)

File ~/miniconda3/envs/polars/lib/python3.10/site-packages/polars/lazyframe/frame.py:1561, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, no_optimization, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, streaming)
   1549     comm_subplan_elim = False
   1551 ldf = self._ldf.optimization_toggle(
   1552     type_coercion,
   1553     predicate_pushdown,
   (...)
   1559     streaming,
   1560 )
-> 1561 return wrap_df(ldf.collect())

PanicException: internal error: entered unreachable code
```

### Expected behavior

Borth joins should have the same behavior. Whether allowing a i32 to i64 join or not, but providing with a better error message.

### Installed versions

<details>

--------Version info---------
Polars:              0.18.11
Index type:          UInt32
Platform:            macOS-11.6.6-x86_64-i386-64bit
Python:              3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:39:40) [Clang 15.0.7 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          <not installed>
numpy:               1.25.1
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Resolves #10278

### CODE REVIEW

File: crates/polars-core/src/frame/asof_join/groups.rs [hunk 1]
```diff
@@ -633,7 +633,12 @@ fn dispatch_join<T: PolarsNumericType>(
     tolerance: Option<AnyValue<'static>>,
 ) -> PolarsResult<Vec<Option<IdxSize>>> {
     let out = if left_by.width() == 1 {
-        match left_by_s.dtype() {
+        let left_dtype = left_by_s.dtype();
```
Comment (mcrumiller) [inline crates/polars-core/src/frame/asof_join/groups.rs:636]: Looks like a dtype check was missed when the `by` parameter was a single column.

Comment (ritchie46) [reply crates/polars-core/src/frame/asof_join/groups.rs:636]: Right, good catch. Thanks!
