### PR TITLE
fix(python): ensure `series_equal` properly accounts for dtypes when strict=True

### LINKED ISSUE #11001: polars.Series.series_equal with strict=True considers Int64 and Float64 series equal
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
pl.Series("a", [1, 2], pl.Float64).series_equal(pl.Series("a", [1, 2], pl.Int64), strict=True)
# Returns True, but expected it to return False
```

### Log output

```shell
No log output
```

### Issue description

The Polars documentation for `Series.series_equal` ([link](https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.series_equal.html#polars.Series.series_equal)) says the following: If `strict=True` then `Don’t allow different numerical dtypes, e.g. comparing pl.UInt32 with a pl.Int64 will return False`.

However, `pl.Series("a", [1, 2], pl.Float64).series_equal(pl.Series("a", [1, 2], pl.Int64), strict=True)` returns `True`, even though the two series have different numerical dtypes (`Int64` and `Float64`).

### Expected behavior

Either
1. change the implementation so that `pl.Series("a", [1, 2], pl.Float64).series_equal(pl.Series("a", [1, 2], pl.Int64), strict=True)` returns `False`, or 
2. update the documentation to clarify why Polars returns `True` in this case.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.19.1
Index type:          UInt32
Platform:            macOS-13.5.2-arm64-arm-64bit
Python:              3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          0.3.2a7
deltalake:           <not installed>
fsspec:              <not installed>
matplotlib:          3.7.2
numpy:               1.25.0
pandas:              2.0.3
pyarrow:             12.0.0
pydantic:            2.2.1
sqlalchemy:          2.0.16
xlsx2csv:            <not installed>
xlsxwriter:          3.1.2
```

</details>

### PR DESCRIPTION
**Pull request by alexander-beedie**
Closes #11001.

`series_equal` was ignoring dtype comparison when `strict=True` (the call to `eq` just ended-up resolving to `series_equal_missing` without ever actually comparing the dtypes).

```
strict
    Don't allow different numerical dtypes, e.g. comparing `pl.UInt32` with a
    `pl.Int64` will return `False`.
```

Fixed this so that we now match the behaviour given in the docs (above), and added some new test coverage.

### CODE REVIEW

File: py-polars/src/series/mod.rs [hunk 1]
```diff
@@ -281,9 +281,10 @@ impl PySeries {
     }
 
     fn series_equal(&self, other: &PySeries, null_equal: bool, strict: bool) -> bool {
-        if strict {
-            self.series.eq(&other.series)
-        } else if null_equal {
+        if strict && self.series.dtype().ne(other.series.dtype()) {
```
Comment (stinodego) [inline py-polars/src/series/mod.rs:284]: Just a very nitpicky thing: The `!=` syntax is more readable to me.

```suggestion
        if strict && (self.series.dtype() != other.series.dtype()) {
```

**Review by stinodego — COMMENTED** [review]
Jep, that fix looks good! Just left one nitpicky thing, otherwise good to merge.

File: py-polars/src/series/mod.rs (hunk 1 above)
Comment (stinodego) [reply py-polars/src/series/mod.rs:284]: I'll go ahead and commit this so I can merge this and forget about it 😄

**Review by stinodego — APPROVED** [review]
