### PR TITLE
fix: Properly write Parquet for sliced lists

### LINKED ISSUE #18069: Possible Bug: assertion failed: 8 * slice.len() >= offset + len
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

chunk_size = 1_000
x = pl.DataFrame({'a': 3_500 * [None, ['-503']]}, schema = pl.Schema([('a', pl.List(pl.String))]))
for partition_number, start_index in enumerate(range(0, x.shape[0], chunk_size), start=1):
    chunk = x.slice(start_index, chunk_size)
    chunk.write_parquet("hi.parquet")
```

### Log output

_No response_

### Issue description

This code causes a PanicException: assertion failed: 8 * slice.len() >= offset + len

I only encounter this issue in polars > 1.2.1. I do not know what is causing this behavior but it is, as far as I can tell, unexpected. Python versions tried: py38, py39, py310. 

### Expected behavior

Expected behavior is: saves parquet file without throwing an exception.

### Installed versions

<details>

```
--------Version info---------
Polars:               1.2.1
Index type:           UInt32
Platform:             Linux-5.10.219-208.866.amzn2.x86_64-x86_64-with-glibc2.35
Python:               3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          2.2.1
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               2023.6.0
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              16.1.0
pydantic:             2.6.4
pyiceberg:            <not installed>
sqlalchemy:           1.4.52
torch:                1.13.1+cu117
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by coastalwhite**
This is a relatively small fix for what was a quite nasty bug.

Fixes #18069.

### CODE REVIEW

File: crates/polars-parquet/src/arrow/write/pages.rs [hunk 1]
```diff
@@ -304,12 +308,13 @@ fn expand_list_validity<'a, O: Offset>(
...
     }
+    validity.extend_constant(array.values().len() - validity.len(), false);
 
     debug_assert_eq!(idx, array.len());
-
     let validity = validity.freeze();
 
-    array_stack.push_front((array.values().as_ref(), BitmapState::SomeSet(validity)));
+    debug_assert_eq!(validity.len(), array.values().len());
+    array_stack.push((array.values().as_ref(), BitmapState::SomeSet(validity)));
```
Comment (ritchie46) [inline crates/polars-parquet/src/arrow/write/pages.rs:317]: Instead of extending the bitmap, can't we slice the values with the offsets start/end? Then we serialize the minimal amount of data.

Comment (coastalwhite) [reply crates/polars-parquet/src/arrow/write/pages.rs:317]: I tried this first and it sadly does work. It would require changing significant part of the Parquet writing code.

Most of the code there assumes that it is being handed the whole array and it can slice it up itself.
