### PR TITLE
feat: Implement/fix unary minus operator `-pl.col(...)`

### LINKED ISSUE #6192: Wrong type promotion on lazy parquet dataframe
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

When reading a parquet dataframe lazily and selecting some transformed Float32 column, the data type gets incorrectly reported as being Float64. After collecting the result however, it's correctly reported as being Float32 again.

### Reproducible example

```python
import polars as pl
import numpy as np

df = pl.DataFrame({
    "x": np.array([1,1,1], dtype="int32"),
    "y": np.array([1,2,3], dtype="float32"),
}).write_parquet("test.parquet")

df = pl.read_parquet("test.parquet").lazy()

print(df.schema)
# {'x': Int32, 'y': Float32}

print(df.select(pl.col("y")).schema)
# {'y': Float32}

# THIS FAILS! Data type should be reported as Float32
print(df.select(-pl.col("y")).schema)
# {'literal': Float64}

# After collecting the dataset, the type is correct
print(df.select(-pl.col("y")).collect().schema)
# {'literal': Float32}
```

### Expected behavior

```python
print(df.schema)
# {'x': Int32, 'y': Float32}

print(df.select(-pl.col("y")).schema)
# {'literal': Float32}
```

### Installed versions

<details>

```
---Version info---
Polars: 0.15.14
Index type: UInt32
Platform: Linux-6.1.0-1.el8.elrepo.x86_64-x86_64-with-glibc2.28
Python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]
---Optional dependencies---
pyarrow: 9.0.0
pandas: 1.5.2
numpy: 1.23.2
fsspec: 2022.01.0
connectorx: <not installed>
xlsx2csv: <not installed>
matplotlib: 3.5.1
```

</details>

### PR DESCRIPTION
**Pull request by stinodego**
Closes #6192

#### Changes

* Implement the `Neg` operator in Rust, dispatch to it from Python
* Turn `__pos__` into a no-op

Point of discussion: for unsigned integers, should we raise (like now) or should we cast it to some supertype, e.g. cast `UInt8` to `Int16`?

### CODE REVIEW

File: crates/polars-plan/src/dsl/arithmetic.rs [hunk 1]
```diff
@@ -43,6 +45,15 @@ impl Rem for Expr {
     }
 }
 
+#[cfg(feature = "negate")]
+impl Neg for Expr {
```
Comment (stinodego) [inline crates/polars-plan/src/dsl/arithmetic.rs:49]: I implemented this as a trait to facilitate `-col(...)`. However, using `col(...).neg()` now requires the user to importing the `Neg` trait. Not sure if this is desirable.

File: crates/polars-plan/src/dsl/arithmetic.rs [hunk 2]
```diff
@@ -43,6 +45,15 @@ impl Rem for Expr {
     }
 }
 
+#[cfg(feature = "negate")]
```
Comment (stinodego) [inline crates/polars-plan/src/dsl/arithmetic.rs:48]: Not sure if this should be hidden behind a feature flag.

**Comment by orlp** [comment]
One thing I would like to note is that overflow on negation isn't unique to the unsigned types. E.g. for `Int8` you also find that `-(-128) 128 (overflow) == -128`.

```rust
>>> pl.Series([-1, -128], dtype=pl.Int8)
shape: (2,)
Series: '' [i8]
[
        -1
        -128
]
>>> -_
shape: (2,)
Series: '' [i8]
[
        1
        -128
]
```

File: crates/polars-plan/src/dsl/arithmetic.rs (hunk 1 above)
Comment (orlp) [reply crates/polars-plan/src/dsl/arithmetic.rs:49]: We can add `std::ops::Neg` to the prelude.

Comment (stinodego) [reply crates/polars-plan/src/dsl/arithmetic.rs:49]: I figured as much, but I couldn't find the other `std::ops` in any preludes - maybe I didn't look hard enough. I'll add it!

File: crates/polars-plan/src/dsl/arithmetic.rs (hunk 2 above)
Comment (stinodego) [reply crates/polars-plan/src/dsl/arithmetic.rs:48]: I also don't think so, I'll get rid of the feature flags.

**Comment by stinodego** [comment]
> One thing I would like to note is that overflow on negation isn't unique to the unsigned types.

I'm aware of this. It currently panicks with the message "attempt to negate with overflow" - there's a test for this. I think that behavior is fine as it is only the lower bound value that causes problems.

**Review by ritchie46 — APPROVED** [review]
Great addition @stinodego. This primitive was long overdue.

**Comment by ritchie46** [comment]
One rebase away....

**Comment by stinodego** [comment]
Rebased 👍 I just want to note that this does break any workflow that relied on doing `-expr` on expressions of unsigned data types. It used to cast so some supertype, now it raises. Could be considered a fix, could be considered breaking. I'll let you be the judge.

**Comment by ritchie46** [comment]
I consider it a fix. The previous behavior was unintentional.
