### PR TITLE
CSV starting point offset meaningless when no data

### LINKED ISSUE #4260: Reading an empty CSV will panic
#### What language are you using?

**Rust**.

#### Which feature gates did you use?

None.

#### Have you tried latest version of polars?

Yes.

#### What version of polars are you using?

0.22.8

#### What operating system are you using polars on?

Ubuntu 22.04

#### What language version are you using
`rustc 1.62.1 (e092d0b6b 2022-07-16)`

#### Describe your bug.

A csv file with no row causes panic when trying to load into a dataframe

#### What are the steps to reproduce the behavior?

```rust
#[cfg(test)]
mod tests {
    use polars::prelude::{CsvReader, PolarsError, SerReader};

    #[test]
    fn it_works() -> Result<(), PolarsError> {
        let data_frame = CsvReader::from_path("./test.csv")?
            .has_header(true)
            .finish()?;
        if data_frame.is_empty() {
            Ok(())
        } else {
            Err(PolarsError::ShapeMisMatch("expected empty df".into()))
        }
    }
}
```

`test.csv` file:
```
A,B
```

#### What is the expected behavior?

Create an empty dataframe with 2 columns.

If this is actually a bug I can try to fix and make a PR.

### PR DESCRIPTION
**Pull request by ydarma**
resolves #4260 

When a CSV contains no row, the `starting_point_offset` value that represents the position of the data may be anything and will not be used. But it can overflow in some situation and panic in debug mode.

The safer solution in my opinion is to return `starting_point_offset` as an `Option` which will be `None` when no data. And use it by calling `unwrap()` ; this should never panic because this part of the code is never reached when no data.

All tests pass in `io::csv`

### CODE REVIEW

**Comment by ydarma** [comment]
All tests pass on my machine... and the failing test has nothing to do with this PR (`make test`)

File: polars/polars-io/src/csv/read_impl.rs [hunk 1]
```diff
@@ -523,7 +527,7 @@ impl<'a> CoreReader<'a> {
                             let local_bytes = &bytes[read..stop_at_nbytes];
 
                             last_read = read;
-                            let offset = read + starting_point_offset;
+                            let offset = read + starting_point_offset.unwrap();
```
Comment (ritchie46) [inline polars/polars-io/src/csv/read_impl.rs:530]: Doesn't this panic on an empty csv as well?

Comment (ydarma) [reply polars/polars-io/src/csv/read_impl.rs:530]: No because this code is never reached when csv is empty.
These existing tests are testing those edge cases and pass:
 - `test_empty_csv()`
 - `test_header_only()`

Comment (ydarma) [reply polars/polars-io/src/csv/read_impl.rs:530]: precisely because when `bytes` is empty `file_chunk` is `Vec[(0,0)]` and  `read == bytes_offset_thread == stop_at_nbytes == 0`

**Comment by ritchie46** [comment]
Alright. Thanks for the PR. :+1:
