### PR TITLE
fix: Restore pyarrow predicate conversion for is_in

### LINKED ISSUE #26802: is_in predicate pushdown silently broken for scan_pyarrow_dataset since 1.28
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```python
import polars as pl
import pyarrow.dataset as ds
import tempfile, pathlib, os

os.environ["POLARS_VERBOSE"] = "1"
os.environ["POLARS_VERBOSE_SENSITIVE"] = "1"

df = pl.DataFrame({"id": [1, 2, 3, 4, 5], "val": [10, 20, 30, 40, 50]})
path = pathlib.Path(tempfile.mkdtemp()) / "test.parquet"
df.write_parquet(path)

dset = ds.dataset(path, format="parquet")
result = pl.scan_pyarrow_dataset(dset).filter(pl.col("id").is_in([1, 3])).collect()
print(result)
```

### Log output

```
[SENSITIVE]: python_scan_predicate: predicate node: col("id").is_in([[1, 3]]), converted pyarrow predicate: <conversion failed>, residual predicate: Some(col("id").is_in([[1, 3]]))
```

### Issue description

`scan_pyarrow_dataset` no longer pushes `is_in` predicates down to PyArrow. Results are correct but PyArrow does a full table scan and Polars filters post-scan.

I think the root cause is in #22178 which changed how Python `is_in` converts list arguments. Before that PR:

```python
other = F.lit(pl.Series(other))._pyexpr      # flat Series([1,3]), dtype Int64
```

After:

```python
other = parse_into_expression(other)           # F.lit([1,3]) → Series([[1,3]]), is_scalar=True
```

`F.lit([1, 3])` wraps the list in another list and sets `is_scalar=True`. In Rust this becomes `Literal(Scalar(List(Int64), AnyValue::List(Series([1,3]))))` instead of the old `Literal(Series([1,3]))`.

`predicate_to_pa()` in `pyarrow.rs` hits the `Literal(lv)` catch-all, calls `to_any_value()`, gets `AnyValue::List(...)`, which falls into the `AnyValue::List(_) => None` rejection. The old flat `Literal(Series(s))` had a dedicated handler that worked fine.

I think the fix is adding an `AnyValue::List(s)` handler in the `Literal(lv)` arm that unwraps the inner series and delegates to the existing serialization logic (gated behind `allow_literal_series`). Happy to open a PR.

### Expected behavior

```
[SENSITIVE]: python_scan_predicate: predicate node: col("id").is_in([[1, 3]]), converted pyarrow predicate: (pa.compute.field('id')).isin([1,3]), residual predicate: None
```

### Installed versions

<details>

Polars 1.38.1

</details>

### PR DESCRIPTION
**Pull request by erandagan**
Closes #26802

AI DIsclosure:
1. I used Claude Code while working on this pull request.
2. I confirm that I have reviewed all changes myself, and I believe they are relevant and correct.

### CODE REVIEW

**Comment by erandagan** [comment]
> This doesn't seem right.. we cannot apply the current conversion on `AnyValue::List` as we would lose a nesting level on list conversion.
> 
> Could you re-work this to ensure the conversion happens as an exception only for the RHS of the `is_in()` operation?

@nameexhaustion Apologies for missing this, I'm not too familiar with the intricacies of the codebase. Pushed a fix.

File: crates/polars-plan/src/plans/python/pyarrow.rs [hunk 1]
```diff
@@ -163,9 +171,19 @@ pub fn predicate_to_pa(
             ..
         } => {
             let col = predicate_to_pa(input.first()?.node(), expr_arena, args)?;
+            let rhs_node = input.get(1)?.node();
             let mut args = args;
             args.allow_literal_series = true;
-            let values = predicate_to_pa(input.get(1)?.node(), expr_arena, args)?;
+            let values = predicate_to_pa(rhs_node, expr_arena, args)
```
Comment (nameexhaustion) [inline crates/polars-plan/src/plans/python/pyarrow.rs]: Can we make this only do the conversion if we have `Literal(List(s))` (i.e. remove the leading `predicate_to_pa().or_else`. It's otherwise not correct to convert the RHS since the semantics are different

Comment (erandagan) [reply crates/polars-plan/src/plans/python/pyarrow.rs]: Makes sense - done.

**Comment by nameexhaustion** [comment]
Thanks for the PR, we want this in today, and there's a lot of hidden complexity, so I'll take it from here. I will leave some notes of the change for learning.

File: crates/polars-plan/src/plans/python/pyarrow.rs [hunk 2]
```diff
@@ -34,12 +37,54 @@ fn sanitize(name: &str) -> Option<&str> {
...
+                let _ = sanitize(s)?;
+                write!(list_repr, "{av},").unwrap();
+            },
+            // Hard to sanitize
+            AnyValue::Binary(_) | AnyValue::List(_) => return None,
+            #[cfg(feature = "dtype-array")]
+            AnyValue::Array(_, _) => return None,
+            #[cfg(feature = "dtype-struct")]
+            AnyValue::Struct(_, _, _) => return None,
+            AnyValue::Null => write!(list_repr, "None,").unwrap(),
```
Comment (nameexhaustion) [inline crates/polars-plan/src/plans/python/pyarrow.rs:74]: Added conversion `AnyValue::Null` to `None`, this previously converted to `null` leading to `NameError: name 'null' is not defined`

File: py-polars/tests/unit/io/test_pyarrow_dataset.py [hunk 3]
```diff
@@ -249,6 +249,136 @@ def test_pyarrow_dataset_partial_predicate_pushdown(
...
+
+    capfd.readouterr()
+    result = q.collect()
+    capture = capfd.readouterr().err
+
+    assert "(pa.compute.field('id')).isin([1,3])" in capture
+    assert "residual predicate: None" in capture
+
+    assert_frame_equal(result, expected)
+    assert_frame_equal(df.filter(pred), expected)
```
Comment (nameexhaustion) [inline py-polars/tests/unit/io/test_pyarrow_dataset.py:273]: We against a statically declared `expected` value, and also perform this assertion with a filter on a polars DataFrame to ensure consistent behavior

File: py-polars/tests/unit/io/test_pyarrow_dataset.py [hunk 4]
```diff
@@ -249,6 +249,136 @@ def test_pyarrow_dataset_partial_predicate_pushdown(
...
+
+    pred = pl.col("id").is_in([1, None, 3])
+    expected = pl.DataFrame({"id": [1, 3], "val": [10, 30]})
+    q = pl.scan_pyarrow_dataset(dset).filter(pred)
+
+    capfd.readouterr()
+    result = q.collect()
+    capture = capfd.readouterr().err
+
+    assert "(pa.compute.field('id')).isin([1,3])" in capture
```
Comment (nameexhaustion) [inline py-polars/tests/unit/io/test_pyarrow_dataset.py:309]: Ensure we drop NULLs from the RHS of is_in if nulls_equal was false.
