### PR TITLE
fix(rust, python): fix cse_plan invalid projection removal

### LINKED ISSUE #9630: Under certain lazy collect conditions: Vstack column names don't match
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

I want to join a dataframe (containing lists of strings column: "a") to itself recursively, so that I build up combinations of "a". Some of these combinations are already present in the dataframe, so I am concating the filtered original dataframe at each recursive level (the filtering is not shown in the example for simplicity).

However, I get an error in Vstack with mismatching column names that only occurs when collecting the lazy pipeline through `pl.concat([dfs]).collect()` and not through collecting the pieces individually (or just using non-lazy dataframes). I think I narrowed it down to the `groupby`-`agg` perhaps being pushed too far up the stack or rearranging the columns?

Its very convoluted, so if you have any suggestions for getting combinations from a list column in polars, it would also be greatly appreciated.

### Reproducible example

```python
import polars as pl

df = (
    pl.DataFrame({"a": [["1"], ["1"], ["3"]], "b": [["4"], ["5"], ["6"]]})
)

dfs = [df.lazy().select("a", "b", a2 = pl.col("a"))]
for n in range(1, 3):
    dfs.append(
        pl.concat([
            dfs[-1]
            .explode("a2")
            .join(dfs[0].explode("a2"), on="a2", how="inner", suffix="_2")
            .select("a", "b"),
            # Original df
            df
            .lazy()
            .select("a", "b")
        ])
        .groupby(pl.col("a").list.sort().list.join(","))
        .agg(
            pl.col("b").flatten(),
            )
        .select(
            pl.col("a").str.split(","),
            pl.col("b").list.unique(),
            a2 = pl.col("a").str.split(",")
            )
    )

pl.concat(dfs).collect()
# exceptions.ShapeError: unable to vstack, column names don't match: "b" and "a"
```

### Expected behavior

```python
# This version of collecting works
pl.concat([dfs[0].collect(), dfs[1].collect(), dfs[2].collect()])
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Linux-4.12.14-122.159-default-x86_64-with-glibc2.22
Python:      3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]

----Optional dependencies----
numpy:       1.25.0
pandas:      2.0.3
pyarrow:     12.0.1
connectorx:  <not installed>
deltalake:   <not installed>
fsspec:      <not installed>
matplotlib:  <not installed>
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #9630

### CODE REVIEW

File: polars/polars-lazy/polars-plan/src/logical_plan/format.rs [hunk 1]
```diff
@@ -96,10 +96,15 @@ impl LogicalPlan {
                 } else {
                     "UNION"
                 };
+                // 3 levels of indentation
+                // - 0 => UNION ... END UNION
+                // - 1 => PLAN 0, PLAN 1, ... PLAN N
+                // - 2 => actual formatting of plans
+                let sub_sub_indent = sub_indent + 2;
                 write!(f, "{:indent$}{}", "", name)?;
```
Comment (ritchie46) [inline polars/polars-lazy/polars-plan/src/logical_plan/format.rs:104]: driveby: Improves nesting in explain
