### PR TITLE
fix(rust): properly read/write fixed-sized lists from/to parquet files

### LINKED ISSUE #16608: Nulls disappear when writing array type (to parquet)
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

dtype = pl.Array(pl.Int64, 2)
df = pl.Series([[1, 2], None, [3, 4]], dtype=dtype).to_frame("x")
print(df)
```

```
shape: (3, 1)
┌───────────────┐
│ x             │
│ ---           │
│ array[i64, 2] │
╞═══════════════╡
│ [1, 2]        │
│ null          │
│ [3, 4]        │
└───────────────┘
```

```python
df.write_parquet("test.parquet")
df = pl.read_parquet("test.parquet")
print(df)
```

```
shape: (2, 1)
┌───────────────┐
│ x             │
│ ---           │
│ array[i64, 2] │
╞═══════════════╡
│ [1, 2]        │
│ [3, 4]        │
└───────────────┘
```

### Log output

_No response_

### Issue description

May be related to https://github.com/pola-rs/polars/issues/16282.

### Expected behavior

Null rows don't go missing.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.30
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:42:31) [MSC v.1937 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            0.10.4
fsspec:               2024.3.1
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.4
nest_asyncio:         1.6.0
numpy:                1.26.4
openpyxl:             <not installed>
pandas:               2.2.2
pyarrow:              16.0.0
pydantic:             2.7.2
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           2.0.30
torch:                2.3.0+cpu
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by coastalwhite**
This PR rewrites many of the parts that relate to Parquet reading and writing of nested fields. This PR is quite large, and I tried my best to extensively test the new implementation, but I am also confident that there are still bugs in it. My view at the moment that these bugs are fringe enough for the moment.

Specifically, this PR merges the `RepLevelIter` and `DefLevelIter` into a `BufferedDremelIter` that properly follows the Parquet specification when it comes to *repetition* and *definition* levels. It is also buffered and thus should be faster (although I don't have numbers to back this up). For the reader side, most of the code is adjusted to skip add elements that are implied by invalid higher-level nestings.

This PR also does many, many drive-by refactors in the Parquet code.

Fixes #16608.

### CODE REVIEW

File: crates/polars-parquet/src/arrow/write/nested/dremel/mod.rs [hunk 1]
```diff
@@ -0,0 +1,422 @@
...
+}
+
+/// This contains the number of elements on the next level for each
+enum LevelLength<'a> {
+    /// Fixed number of elements based on the validity of this element
+    Optional(usize),
+    /// Fixed number of elements irregardless of the validity of this element
+    Constant(usize),
+    /// Variable number of elements and calculated from the difference between two `i32` offsets
+    OffsetsI32(&'a OffsetsBuffer<i32>),
```
Comment (ritchie46) [inline crates/polars-parquet/src/arrow/write/nested/dremel/mod.rs:53]: Not for now, but I think we can remove this. We should only support the larger index types.

File: crates/polars-utils/src/fixedringbuffer.rs [hunk 2]
```diff
@@ -0,0 +1,174 @@
+pub struct FixedRingBuffer<T> {
+    start: usize,
+    length: usize,
+    buffer: *mut T,
+
+    buffer_capacity: usize,
+
+    /// I know that `buffer` also stores a capacity, but these are different. I promise.
```
Comment (ritchie46) [inline crates/polars-utils/src/fixedringbuffer.rs:8]: Maybe explain here why capacity is different? ;)

**Review by ritchie46 — APPROVED** [review]
