### PR TITLE
fix: Prevent false positives in is_in for large integers

### LINKED ISSUE #21966: False positives by is_in when working with large numbers
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

The output from the following code is 'true' while it should be 'false' as the two numbers are not equal. In this case the output remains 'true' as long as the number difference is lower than or equal to 3. It works correctly if we set the dtype to pl.Int128.
 
```python
import polars as pl
pl.Series([58830407606777880], dtype=pl.UInt64).is_in([58830407606777883])
```

### Log output

```shell
Series: '' [bool]
[
	true
]
```

### Issue description

It seems that is_in does an approximate instead of exact matching for large numbers. The provided example, though large, is much smaller than pl.UInt64.max().

### Expected behavior

Series: '' [bool]
[
	false
]

### Installed versions

<details>

```
--------Version info---------
Polars:              1.26.0
Index type:          UInt32
Platform:            macOS-15.3.2-arm64-arm-64bit
Python:              3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:38:07) [Clang 16.0.6 ]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                1.35.44
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2024.10.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.9.2
numpy                1.23.5
openpyxl             3.1.2
pandas               2.2.3
polars_cloud         <not installed>
pyarrow              19.0.1
pydantic             2.4.2
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>```

</details>

### PR DESCRIPTION
**Pull request by wtn**
Fixes #21966.

### Cause

When comparing e.g. `UInt64` with `Int32`, `try_get_supertype()` returns `Float64`. Since `Float64` can only exactly represent integers up to 2^53, large values lose precision and compare as equal when they shouldn't.

### Fix

Use `get_numeric_upcast_supertype_lossless()` for integer-to-integer comparisons, falling back to the left (series) type when no lossless supertype exists. Mixed integer/float comparisons continue to use the standard supertype.

Additionally, fixed a bug in `cast_expr_ir` where the fallback cast (when inline literal casting isn't possible) always used `CastOptions::Strict` instead of respecting the caller's requested options. This caused errors when casting negative signed integers to unsigned types during `is_in` coercion, instead of producing nulls as expected with `NonStrict`.

### CODE REVIEW

**Comment by orlp** [comment]
Isn't this a breaking change? There's an entire comment just above the code you edited which explains this is a todo and should be done in 2.0.

Your commits are marked as co-authored by Claude. To what extent are you using it?

File: crates/polars-plan/src/plans/conversion/type_coercion/is_in.rs [hunk 1]
```diff
@@ -157,9 +157,21 @@ See https://github.com/pola-rs/polars/issues/22149 for more information."
...
+                    // UInt64 + Int64 would otherwise become Float64). When no lossless supertype
+                    // exists (e.g., UInt128 vs Int64), fall back to the series type.
                     let super_type =
-                        polars_core::utils::try_get_supertype(&type_left, type_other_inner)?;
+                        if !a.is_unknown() && !b.is_unknown() && a.is_integer() && b.is_integer() {
+                            polars_core::utils::get_numeric_upcast_supertype_lossless(
+                                &type_left,
+                                type_other_inner,
+                            )
+                            .unwrap_or_else(|| type_left.clone())
```
Comment (nameexhaustion) [inline crates/polars-plan/src/plans/conversion/type_coercion/is_in.rs]: I don't think just taking the LHS type is correct here.

For this PR I believe we just need to add a call to `get_numeric_upcast_supertype_lossless()`, and then fallback to the existing `try_get_supertype()` if that doesn't work

File: crates/polars-plan/src/plans/conversion/type_coercion/mod.rs [hunk 2]
```diff
@@ -1278,7 +1278,7 @@ fn cast_expr_ir(
     e.set_node(expr_arena.add(AExpr::Cast {
         expr: e.node(),
         dtype: to_dtype.clone(),
-        options: CastOptions::Strict,
+        options,
```
Comment (nameexhaustion) [inline crates/polars-plan/src/plans/conversion/type_coercion/mod.rs]: Does this change affect this PR?

**Review by nameexhaustion — CHANGES_REQUESTED** [review]
see above

File: crates/polars-plan/src/plans/conversion/type_coercion/mod.rs (hunk 2 above)
Comment (wtn) [reply crates/polars-plan/src/plans/conversion/type_coercion/mod.rs]: Yes, the `SuperType` case passes `NonStrict`, so need to undo the hard-coding here.

**Comment by wtn** [comment]
Updated to try `get_numeric_upcast_supertype_lossless()` first, then fall back to `try_get_supertype()`. Added tests.

File: crates/polars-plan/src/plans/conversion/type_coercion/mod.rs (hunk 2 above)
Comment (nameexhaustion) [reply crates/polars-plan/src/plans/conversion/type_coercion/mod.rs]: Could we leave it as is? Changing this is a bit of risk that's unnecessary for this PR, unless it's causing test failures?

Comment (wtn) [reply crates/polars-plan/src/plans/conversion/type_coercion/mod.rs]: Yes, I've reverted this change.
