### PR TITLE
fix(rust, python): validate time zone in cast and from_arrow operations

### LINKED ISSUE #9595: .cast(pl.Datetime('ns', 'some_invalid_time_zone')) doesn't raise
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

The code below doesn't error

### Reproducible example

```python
In [14]: pl.Series(['2020-01-01']).str.to_datetime().dt.replace_time_zone('UTC').cast(pl.Datetime('ns', 'fdafdsfasda'))
Out[14]:
shape: (1,)
Series: '' [datetime[ns, fdafdsfasda]]
[
        invalid timezone
]
```

### Expected behavior

I'd expect
```python
ComputeError: unable to parse time zone: 'fdasfsda'
```

### Installed versions

<details>

```
--------Version info---------
Polars:      0.18.4
Index type:  UInt32
Platform:    Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:      3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

----Optional dependencies----
numpy:       1.24.3
pandas:      2.0.2
pyarrow:     12.0.0
connectorx:  <not installed>
deltalake:   0.9.0
fsspec:      <not installed>
matplotlib:  3.7.1
xlsx2csv:    <not installed>
xlsxwriter:  <not installed>

```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #9595 
xref #9586 (not totally sure this closes it, but it at least prevents users from getting invalid results)

### CODE REVIEW

File: polars/polars-core/src/series/from.rs [hunk 1]
```diff
@@ -199,7 +201,10 @@ impl Series {
                 if tz.as_deref() == Some("") {
                     tz = None;
                 }
-                // we still drop timezone for now
```
Comment (MarcoGorelli) [inline polars/polars-core/src/series/from.rs:202]: hasn't been true for a while 😄

File: polars/polars-core/src/chunked_array/temporal/datetime.rs [hunk 2]
```diff
@@ -262,7 +256,7 @@ impl DatetimeChunked {
     /// Change the underlying [`TimeZone`]. This does not modify the data.
     #[cfg(feature = "timezones")]
     pub fn set_time_zone(&mut self, time_zone: TimeZone) -> PolarsResult<()> {
-        validate_time_zone(time_zone.to_string())?;
+        validate_time_zone(&time_zone)?;
```
Comment (MarcoGorelli) [inline polars/polars-core/src/chunked_array/temporal/datetime.rs:259]: removing an unnecessary `to_string()` from when I didn't know any better 🙈

**Review by ritchie46 — APPROVED** [review]
Good catch indeed. :+1:
