### PR TITLE
fix: `group_by` multiple null columns produce phantom row

### LINKED ISSUE #15623: Grouping empty dataframe by multiple columns with aliased pl.len() creates a row of nulls
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl
df_dict = {"col": [], "col1": []}
df = pl.DataFrame(df_dict)
assert df.height == 0
assert df.dtypes == [pl.Null, pl.Null]
df_agg = df.group_by("col", "col1").agg(pl.len().alias("cnt"))
df_agg.height # 1!!!!
```

### Log output

```shell
Nothing
```

### Issue description

So basically grouping creates a row out of thin air.

Quite a bizarre bug. From my brief testing the necessary conditions for a row appearing:

* more than one column in group by
* column types must NOT be provided, i.e. inferred as nulls by polars
* alias on the `pl.len()`

Encountered while migrating from 0.17 smth. version on production code. 

### Expected behavior

No rows

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.19
Index type:           UInt32
Platform:             macOS-14.4.1-arm64-arm-64bit
Python:               3.11.8 (main, Apr  1 2024, 19:34:05) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           <not installed>
nest_asyncio:         1.6.0
numpy:                <not installed>
openpyxl:             <not installed>
pandas:               <not installed>
pyarrow:              <not installed>
pydantic:             1.10.14
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           3.0.9
```

</details>

### PR DESCRIPTION
**Pull request by reswqa**
This fixes #15623.

### CODE REVIEW

File: crates/polars-core/src/frame/group_by/mod.rs [hunk 1]
```diff
@@ -76,9 +76,16 @@ impl DataFrame {
                 .cloned()
                 .collect::<Vec<_>>();
             if by.is_empty() {
-                Ok(GroupsProxy::Slice {
-                    groups: vec![[0, self.height() as IdxSize]],
-                    rolling: false,
+                Ok(if self.height() == 0 {
+                    GroupsProxy::Slice {
+                        groups: vec![],
```
Comment (ritchie46) [inline crates/polars-core/src/frame/group_by/mod.rs:81]: We can factor out the `GroupsProxy::Slice` and assign the `groups` variable.

``` 
let groups = if self.height() == 0 {
   vec![]
else {
   ...
};

GroupsProxy::Slice {
   groups,
   ...
  }
```
