### PR TITLE
fix[rust]: overlapping groups should not explode data in groupby

### LINKED ISSUE #4628: Nondeterministic validity mask length not matching list length on groupby_rolling shift operation
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of polars.

### Issue Description

This bug is nondeterministic sometimes:

```
*** pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("validity mask length must match the number of values")
(Pdb) node.collect()
thread '<unnamed>' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: OutOfSpec("validity mask length must match the number of values")<unnamed>', ' panicked at '/root/.cargo/git/checkouts/arrow2-8a2ad61d97265680/0b345ae/src/array/primitive/mod.rscalled `Result::unwrap()` on an `Err` value: OutOfSpec("validity mask length must match the number of values"):', 420/root/.cargo/git/checkouts/arrow2-8a2ad61d97265680/0b345ae/src/array/primitive/mod.rs::52420
:52
*** pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("validity mask length must match the number of values")
(Pdb) node.collect()
shape: (24, 3)
┌─────────────────────┬──────┬──────┐
│ ts                  ┆ a1   ┆ a2   │
│ ---                 ┆ ---  ┆ ---  │
│ datetime[ns]        ┆ f64  ┆ f64  │
╞═════════════════════╪══════╪══════╡
│ 2021-02-08 09:50:00 ┆ null ┆ null │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2021-02-08 11:50:00 ┆ null ┆ null │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2021-02-08 13:20:00 ┆ null ┆ null │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2021-02-09 09:20:00 ┆ null ┆ null │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ ...                 ┆ ...  ┆ ...  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2021-02-11 13:50:00 ┆ 0.02 ┆ 0.02 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2021-02-12 09:20:00 ┆ null ┆ null │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2021-02-12 10:50:00 ┆ null ┆ null │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2021-02-12 11:50:00 ┆ null ┆ null │
└─────────────────────┴──────┴──────┘
```

The full rust stacktrace:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfSpec("validity mask length must match the number of values")', /root/.cargo/git/checkouts/arrow2-8a2ad61d97265680/0b345ae/src/array/primitive/mod.rs:420:52
stack backtrace:
   0:     0x7fa0bf619dc0 - <unknown>
   1:     0x7fa0be6ed97e - <unknown>
   2:     0x7fa0bf5f04a2 - <unknown>
   3:     0x7fa0bf61ab63 - <unknown>
   4:     0x7fa0bf61bab5 - <unknown>
   5:     0x7fa0bf61b652 - <unknown>
   6:     0x7fa0bf61b5be - <unknown>
   7:     0x7fa0bf61b591 - <unknown>
   8:     0x7fa0bdc16ca2 - <unknown>
   9:     0x7fa0bdc16f22 - <unknown>
  10:     0x7fa0be8c427e - <unknown>
  11:     0x7fa0bed0f2c8 - <unknown>
  12:     0x7fa0bf2fa324 - <unknown>
  13:     0x7fa0bf2befb2 - <unknown>
  14:     0x7fa0bf3d0504 - <unknown>
  15:     0x7fa0bf3d00d0 - <unknown>
  16:     0x7fa0bf3d143d - <unknown>
  17:     0x7fa0bdc9ce6c - <unknown>
  18:     0x7fa0bf574526 - <unknown>
  19:     0x7fa0bf5740db - <unknown>
  20:     0x7fa0bf61c955 - <unknown>
  21:     0x7fa11dd19fa3 - start_thread
                               at /usr/src/packages/BUILD/nptl/pthread_create.c:486:8
  22:     0x7fa11dabe71f - __GI___clone
                               at /usr/src/packages/BUILD/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  23:                0x0 - <unknown>
  ```

The reproducible example below always fails for me though:

### Reproducible Example

Here, I set `POLARS_MAX_THREADS=1`

```python
import datetime
import itertools

df = pl.DataFrame(
    list(
        itertools.chain.from_iterable(
            [
                {"ts": datetime.datetime(2021, 2, i, 9, 20), "a1": 1.04, "a2": 0.9},
                {"ts": datetime.datetime(2021, 2, i, 9, 50), "a1": 1.04, "a2": 0.9},
                {"ts": datetime.datetime(2021, 2, i, 10, 20), "a1": 1.04, "a2": 0.9},
                {"ts": datetime.datetime(2021, 2, i, 11, 20), "a1": 1.08, "a2": 0.9},
                {"ts": datetime.datetime(2021, 2, i, 11, 50), "a1": 1.08, "a2": 0.9},
                {"ts": datetime.datetime(2021, 2, i, 13, 20), "a1": 1.16, "a2": 0.8},
                {"ts": datetime.datetime(2021, 2, i, 13, 50), "a1": 1.18, "a2": 0.8},
                {"ts": datetime.datetime(2021, 2, i, 14, 20), "a1": 1.18, "a2": 0.8},
                {"ts": datetime.datetime(2021, 2, i, 14, 50), "a1": 1.18, "a2": 0.8},
            ]
            for i in range(1, 29)
        )
    )
).lazy()

# This SOMETIMES fails - it fails with
# PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("validity mask length must match the number of values")
df.sort("ts").groupby_rolling("ts", period="1h", by=None).agg(
    [
        (pl.col("a1") - pl.col("a1").shift(1)).sum().alias("a1"),
        (pl.col("a2") - pl.col("a2").shift(1)).sum().alias("a2"),
    ]
).collect()
```

### Expected Behavior

This should just work I believe. Am I doing something wrong?

### Installed Versions

<details>
---Version info---
Polars: 0.14.6
Index type: UInt32
Platform: Linux-5.4.117.hrtdev-x86_64-with
Python: 3.8.7 (default, Dec 22 2020, 16:05:35) 
[GCC 8.3.0]
---Optional dependencies---
pyarrow: 7.0.0
pandas: 1.1.5
numpy: 1.18.5
fsspec: 0.8.5
connectorx: <not installed>
xlsx2csv: <not installed>
</details>

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #4628 

There is more to do here. We did many optimizations on the assumption that we could exploded/flatten an aggregated list for free. This is not the case if groups are overlapping. An explode an a groupby rolling `col().list()` increases `n` elements to `n * avg(group_len)` which can be a lot!.

I shall see if we can change strategies in more operations for overlapping groups.

### CODE REVIEW

**Comment by OneRaynyDay** [comment]
Aha - this must also be why some of my rolling window functions via groupby_rolling are huge ram eaters as opposed to simple `over()` expressions!

File: polars/polars-lazy/src/physical_plan/expressions/mod.rs [hunk 1]
```diff
@@ -134,7 +134,10 @@ impl<'a> AggregationContext<'a> {
                         })
                     }
                     // sliced groups are already in correct order
-                    GroupsProxy::Slice { .. } => {}
+                    GroupsProxy::Slice { groups, .. } => {
+                        dbg!(groups);
+                        dbg!("hree");
```
Comment (OneRaynyDay) [inline polars/polars-lazy/src/physical_plan/expressions/mod.rs:139]: is this a debug comment that made it through?
