### PR TITLE
fix: Flip order on right join

### LINKED ISSUE #20350: Join's `maintain_order` not respected for right joins
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

When `how="right"` and `maintain_order="left"`, it looks like we are preserving the order of the right DF:

```python
left = pl.LazyFrame({"a": [None, 2, 1, 1, 5]})
right = pl.LazyFrame({"a": [1, 1, None, 2], "b": [6, 7, 8, 9]})
print(
    left.join(
        right, on="a", how="right", maintain_order="left"
    )
)
```
```
shape: (6, 2)
┌──────┬─────┐
│ a    ┆ b   │
│ ---  ┆ --- │
│ i64  ┆ i64 │
╞══════╪═════╡
│ 1    ┆ 6   │
│ 1    ┆ 6   │
│ 1    ┆ 7   │
│ 1    ┆ 7   │
│ null ┆ 8   │
│ 2    ┆ 9   │
└──────┴─────┘
```

When `how="right"` and `maintain_order="right"`, it looks like we are preserving the order of the left DF:

```py
print(
    left.join(
        right, on="a", how="right", maintain_order="right"
    )
)
```
```
shape: (6, 2)
┌──────┬─────┐
│ a    ┆ b   │
│ ---  ┆ --- │
│ i64  ┆ i64 │
╞══════╪═════╡
│ 2    ┆ 9   │
│ 1    ┆ 6   │
│ 1    ┆ 7   │
│ 1    ┆ 6   │
│ 1    ┆ 7   │
│ null ┆ 8   │
└──────┴─────┘
```

### Log output

_No response_

### Issue description

When doing a right join with `maintain_order` set to a value other than `none`, the orders are not respected.
(Looks like it's respecting the opposite order.)

### Expected behavior

The row order of the correct dataframe is respected.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.17.1
Index type:          UInt32
Platform:            macOS-15.1.1-arm64-arm-64bit-Mach-O
Python:              3.13.0 (main, Oct 16 2024, 08:05:40) [Clang 18.1.8 ]
LTS CPU:             False

----Optional dependencies----
adbc_driver_manager  <not installed>
altair               <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
nest_asyncio         <not installed>
numpy                <not installed>
openpyxl             <not installed>
pandas               <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by stijnherfst**
Fixes #20350

When doing a right join the dataframes were swapped and a left join was done. For this the maintain_order argument also needs to be flipped. Thanks @rodrigogiraoserrao for catching this.

### CODE REVIEW

File: crates/polars-ops/src/frame/join/args.rs [hunk 1]
```diff
@@ -81,6 +81,18 @@ pub enum MaintainOrderJoin {
     RightLeft,
 }
 
+impl MaintainOrderJoin {
+    pub fn flip(&self) -> Self {
```
Comment (ritchie46) [inline crates/polars-ops/src/frame/join/args.rs:85]: Can we set this to minimal need publicity.

File: py-polars/tests/unit/operations/test_join.py [hunk 2]
```diff
@@ -1243,6 +1243,20 @@ def test_join_preserve_order_left() -> None:
         5,
     ]
 
+    right_left = left.join(right, on="a", how="right", maintain_order="left").collect()
```
Comment (rodrigogiraoserrao) [inline py-polars/tests/unit/operations/test_join.py:1246]: It feels a bit odd to have tests for right joins in the `test_join_preserve_order_left` function, but oh well.
IMO the fact that the right join is implemented in terms of the left join is just a (clever) implementation detail.
Leaning on that was what led to this bug in the first place 😁
