### PR TITLE
fix: Method `dt.ordinal_day` was returning UTC results as opposed to those on the local timestamp

### LINKED ISSUE #21406: ordinal_day() returns 365 on January 1st (depending on time and year)
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
>>> pl.select(pl.datetime(2023,1,1,7,time_zone="Asia/Singapore").dt.ordinal_day())
shape: (1, 1)
┌──────────┐
│ datetime │
│ ---      │
│ i16      │
╞══════════╡
│ 365      │
└──────────┘
```

### Log output

```shell

```

### Issue description

Apparently `dt.ordinal_day()` returns the ordinal day according to _UTC_. This is not consistent with the behavior of `dt.day()` etc. which return according to the _local time zone_.

### Expected behavior

`dt.ordinal_day()` returns the ordinal day according to the _local time zone_.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.22.0
Index type:          UInt32
Platform:            macOS-15.3.1-arm64-arm-64bit-Mach-O
Python:              3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.2.3
openpyxl             <not installed>
pandas               2.2.3
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #21406

### CODE REVIEW

File: crates/polars-time/src/chunkedarray/datetime.rs [hunk 1]
```diff
@@ -129,7 +129,20 @@ pub trait DatetimeMethods: AsDatetime {
...
+                let ca_local = polars_ops::chunked_array::replace_time_zone(
+                    ca,
+                    None,
+                    &StringChunked::new("".into(), ["raise"]),
+                    NonExistent::Raise,
+                )
+                .expect("Removing time zone is infallible");
+                ca_local.apply_kernel_cast::<Int16Type>(&f)
+            },
+            _ => ca.apply_kernel_cast::<Int16Type>(&f),
```
Comment (ritchie46) [inline crates/polars-time/src/chunkedarray/datetime.rs:144]: Can we return `ca` from the match statement?

Then we only have to apply `&f` once, saving some compiler bloat.

Comment (ritchie46) [reply crates/polars-time/src/chunkedarray/datetime.rs:144]: Will already merge so it's included in release. Could you make a follow up?
