### PR TITLE
fix: Don't silently produce null values from invalid input to `pl.datetime` and `pl.date`

### LINKED ISSUE #20977: `pl.datetime` does not raise with argument values outside of the specified domain
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
import polars as pl

pl.select(pl.datetime(year=2025, month=1, day=1, hour=24))
```

### Log output

```shell
shape: (1, 1)
┌──────────────┐
│ datetime     │
│ ---          │
│ datetime[μs] │
╞══════════════╡
│ null         │
└──────────────┘
```

### Issue description

null

### Expected behavior

The code should raise

### Installed versions

<details>

```
--------Version info---------
Polars:              1.21.0
Index type:          UInt32
Platform:            macOS-14.4.1-arm64-arm-64bit
Python:              3.12.8 (main, Dec 19 2024, 14:22:58) [Clang 18.1.8 ]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               5.5.0
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          2.38.0
great_tables         <not installed>
matplotlib           3.10.0
numpy                2.2.2
openpyxl             <not installed>
pandas               2.2.3
pyarrow              19.0.0
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           2.0.37
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

### PR DESCRIPTION
**Pull request by mcrumiller**
Fixes #20977.

I am not sure if this is a breaking change or not.

Example of new behavior:

```pycon
>>> import polars as pl
>>> pl.select(pl.date(2025, 13, 1))  # month 13 is invalid (pl.Date)
polars.exceptions.ComputeError: Invalid date components (2025, 13, 1) supplied

>>> pl.select(pl.datetime(2025, 13, 1))  # month 13 is invalid (pl.Datetime)
polars.exceptions.ComputeError: Invalid date components (2025, 13, 1) supplied


>>> pl.select(pl.datetime(2025, 1, 1, 25))  # hour 25 is invalid
polars.exceptions.ComputeError: Invalid time components (25, 0, 0, 0) supplied
```

### CODE REVIEW

**Review by ritchie46 — CHANGES_REQUESTED** [review]
We really should return an error here, not a panic.

**Comment by mcrumiller** [comment]
@ritchie46 I wasn't quite sure how to go about this, so let me knwo if it needs rework. Right now, we have an iterator that yields `Option<i32>`s that are collected by the trusted len iterator. I could have returned `Result<Option<i32>>` for each item and updated the trusted len iterator to collect this into a `Result<Int32Chunked>` but this would require messing with the legacy module in polars-arrow which I didn't really want to do, since `FromTrustedLenIterator` doesn't collect Results.

Instead, I opted to flag if an invalid value is observed during the array creation, and proceed as we used to (filling with nulls). Then I check in hindsight if an invalid value was observed, and at that point throw a `ComputeError`. The downside is that the iterator doesn't halt immediately, but since the operation is failing anyway this doesn't seem that awful to me. Let me know if this sounds reasonable, and if not I can try to rework it some more.

File: crates/polars-time/src/chunkedarray/date.rs [hunk 1]
```diff
@@ -84,19 +84,32 @@ pub trait DateMethods: AsDate {
...
+                            None
+                        },
+                        // We have a valid date.
+                        |ns| Some(ns.num_days_from_ce() - EPOCH_DAYS_FROM_CE),
+                    )
                 } else {
                     None
                 }
             })
             .collect_trusted();
```
Comment (ritchie46) [inline crates/polars-time/src/chunkedarray/date.rs:108]: You can return a result and then call `try_collect_ca_with_dtype`, that's a bit cleaner.

**Review by ritchie46 — APPROVED** [review]
