### PR TITLE
fix explode with empty lists

### LINKED ISSUE #4107: `explode` on empty list misaligns columns
#### What language are you using?
Python
#### Have you tried latest version of polars?
yes
#### What version of polars are you using?
0.13.55

#### What operating system are you using polars on?
Linux Mint 20.3

#### What language version are you using
python 3.10.4
#### Describe your bug.
When a column of lists contains an empty list, `explode` misaligns the columns.

#### What are the steps to reproduce the behavior?
Starting with this data:
```python
import polars as pl

df = pl.DataFrame({
    "b": [[1], [2], []] * 2,
}).with_row_count()
df
```
```
shape: (6, 2)
┌────────┬───────────┐
│ row_nr ┆ b         │
│ ---    ┆ ---       │
│ u32    ┆ list[i64] │
╞════════╪═══════════╡
│ 0      ┆ [1]       │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 1      ┆ [2]       │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2      ┆ []        │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3      ┆ [1]       │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 4      ┆ [2]       │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 5      ┆ []        │
└────────┴───────────┘
```
An `explode` on `b` will misalign columns.
```python3
df.explode(['b'])
```

```
>>> df.explode(['b'])
shape: (6, 2)
┌────────┬──────┐
│ row_nr ┆ b    │
│ ---    ┆ ---  │
│ u32    ┆ i64  │
╞════════╪══════╡
│ 0      ┆ 1    │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1      ┆ 2    │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2      ┆ null │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 3      ┆ 1    │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 5      ┆ 2    │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 5      ┆ null │
└────────┴──────┘
```
Notice that `row_nr` 4 disappears, and `row_nr` 5 is duplicated.

The correct result should be:
```
>>> df.explode(['b']).drop('row_nr').with_row_count()
shape: (6, 2)
┌────────┬──────┐
│ row_nr ┆ b    │
│ ---    ┆ ---  │
│ u32    ┆ i64  │
╞════════╪══════╡
│ 0      ┆ 1    │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 1      ┆ 2    │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2      ┆ null │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 3      ┆ 1    │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 4      ┆ 2    │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 5      ┆ null │
└────────┴──────┘
```
#### Test Case
```python
df = pl.DataFrame({"b": [[1], [2], []] * 2}).with_row_count()

pl.testing.assert_frame_equal(
    df.explode(['b']),
    df.explode(['b']).drop('row_nr').with_row_count()
)
```
```
>>> pl.testing.assert_frame_equal(
...     df.explode(['b']),
...     df.explode(['b']).drop('row_nr').with_row_count()
... 
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/testing.py", line 139, in assert_frame_equal
    _assert_series_inner(
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/testing.py", line 245, in _assert_series_inner
    raise_assert_detail(
  File "/home/corey/.virtualenvs/PolarsIssue3.10/lib/python3.10/site-packages/polars/testing.py", line 266, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame are different

Value mismatch
[left]:  [5]
[right]: [4]
```
#### Other Notes
I found this while testing two answers for this [Stack Overflow](https://stackoverflow.com/questions/73061008/is-there-a-polars-function-to-dot-product-two-lists) question.  The OP states that they are concerned about RAM, so I designed two performant -- and yet RAM-saving -- solutions.  This bug arose as I was attempting to benchmark against a simple `explode` solution, in terms of wall-clock and maximum RAM.

### PR DESCRIPTION
**Pull request by ritchie46**
fixes #4107

### CODE REVIEW

File: polars/polars-core/src/chunked_array/ops/explode.rs [hunk 1]
```diff
@@ -249,33 +249,38 @@ pub(crate) fn offsets_to_indexes(offsets: &[i64], capacity: usize) -> Vec<IdxSiz
     }
     let mut idx = Vec::with_capacity(capacity);
 
-    let mut count = 0;
+    // `value_count` counts the taken values from the list values
+    // and aret the same unit as `offsets`
```
Comment (ghuls) [inline polars/polars-core/src/chunked_array/ops/explode.rs:253]: aren't

Comment (ritchie46) [reply polars/polars-core/src/chunked_array/ops/explode.rs:253]: Thanks, will update it.
