### PR TITLE
fix: Fix `scatter` for null values

### LINKED ISSUE #13547: Datetime value assignment ignored
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

Running 
```python
from datetime import datetime
import polars as pl

df = pl.DataFrame(
    {
        "date": [None, None],
        "count": [1, 2]
    },
    schema={"date": datetime, "count": pl.Int64}
)

df[0, "date"] = pl.Series([datetime.today()])
print(df)
```
results in:
```
shape: (2, 2)
┌──────────────┬───────┐
│ date         ┆ count │
│ ---          ┆ ---   │
│ datetime[μs] ┆ i64   │
╞══════════════╪═══════╡
│ null         ┆ 1     │
│ null         ┆ 2     │
└──────────────┴───────┘
```

However, when atleast one value in the date column is set, the assignment works as desired. The code:
```python
from datetime import datetime
import polars as pl

df = pl.DataFrame(
    {
        "date": [None, datetime.today()],
        "count": [1, 2]
    },
    schema={"date": pl.Datetime, "count": pl.Int64}
)

df[0, "date"] = pl.Series([datetime.today()])
print(df)
```
results in:

```
shape: (2, 2)
┌────────────────────────────┬───────┐
│ date                       ┆ count │
│ ---                        ┆ ---   │
│ datetime[μs]               ┆ i64   │
╞════════════════════════════╪═══════╡
│ 2024-01-08 22:32:00.113570 ┆ 1     │
│ 2024-01-08 22:32:00.111568 ┆ 2     │
└────────────────────────────┴───────┘
```

### Log output

_No response_

### Issue description

As shown in the example, the assignment of a date to a specific entry in a Datetime column is ignored without any info or error message. Therefore, if a date column is initalized with solely None values, it is impossible to set any date afterwards.

### Expected behavior

The expected behaviour is shown in the second code example. Assigning a new value to a cell should actually change the dataframe.

### Installed versions

<details>

```
--------Version info---------
Polars:               0.20.3
Index type:           UInt32
Platform:             Windows-10-10.0.19045-SP0
Python:               3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
numpy:                1.26.1
openpyxl:             3.1.2
pandas:               2.1.2
pyarrow:              14.0.2
pydantic:             <not installed>
pyiceberg:            <not installed>
pyxlsb:               <not installed>
sqlalchemy:           <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>

```

</details>

### PR DESCRIPTION
**Pull request by stinodego**
Closes #13547

### CODE REVIEW

File: crates/polars-core/src/chunked_array/ops/chunkops.rs [hunk 1]
```diff
@@ -60,12 +60,24 @@ impl<T: PolarsDataType> ChunkedArray<T> {
...
 
+    /// Set the null count directly.
+    ///
+    /// This can be be useful after mutably adjusting the validity of the
+    /// underlying Arrays.
+    ///
+    /// # Safety
+    /// The new null count must match the total null count of the underlying
+    /// Arrays.
+    pub unsafe fn set_null_count(&mut self, null_count: IdxSize) {
```
Comment (ritchie46) [inline crates/polars-core/src/chunked_array/ops/chunkops.rs:77]: This isn't `unsafe`. It leads to incorrect queries, but it will be sound.
